### ISSUE TITLE
Copy fails with complex dtype

### ISSUE THREAD

**Issue by CompPhysChris** [h5py/h5py#1005]
I'm trying to copy a complex dataset from one file to another.  I'm running on Linux Mint 18.2 and with Python 3.5.2 from the package manager.  I use h5py 2.7.1 and HDF5 1.8.18.  Below is a test script that reproduces the problem and the output I receive.

```
import numpy as np
import h5py

print('H5PY info:', h5py.version.info)

data = np.random.rand(10)+np.random.rand(10)*1j

h5_file = h5py.File('test.h5', mode='w')

h5_source = h5_file.create_dataset('Data', data=data)

h5_group = h5_file.create_group('Group')

h5_file.copy(h5_source, h5_group)
h5_dest = h5_group['Data']

print(np.all(np.isclose(h5_source[()], h5_dest[()])))
```

> H5PY info: Summary of the h5py configuration
> ---------------------------------
> 
> h5py    2.7.1
> HDF5    1.8.18
> Python  3.5.2 (default, Nov 23 2017, 16:37:01) 
> [GCC 5.4.0 20160609]
> sys.platform    linux
> sys.maxsize     9223372036854775807
> numpy   1.14.0

```
Traceback (most recent call last):
  File "/home/challtdow/workspace/pytest/bin/h5_bugtest.py", line 14, in <module>
    h5_file.copy(h5_source, h5_group)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/group.py", line 372, in copy
    dest_path = pp.basename(h5i.get_name(source[source_path].id))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/dataset.py", line 429, in __getitem__
    new_dtype = readtime_dtype(self.id.dtype, names)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/dataset.py", line 44, in readtime_dtype
    raise ValueError("Field names only allowed for compound types")
ValueError: Field names only allowed for compound types
```

**Comment by DTHaydon** [comment]
This is still a problem with: h5py 2.9
A work around is to provide the path to where the object should be create instead of the group.

`h5_file.copy(h5_source, "/".join(h5_group.name, "Data")`
