### ISSUE TITLE
h5py-2.8.0rc1-cp37-cp37m-win32 test failures/errors

### ISSUE THREAD

**Issue by cgohlke** [h5py/h5py#1011]
```
Summary of the h5py configuration
---------------------------------

h5py    2.8.0rc1
HDF5    1.10.1
Python  3.7.0b2 (v3.7.0b2:b0ef5c979b, Feb 28 2018, 01:32:48) [MSC v.1912 32 bit (Intel)]
sys.platform    win32
sys.maxsize     2147483647
numpy   1.14.1
```

```
.....................................................x...............................s..................EF...............x....................................s...s......ss.ss.............................................................................ss....................ssssss...................................................................x....x.........................x......x......................................s..........ssss................                          ======================================================================
ERROR: test_create_ref (h5py.tests.old.test_dataset.TestRegionRefs)                                                     Region references can be used as slicing arguments
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python37-x32\lib\site-packages\h5py\tests\old\test_dataset.py", line 921, in test_create_ref
    self.assertArrayEqual(self.dset[ref], self.data[slic])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "X:\Python37-x32\lib\site-packages\h5py\_hl\dataset.py", line 446, in __getitem__
    out = numpy.empty(mshape, dtype=new_dtype)
ValueError: Maximum allowed dimension exceeded
======================================================================
FAIL: test_ref_shape (h5py.tests.old.test_dataset.TestRegionRefs)                                                       Region reference shape and selection shape                                                                              ----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python37-x32\lib\site-packages\h5py\tests\old\test_dataset.py", line 928, in test_ref_shape
    self.assertEqual(self.dset.regionref.selection(ref), (10, 18))
AssertionError: Tuples differ: (10, 4294967382) != (10, 18)

First differing element 1:
4294967382
18

- (10, 4294967382)
+ (10, 18)

----------------------------------------------------------------------
Ran 454 tests in 2.234s

FAILED (failures=1, errors=1, skipped=20, expected failures=6)
S  old.test_dataset.TestCreateShape.test_complex256 (No support for complex256)
S  old.test_dimension_scales.TestH5DSBindings.test_label_dimensionscale (Reading non-existent label segfaults)
S  old.test_file.TestClose.test_close_multiple_mpio_driver (Parallel HDF5 is required for MPIO driver test)
S  old.test_file.TestDrivers.test_mpi_atomic (Parallel HDF5 required)
S  old.test_file.TestDrivers.test_mpio (Parallel HDF5 is required for MPIO driver test)
S  old.test_file.TestDrivers.test_sec2 (Sec2 driver is supported on posix)
S  old.test_file.TestDrivers.test_stdio (Stdio driver is supported on posix)
S  old.test_group.TestExternalLinks.test_unicode_decode (No unicode filename support)
S  old.test_group.TestExternalLinks.test_unicode_encode (No unicode filename support)
S  old.test_group.TestPy2Dict.test_items (Py2)
S  old.test_group.TestPy2Dict.test_iteritems (Py2)
S  old.test_group.TestPy2Dict.test_iterkeys (Py2)
S  old.test_group.TestPy2Dict.test_itervalues (Py2)
S  old.test_group.TestPy2Dict.test_keys (Py2)
S  old.test_group.TestPy2Dict.test_values (Py2)
S  hl.test_dataset_getitem.TestVeryLargeArray.test_size (Maximum integer size >= 2**31 required)
S  hl.test_dataset_swmr.TestSwmrNotAvailable.test_flush_raises (SWMR is available. Skipping backwards compatible tests)
S  hl.test_dataset_swmr.TestSwmrNotAvailable.test_open_swmr_raises (SWMR is available. Skipping backwards compatible tests)
S  hl.test_dataset_swmr.TestSwmrNotAvailable.test_refresh_raises (SWMR is available. Skipping backwards compatible tests)
S  hl.test_dataset_swmr.TestSwmrNotAvailable.test_swmr_mode_raises (SWMR is available. Skipping backwards compatible tests)
X  old.test_dataset.TestCreateData.test_create_bytestring
X  old.test_dataset.TestStrings.test_unicode_write_error
X  hl.test_dataset_getitem.Test1DFloat.test_index_illegal
X  hl.test_dataset_getitem.Test1DFloat.test_indexlist_empty
X  hl.test_dataset_getitem.Test1DZeroFloat.test_indexlist
X  hl.test_dataset_getitem.Test2DZeroFloat.test_indexlist
```

**Comment by aragilar** [comment]
I had a look at this, nothing seems to have changed with the selection code, so unless something has changed with numpy (which we'd presumably see with other versions of python), something has changed in py37.

**Comment by cgohlke** [comment]
The tests now pass with latest builds of CPython, numpy, and HDF5. 
```
Summary of the h5py configuration
---------------------------------

h5py    2.8.0rc1
HDF5    1.10.2
Python  3.7.0b3 (v3.7.0b3:4e7efa9c6f, Mar 29 2018, 17:46:48) [MSC v.1913 32 bit (Intel)]
sys.platform    win32
sys.maxsize     2147483647
numpy   1.14.2
```
```
.....................................................x...............................s...................................x....................................s...s......ss.ss.............................................................................ss....................ssssss...................................................................x....x.........................x......x......................................s..........ssss................
----------------------------------------------------------------------
Ran 454 tests in 1.984s
```
