### ISSUE TITLE
h5py-2.8.0rc1-pp3510-pp3510-win32 test failures/errors

### ISSUE THREAD

**Issue by cgohlke** [h5py/h5py#1012]
```
Summary of the h5py configuration
---------------------------------

h5py    2.8.0rc1
HDF5    1.10.1
Python  3.5.3 (3f6eaa010fce, Jan 11 2018, 04:46:12)
[PyPy 5.10.1 with MSC v.1500 32 bit]
sys.platform    win32
sys.maxsize     2147483647
numpy   1.14.1
```

```
..F.......................FFFF.......................x...............................s...................................x....................................s...s......ss.ss..............................E....................E........E............E......ss....................ssssss...................................E................................x....x.........................x......x......................................s..........ssss.FE..E............
======================================================================
ERROR: tearDownClass (h5py.tests.old.test_file_image.TestFileImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\common.py", line 60, in tearDownClass
    shutil.rmtree(cls.tempdir)
  File "x:\pypy3\lib-python\3\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "x:\pypy3\lib-python\3\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "x:\pypy3\lib-python\3\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\h5py-test_y867m6va\\w_uj9kfn.hdf5'

======================================================================
ERROR: test_copy_external_links (h5py.tests.old.test_group.TestCopy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\old\test_group.py", line 995, in test_copy_external_links
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\h5py-test_ojfl85ul\\c7jy7hsz.hdf5'

======================================================================
ERROR: tearDownClass (h5py.tests.old.test_group.TestCopy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\common.py", line 60, in tearDownClass
    shutil.rmtree(cls.tempdir)
  File "x:\pypy3\lib-python\3\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "x:\pypy3\lib-python\3\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "x:\pypy3\lib-python\3\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\h5py-test_ojfl85ul\\c7jy7hsz.hdf5'

======================================================================
ERROR: tearDownClass (h5py.tests.old.test_group.TestExtLinkBugs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\common.py", line 60, in tearDownClass
    shutil.rmtree(cls.tempdir)
  File "x:\pypy3\lib-python\3\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "x:\pypy3\lib-python\3\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "x:\pypy3\lib-python\3\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\h5py-test_t32a89ek\\oydv8h1f.hdf5'

======================================================================
ERROR: tearDownClass (h5py.tests.old.test_h5t.TestTypeFloatID)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\common.py", line 60, in tearDownClass
    shutil.rmtree(cls.tempdir)
  File "x:\pypy3\lib-python\3\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "x:\pypy3\lib-python\3\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "x:\pypy3\lib-python\3\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\h5py-test_t7g6uyc_\\b3alzu1a.hdf5'

======================================================================
ERROR: tearDownClass (h5py.tests.hl.test_file.TestDealloc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\common.py", line 60, in tearDownClass
    shutil.rmtree(cls.tempdir)
  File "x:\pypy3\lib-python\3\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "x:\pypy3\lib-python\3\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "x:\pypy3\lib-python\3\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\h5py-test_044nlbfy\\illm7z8g.hdf5'

======================================================================
ERROR: tearDownClass (h5py.tests.hl.test_file.TestDriverRegsitration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\common.py", line 60, in tearDownClass
    shutil.rmtree(cls.tempdir)
  File "x:\pypy3\lib-python\3\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "x:\pypy3\lib-python\3\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "x:\pypy3\lib-python\3\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\h5py-test_rfa8k356\\fpqs79oj.hdf5'

======================================================================
FAIL: test_overwrite (h5py.tests.old.test_attrs.TestAccess)
Attributes are silently overwritten
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\old\test_attrs.py", line 58, in test_overwrite
    self.assertEqual(self.f.attrs['a'], 5.0)
AssertionError: 4.0 != 5.0

======================================================================
FAIL: test_complex (h5py.tests.old.test_attrs_data.TestTypes)
Storage of complex types
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\old\test_attrs_data.py", line 124, in test_complex
    self.assertEqual(out.dtype, dt)
AssertionError: dtype('complex64') != dtype('>c8')

======================================================================
FAIL: test_float (h5py.tests.old.test_attrs_data.TestTypes)
Storage of floating point types
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\old\test_attrs_data.py", line 112, in test_float
    self.assertEqual(out.dtype, dt)
AssertionError: dtype('<f4') != dtype('>f4')

======================================================================
FAIL: test_int (h5py.tests.old.test_attrs_data.TestTypes)
Storage of integer types
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\old\test_attrs_data.py", line 100, in test_int
    self.assertEqual(out.dtype, dt)
AssertionError: dtype('int8') != <class 'numpy.int16'>

======================================================================
FAIL: test_string (h5py.tests.old.test_attrs_data.TestTypes)
Storage of fixed-length strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\old\test_attrs_data.py", line 136, in test_string
    self.assertEqual(out.dtype, dt)
AssertionError: dtype('S1') != dtype('S10')

======================================================================
FAIL: test_autoclose (h5py.tests.hl.test_file.TestDealloc)
File objects close automatically when out of scope, but
----------------------------------------------------------------------
Traceback (most recent call last):
  File "x:\pypy3\site-packages\h5py\tests\hl\test_file.py", line 53, in test_autoclose
    self.assertEqual(nfiles(), start_nfiles)
AssertionError: 3 != 2

----------------------------------------------------------------------
Ran 454 tests in 5.359s

FAILED (failures=6, errors=7, skipped=20, expected failures=6)
S  old.test_dataset.TestCreateShape.test_complex256 (No support for complex256)
S  old.test_dimension_scales.TestH5DSBindings.test_label_dimensionscale (Reading non-existent label segfaults)
S  old.test_file.TestClose.test_close_multiple_mpio_driver (Parallel HDF5 is required for MPIO driver test)
S  old.test_file.TestDrivers.test_mpi_atomic (Parallel HDF5 required)
S  old.test_file.TestDrivers.test_mpio (Parallel HDF5 is required for MPIO driver test)
S  old.test_file.TestDrivers.test_sec2 (Sec2 driver is supported on posix)
S  old.test_file.TestDrivers.test_stdio (Stdio driver is supported on posix)
S  old.test_group.TestExternalLinks.test_unicode_decode (No unicode filename support)
S  old.test_group.TestExternalLinks.test_unicode_encode (No unicode filename support)
S  old.test_group.TestPy2Dict.test_items (Py2)
S  old.test_group.TestPy2Dict.test_iteritems (Py2)
S  old.test_group.TestPy2Dict.test_iterkeys (Py2)
S  old.test_group.TestPy2Dict.test_itervalues (Py2)
S  old.test_group.TestPy2Dict.test_keys (Py2)
S  old.test_group.TestPy2Dict.test_values (Py2)
S  hl.test_dataset_getitem.TestVeryLargeArray.test_size (Maximum integer size >= 2**31 required)
S  hl.test_dataset_swmr.TestSwmrNotAvailable.test_flush_raises (SWMR is available. Skipping backwards compatible tests)
S  hl.test_dataset_swmr.TestSwmrNotAvailable.test_open_swmr_raises (SWMR is available. Skipping backwards compatible tests)
S  hl.test_dataset_swmr.TestSwmrNotAvailable.test_refresh_raises (SWMR is available. Skipping backwards compatible tests)
S  hl.test_dataset_swmr.TestSwmrNotAvailable.test_swmr_mode_raises (SWMR is available. Skipping backwards compatible tests)
X  old.test_dataset.TestCreateData.test_create_bytestring
X  old.test_dataset.TestStrings.test_unicode_write_error
X  hl.test_dataset_getitem.Test1DFloat.test_index_illegal
X  hl.test_dataset_getitem.Test1DFloat.test_indexlist_empty
X  hl.test_dataset_getitem.Test1DZeroFloat.test_indexlist
X  hl.test_dataset_getitem.Test2DZeroFloat.test_indexlist
```

**Comment by aragilar** [comment]
Has pypy worked previously? The PermissionErrors look like some kind of race condition with the clean up code, the others are more interesting.

**Comment by tacaswell** [comment]
```pytb
16:34 $ pytest
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.5.3[pypy-6.0.0-final], pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/tcaswell/source/p/h5py, inifile:
collected 458 items                                                                                                                                                                                                                                          

h5py/tests/hl/test_attribute_create.py ..                                                                                                                                                                                                              [  0%]
h5py/tests/hl/test_dataset_getitem.py .......................................x........x....x......................x...                                                                                                                                 [ 17%]
h5py/tests/hl/test_dataset_swmr.py ssss..........                                                                                                                                                                                                      [ 20%]
h5py/tests/hl/test_datatype.py ........                                                                                                                                                                                                                [ 22%]
h5py/tests/hl/test_dims_dimensionproxy.py .                                                                                                                                                                                                            [ 22%]
h5py/tests/hl/test_file.py F..                                                                                                                                                                                                                         [ 23%]
h5py/tests/hl/test_filters.py ..                                                                                                                                                                                                                       [ 24%]
h5py/tests/hl/test_threads.py ..                                                                                                                                                                                                                       [ 24%]
h5py/tests/old/test_attrs.py ..F...........                                                                                                                                                                                                            [ 27%]
h5py/tests/old/test_attrs_data.py .....FFFF...........                                                                                                                                                                                                 [ 31%]
h5py/tests/old/test_base.py .....                                                                                                                                                                                                                      [ 32%]
h5py/tests/old/test_dataset.py .........x............................................................x..........................                                                                                                                       [ 54%]
h5py/tests/old/test_datatype.py ..                                                                                                                                                                                                                     [ 54%]
h5py/tests/old/test_dimension_scales.py ....s................                                                                                                                                                                                          [ 59%]
h5py/tests/old/test_file.py .............ss.....................s........                                                                                                                                                                              [ 68%]
h5py/tests/old/test_file_image.py .                                                                                                                                                                                                                    [ 69%]
h5py/tests/old/test_group.py .................................ssssss...................................................                                                                                                                                [ 88%]
h5py/tests/old/test_h5.py .....                                                                                                                                                                                                                        [ 89%]
h5py/tests/old/test_h5d_direct_chunk_write.py .                                                                                                                                                                                                        [ 90%]
h5py/tests/old/test_h5f.py .....                                                                                                                                                                                                                       [ 91%]
h5py/tests/old/test_h5p.py ......                                                                                                                                                                                                                      [ 92%]
h5py/tests/old/test_h5t.py ....                                                                                                                                                                                                                        [ 93%]
h5py/tests/old/test_objects.py ...                                                                                                                                                                                                                     [ 94%]
h5py/tests/old/test_selections.py ....                                                                                                                                                                                                                 [ 94%]
h5py/tests/old/test_slicing.py .......................                                                                                                                                                                                                 [100%]

========================================================================================================================== FAILURES ==========================================================================================================================
_________________________________________________________________________________________________________________ TestDealloc.test_autoclose _________________________________________________________________________________________________________________

self = <h5py.tests.hl.test_file.TestDealloc testMethod=test_autoclose>

    def test_autoclose(self):
        """ File objects close automatically when out of scope, but
            other objects remain open. """
    
        start_nfiles = nfiles()
        start_ngroups = ngroups()
    
        fname = self.mktemp()
        f = h5py.File(fname, 'w')
        g = f['/']
    
        self.assertEqual(nfiles(), start_nfiles+1)
        self.assertEqual(ngroups(), start_ngroups+1)
    
        del f
    
        self.assertTrue(g)
>       self.assertEqual(nfiles(), start_nfiles)
E       AssertionError: 2 != 1

h5py/tests/hl/test_file.py:53: AssertionError
_________________________________________________________________________________________________________________ TestAccess.test_overwrite __________________________________________________________________________________________________________________

self = <h5py.tests.old.test_attrs.TestAccess testMethod=test_overwrite>

    def test_overwrite(self):
        """ Attributes are silently overwritten """
        self.f.attrs['a'] = 4.0
        self.f.attrs['a'] = 5.0
>       self.assertEqual(self.f.attrs['a'], 5.0)
E       AssertionError: 4.0 != 5.0

h5py/tests/old/test_attrs.py:58: AssertionError
___________________________________________________________________________________________________________________ TestTypes.test_complex ___________________________________________________________________________________________________________________

self = <h5py.tests.old.test_attrs_data.TestTypes testMethod=test_complex>

    def test_complex(self):
        """ Storage of complex types """
        dtypes = tuple(np.dtype(x) for x in ('<c8','>c8','<c16','>c16'))
    
        for dt in dtypes:
            data = np.ndarray((1,), dtype=dt)
            data[...] = -4.2j+35.9
            self.f.attrs['x'] = data
            out = self.f.attrs['x']
>           self.assertEqual(out.dtype, dt)
E           AssertionError: dtype('complex64') != dtype('>c8')

h5py/tests/old/test_attrs_data.py:124: AssertionError
____________________________________________________________________________________________________________________ TestTypes.test_float ____________________________________________________________________________________________________________________

self = <h5py.tests.old.test_attrs_data.TestTypes testMethod=test_float>

    def test_float(self):
        """ Storage of floating point types """
        dtypes = tuple(np.dtype(x) for x in ('<f4','>f4','<f8','>f8'))
    
        for dt in dtypes:
            data = np.ndarray((1,), dtype=dt)
            data[...] = 42.3
            self.f.attrs['x'] = data
            out = self.f.attrs['x']
>           self.assertEqual(out.dtype, dt)
E           AssertionError: dtype('<f4') != dtype('>f4')

h5py/tests/old/test_attrs_data.py:112: AssertionError
_____________________________________________________________________________________________________________________ TestTypes.test_int _____________________________________________________________________________________________________________________

self = <h5py.tests.old.test_attrs_data.TestTypes testMethod=test_int>

    def test_int(self):
        """ Storage of integer types """
        dtypes = (np.int8, np.int16, np.int32, np.int64,
                  np.uint8, np.uint16, np.uint32, np.uint64)
        for dt in dtypes:
            data = np.ndarray((1,), dtype=dt)
            data[...] = 42
            self.f.attrs['x'] = data
            out = self.f.attrs['x']
>           self.assertEqual(out.dtype, dt)
E           AssertionError: dtype('int8') != <class 'numpy.int16'>

h5py/tests/old/test_attrs_data.py:100: AssertionError
___________________________________________________________________________________________________________________ TestTypes.test_string ____________________________________________________________________________________________________________________

self = <h5py.tests.old.test_attrs_data.TestTypes testMethod=test_string>

    def test_string(self):
        """ Storage of fixed-length strings """
        dtypes = tuple(np.dtype(x) for x in ('|S1', '|S10'))
    
        for dt in dtypes:
            data = np.ndarray((1,), dtype=dt)
            data[...] = 'h'
            self.f.attrs['x'] = data
            out = self.f.attrs['x']
>           self.assertEqual(out.dtype, dt)
E           AssertionError: dtype('S1') != dtype('S10')

h5py/tests/old/test_attrs_data.py:136: AssertionError
================================================================================================ 6 failed, 432 passed, 14 skipped, 6 xfailed in 5.89 seconds =================================================================================================
```

I get a similar set of failures locally.  The first I suspect is the details of object de-allocation being different and the rest look like numpy type issues related to endianness.  I am not sure the full numpy test suite passes on pypy yet so I am not super worried.

Not going to block 2.8 on this, re-milestoning to 2.9

**Comment by tacaswell** [comment]
Bumping to the next release (again)

**Comment by takluyver** [comment]
Dropping the milestone - if no-one's working on this, I don't think it's useful to bump it along from release to release.

**Comment by takluyver** [comment]
(Wrong button)
