### ISSUE TITLE
Conflict of 'numpy.pxd' of h5py and numpy package: AttributeError: 'module' object has no attribute 'loadtxt'

### ISSUE THREAD

**Issue by omkar13** [h5py/h5py#1021]
OS: Ubuntu 16.04
Python version: 2.7.14 (Anaconda)
h5py version: 2.7.1
hdf5 version: 1.10.1

The full traceback is as follows:
```pytb
Traceback (most recent call last):
  File "tools/eval.py", line 19, in <module>
    import h5py
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
  File "h5py/numpy.pxd", line 66, in init h5py.h5t
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/__init__.py", line 158, in <module>
    from . import add_newdocs
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/core/__init__.py", line 74, in <module>
    from numpy.testing import _numpy_tester
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/testing/decorators.py", line 6, in <module>
    from .nose_tools.decorators import *
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/testing/nose_tools/decorators.py", line 20, in <module>
    from .utils import SkipTest, assert_warns
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/home/omkar/anaconda3/envs/eval17/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/home/omkar/Documents/Omkar/PycharmProjects/davis-2017-master_modified/python/tools/io.py", line 6, in <module>
    from config import phase,cfg
  File "/home/omkar/Documents/Omkar/PycharmProjects/davis-2017-master_modified/python/tools/config.py", line 118, in <module>
    __C.palette = numpy.loadtxt(__C.PATH.PALETTE,dtype=np.uint8).reshape(-1,3)
AttributeError: 'module' object has no attribute 'loadtxt'

```
There seems to be conflict of modules with the name numpy. I tried uninstalling and reinstalling (using conda manager) numpy as well as h5py but it did not help. I also tried using pip versions but the same error was shown. 

Please let me know how to resolve this issue.

Thank you.

**Comment by tacaswell** [comment]
The problem is that you have a local file shadowing the standard library `io` module.  `io` is imported as part of importing numpy (so the full import is not complete) but your version imports numpy which leads to circular imports.

The solution is to change to a different directory (so your `io.py` is not in the current working directory) or to rename you `io.py` to not shadow a built in module.
