### ISSUE TITLE
'Unable to open file' and 'create file' issue in h5f.pyx

### ISSUE THREAD

**Issue by aGIToz** [h5py/h5py#1030]
HDF5    1.8.18
Python  3.6.3 (default, Nov 28 2017, 18:54:13) 
[GCC 4.9.4]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.14.2

```
Traceback (most recent call last):
  File "/home_expes/tools/python/python-3.6.3_gpu/lib/python3.6/site-packages/h5py/_hl/files.py", line 119, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 1293590528, sblock->base_addr = 0, stored_eoa = 3681077344)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home_expes/tools/python/python-3.6.3_gpu/lib/python3.6/site-packages/h5py/_hl/files.py", line 122, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 1293590528, sblock->base_addr = 0, stored_eoa = 3681077344)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 29, in <module>
    inputs = HDF5DatasetGenerator(config.INPUTS_DB, config.BATCH_SIZE)
  File "/home_expes/aa08110r/SrCNN/chap17/chapter17-super_resolution/myUtils/hdf5datasetgenerator.py", line 20, in __init__
    self.db = h5py.File(dbPath, libver='latest')
  File "/home_expes/tools/python/python-3.6.3_gpu/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home_expes/tools/python/python-3.6.3_gpu/lib/python3.6/site-packages/h5py/_hl/files.py", line 124, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/home_expes/aa08110r/SrCNN/chap17/output/inputs.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
srun: error: calcul-gpu-lahc-3: task 0: Exited with exit code 1

```
I did my best but couldn't find it any previous issues. Kindly help!

**Comment by aragilar** [comment]
That looks like the file is damaged in some way. Try reading it with h5dump, and if that errors, then there is a problem with the file.

**Comment by takluyver** [comment]
Closing as this probably isn't an h5py issue.
