### ISSUE TITLE
Tests test_out_of_order_offsets fail with python-numpy 1.14.3

### ISSUE THREAD

**Issue by pini-gh** [h5py/h5py#1037]
When built against python-numpy 1.14.3 the tests fail with:
```
======================================================================
FAIL: test_out_of_order_offsets (h5py.tests.hl.test_datatype.TestOffsets)
- ----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/hl/test_datatype.py", line 198, in test_out_of_order_offsets
    self.assertArrayEqual(fd['data'], data)
  File "h5py/tests/common.py", line 124, in assertArrayEqual
    "Dtype mismatch (%s vs %s)%s" % (dset.dtype, arr.dtype, message)
AssertionError: Dtype mismatch ({'names':['f1','f3','f2'], 'formats':['<f4','<f8','<i4'], 'offsets':[0,8,16], 'itemsize':20} vs {'names':['f1','f2','f3'], 'formats':['<f4','<i4','<f8'], 'offsets':[0,16,8], 'itemsize':20})

======================================================================
FAIL: test_out_of_order_offsets (h5py.tests.old.test_h5t.TestCompound)
- ----------------------------------------------------------------------
Traceback (most recent call last):
  File "h5py/tests/old/test_h5t.py", line 61, in test_out_of_order_offsets
    self.assertEqual(tid.dtype, expected_dtype)
AssertionError: dtype({'names':['f1','f3','f2'], 'formats':['<f4','<f8','<i4'], 'offsets':[0,8,16], 'itemsize':20}) != dtype({'names':['f1','f2','f3'], 'formats':['<f4','<i4','<f8'], 'offsets':[0,16,8], 'itemsize':20})

- ----------------------------------------------------------------------
Ran 447 tests in 1.206s

FAILED (failures=2, skipped=18, expected failures=6)
```
These tests are successful with the previous python-numpy release in Debian (1.13.3).

 * Operating System = Debian unstable
 * Python version 2.7.15rc1
* python-numpy version 1.14.3
 * h5py version 2.7.1
 * HDF5 version 1.10.0-patch1

**Comment by tacaswell** [comment]
Can you please try with the 2.8.0rc1 currently on pypi ?

**Comment by pini-gh** [comment]
I've successfully tested release 2.8.0 fron the Github repo. Any idea about which commit(s) solve the problem? I'd like to submit a patch against the Debian package in order to not depend on the packaging of the new release. Thanks.

**Comment by pini-gh** [comment]
Must be 5009e06 obviously.

**Comment by pini-gh** [comment]
Closing.
