### ISSUE TITLE
Unable to create attribute (Object header message is too large)

### ISSUE THREAD

**Issue by kitchoi** [h5py/h5py#1053]
* Operating System: Windows 7, Mac OSX 10.11
 * Python version: 2.7, 3.6
 * Where Python was acquired: EDM
 * h5py version: 2.7.0
 * HDF5 version: 1.8.16

Attempting to write a long array of strings as an HDF5 attribute results in an error.
To reproduce:

```
import os
import shutil
import tempfile

import numpy
import h5py

print(h5py.version.info)

attrs = numpy.arange(3117, dtype=numpy.int64).astype("S")
tempdir = tempfile.mkdtemp()
filepath = os.path.join(tempdir, "tmp.h5")

try:
    with h5py.File(filepath, "w") as fhandle:
        fhandle.attrs["Name"] = attrs
finally:
    os.remove(filepath)
    shutil.rmtree(tempdir)
```

Traceback:
```
---------------------------------

h5py    2.7.0
HDF5    1.8.16
Python  3.6.0 |Enthought, Inc. (x86_64)| (default, Mar  3 2017, 03:26:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.13.3

h5py version: 2.7.0
hdf5 version: 1.8.16
Traceback (most recent call last):
  File "VM_shared/create_attr.py", line 18, in <module>
    fhandle.attrs["Name"] = attrs
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/vagrant/workspace/lay-eggs/c25aeab8/pisi/tmp/h5py-2.7.0-2/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/vagrant/workspace/lay-eggs/c25aeab8/pisi/tmp/h5py-2.7.0-2/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "/Users/kchoi/.edm/envs/h5py36/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 93, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/Users/kchoi/.edm/envs/h5py36/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 188, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/vagrant/workspace/lay-eggs/c25aeab8/pisi/tmp/h5py-2.7.0-2/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/vagrant/workspace/lay-eggs/c25aeab8/pisi/tmp/h5py-2.7.0-2/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5a.pyx", line 47, in h5py.h5a.create (/Users/vagrant/workspace/lay-eggs/c25aeab8/pisi/tmp/h5py-2.7.0-2/work/h5py-2.7.0/h5py/h5a.c:2075)
RuntimeError: Unable to create attribute (Object header message is too large)
```

I believe this is not a limitation of HDF5. Furthermore, the array here is small enough to be supported: https://support.hdfgroup.org/HDF5/faq/limits.html

**Comment by chutongz** [comment]
Hi, I'm having the same problem as yours.
```
Traceback (most recent call last):
  File "INQ.py", line 258, in <module>
    verbose=2)
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1705, in fit
    validation_steps=validation_steps)
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1256, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/keras/callbacks.py", line 458, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py", line 2591, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/keras/models.py", line 185, in save_model
    optimizer_weights_group.attrs['weight_names'] = weight_names
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/h5py/_hl/attrs.py", line 188, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 47, in h5py.h5a.create
RuntimeError: Unable to create attribute (object header message is too large)
```

Did you fix it?

**Comment by khinsen** [comment]
One more case, running a Python program that worked fine two years ago. The code is too large to post here (but I can deposit it somewhere if useful). The traceback:

```
Traceback (most recent call last):
  File "<protein_random_walk.ap>:/code/astral_msds", line 44, in <module>
  File "/home/hinsen/Development/activepapers/activepapers-python/lib/activepapers/execution.py", line 390, in __setitem__
    stamp(node, "data", self._codelet.dependency_attributes())
  File "/home/hinsen/Development/activepapers/activepapers-python/lib/activepapers/utility.py", line 78, in stamp
    shape = (len(value),), dtype=h5vstring)
  File "/Users/hinsen/anaconda3/envs/py35/lib/python3.5/site-packages/h5py/_hl/attrs.py", line 183, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2541)
  File "h5py/h5a.pyx", line 47, in h5py.h5a.create (-------src-dir--------/h5py/h5a.c:1812)
RuntimeError: Unable to create attribute (Object header message is too large)
> /home/hinsen/projects/protein_random_walk/active_paper/h5py/h5a.pyx(47)h5py.h5a.create (-------src-dir--------/h5py/h5a.c:1812)()
```

This is from an execution under macOS, but the same happens under Linux. Both platforms run h5py 2.8.0, but different versions of HDF5 (1.8.6 under macOS, 1.10.3 under Linux).

**Comment by emilwallner** [comment]
I'm facing the same problem. It worked on Keras 2.2.2, but when I updated to the current master I started seeing this issue. 

```
"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 188, in create attr = h5a.create(self._id, self._e(tempname), htype, space)
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5a.pyx", line 47, in h5py.h5a.create
RuntimeError: Unable to create attribute (Object header message is too large)
```

**Comment by khinsen** [comment]
@youngmit Yes, everything was exactly the same. I ran the exact same Python code and used the exact same input data. Only the versions of all the software was different. In fact, I was re-running the code to check if I would still get the same output.

@tacaswell I tried this last year before posting, but didn't succeed. This looks like a Heisenbug, even minor changes to the code that affect the output file make it disappear.

What I can try is do another test run with recent code versions, if that would help. Not before next week though because I don't have the input datasets at hand right now.

**Comment by khinsen** [comment]
@youngmit I was aware of that limitation, but since I was just reproducing a computation that worked before, I had mentally excluded it from the list of possible causes. However, now that I rethink it, the attributes I set are the results of nontrivial computations and might have become bigger due to a bug in some other code involved. I'll explore this next week.

**Comment by aragilar** [comment]
I'm going to tag this as a good first issue, the patch(es) will need to add `H5Pset_attr_phase_change` to https://github.com/h5py/h5py/blob/master/h5py/api_functions.txt, add a wrapper function to https://github.com/h5py/h5py/blob/master/h5py/h5a.pyx, and then expose a pythonic version via https://github.com/h5py/h5py/blob/master/h5py/_hl/attrs.py (you don't need to do everything in one PR).

**Comment by dota17** [comment]
Update: The `track_order` can effect the result, this quit surprising.

**Comment by erikhuck** [comment]
For those of you still struggling with this, to elaborate on @dota17's comment, you can set the `track_order` parameter of the `create_group` or `create_dataset` function to `True` and that inexplicably allows you to create attributes of seemingly unlimited size. This is not an ideal solution, and @selmanozleyen is working on a better solution in #2311 , but in the meantime setting `track_order` to `True` is an incredibly simple workaround.
