### ISSUE TITLE
Issue saving np.longdouble in version 2.8.0

### ISSUE THREAD

**Issue by dguest** [h5py/h5py#1077]
I found something pretty odd working on osx 10.11.6, python 3.6.4, h5py 2.8.0 as installed via pip. I have the same issue working with python 3.6.1 on a CentOS-derived system (Scientific Linux CERN SLC release 6.9).

When I save a `np.longdouble` I don't get sensible results. The following few lines reproduce the error:

```python
import h5py
import numpy as np

f = h5py.File('test.h5', 'w')
ald = np.arange(10, dtype=np.longdouble)
f.create_dataset('longd', data=ald)
af = np.arange(10, dtype=float)
f.create_dataset('float', data=af)
f.close()
```

when I run `h5ls -d test.h5` I get this

```
float                    Dataset {10}
    Data:
        (0) 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
longd                    Dataset {10}
    Data:
        (0) 6.95322106680147e-310, 6.95322106680147e-310, 6.95322106680147e-310, 6.95322106680147e-310, 6.95322106680147e-310, 6.95322106680147e-310,
        (6) 6.95322106680147e-310, 6.95322106680147e-310, 6.95322106680147e-310, 6.95322106680147e-310
```

When I try to convert the dataset back to a numpy array within the script I also get an exception: 

```
Traceback (most recent call last):
  File "h5py/h5t.pyx", line 1397, in h5py.h5t._c_float
KeyError: <class 'numpy.float128'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./break-script.py", line 9, in <module>
    print(ds, np.array(ds))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 696, in __array__
    self.read_direct(arr)
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 657, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 171, in h5py.h5d.DatasetID.read
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1636, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1403, in h5py.h5t._c_float
TypeError: Unsupported float type (float128)
```

I also found that I can fix this by backporting to 2.7.1, but **this only works on the CentOS machine**. On OSX I get the same problem.

**Comment by will133** [comment]
I'm running python 2.7 on a CentOS box and I want to second this issue.  I have some existing files that's written with float128 and I can't seem to read it back with h5py 2.8.0 (with the same "Unsupported float type" issue).  Thus, I don't think it's purely a writer problem.

I downgraded to 2.7.1 and it would seem fine.  It seems like the float128 dtype handler is not happy in the _c_float function.  I was upgrading from 2.6.x where the float128 was initially implemented so there's probably something changed from 2.7.1 to 2.8 that caused this bug.

**Comment by will133** [comment]
Going through the history it seems there's quite a bit of the change in how the float type is handled in this change set:

https://github.com/h5py/h5py/commit/14fff7ae7b66cdd7b79bf2f454ed7f34efadf3f7

This happens after the 2.7.1 release, so it may be what's causing the behavior to be different.

**Comment by tacaswell** [comment]
git bisect agrees that 14fff7ae7b66cdd7b79bf2f454ed7f34efadf3f7 is the first bad commit.


```python
import h5py
import numpy as np

with h5py.File('/tmp/test.h5', 'w') as f:
    ald = np.arange(10, dtype=np.longdouble)
    f.create_dataset('longd', data=ald)
    af = np.arange(10, dtype=float)
    f.create_dataset('float', data=af)

print('done writing')

with h5py.File('/tmp/test.h5', 'r') as f:
    print(f['longd'][:].dtype)
    print(f['float'][:].dtype)

```

The float128 support is ending up in the 'native' mapping, but not the LE or BE mappings.

```
In [14]: h5py.h5t._get_float_dtype_to_hdf5()
Out[14]: 
({numpy.float16: <h5py.h5t.TypeFloatID at 0x7f922956f678>,
  numpy.float32: <h5py.h5t.TypeFloatID at 0x7f922955e888>,
  numpy.float64: <h5py.h5t.TypeFloatID at 0x7f922955e938>},
 {numpy.float16: <h5py.h5t.TypeFloatID at 0x7f922956f620>,
  numpy.float32: <h5py.h5t.TypeFloatID at 0x7f922955e8e0>,
  numpy.float64: <h5py.h5t.TypeFloatID at 0x7f922955e990>},
 {numpy.float16: <h5py.h5t.TypeFloatID at 0x7f922956f678>,
  numpy.float32: <h5py.h5t.TypeFloatID at 0x7f922955e888>,
  numpy.float64: <h5py.h5t.TypeFloatID at 0x7f922955e938>,
  numpy.float128: <h5py.h5t.TypeFloatID at 0x7f922956f308>})

```

I suspect the bug is in ` _get_available_ftypes` or `_get_float_dtype_to_hdf5` where we match the hdf5 types against the numpy types.

**Comment by tacaswell** [comment]
ok, making slow progresses on this.  The issue is that we were using IEEE_FLOAT128 which is not a float type that real systems actually support (see 
http://numpy-discussion.10968.n7.nabble.com/float128-in-fact-float80-td8761.html ).  np.float128 tends to map to 80 bit floats.

Else where is the code we have a bunch of logic to fix the mapping between hdf5 <-> numpy, but it is missing here.  PR will be coming in a few hours (have working code, but out of time on the train to push!).
