### ISSUE TITLE
Problem with numpy dtype size.

### ISSUE THREAD

**Issue by mingwandroid** [h5py/h5py#1080]
Hi,

This is probably more of a question than a bug report. On AD we like to build against an old numpy and take advantage of its forward binary compatibility promises (see: e.g. https://stackoverflow.com/a/18369312/3257826)

This has worked well for ages on all 3 main OSes, but today it's started to fail on Linux during builds of h5py.

The error originates at https://github.com/cython/cython/blob/23c68023df41b91654a739c4ff55bdb4e4c7249c/Cython/Utility/ImportExport.c

I notice that there's a `strict` parameter which in this case must be enabled.

Is what we are doing correct and is there some bug or other related to this or should we build a h5py against each numpy version we support? It would be great if someone can assist us here!

 * OS: CentOS6
 * Python version: tested 2.7, but likely any
 * Where Python was acquired: Anaconda
 * h5py version: 2.8.0
 * HDF5 version: 1.8.20
 * The full traceback/stack trace shown (if it appears)

```
===== testing package: h5py-2.8.0-py27h39dcb92_2 =====
running run_test.py
Traceback (most recent call last):
  File "/opt/conda/conda-bld/h5py_1534359802648/test_tmp/run_test.py", line 5, in <module>
    import h5py
  File "/opt/conda/conda-bld/h5py_1534359802648/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python2.7/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
  File "h5py/numpy.pxd", line 66, in init h5py.h5t
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 52, got 56
Tests failed for h5py-2.8.0-py27h39dcb92_2.tar.bz2 - moving package to /opt/conda/conda-bld/broken
WARNING:conda_build.build:Tests failed for h5py-2.8.0-py27h39dcb92_2.tar.bz2 - moving package to /opt/conda/conda-bld/broken
removing: h5py-2.8.0-py27h39dcb92_2.tar.bz2
TESTS FAILED: h5py-2.8.0-py27h39dcb92_2.tar.bz2
```

**Comment by mingwandroid** [comment]
OK this is likely a user error. I built against 1.11 then tested against 1.9, oops.
