### ISSUE TITLE
Unable to create file on CentOS (unable to lock file, errno = 37, error message = 'No locks available')

### ISSUE THREAD

**Issue by jerermyyoung** [h5py/h5py#1082]
Hi everyone 
I'm using Python 3.6.3 on CentOS 7.4.1108. My h5py version is 2.8.0 with HDF5 version being 1.10.2 and numpy 1.14.5. When I trying to create a file following the tutorial, I encountered with such problem

>>> import h5py
>>> import numpy as np
>>> with h5py.File("mytestfile.hdf5", "w") as f:
...     dset = f.create_dataset("mydataset", (100,), dtype='i')
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user02/opt/python3/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/user02/opt/python3/lib/python3.6/site-packages/h5py/_hl/files.py", line 148, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 37, error message = 'No locks available')

I'm testing a remote server which used NFS file format so I wonder it's the file format that causes this problem. But I have no idea on how to solve it. Is there anyone having similar problems?

**Comment by vasole** [comment]
Hello,

We faced a similar (the same?) problem with an NFS mounted file system. At the client side of the NFS (where we were running h5py), we were able to workaround the issue by setting the environment variable HDF5_USE_FILE_LOCKING to the five-character string 'FALSE'. The actual fix came from one of our system administrators who changed some of the NFS parameters at the server side. Unfortunately that knowledge was not shared with us. If you are successful with the workaround you are very likely facing the same issue.

**Comment by jerermyyoung** [comment]
@vasole Seems that it works well on our server...Now I can create .h5 file on it. Thanks a lot and I think that this issue can be closed if nobody post the 'actual fix' that you mentioned.

**Comment by alanlivio** [comment]
Just to registred here I was able to bypass the error by using the variable HDF5_USE_FILE_LOCKING='FALSE' from the command line.
