### ISSUE TITLE
TypeError: __cinit__() takes exactly 1 positional argument (0 given)

### ISSUE THREAD

**Issue by CynthiaChuang** [h5py/h5py#1092]
When I use ```torch.multiprocessing``` and ```get_context('spawn')``, I get the  following  message.

```
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "stringsource", line 5, in h5py.h5f.__pyx_unpickle_FileID
  File "h5py/_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
```

To assist reproducing bugs, please include the following:
 * Operating System  : Ubuntu 16.04
 * Python version : 3.6.5
 * Where Python was acquired : pypi
 * h5py version: 2.8.0
 * HDF5 version  1.10.2

**Comment by tacaswell** [comment]
Can you reproduce this with out `torch`?  I suspect this bug report should go to them.

Can you provide a minimal example of how to reproduce this issue?

The underlying c/c++ objects hold file handles which are not readily pickable.  I suspect that what ever you are trying to push across the multiprocessing edge, it is better to push the filename / dataset name and construct the h5py object on the worker (rather than creating the object in the parent, pickling it, and reconstructing it on the worker).

**Comment by nanda-malve** [comment]
The following snippet resulting in the same error:
```
h5f = h5py.File(path_for_model, 'r')
pickled_value = pickle.dumps(h5f)
unpickled_value = pickle.loads(pickled_value)
```

```
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Traceback (most recent call last):
  File "pickle_test.py", line 23, in <module>
    unpickled_value = pickle.loads(pickled_value)
  File "stringsource", line 5, in h5py.h5f.__pyx_unpickle_FileID
  File "h5py/_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
```

**Comment by takluyver** [comment]
With #1194 merged, pickle will explicitly fail with a clearer error message. To use h5py with multiprocessing, you should therefore either:

1. Transfer the paths to the file and the paths to objects inside the file, and explicitly open the HDF5 files you need within each worker, or:
2. Use [h5pickle](https://github.com/exteris/h5pickle), which is basically just a wrapper to do option 1 automatically.
