### ISSUE TITLE
problem with using as multiprocessing.pool shared memory

### ISSUE THREAD

**Issue by alexxchen** [h5py/h5py#1102]
```
def func(view_name, view, serial_str_keys_data_views, file_path):
    file = h5py.File(file_path, 'r')
    view = dict(view)
    for label, label_group in view.items():
        label_group = dict(label_group)
        view[label] = label_group
        for subject_id, value in label_group.items():
            label_group[subject_id] = file[serial_str_keys_data_views][view_name][label][subject_id][()]
    file.close()
    return view_name, view


p_func = partial(func, serial_str_keys_data_views=self._serial_str_keys.data_views, file_path=file_path)

    with multiprocessing.Pool(3) as pool:     
         for i, view_name, view in enumerate(pool.imap_unordered(p_func, data_views.items())):
              data_views[view_name] = view
```

 * Operating System Ubuntu 16.04.2 LTS
 * Python version 3.6.5
 * Where Python was acquired  Anaconda on Linux
 * h5py version 2.7.1
 * HDF5 version 1.10.2
 * The full traceback/stack trace shown (if it appears)

```
Process ForkPoolWorker-56:
Traceback (most recent call last):
  File "/home/jh/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jh/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jh/anaconda3/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/jh/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "stringsource", line 5, in h5py.h5g.__pyx_unpickle_GroupID
  File "h5py/_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
```

I have tried a lot, but still not working. So what's the point that I didn't get? Thanks

Update
I find out the problem is about the restriction that processes should have independent attribute,
but the problem is multiprocessing does not support HDF5 file as shared memory, how can I mapping it into a dict or something to meet the requirement?
Or is there any package support HDF5 as shared memory?

**Comment by takluyver** [comment]
Similar: #1092

**Comment by takluyver** [comment]
And the underlying issue: #531

**Comment by takluyver** [comment]
With #1194 merged, pickle will explicitly fail with a clearer error message. To use h5py with multiprocessing, you should therefore either:

1. Transfer the paths to the file and the paths to objects inside the file, and explicitly open the HDF5 files you need within each worker, or:
2. Use [h5pickle](https://github.com/exteris/h5pickle), which is basically just a wrapper to do option 1 automatically.
