### ISSUE TITLE
Cannot create dataset with sole dot as name

### ISSUE THREAD

**Issue by hdkire** [h5py/h5py#1106]
* Operating System: MacOS 10.13.6
* Python version: Python 3.6.6 MacPorts
* H5py version: 2.8.0
* Hdf5 version: 1.10.2
* Steps to reproduce:
```
import h5py
f = h5py.File('w', 'w')
f.create_dataset(name='.', data=[])
```
=>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    f.create_dataset(name='.', data=[])
  File ".../venv36/lib/python3.6/site-packages/h5py/_hl/group.py", line 119, in create_dataset
    self[name] = dset
  File ".../venv36/lib/python3.6/site-packages/h5py/_hl/group.py", line 287, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)
```

**Comment by aparamon** [comment]
It is a limitation of HDF5 library, but I bet you'll fail to create a file named "." is your OS, too.
