### ISSUE TITLE
Import h5py (import _errors)

### ISSUE THREAD

**Issue by BordiaS** [h5py/h5py#1128]
I get the following error while importing h5py (python 2.7)
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: cannot import name _errors

Please advice.

Thanks,
Shikha

**Comment by chrisjbillington** [comment]
It looks like you might be running python from within the directory that h5py is installed to. For some reason I don't quite follow, importing h5py from that location doesn't work. But it should import fine if you change to a different directory first.

**Comment by tacaswell** [comment]
@BordiaS How did you install h5py?  When we have seen that sort of import error, it tends to be due to a croupted installation.

**Comment by mthirani** [comment]
@chrisjbillington @tacaswell 
I have the same issue, Currently trying to make it work with spark-submit command.
Created a wheel file based on my requirements.txt file which has **h5py==2.10.0**
Wheel package is created based on Spark document: https://issues.apache.org/jira/browse/SPARK-6764. 
Below command used to create h5py wheel package out of it

`pip wheel --wheel-dir /home/hadoop/allmodules --requirement requirements.txt`.

`-rwxrwxrwx 1 hadoop hadoop  2801807 Apr 24 23:33 h5py-2.10.0-cp27-cp27mu-manylinux1_x86_64.whl`

`[hadoop@ip-172-31-33-105 ~]$ spark-submit --py-files $(find /home/hadoop/wheel_allmodules/ -name "*.whl" -print0 | sed -e 's/\x0/,/g') s3://mthirani/scripts/hdf_json_metadata_multi_files_compressed_distributed_v4.py s3://mthirani/hd5_files s3://mthirani/json_files_1/
Warning: Ignoring non-spark config property: yarn.nodemanager.pmem-check-enabled=false
Warning: Ignoring non-spark config property: yarn.nodemanager.vmem-check-enabled=false
Traceback (most recent call last):
  File "/mnt/tmp/spark-6ad08044-465d-4b9c-ab11-432cc7764523/hdf_json_metadata_multi_files_compressed_distributed_v4.py", line 7, in <module>
    import h5py
  File "/home/hadoop/wheel_allmodules/h5py-2.10.0-cp27-cp27mu-manylinux1_x86_64.whl/h5py/__init__.py", line 26, in <module>
    
ImportError: cannot import name _errors
20/04/24 23:34:44 INFO ShutdownHookManager: Shutdown hook called
20/04/24 23:34:44 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-6ad08044-465d-4b9c-ab11-432cc7764523
`

Spark Version: 2.4.3
Python Version: 2.7.16
`NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
`

Any suggestions?

**Comment by aragilar** [comment]
@mthirani This looks like an issue with spark, I'm not familiar with it enough to understand why, but I suspect it's not installing things properly.
