### ISSUE TITLE
Error trying to do chunked, compressed parallel write with MPI

### ISSUE THREAD

**Issue by rabernat** [h5py/h5py#1159]
I am trying to do a chunked, compressed parallel write using h5py. My test script is a slightly modified version of the [one from the docs](http://docs.h5py.org/en/stable/mpi.html#using-parallel-hdf5-from-h5py):
```python
from mpi4py import MPI
import h5py
import numpy as np

rank = MPI.COMM_WORLD.rank  # The process ID (integer 0-3 for 4-process run)

f = h5py.File('parallel_test.hdf5', 'w', driver='mpio', comm=MPI.COMM_WORLD)

dset = f.create_dataset('test', (4, 1000), dtype='i',
                        chunks=(1, 1000), compression="gzip")
dset[rank] = np.full(1000, rank)

f.close()
```

I run this via `mpirun -np 4 python basic_hdf_write.py`. This produces the error:

```
_frozen_importlib:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 88 from C header, got 96 from PyObject
Traceback (most recent call last):
  File "basic_hdf_write.py", line 11, in <module>
    dset[rank] = np.full(1000, rank)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/rigel/ocp/users/ra2697/conda/envs/hdf5_zarr/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 708, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't write data (Can't perform independent write with filters in pipeline.
    The following caused a break from collective I/O:
        Local causes: independent I/O was requested; datatype conversions were required
        Global causes: independent I/O was requested; datatype conversions were required)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't close file, there are objects still open)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[25903,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

Googline the `Can't perform independent write with filters in pipeline` error lead me to the following HDF5 threads:
- https://groups.google.com/forum/#!topic/h5py/bElGpATAwAI
- https://forum.hdfgroup.org/t/parallel-i-o-does-not-support-filters-yet/884 (March '18)
- https://www.hdfgroup.org/2018/04/why-should-i-care-about-the-hdf5-1-10-2-release/ (describes how to use compression with HDF5 parallel applications)
- https://forum.hdfgroup.org/t/compressed-parallel-writing-problem/4979/2 (Oct. '18)

It sounds like compressed, parallels writes should definitely work with HDF5 1.10.4 (the version I am using with h5py). However, the h5py docs don't give any examples of how to use this feature.

I would appreciate any suggestions you may have.

My h5py was installed from the [new conda-forge build with mpi support](https://github.com/conda-forge/h5py-feedstock/pull/45). I am on Linux.
```
h5py    2.9.0
HDF5    1.10.4
Python  3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.15.0
```
I am using Open MPI version 3.1.2.

**Comment by aparamon** [comment]
Thank you for the report!

Does it work if you replace
````py
dset[rank] = np.full(1000, rank)
````
with
````py
with dset.collective:
    dset[rank] = np.full(1000, rank)
````
?

(It is unfortunate that `collective` helper is not documented in http://docs.h5py.org/en/stable/mpi.html, only in https://github.com/h5py/h5py/blob/master/examples/collective_io.py)

**Comment by rabernat** [comment]
Thanks for the suggestion! Sounds promising...

But unfortunately no, the `collective` context manager makes no difference. Same exact error.

**Comment by aparamon** [comment]
Hmm, I think now we need to bisect the root of the problem between h5py and HDF5 library.
@rabernat Could I kindly ask you to try to reproduce your program in C? I'm a bit afraid of setting up and debugging MPI correctly, and the only C MPI code I've ever written was for some ancient SPARCs during my university times ;-)

**Comment by rabernat** [comment]
Hi @aparamon - thanks for your helpful reply!

> Could I kindly ask you to try to reproduce your program in C?

Unfortunately this is beyond my programming expertise. I would have no idea where to start. It's not a project I can undertake.

**Comment by epourmal** [comment]
I suggest you try HDF5 1.10.5 and the OpenMPI 4.0.0. There were known issues in HD5 and OpenMPI. Please see this [document](https://portal.hdfgroup.org/display/knowledge/OpenMPI+Build+Issues) on HDF5 and OpenMPI.

**Comment by chanshing** [comment]
Has this been resolved? Does the example work with HDF5 1.10.5?

**Comment by a6** [comment]
I can confirm that this error is still present, even with using the collective helper, with HDF5 1.10.5, h5py 2.9.0, and OpenMPI 3.1.4.

**Comment by cbyrohl** [comment]
Same problem occurs with HDF5 1.10.4, h5py 2.9.0 and IntelMPI 2018.2

**Comment by epourmal** [comment]
HDF5 parallel compression will work only when H5Dwrite is a collective call (all processes in communicator participate). Could you please verify that this is indeed the the case?

I also suggest to check the issue with HDF5 1.10.5.

**Comment by ivan-usov** [comment]
@rabernat , in your example there are actually 2 issues reported by h5py:
```
OSError: Can't write data (Can't perform independent write with filters in pipeline.
    The following caused a break from collective I/O:
        Local causes: independent I/O was requested; datatype conversions were required
        Global causes: independent I/O was requested; datatype conversions were required)
```
A suggestion by @aparamon to make writes within a collective context manager solves the first issue (independent I/O was requested).

An explicit conversion of your data to int will solve the second issue:
```python
with dset.collective:
    dset[rank] = np.full(1000, rank, dtype='i')
```

At least, it works for me with
```
python                    3.6.9                h265db76_0
h5py                      2.10.0          mpi_mpich_py36haaae0f6_1    conda-forge
hdf5                      1.10.5          mpi_mpich_ha7d0aea_1004    conda-forge
```

**Comment by lsawade** [comment]
Just for posterity, I attached a code with an added complexity that is writing irregularly size arrays using offset to the same array. There were a couple of hiccups. This seems to work for me without any problem!

Quite necessary was the qualifier
```
if offsets[rank]-offsets[rank+1] > 0:
```
without which the program would just hang [In my use case, I only need to write from some processors].


```python
import numpy as np
from mpi4py import MPI
import h5py


comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

N = np.array([3, 4, 0, 2])
Ntot = np.sum(N)
offsets = np.hstack((np.array([0]), np.cumsum(N)))

if size != 4:
    raise ValueError('This was made to be run with 4 processors.')

if rank == 0:
    x = np.random.randint(0, high=500, size=(3, 1000), dtype='f')
elif rank == 1:
    x = np.random.randint(0, high=500, size=(4, 1000), dtype='f')
elif rank == 2:
    x = np.random.randint(0, high=500, size=(0, 1000), dtype='f')
elif rank == 3:
    x = np.random.randint(0, high=500, size=(2, 1000), dtype='f')

comm.Barrier()

with h5py.File('parallel_test.h5', 'w', driver='mpio', comm=comm) as db:

    dset = db.create_dataset('test', (Ntot, 1000), dtype='f',
                             chunks=(1, 1000), compression="gzip")
    with dset.collective:
        if offsets[rank]-offsets[rank+1] > 0:
            dset[offsets[rank]:offsets[rank+1], :] = x

```

It is important to note that I compiled `HDF5` "by hand" using installed cluster `gcc`, and `openmpi`.


<details>
<summary><code>h5pcc -showconfig </code></summary>

```
           SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.12.2
                  Configured on: Tue Nov 15 13:47:08 EST 2022
                  Configured by: lsawade@traverse.princeton.edu
                    Host system: powerpc64le-unknown-linux-gnu
              Uname information: Linux traverse.princeton.edu 4.18.0-372.32.1.el8_6.ppc64le #1 SMP Fri Oct 7 11:37:39 EDT 2022 ppc64le ppc64le ppc64le GNU/Linux
                       Byte sex: little-endian
             Installation point: /scratch/gpfs/lsawade/SpecfemMagicGF/packages/hdf5/build

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables: 
                        LDFLAGS: -L/usr/local/cuda-11.7/lib64
                     H5_LDFLAGS: 
                     AM_LDFLAGS: 
                Extra libraries: -lz -ldl -lm 
                       Archiver: ar
                       AR_FLAGS: cr
                         Ranlib: ranlib

Languages:
----------
                              C: yes
                     C Compiler: /usr/local/openmpi/4.0.4/gcc/ppc64le/bin/mpicc ( gcc (GCC) 8.5.0 20210514 )
                       CPPFLAGS: 
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS: 
                        C Flags: 
                     H5 C Flags:  -std=c99  -Wall -Wcast-qual -Wconversion -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wshadow -Wundef -Wwrite-strings -pedantic -Wno-c++-compat -Wlarger-than=2560 -Wlogical-op -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wsync-nand -Wstrict-overflow=5 -Wno-unsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wmaybe-uninitialized -Wdate-time -Warray-bounds=2 -Wc99-c11-compat -Wduplicated-cond -Whsa -Wnormalized -Wnull-dereference -Wunused-const-variable -Walloca -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=1 -Wrestrict -Wattribute-alias -Wcast-align=strict -Wshift-overflow=2 -fstdarg-opt  -s  -Wbad-function-cast -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-sign -Wpointer-to-int-cast -Wint-to-pointer-cast -Wredundant-decls -Wstrict-prototypes -Wswitch -Wunused-function -Wunused-variable -Wunused-parameter -Wcast-align -Wunused-but-set-variable -Wformat -Wincompatible-pointer-types -Wint-conversion -Wshadow -Wcast-function-type -Wmaybe-uninitialized -Wno-aggregate-return -Wno-inline -Wno-missing-format-attribute -Wno-missing-noreturn -Wno-overlength-strings -Wno-jump-misses-init -Wno-suggest-attribute=const -Wno-suggest-attribute=noreturn -Wno-suggest-attribute=pure -Wno-suggest-attribute=format -Wno-suggest-attribute=cold -Wno-suggest-attribute=malloc -O3
                     AM C Flags: 
               Shared C Library: yes
               Static C Library: yes


                        Fortran: yes
               Fortran Compiler: /usr/local/openmpi/4.0.4/gcc/ppc64le/bin/mpif90 ( Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-targets=powerpcle-linux --disable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --with-cpu-32=power8 --with-tune-32=power8 --with-cpu-64=power8 --with-tune-64=power8 --build=ppc64le-redhat-linux built with gcc version 8.5.0 20210514 (Red Hat 8.5.0-10) (GCC))
                  Fortran Flags: 
               H5 Fortran Flags:  -std=f2008  -Waliasing -Wall -Wcharacter-truncation -Wextra -Wimplicit-interface -Wsurprising -Wunderflow -pedantic -Warray-temporaries -Wintrinsics-std -Wimplicit-procedure -Wreal-q-constant -Wfunction-elimination -Wrealloc-lhs -Wrealloc-lhs-all -Wno-c-binding-type -Winteger-division -Wfrontend-loop-interchange   -s -O3
               AM Fortran Flags: 
         Shared Fortran Library: yes
         Static Fortran Library: yes

                            C++: no

                           Java: no


Features:
---------
                     Parallel HDF5: yes
  Parallel Filtered Dataset Writes: yes
                Large Parallel I/O: yes
                High-level library: yes
Dimension scales w/ new references: no
                  Build HDF5 Tests: yes
                  Build HDF5 Tools: yes
                      Threadsafety: no
               Default API mapping: v112
    With deprecated public symbols: yes
            I/O filters (external): deflate(zlib)
                               MPE: 
                     Map (H5M) API: no
                        Direct VFD: no
                        Mirror VFD: no
                (Read-Only) S3 VFD: no
              (Read-Only) HDFS VFD: no
                           dmalloc: no
    Packages w/ extra debug output: none
                       API tracing: no
              Using memory checker: no
   Memory allocation sanity checks: no
            Function stack tracing: no
                  Use file locking: best-effort
         Strict file format checks: no
      Optimization instrumentation: no
```

</details>

**Comment by orioltinto** [comment]
Hi,
I think my problem might be related.
I'm trying to use parallel h5py to write to different variables from different MPI processes and I'm finding a quite strange buggy behaviour when using compression.

```python
def debug_parallel_write(compression=None, length:int = 5):
    from mpi4py import MPI
    import h5py
    import contextlib

    comm = MPI.COMM_WORLD

    rank: int = comm.Get_rank()
    size: int = comm.Get_size()

    with h5py.File(f'parallel_test_{str(compression)}.h5', 'w', driver='mpio', comm=comm) as f:
        datasets = {}
        # Create a dataset for each rank.
        for i in range(size):
            datasets[i] = f.create_dataset(f"dataset_{i}", (size, length), "i8", chunks=(1, length), compression=compression)

        # Use contextlib to deal with multiple context managers.
        ctx_managers = [ds.collective for ds in datasets.values()]
        with contextlib.ExitStack() as stack:
            for mgr in ctx_managers:
                stack.enter_context(mgr)
            
            value = 10*(rank+1)
            print(f"Rank {rank} saving {value} in {datasets[rank].name} row {rank}")
            # Each rank writes to a slice of its corresponding dataset.
            datasets[rank][rank,:] = value

if __name__ == "__main__":
    debug_parallel_write()
    debug_parallel_write("gzip")
```

If I run this code with `mpirun -n 2 python debug_parallel_write.py" I obtain the following results:

```
Case: compression=None
    Rank 0 saving 10 in /dataset_0 row 0
    Rank 1 saving 20 in /dataset_1 row 1
Case: compression='gzip'
    Rank 0 saving 10 in /dataset_0 row 0
    Rank 1 saving 20 in /dataset_1 row 1
```
The log look as expected and without compression the results look correct:
`h5dump parallel_test_None.h5`
```
HDF5 "parallel_test_None.h5" {
GROUP "/" {
   DATASET "dataset_0" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 2, 5 ) / ( 2, 5 ) }
      DATA {
      (0,0): 10, 10, 10, 10, 10,
      (1,0): 0, 0, 0, 0, 0
      }
   }
   DATASET "dataset_1" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 2, 5 ) / ( 2, 5 ) }
      DATA {
      (0,0): 0, 0, 0, 0, 0,
      (1,0): 20, 20, 20, 20, 20
      }
   }
}
}
```

However, with compression (gzip in this case) the resulting dataset has the values in the wrong place and it seems that both processes write to the same dataset (?).
`h5dump parallel_test_gzip.h5`
```

HDF5 "parallel_test_gzip.h5" {
GROUP "/" {
   DATASET "dataset_0" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 2, 5 ) / ( 2, 5 ) }
      DATA {
      (0,0): 0, 0, 0, 0, 0,
      (1,0): 0, 0, 0, 0, 0
      }
   }
   DATASET "dataset_1" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 2, 5 ) / ( 2, 5 ) }
      DATA {
      (0,0): 10, 10, 10, 10, 10,
      (1,0): 20, 20, 20, 20, 20
      }
   }
}
}
```

I don't even have an idea about what can be happening here. Any clue?
