### ISSUE TITLE
import h5py: undefined symbol: H5Ovisit_by_name

### ISSUE THREAD

**Issue by qmpzzpmq** [h5py/h5py#1172]
To assist reproducing bugs, please include the following:
 * Operating System Ubuntu 16.04.2 LTS
 * Python version 3.6
 * Where Python was acquired: Anaconda
 * h5py version 2.9.0.post0
 * HDF5 version 1.10.4
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

I installed mpi hdf5 as following:
```
export CC=mpicc
python setup.py configure --mpi 
python setup.py build
python setup.py install
```
but when in import h5py, it shows that
`/home/studenter/haoyut/anaconda3/lib/python3.6/site-packages/h5py/defs.cpython-36m-x86_64-linux-gnu.so: undefined symbol: H5Ovisit_by_name`

it seems with lib things, I have add this to my .bashrc:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/studenter/haoyut/local_install/hdf5-1.10.4/install/lib
export LD_RUN_PATH=$LD_RUN_PATH:/home/studenter/haoyut/local_install/hdf5-1.10.4/install/lib`

**Comment by qmpzzpmq** [comment]
`ImportError: /home/studenter/haoyut/anaconda3/lib/python3.6/site-packages/h5py/defs.cpython-36m-x86_64-linux-gnu.so: undefined symbol: H5Ovisit_by_name
Traceback (most recent call last):
  File "paralleltest.py", line 2, in <module>
    import h5py
  File "/home/studenter/haoyut/anaconda3/lib/python3.6/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5r.pxd", line 21, in init h5py._conv
  File "h5py/_objects.pxd", line 12, in init h5py.h5r
  File "h5py/_objects.pyx", line 1, in init h5py._objects
ImportError: /home/studenter/haoyut/anaconda3/lib/python3.6/site-packages/h5py/defs.cpython-36m-x86_64-linux-gnu.so: undefined symbol: H5Ovisit_by_name`

**Comment by aparamon** [comment]
Hi @qmpzzpmq!
You've just been hit by https://forum.hdfgroup.org/t/c-c-abi-stability-and-binary-compatibility-between-patch-versions/5312.
It will be fixed in the upcoming HDF5 1.10.5: https://forum.hdfgroup.org/t/hdf5-1-10-5-pre1-available-for-testing/5436.

**Comment by takluyver** [comment]
HDF5 1.10.5 is out now - does that mean this can be closed?

**Comment by lldelisle** [comment]
Unfortunately the problem is still present. 
I still have the issue when I use python 3.7:
With conda:
`conda create --name justh5pypy3.6 h5py python=3.6
conda activate justh5pypy3.6
python -c "import h5py"
# No issue
conda install python=3.7
python -c "import h5py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5r.pxd", line 21, in init h5py._conv
  File "h5py/_objects.pxd", line 12, in init h5py.h5r
  File "h5py/_objects.pyx", line 1, in init h5py._objects
ImportError: /usr/lib/python3.7/site-packages/h5py/defs.cpython-37m-x86_64-linux-gnu.so: undefined symbol: H5Ovisit_by_name`
If you need more log, do not hesitate.
Thanks,

Lucille

**Comment by takluyver** [comment]
I don't think this is anything to do with the Python version, but rather the version of libhdf5.

**Comment by lldelisle** [comment]
How could I check that with conda?

**Comment by takluyver** [comment]
`conda list` should show you which version of HDF5 you have installed. But I think this also depends what version of hdf5 was there when h5py was built, and I don't know how to tell that if you can't import the package. You could try recompiling h5py from source.

**Comment by lldelisle** [comment]
When I do conda list I have `hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge` for both.
But you are write what is important should be which version was used to compile:
`h5py                        2.9.0-nompi_py36hf008753_1102 --> 2.9.0-nompi_py37hf008753_1102`.
I am going to try to install from binaries but you are right this does not depend on python version. I have python3.7 and h5py working well... It might be something with the conda version no?

**Comment by lldelisle** [comment]
When I look at the archive files on conda in the info/recipe/meta.yaml I find:
```
     run:
        - hdf5 >=1.10.4,<1.10.5.0a0
```
But I do not know where is the conda recipe...

**Comment by lldelisle** [comment]
I guess this is:
[https://github.com/conda-forge/h5py-feedstock/blob/master/recipe/conda_build_config.yaml](here)

**Comment by lldelisle** [comment]
bgruening made a [PR](https://github.com/conda-forge/h5py-feedstock/pull/58). I hope it will solve the issue.

**Comment by bgruening** [comment]
@lldelisle can you try this again?

**Comment by lldelisle** [comment]
```
conda create -n testh5py h5py
conda activate testh5py
python --version
# Python 3.7.3
python -c "import h5py"
```
It worked, many thanks.
