### ISSUE TITLE
OSError: Can't write data (can't open directory)

### ISSUE THREAD

**Issue by Daniel-Nabil-Artil** [h5py/h5py#1209]
Hi,

so my code was running and after few times it started sending errors for commands that were working already.

I stated the error with all data requested please let me know what could be the problem.
Thanks

 * Operating System (Windows 8.1)
 * Python version (3.7)
 * Where Python was acquired (Anaconda)
 * h5py version (e.g. 2.9)
 * HDF5 version (e.g. 1.10.4)

h5py    2.9.0
HDF5    1.10.4
Python  3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.15.4

Traceback (most recent call last):

  File "<ipython-input-1-9a231eb9b73f>", line 1, in <module>
    runfile('C:/Users/Daniel/Documents/Master/ThermoVault/Data/h5.py', wdir='C:/Users/Daniel/Documents/Master/ThermoVault/Data')

  File "C:\Users\Daniel\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\Daniel\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Daniel/Documents/Master/ThermoVault/Data/h5.py", line 59, in <module>
    f1['building1/elec/meter6/table'][1]=(1436047212000000000, [0])

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "C:\Users\Daniel\Anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 708, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5d.pyx", line 221, in h5py.h5d.DatasetID.write

  File "h5py\_proxy.pyx", line 132, in h5py._proxy.dset_rw

  File "h5py\_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite

OSError: Can't write data (can't open directory)

**Comment by aparamon** [comment]
Hi @Daniel-Nabil-Artil,
Thank you for reporting the problem! Could you please provide the problematic code, so that h5py maintainers could help you localize and eliminate the issue?

**Comment by Daniel-Nabil-Artil** [comment]
thank you for your reply
here is the code
please let me know if you can help

`#.h5

import numpy as np
import h5py

h5_path = r'C:\Users\Daniel\Documents\Python Scripts\nilmtk-master\data\DRED1.h5'

f = h5py.File(r'C:\Users\Daniel\Documents\Python Scripts\nilmtk-master\data\DRED1.h5','r+')

print(list(f.items()))
print(list(f.keys()))

a_group_key = list(f.keys())[0]

data = list(f[a_group_key].items())

d = list(f.items())

s = f.get('building1')
print(list(s.items()))

m = f.get('building1/elec')
print(list(m.items()))

m = f.get('building1/elec/cache')
print(list(m.items()))

m = f.get('building1/elec/cache/meter6')
print(list(m.items()))

m = f.get('building1/elec/meter1')
print(list(m.items()))

m = f.get('building1/elec/meter1/_i_table')
print(list(m.items()))

m = f.get('building1/elec/meter1/_i_table/index')
print(list(m.items()))

m_ = m.get('abounds')
print(np.array(m_))

m = m.get('indices')
print(np.array(m))

dd = f.get('building1/elec/meter1')
print(f['building1/elec/meter6/table'])

dd = f.get('building1/elec/meter4')
print(np.array(dd.get('table')))
#
#dd = f.get('building1/elec/meter6')  #elec_ heater
#print(np.array(dd.get('table')[1]))


f.close()

f1 = h5py.File(h5_path, 'r+')     # open the file
f1['building1/elec/meter6/table'][1]=(1436047212000000000, [0]) 

dd = f1.get('building1/elec/meter6')
print(np.array(dd.get('table')[1]))

f1.close()  `

the problem happens at  tthis line
```
dd = f.get('building1/elec/meter1')
print(f['building1/elec/meter6/table'])
```
or similarly
`f1 = h5py.File(h5_path, 'r+')     # open the file
f1['building1/elec/meter6/table'][1]=(1436047212000000000, [0]) `

**Comment by aragilar** [comment]
Possibly the issue is related to replacing `meter1` with `meter6` sometimes? I think we'd the the code which created the file or the original file.
