### ISSUE TITLE
Parallel HDF5 h5py test Wrong

### ISSUE THREAD

**Issue by tyszwh** [h5py/h5py#1215]
Hi guys

 I complied hdf5 with the option --enable-parallel --enable-shared, and then build the h5py with the following guide 
```
$ export CC=mpicc
$ python setup.py configure --mpi [--hdf5=/path/to/parallel/hdf5]
$ python setup.py build). 
```

However, the following test is wrong. I can not figure out the reason. 

f = h5py.File('parallel_test.hdf5', 'w', driver='mpio', comm=MPI.COMM_WORLD)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.7/site-packages/h5py/_hl/files.py", line 391, in __init__
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
  File "/usr/local/python3/lib/python3.7/site-packages/h5py/_hl/files.py", line 132, in make_fapl
    set_fapl(plist, **kwds)
  File "/usr/local/python3/lib/python3.7/site-packages/h5py/_hl/files.py", line 45, in _set_fapl_mpio
    plist.set_fapl_mpio(**kwargs)
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'
```

**Comment by takluyver** [comment]
It sounds like it hasn't successfully built against MPI for some reason. You can double check with:

```python
h5py.h5.get_config().mpi
```

I don't know what might have gone wrong.

**Comment by tyszwh** [comment]
The problem has been solved after I reinstall mpich and hdf5. Thanks very much.
