### ISSUE TITLE
Empty fancy index selection yields UnboundLocalError: local variable 'count' referenced before assignment

### ISSUE THREAD

**Issue by JohannesBuchner** [h5py/h5py#1223]
* Ubuntu Linux  18.04
* (system) Python  3.6.7 (default, Oct 22 2018, 11:32:17) 
* h5py    2.9.0
* HDF5    1.10.4
* [GCC 8.2.0]
* sys.maxsize     9223372036854775807
* numpy   1.16.3

Code like:

```
import h5py
import numpy as np

fileobj = h5py.File('test.h5')
fileobj.create_dataset('points', shape=(10, 10))
idx = np.arange(0)
print(fileobj['points'][idx,:])

```

Should return an empty array (because nothing is selected, idx = [])

Instead, it produces the following exception, and an error in the exception handling:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: only size-1 arrays can be converted to Python scalars

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/testsine.py", line 86, in <module>
    main(args)
  ...
  File "/path/to/mydir/store.py", line 166, in _load
    self.data = list(self.fileobj['points'][idx,:])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 398, in __getitem__
    mshape = list(count)
UnboundLocalError: local variable 'count' referenced before assignment
```

**Comment by takluyver** [comment]
This will be possible in h5py 2.10, following PR #1174. It's a [documented limitation](http://docs.h5py.org/en/stable/high/dataset.html#fancy-indexing) in the current version.
