### ISSUE TITLE
SWMR mode does not work with vlen_strings

### ISSUE THREAD

**Issue by arolin** [h5py/h5py#1273]
* Operating System Windows 10
Summary of the h5py configuration
---------------------------------
h5py    2.9.0
HDF5    1.10.4
Python  3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.13.3

The writer
```python
import h5py
f = h5py.File("swmr.h5", 'w', libver='latest')
dt = h5py.special_dtype(vlen=bytes)
dset = f.create_dataset("data", shape=(0,), maxshape=(None,), dtype=dt)
f.swmr_mode = True
# Now it is safe for the reader to open the swmr.h5 file
for i in range(5):
    dset.resize( (dset.shape[0]+1,) )
    dset[-1] = "hello world"
    dset.flush()
    # Notify the reader process that new data has been written
input("press enter")
```

The reader
```
import h5py
f = h5py.File("swmr.h5", 'r', libver='latest', swmr=True)
print(f["data"][:])
```
If the file has been properly closed in the writer the reader will succeed.

If the file is still open in the writer (waiting at the input in the reader)  or the writer was aborted without closing the file, the the reader will error as such:
```
Traceback (most recent call last):
  File "C:/sandbox/applanixmanager/PyEnsco/PyENSCO/HDF5Utils/test/scrach_swmr_reader.py", line 3, in <module>
    print(f["data"][:])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\sandbox\applanixmanager\win_venv\lib\site-packages\h5py\_hl\dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py\_proxy.pyx", line 158, in h5py._proxy.dset_rw
  File "h5py\_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (address of object past end of allocation)
```

The reader works as expected if the dtype is set to something simple like int.

**Comment by tacaswell** [comment]
This is coming up out of libhdf5, are we sure SWMR is implemented for vlen datasets?

**Comment by epourmal** [comment]
Current version of HDF5 SWMR doesn't support VL types. The limitation will be removed in the new version of SWMR (SWMR VFD). Recommend to close this issue.
