### ISSUE TITLE
Cant use SWMR mode on file writted by instrument

### ISSUE THREAD

**Issue by naxsor** [h5py/h5py#1276]
#Specifications:
 * Operating System; Windows 10
 * Python version: 2.7
 * h5py: 2.5
 * HDF5 version: 1.10 

I'm reading a HDF5 file generated by and instrument called the WIBS-NEO. I'm trying to read that file while being written. While doing it i received an 'addr overflow', so i was trying to implement SWMR mode on my file. But when run it i receive an error. This is the code.

```
 with h5.File(self.file_path, 'r+', libver='latest') as file:
            print (file.libver)
            file.swmr_mode = True
            Monitored_Data = file.get('NEO/MonitoringData') #Get Monitoring Group
            Particle_Data = file.get('NEO/ParticleData') #Get Particle Group
            file.visititems(get_objects) #Visil al items in the file`
 
`Traceback (most recent call last):
('earliest', 'latest')
  File "C:/Users/naxso/PycharmProjects/ACAS/Main/Tester/test.py", line 17, in <module>
    read = reader('Main/File_Samples/20190619143438__x2.h5')
  File "C:\Users\naxso\PycharmProjects\ACAS\Main\Readers\reader.py", line 13, in __init__
    self.extension_reader()
  File "C:\Users\naxso\PycharmProjects\ACAS\Main\Readers\reader.py", line 26, in extension_reader
    self.readerNEO
  File "C:\Users\naxso\PycharmProjects\ACAS\Main\Readers\reader.py", line 72, in readerNEO
    file.swmr_mode = True
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Python27\lib\site-packages\h5py\_hl\files.py", line 302, in swmr_mode
    self.id.start_swmr_write()
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 538, in h5py.h5f.FileID.start_swmr_write
ValueError: Unable to convert file format (file superblock version - should be at least 3)
```

[@tacaswell edited to tweak md markup]

**Comment by tacaswell** [comment]
For SWMR to work the writing needs to be SWMR aware and declare it as such when it is created.  This is a constraint of hdf5 (to make SWMR work there is a bit of extra book-keeping and hand-shaking in writing things to the file to make sure you always get an atomically consistent view).

I am going to close this because there is nothing we can do about this on the h5py side, you need to take this up with your hardware vendor (good luck!).
