### ISSUE TITLE
Not compatible with tensorflow 

### ISSUE THREAD

**Issue by caseyhcjen** [h5py/h5py#1280]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7) -- Windows 10
 * Python version (e.g. 2.7, 3.5) -- python 3.7.3 
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows) -- Anaconda
 * h5py version (e.g. 2.6) --2.9.0 (release date 2019/8/8)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

========================
The latest released version has below issue when import tensorflow.
However, when replace with the version of 2018/12/21, the issue was gone. 
========================
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\.conda\envs\tf\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\.conda\envs\tf\lib\site-packages\tensorflow\python\__init__.py", line 82, in <module>
    from tensorflow.python import keras
  File "C:\Users\.conda\envs\tf\lib\site-packages\tensorflow\python\keras\__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "C:\Users\.conda\envs\tf\lib\site-packages\tensorflow\python\keras\activations.py", line 24, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "C:\Users\.conda\envs\tf\lib\site-packages\tensorflow\python\keras\utils\__init__.py", line 34, in <module>
    from tensorflow.python.keras.utils.io_utils import HDF5Matrix
  File "C:\Users\.conda\envs\tf\lib\site-packages\tensorflow\python\keras\utils\io_utils.py", line 29, in <module>
    import h5py
  File "C:\Users\.conda\envs\tf\lib\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\h5r.pyx", line 145, in init h5py.h5r
AttributeError: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'

**Comment by tacaswell** [comment]
Which conda channels did you install from?

https://github.com/cython/cython/issues/1953 seems related, I suspect that this issue due to miss-matched versions of cython used to compile and should be reported to anaconda as a build issue.

**Comment by caseyhcjen** [comment]
I get most recently python packages from channel --> conda-forge 
via create new environment --> conda create -n tf python=3.7.3 anaconda

I also check the file on conda-forge (https://anaconda.org/conda-forge/h5py/files) --> h5py-2.9.0-nompi_py36h422b98e_1104.tar.bz2 (the file compiled date is 2019-08-08 ) which match with the one on my machine.

However, therefore is no any issue in the h5py package of the default Anaconda3-2019.07-Windows-x86_64.exe (which the file released date is 2018/12/21) while import.

Thanks

==================
Issue on just import h5py
==================
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\.conda\envs\pybase\lib\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\_objects.pxd", line 12, in init h5py.h5r
  File "h5py\_objects.pyx", line 1, in init h5py._objects
ImportError: DLL load failed: The specified procedure could not be found.
