### ISSUE TITLE
Bad Object Header Error When Reading Large Unicode Strings

### ISSUE THREAD

**Issue by SamChill** [h5py/h5py#1284]
To assist reproducing bugs, please include the following:
 * Operating System: **Ubuntu 18.04.2 LTS**
 * Python version: **3.7.1**
 * Where Python was acquired: **pyenv**
 * h5py version: **2.9.0**
 * HDF5 version: **1.10.4**
 * The full traceback/stack trace shown (if it appears)

```
Traceback (most recent call last):
  File "minimal_failure.py", line 15, in <module>
    assert(hdf5[dset_name][()] == long_string)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/schill/git/quantumsource-dev/external-libs/build/lib/python3.6/site-packages/h5py-2.7.1-p
y3.6-linux-x86_64.egg/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (bad object header version number)'
```

I am trying to create a dataset with a very large unicode string. If the string is larger than 2^25 - 512 bytes (i.e. 33,553,920 bytes or larger) then the above exception is raised upon reading the dataset. Here is the code to reproduce:

```python
import h5py

# Any size larger or equal to this fails with libver='latest', but works with
# libver='earliest'.
size = (2**25 - 512) + 1
long_string = size * 's'
filename = 'test.hdf5'
dset_name = 'longstring'

with h5py.File(filename, 'w', libver='latest') as hdf5:
    hdf5.create_dataset(dset_name, data=long_string)

with h5py.File(filename, 'r', libver='latest') as hdf5:
    assert(hdf5[dset_name][()] == long_string)
```
Interestingly, with `libver='earliest'` this works fine. Also, if instead of using a unicode string, I instead save raw binary data using `numpy.void` and encoding the string as utf-8, it works fine.

Does anyone know what is going on here? I didn't except to run into this type of size limitation with HDF5 and I would prefer not to have to work around this issue.

**Comment by takluyver** [comment]
Have you tried storing the same data with the HDF5 C API?

**Comment by aragilar** [comment]
The assert passes for me on Debian Unstable on py38 with the latest master (HDF5 1.10.6)

**Comment by takluyver** [comment]
I tested and also couldn't reproduce this - probably something got fixed in HDF5 at some point.
