### ISSUE TITLE
Issue reading szip compressed datasets with anaconda install vs pip install

### ISSUE THREAD

**Issue by dwr-psandhu** [h5py/h5py#1293]
**conda install h5py and reading a h5 file with szip compression causes error above. No issues reading tables in same file with no compression.**

Uninstalling h5py and installing using pip works fine for all tables. 

To reproduce just try to read a h5 file with szip compressed data or i can provide a sample one

 * Windows10
 * Python version 3.7
 * Anaconda
 * h5py version (2.9.0)
 * HDF5 version (1.10+ or whatever h5py installs)

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "d:\Programs\Anaconda2\envs\dsm2\lib\site-packages\h5py\_hl\dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py\_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py\_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (can't open directory)

**Comment by tacaswell** [comment]
This looks like a build issue and should be reported against who ever built the conda package you were using.

As it works with the wheel, it is very unlikely that there is a bug in h5py that we can do anything about.

**Comment by dwr-psandhu** [comment]
@tacaswell Do you know who is submitting the h5py to conda-forge?

**Comment by tacaswell** [comment]
Please report bugs with conda-forge packages at their feedstocks (https://github.com/conda-forge/h5py-feedstock/issues for h5py).
