### ISSUE TITLE
Copy a group of h5py files to another h5py file

### ISSUE THREAD

**Issue by kingdsz** [h5py/h5py#1329]
```python
f1 = h5py.File('./out_my_model/ResNet50/only_input1_ResNet50_model.h5','a')
f2 = h5py.File('./out_my_model/ResNet50/only_input2_ResNet50_model.h5','a')
f3 = h5py.File('./out_my_model/ResNet50/only_input3_ResNet50_model.h5','a')

f1['model_weights']['conv1_2']=f2['model_weights']['conv1_2']
f1['model_weights']['conv1_3']=f3['model_weights']['conv1_3']
```

```
Traceback (most recent call last):
  File "C:/Users/54631/PycharmProjects/keras_one-label/dong.py", line 130, in <module>
    f1['model_weights']['conv1_2']=f2['model_weights']['conv1_2']
  File "C:\Users\54631\Anaconda3\envs\keras\lib\site-packages\h5py\_hl\group.py", line 371, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (interfile hard links are not allowed)
```

**Comment by takluyver** [comment]
Assigning a dataset object tries to create a hard link to it. To copy it, you need to read the data and write it to the new file. If it's small enough to fit in memory, that's easy:

```python
f1['model_weights']['conv1_2'] = f2['model_weights']['conv1_2'][()]
```

The `[()]` at the end reads it into a numpy array.

If you can't fit it in memory, you'll need to make a new dataset, and then read and write chunks in a loop.

```
f1.create_dataset_like('model_weights/conv1_2', f2['model_weights/conv1_2'])
# Looping left as an exercise to the reader.
```

**Comment by takluyver** [comment]
There is also a `group.copy()` method. I'd hope that's smart enough to copy data without loading it all into memory at once, but I haven't looked into it:

http://docs.h5py.org/en/stable/high/group.html#Group.copy
