### ISSUE TITLE
How to store list with variable dimension (string/numeric values) as attributes in HDF5 

### ISSUE THREAD

**Issue by veritolilo** [h5py/h5py#1397]
Hi, 
I am a new user of h5py. The main idea is to generated a hdf5 file from dlis (digital log interchangeable standard). My issues is mainly that I need to add metadata to each dataset (logs) and also to groups and subgroups into the file. I am using the attributes to do that, however, I have problems with some of the metadata since these are not single values either string or numeric values.  In other words, for the same metadata field i can have different dimension it could be a list with a single value or it could be a list with 3, 4 or 20 values or strings.  I saw the function h5py.special_dtype(vlen=str) but it only works if i have a single string that varies in length but it doesn't work if i have more than one string and if all of them varies in length. At the same time I saw this other function h5py.vlen_dtype(np.dtype('int32')) but this one doesn't work at all. My python doesn't recognized and it should be I think. 
I am trying to generated all this attributes as a part of a loop since I have hundreds or even thousands logs so doing it by hand is not an option.  Part of my code is as follow: 

```python
FILE = "mytestfileEWL1.hdf5"   
for ch in frames[i].channels:
    DATASET=ch.name
    ATTRIBUTE = "Metadata"
    DIM0 = 1
    
    def run():
    
        # Create the compound datatype.
        dtype = np.dtype([("Long-name",  h5py.special_dtype(vlen=str)), 
                          ("Properties",      h5py.special_dtype(vlen=str)),
                          ("Representation-Code",   np.float),
                          ("Units",       h5py.special_dtype(vlen=str)),
                          ("Dimension", h5py.special_dtype(vlen=np.dtype('int32'))),
                          ("Element-Limit", np.int32),
                          ("Frame", h5py.special_dtype(vlen=str)),
                          ("Source", h5py.special_dtype(vlen=str))])
    
        wdata = np.zeros((DIM0,), dtype=dtype)
        wdata['Long-name'] = (ch.long_name)
        wdata['Properties'] = (ch.properties)
        wdata['Representation-Code'] = (ch.reprc)
        wdata['Units'] = (ch.units)
        wdata['Dimension']= (np.array(ch.dimension))
        wdata['Element-Limit']=(ch.element_limit)
        wdata['Frame']=(ch.frame)
        wdata['Source']= (ch.source)
        with h5py.File(FILE, 'r') as f:
            dset=grp[i].create_dataset(DATASET, data=ch.curves())
            dset.attrs.create(ATTRIBUTE, wdata,dtype=dtype)
    
        with h5py.File(FILE) as f:
            rdata = f[dset.name].attrs[ATTRIBUTE]
    
        print(rdata)
    
    
    if __name__ == "__main__":
        run()
```

```
Traceback (most recent call last):

  File "<ipython-input-235-d0b6a741094b>", line 39, in <module>
    run()

  File "<ipython-input-235-d0b6a741094b>", line 30, in run
    dset.attrs.create(ATTRIBUTE, wdata,dtype=dtype)

  File "C:\Users\veront\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\_hl\attrs.py", line 200, in create
    attr.write(data, mtype=htype2)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5a.pyx", line 383, in h5py.h5a.AttrID.write

  File "h5py\_proxy.pyx", line 63, in h5py._proxy.attr_rw

  File "h5py\defs.pyx", line 3405, in h5py.defs.H5Tconvert

  File "h5py\_conv.pyx", line 745, in h5py._conv.ndarray2vlen

AttributeError: 'int' object has no attribute 'dtype'
```

And this is the error when I keep the dimensions as a single integer: 

```python
for ch in frames[0].channels:
    DATASET=ch.name
    ATTRIBUTE = "Metadata"
    DIM0 = 1
    
    def run():
    
        # Create the compound datatype.
        dtype = np.dtype([("Long-name",  h5py.special_dtype(vlen=str)), 
                          ("Properties",      h5py.special_dtype(vlen=str)),
                          ("Representation-Code",   np.float),
                          ("Units",       h5py.special_dtype(vlen=str)),
                          ("Dimension", np.int32),
                          ("Element-Limit", np.int32),
                          ("Frame", h5py.special_dtype(vlen=str)),
                          ("Source", h5py.special_dtype(vlen=str))])
    
        wdata = np.zeros((DIM0,), dtype=dtype)
        wdata['Long-name'] = (ch.long_name)
        wdata['Properties'] = (ch.properties)
        wdata['Representation-Code'] = (ch.reprc)
        wdata['Units'] = (ch.units)
        wdata['Dimension']= (np.array(ch.dimension))
        wdata['Element-Limit']=(ch.element_limit)
        wdata['Frame']=(ch.frame)
        wdata['Source']= (ch.source)
        with h5py.File(FILE, 'r') as f:
            dset=grp[0].create_dataset(DATASET, data=ch.curves())
            dset.attrs.create(ATTRIBUTE, wdata,dtype=dtype)
    
        with h5py.File(FILE) as f:
            rdata = f[dset.name].attrs[ATTRIBUTE]
    
        print(rdata)
    
    
    if __name__ == "__main__":
        run()        
```

```
Traceback (most recent call last):

  File "<ipython-input-243-75c974cf551b>", line 38, in <module>
    run()

  File "<ipython-input-243-75c974cf551b>", line 23, in run
    wdata['Dimension']= (np.array(ch.dimension))

ValueError: could not broadcast input array from shape (2) into shape (1)


Error for the h5py.vlen_dtype(np.dtype('int32')) function: 
h5py.vlen_dtype(np.dtype('int32'))
Traceback (most recent call last):

  File "<ipython-input-244-f24a84cb9dda>", line 1, in <module>
    h5py.vlen_dtype(np.dtype('int32'))

AttributeError: module 'h5py' has no attribute 'vlen_dtype'
 


To assist reproducing bugs, please include the following:
 * Operating System: Windows 10.
 * Python version: 3.6.8
 * Where Python was acquired: Anaconda on Windows
 * h5py version 2.9
 * HDF5 version 1.10.4
 * The full traceback/stack trace shown (if it appears)
h5py.version.info
Out[246]: 'Summary of the h5py configuration\n---------------------------------\n\nh5py    2.9.0\nHDF5    1.10.4\nPython  3.6.8 |Anaconda custom (64-bit)| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]\nsys.platform    win32\nsys.maxsize     9223372036854775807\nnumpy   1.16.4\n'

```

**Comment by takluyver** [comment]
It's probably possible to store all that information in one attribute, but the obvious answer is to store each field ("Long-name", "Properties" etc.) in its own attribute.

**Comment by aragilar** [comment]
I'm going to close this as invalid, as it is more of a request for help/design than an issue.
