### ISSUE TITLE
ValueError: Unable to create group (Name already exists)

### ISSUE THREAD

**Issue by vladimirry** [h5py/h5py#1438]
To assist reproducing bugs, please include the following:
 * Operating System Ubuntu 16.04.2 LTS
 * Python version (3.6)
 * Where Python was acquired (Anaconda on Linux)
 * h5py version (2.7.0)
 * HDF5 version (1.8.17)
 * The full traceback/stack trace shown (if it appears)

I'm creating an HDF5 file with many groups (2476)
The process of group creation and filling in the data stops at group number 1868  with the name
/TTF2.FEL/DELLINE.ENC/IK220.0

Obviously there is no group with the name  /TTF2.FEL/DELLINE.ENC/IK220.0 before.

GROUP[1]: /TTF2.FEL/VDOT32/VDOT32/REG_0_IN
GROUP[2]: /TTF2.FEL/VDOT32/VDOT32/REG_1_IN
GROUP[3]: /TTF2.FEL/VDOT32/VDOT32/REG_1_OUT
GROUP[4]: /TTF2.FEL/VDOT32/VDOT32/REG_2_OUT
GROUP[5]: /TTF2.FEL/VDOT32/VDOT32/REG_3_OUT

....
GROUP[1865]: /TTF2.MAGNETS/QUAD/Q3.5ECOL/PS
GROUP[1866]: /TTF2.MAGNETS/QUAD/RESV-HB1/PS
GROUP[1867]: /TTF2.MAGNETS/QUAD/RESV-HB2/PS
GROUP[1868]: /TTF2.FEL/DELLINE.ENC/IK220.0
Traceback (most recent call last):
  File "/home/rybnikov/test/python/DAQ/raw2hdf5/daqraw2hdf5.py", line 412, in <module>
    group = fd.create_group(groupname)
  File "/opt/anaconda4/lib/python3.6/site-packages/h5py/_hl/group.py", line 52, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/_objects.c:2804)
  File "h5py/h5g.pyx", line 151, in h5py.h5g.create (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/h5g.c:2929)
ValueError: Unable to create group (Name already exists)

**Comment by takluyver** [comment]
Your versions of hdf5 and h5py are both quite old. Can you try this with more recent versions of both?

If you still see the bug, can you try to produce a minimal example that reproduces it? E.g. does it happen if you just create the groups without filling them with data?

**Comment by vladimirry** [comment]
Thank you for the fast reply.
I've installed the latest version and it fails at the same point:

python3.6  daqraw2hdf5_reduced.py 
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.4
Python  3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.14.3

Working with 2476 channels

1858  group:/TTF2.FEL/DELLINE.ENC/IK220.0 Traceback (most recent call last):
  File "/home/rybnikov/test/python/DAQ/raw2hdf5/daqraw2hdf5_reduced.py", line 66, in <module>
    group = fd.create_group(groupname)
  File "/home/rybnikov/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 68, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 161, in h5py.h5g.create
ValueError: Unable to create group (name already exists)



I've attached the python script that reproduces the problem and the required pickle file
[create_grpoup_problem.zip](https://github.com/h5py/h5py/files/3887294/create_grpoup_problem.zip)

**Comment by takluyver** [comment]
I think you're creating child groups (e.g. `/TTF2.FEL/DELLINE.ENC/IK220.0/ENC.CONVERSION`) before a parent group (`/TTF2.FEL/DELLINE.ENC/IK220.0`). Creating the child group automatically creates the parent group as well, so this is expected behaviour.

Depending on your needs, you could do some preprocessing to ensure parent names are before their children (I think sorting the list of names is sufficient), or you could use [require_group()](http://docs.h5py.org/en/latest/high/group.html#Group.require_group), which creates groups only if they don't already exist.
