### ISSUE TITLE
h5py/_hl/selections.py integer division or modulo by zero

### ISSUE THREAD

**Issue by stela2502** [h5py/h5py#1455]
CentOS 7, python3.7, Anaconda 4.7.12, h5py==2.9.0

adata.write( 'dataFile.h5ad' )

adata = anndata.read( 'dataFile.h5ad' )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/anndata/readwrite/read.py", line 447, in read_h5ad
    constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
  File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/anndata/readwrite/read.py", line 486, in _read_args_from_h5ad
    _read_key_value_from_h5(f, d, key, chunk_size=chunk_size)
  File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/anndata/readwrite/read.py", line 510, in _read_key_value_from_h5
    _read_key_value_from_h5(f, d[key_write], key + '/' + k, k, chunk_size)
  File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/anndata/readwrite/read.py", line 522, in _read_key_value_from_h5
    value = ds.value
  File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/anndata/h5py/h5sparse.py", line 318, in value
    object['data'].read_direct(data_array.data)
  File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 732, in read_direct
    for mspace in dest_sel.broadcast(source_sel.mshape):
  File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/h5py/_hl/selections.py", line 309, in broadcast
    chunks = tuple(x//y for x, y in zip(count, tshape) if y != 0 )
  File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/h5py/_hl/selections.py", line 309, in <genexpr>
    chunks = tuple(x//y for x, y in zip(count, tshape) if y != 0 )
ZeroDivisionError: integer division or modulo by zero

**Comment by stela2502** [comment]
A fix that cleared out this problem:
File "/projects/fs1/common/software/Anaconda/4.7.12/lib/python3.7/site-packages/h5py/_hl/selections.py", line 309:

chunks = tuple(x//y for x, y in zip(count, tshape) )

convert to

chunks = tuple(x//y for x, y in zip(count, tshape) if y != 0 )

**Comment by stela2502** [comment]
Is that a valid fix or would it break something?

**Comment by tacaswell** [comment]
That will result in `chunks` being a different length that `count` and `tshape` which I think will generically cause problems in the multi-index ravel logic below.

I suspect that a better place to fix this would be earlier in the function detect that the `target_shape` has a 0 in it so there is no work to do.

Can you trigger this issue without using `anndata`?

**Comment by stela2502** [comment]
I am VERY new to python (like 2 weeks ;-) hence I am kind of glad I found this quick fix.
I have in addition not tried to trigger this issue with anything else than the file that causes the issue.

It seams as if I would not suffer any consequences of the fix in my analysis (as far as I see that). Hence I will just go for the fix. I do not understand python well enough to fix this problem earlier in the function. Or can you point me to the best line? ;-)

**Comment by tacaswell** [comment]
In this function we should have the invariant that the length of  `tshape`, `count`, and `chunks`,  are all the same (as the dimensionality  needs to match).  Your proposed fix violates this by dropping the 0 dimensions which makes the logic in https://github.com/h5py/h5py/blob/81fa9e86bd260bb92fd75deed1ff8f4f1c3fcc9c/h5py/_hl/selections.py#L290-L293 seem wrong (as now the computed offset is going to be the wrong rank for the selection). 

The better fix is to check if we have an 0 dimensions (probably at https://github.com/h5py/h5py/blob/81fa9e86bd260bb92fd75deed1ff8f4f1c3fcc9c/h5py/_hl/selections.py#L281-L283 so it is after verifying that the broadcast is possible but before we do the div-by-0) and returning.

**Comment by aragilar** [comment]
I'm dropping the 2.10.1 milestone, as we're aiming for 3.0 (and this was the last 2.10.1 issue), and there hasn't been any progress on this for a while.

**Comment by takluyver** [comment]
I think this is a duplicate of #870, which already had a straightforward example to reproduce it, so I'll close this one. I've tried to fix it in #2577.
