### ISSUE TITLE
 File "h5py\h5f.pyx", line 88, in h5py.h5f.open OSError    windows10

### ISSUE THREAD

**Issue by Kimtaehung123** [h5py/h5py#1462]
I need help
  File "E:\software\python\python\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "E:\software\python\python\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError

**Comment by takluyver** [comment]
There's not enough information here to understand what went wrong - it looks like the error message is missing.

**Comment by jakeogh** [comment]
I hit the same issue on git-latest (git-latest SDF-Python as well). I am betting on user error since I have no experience with SDF files.

```python3
$ cat test.py 
#!/usr/bin/env python3

import sys
import sdf

if __name__ == "__main__":
    result = sdf.load(sys.argv[1])

$ ls -alh ~/pubchem/Compound/CURRENT-Full/SDF/Compound_000000001_000500000.sdf
-rw-r--r-- 1 user user 2.6G 2020-07-18 14:27:56 /home/user/pubchem/Compound/CURRENT-Full/SDF/Compound_000000001_000500000.sdf

$ # from: ftp://ftp.ncbi.nlm.nih.gov/pubchem/Compound/CURRENT-Full/SDF/Compound_000000001_000500000.sdf.gz

$ head -c 2000 /home/user/pubchem/Compound/CURRENT-Full/SDF/Compound_000000001_000500000.sdf
1
  -OEChem-07162020442D

 31 30  0     1  0  0  0  0  0999 V2000
    2.8660    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.8660   -2.2500    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
    2.0000   -0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.7320    2.2500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.4641    0.2500    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
    4.5981    0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7320    0.2500    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0
    6.3301   -0.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.9641    1.1160    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.9641   -0.6160    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7320   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.8660   -1.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.8660    1.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.0000    2.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.9966    1.2250    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.1996    1.2250    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.7320    0.8700    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    6.0201   -0.7869    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    6.8671   -0.5600    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    6.6401    0.2869    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    6.5010    0.8060    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    6.2741    1.6530    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.4272    1.4260    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.4272   -0.3060    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.6541   -1.1530    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.5010   -0.9260    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.9441   -1.3326    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.3426   -0.6423    0.0000 H   0  0  0  

$ ./test.py /home/user/pubchem/Compound/CURRENT-Full/SDF/Compound_000000001_000500000.sdf
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    result = sdf.load(sys.argv[1])
  File "/usr/lib/python3.7/site-packages/sdf/__init__.py", line 190, in load
    obj = hdf5.load(filename, objectname)
  File "/usr/lib/python3.7/site-packages/sdf/hdf5.py", line 21, in load
    with h5py.File(filename, 'r') as f:
  File "/usr/lib/python3.7/site-packages/h5py/_hl/files.py", line 425, in __init__
    swmr=swmr)
  File "/usr/lib/python3.7/site-packages/h5py/_hl/files.py", line 188, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

**Comment by takluyver** [comment]
For anyone else reading this in the future: HDF5 is a binary format. If you can inspect the data with `head`, it's text based, so it's not HDF5. Technically it's possible to make an HDF5 file with some separate text data stuck on the beginning, but in general if you see text, it's probably not HDF5.

I'm going to close this now, as there wasn't enough information on the original error to make a meaningful issue. `OSError` is fairly generic and could have all sorts of causes.
