### ISSUE TITLE
Capture "file locked" exception

### ISSUE THREAD

**Issue by woutdenolf** [h5py/h5py#1478]
```
h5py    2.9.0
HDF5    1.10.4
Python  3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.17.4
```

When I open a file in append mode but the file is locked I get a chained exception (see below). The first exception is the file locked exception and the second is a file creation exception. To distinguish this file locked exception from others I wanted to catch `OSError` exceptions and check `exc.__cause__.errno == errno.EAGAIN`. However `exc.__cause__.errno is None`. I can do string parsing on the traceback but that's not very elegant.

So how do I distinguish file locked exceptions from other OSError exceptions when opening a file in append mode?

Remark: if a file lock exception is raised, why do we try to create the file? I guess because "Resource temporarily unavailable" can be something else than the file being locked?

```python
Traceback (most recent call last):
  File "/data/id21/inhouse/wout/dev/virtualenvs/rnice8/bliss/py37/lib/python3.7/site-packages/h5py/_hl/files.py", line 182, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    f = h5py.File("test.h5", mode="a")
  File ".../site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File ".../site-packages/h5py/_hl/files.py", line 184, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'test.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)
```

**Comment by takluyver** [comment]
We don't currently provide errno for any errors coming from HDF5, because the HDF5 library itself doesn't store that in any machine readable way - see #1133 and https://forum.hdfgroup.org/t/get-posix-errno-from-hdf5-errors/5003 .

As the error messages stand at the moment, we could scrape it from the message (`errno = (\d+)`), but HDF group have said that there are no guarantees about error messages, and we shouldn't try to parse them.
