### ISSUE TITLE
TypeError: Can't broadcast (1024, 6272) -> (1024, 25088)

### ISSUE THREAD

**Issue by sanolans** [h5py/h5py#1479]
I am trying to save features extracted from a small animal dataset using an encoder, but I got the following error:

```
Traceback (most recent call last):####                          | ETA:  0:00:51
  File "extract_features.py", line 107, in <module>
    dataset.add(features, batchLabels)
  File "D:\Clones\feature_extraction_try\pyimagesearch\io\hdf5datasetwriter.py", line 37, in add
    self.flush()
  File "D:\Clones\feature_extraction_try\pyimagesearch\io\hdf5datasetwriter.py", line 42, in flush
    self.data[self.idx:i] = self.buffer["data"]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\sancy\Anaconda3\envs\tensorflow2\lib\site-packages\h5py\_hl\dataset.py", line 707, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "C:\Users\sancy\Anaconda3\envs\tensorflow2\lib\site-packages\h5py\_hl\selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (1024, 6272) -> (1024, 25088)>
```

I am using tensorflow 2.0, python 3.7.6(Anaconda) on windows 10.

```
h5py    2.9.0
HDF5    1.10.4
Python  3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.17.4
```

Can anyone please tell me what I'm doing wrong? Looking forward to your comments, thanks.

**Comment by takluyver** [comment]
The first tuple is the shape of your data (i.e. an array of 1024 x 6272 elements). The second is the shape of the selected block you're trying to write it into. I don't know precisely what your code is doing, but you most likely need those two shapes to match.

("Broadcasting" means expanding a smaller amount of data to fill a larger shape, which I'm guessing is not what you want)

**Comment by sanolans** [comment]
@takluyver Thanks for your response. The error occurred because I had two different dimensions in my code (128 * 7 * 7 & 512* 7 * 7).
