### ISSUE TITLE
File can not be oneped by h5py but is opened with no issues by HDF View

### ISSUE THREAD

**Issue by Gabriel-p** [h5py/h5py#1488]
The attached file [data.hdf.tar.gz](https://github.com/h5py/h5py/files/4151031/data.hdf.tar.gz) can be opened without issues by [HDF View ](https://www.hdfgroup.org/downloads/hdfview/)v2.11 but can not be opened using `h5py`.

Info:
 * elementary OS 5.1 (based on Ubuntu 18.04)
 * Conda environment (`py3`)
```
(py3) $  python -c 'import h5py; print(h5py.version.info)'
Summary of the h5py configuration
---------------------------------

h5py    2.9.0
HDF5    1.10.4
Python  3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.16.4
```

 * The full traceback/stack trace shown (if it appears)

```
>>> import h5py
>>> filename = 'data.hdf'
>>> data = h5py.File(filename, 'r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

Using `pandas v0.24.2`, same result:
```
>>> import pandas as pd
>>> data = pd.HDFStore(filename, mode='r')
Traceback (most recent call last):
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/pytables.py", line 603, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1604, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 413, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file 'data.hdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/pytables.py", line 488, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/pytables.py", line 636, in open
    raise IOError(str(e))
OSError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1604, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 413, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file 'data.hdf'
```

another approach:

```
>>> data = pd.io.pytables.read_hdf(filename)
Traceback (most recent call last):
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/pytables.py", line 603, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1604, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 413, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file 'data.hdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/pytables.py", line 368, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/pytables.py", line 488, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/gabriel/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/pytables.py", line 636, in open
    raise IOError(str(e))
OSError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1604, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 413, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file 'data.hdf'
```

**Comment by tacaswell** [comment]
That file also can not be opened by `h5ls`.  

```
jupiter@21:25  ➤  tar -xvf data.hdf.tar.gz 
data.hdf
✔  /tmp
jupiter@21:25  ➤  h5ls data.hdf
data.hdf: unable to open file
✘  /tmp
jupiter@21:25  ➤  sha256sum data.hdf
5c60633e68cb0f75b992731eab51913ee9d6ce12573d127ebe1433c5c26882de  data.hdf
✔  /tmp
jupiter@21:26  ➤  h5ls data.hdf.tar.gz 
data.hdf.tar.gz: unable to open file
✘  /tmp
jupiter@21:26  ➤  sha256sum data.hdf.tar.gz 
023dd60ade452fdda659b426a32667f4557f45ff20ee007a54efa19467efff76  data.hdf.tar.gz
✔  /tmp

```

I think that is actually an hdf4 file, not and hdf5 file

```
jupiter@21:26  ➤  head data.hdf
��\B�&(6U�B�V�(V��u��=5�        �r�
��U�
��;�
    �U�
       �s7�     ��[�
�v;���U             ��
       HDF Version 4.2 Release 11, February 5, 2015��x^,�c�#�À��m۶m��]�]۶��v�ɓ�d�����m[o}x?�����ٙIҿz�Y���'��b*#f�bt��y�&����EC�5��}w������jG\�=�nw"�DV����&+��Ŀv�Py Ú�WE.{��|U�_����d=Z#[�/������B��$�▒f��
(MGy�>J����E��f��J騺
```

**Comment by Gabriel-p** [comment]
That would explain it. Thank you @tacaswell!
