### ISSUE TITLE
"S3File object has no attribute closed" when opening from S3

### ISSUE THREAD

**Issue by idavydov** [h5py/h5py#1530]
Hi, I'm trying to open an HDF5 file from S3 using s3fs. And I am using approach proposed here: https://github.com/h5py/h5py/issues/1434#issuecomment-561112367

```python
import s3fs
import h5py
s3 = s3fs.S3FileSystem(...)
with s3.open(url, 'r') as s3file:
    with h5py.File(s3file, 'r') as h5f:
        pass
```

Here is what I get:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-fc3190418f71> in <module>
      1 with s3.open(url, 'r') as s3file:
----> 2     with h5py.File(s3file, 'r') as h5f:
      3         pass

~/.conda/envs/myjupenv/lib/python3.7/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    406                 fid = make_fid(name, mode, userblock_size,
    407                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 408                                swmr=swmr)
    409 
    410             if isinstance(libver, tuple):

~/.conda/envs/myjupenv/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

h5py/defs.pyx in h5py.defs.H5Fopen()

h5py/h5fd.pyx in h5py.h5fd.H5FD_fileobj_read()

AttributeError: 'S3File' object has no attribute 'closed'
```

 * Operating System: Linux/x64
 * Python version: 3.7
 * Where Python was acquired: Anaconda
 * h5py version: 2.10.0
 * HDF5 version 1.10.4
 * s3fs: 0.4.0

```
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.4
Python  3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.18.1
```

**Comment by tacaswell** [comment]
I think this should be reported against `s3fs` as their file-like is not enough like a file.  

That said, the function where this is raising is https://github.com/h5py/h5py/blob/79a5cf835d6e071c76e1baa4c65cbedab9e89093/h5py/h5fd.pyx#L153-L165 so I don't quite understand where we are trying to use `closed`.

**Comment by idavydov** [comment]
@tacaswell at a first glance it seems that S3File has a `closed` attribute. Also see [here](https://github.com/dask/s3fs/issues/313).

 I just tried the following code (on a completely different machine/os):
```
with s3.open(url, 'r') as s3file:
    print(s3file.closed)
    with h5py.File(s3file, 'r') as h5f:
        pass
```

And I got the following output:

```
False
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-1631a055f2fd> in <module>
      1 with s3.open(url, 'r') as s3file:
      2     print(s3file.closed)
----> 3     with h5py.File(s3file, 'r') as h5f:
      4         pass

~/tmp/s3test/lib/python3.7/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    406                 fid = make_fid(name, mode, userblock_size,
    407                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 408                                swmr=swmr)
    409 
    410             if isinstance(libver, tuple):

~/tmp/s3test/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

h5py/defs.pyx in h5py.defs.H5Fopen()

h5py/h5fd.pyx in h5py.h5fd.H5FD_fileobj_read()

AttributeError: 'S3File' object has no attribute 'closed'
```

**Comment by idavydov** [comment]
Ok, it seems that the problem is reading attributes `s3.open(..., 'r')` I changed the code to following and it seems to work now. Thank you.

```python
with s3.open(url, 'rb') as s3file:
    with h5py.File(s3file, 'r') as h5f:
        pass
```

Not sure the error message is a bug or known behaviour.

**Comment by tacaswell** [comment]
My guess is that something is going sideways because we are expecting bytes instead of str or there is a decode error (because it is unlikely that hdf5 byte streams are actually valid utf-8 or any encoding).  During the unwinding of the context manager something else goes wrong but because we are coming out of cython we don't handle the fact that the exception string was changed under us so we get the right (ish) trace back but wrong error message.

If you pass the the text-mode s3file in _not_ in a context manager do you get a more sensible error?

**Comment by idavydov** [comment]
That what happens if I try:
```python
s3file=s3.open(url, 'r')
h5f=h5py.File(s3file, 'r')
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-59828e7c5948> in <module>
      1 s3file=s3.open(url, 'r')
----> 2 h5f=h5py.File(s3file, 'r')

~/tmp/s3test/lib/python3.7/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    406                 fid = make_fid(name, mode, userblock_size,
    407                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 408                                swmr=swmr)
    409 
    410             if isinstance(libver, tuple):

~/tmp/s3test/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

h5py/defs.pyx in h5py.defs.H5Fopen()

h5py/h5fd.pyx in h5py.h5fd.H5FD_fileobj_read()

AttributeError: 'S3File' object has no attribute 'closed'
```

And this is unicode error I get if I read from it:
```python
s3file=s3.open(url, 'r')
x=s3file.read(10)
```

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-42-e35d4da73c1d> in <module>
      1 s3file=s3.open(url, 'r')
----> 2 x=s3file.read(10)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by takluyver** [comment]
So the bug for h5py is that the unicode error which should be exposed is somehow being replaced by the confusing AttributeError.

Is anyone willing to share a public S3 URL for an HDF5 file so other people can quickly test this? I appreciate that would mean paying for data transfer. Or is there a way to test `S3File` with local data which can reproduce the same bug?

**Comment by aragilar** [comment]
s3fs seems to use https://github.com/spulec/moto for testing, @idavydov would you be able to see if you can use that to reproduce your error with s3fs (in case it's not reproducible with it, in which case we would need an actual test bucket).

**Comment by idavydov** [comment]
@aragilar I will try and let you know.

**Comment by takluyver** [comment]
I think I may have found what is mangling errors when using h5py with a Python file object. If someone can conveniently reproduce this, try building h5py from PR #1642 ([instructions for building from source](https://docs.h5py.org/en/stable/build.html#source-installation)).

**Comment by takluyver** [comment]
Can someone try this again with h5py 3.0? We have hopefully fixed the bug that obscured the real error.

**Comment by luyang93** [comment]
```
fs = s3fs.S3FileSystem(...)
file = fs.open("s3://path/to/file.h5ad", 'rb')
h5f = h5py.File(file, 'r')
```
It's work well.


but when read as plain text, 

```
fs = s3fs.S3FileSystem(...)
file = fs.open("s3://path/to/file.h5ad", 'r')
h5f = h5py.File(file, 'r')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/SGRNJ/Public/Software/conda_env/h5py/lib/python3.9/site-packages/h5py/_hl/files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/SGRNJ/Public/Software/conda_env/h5py/lib/python3.9/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
  File "h5py/h5fd.pyx", line 160, in h5py.h5fd.H5FD_fileobj_read
  File "/SGRNJ/Public/Software/conda_env/h5py/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by takluyver** [comment]
OK, I think this is fixed. The `UnicodeDecodeError` is what I'd expect (HDF5 files are binary, so you can't read them as text). The bug here was that h5py was turning the real, meaningful error into a confusing and incorrect one. Now you can see the real error.
