### ISSUE TITLE
"Conversion function not found" when reading h5 file generated on x86?

### ISSUE THREAD

**Issue by rposts** [h5py/h5py#1554]
To assist reproducing bugs, please include the following:
 * Ubuntu 18.04 s390x architecture (big-endian)
 * Python version: 3.6.9
 * Where Python was acquired:  System Python
 * h5py version: 2.10.0
 * HDF5 version: 1.10.4
 * The full traceback/stack trace shown (if it appears)
```
python h5error.py
Failed to find converter for 8 -> b'PYTHON:OBJECT'
Traceback (most recent call last):
  File "h5error.py", line 3, in <module>
    original_keras_version = h5_file.file.attrs['keras_version'].decode('utf8')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/attrs.py", line 81, in __getitem__
    attr.read(arr, mtype=htype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 355, in h5py.h5a.AttrID.read
  File "h5py/_proxy.pyx", line 50, in h5py._proxy.attr_rw
  File "h5py/_proxy.pyx", line 319, in h5py._proxy.needs_bkg_buffer
  File "h5py/_proxy.pyx", line 316, in h5py._proxy.needs_bkg_buffer
KeyError: 'Conversion function not found (no appropriate function for conversion path)'

```
I created a `h5` file on x86 as follows:
```
import h5py as h5

#create file and ASCII attribute
h5_file = h5.File('hdf5_primer.h5')
h5_file.attrs['keras_version'] =b'2.2.1'
original_keras_version = h5_file.file.attrs['keras_version'].decode('utf8')
print(original_keras_version)
```
Then, I tried to read this file on `s390x` architecture where it failed with the following error:
```
import h5py as h5
h5_file = h5.File('hdf5_primer.h5', 'r')
original_keras_version = h5_file.file.attrs['keras_version'].decode('utf8')
print(original_keras_version)

python h5error.py
Failed to find converter for 8 -> b'PYTHON:OBJECT'
Traceback (most recent call last):
  File "h5error.py", line 3, in <module>
    original_keras_version = h5_file.file.attrs['keras_version'].decode('utf8')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/attrs.py", line 81, in __getitem__
    attr.read(arr, mtype=htype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 355, in h5py.h5a.AttrID.read
  File "h5py/_proxy.pyx", line 50, in h5py._proxy.attr_rw
  File "h5py/_proxy.pyx", line 319, in h5py._proxy.needs_bkg_buffer
  File "h5py/_proxy.pyx", line 316, in h5py._proxy.needs_bkg_buffer
KeyError: 'Conversion function not found (no appropriate function for conversion path)'
```
`h5dump` shows:
```
HDF5 "hdf5_primer.h5" {
GROUP "/" {
   ATTRIBUTE "keras_version" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "2.2.1"
      }
   }
}
}
```
I was expecting this to work  but it appears that `CSET H5T_CSET_ASCII` causes issues when saving/reading platform are different(?)

I am not clear if this is an expected behavior.

Thanks for your input.

**Comment by rposts** [comment]
Hi there - can you please let me know if this is a supported scenario?  Storing attribute as string does seem to work across platforms.

Thanks.

**Comment by rposts** [comment]
Closing as duplicate of https://github.com/h5py/h5py/issues/428.
