### ISSUE TITLE
group.copy of dataset does not copy scales, and prevents scales from being attached

### ISSUE THREAD

**Issue by cboulay** [h5py/h5py#1556]
>Summary of the h5py configuration
> h5py    2.10.0
> HDF5    1.10.5
> Python  3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
> sys.platform    win32
> sys.maxsize     9223372036854775807
> numpy   1.18.2

The code segment below creates a dataset in f1 (data dim = (10, 1)), optionally creates a scale in the same file and attaches it to the data set, then uses `group.copy` to copy the dataset to f2.

Can confirm that f2's dataset has the copied data.

Attempting to access f2's dataset.dims[0].keys() results in a RuntimeError (stack trace below code segment). Creating a new scale dataset in f2 then attempting to `attach_scale` also results in an error; anything related to dim0 seems to be broken.

If I skip attaching a scale to dim0 in the first dataset then I am able to attach scales to the second dataset in dim0. Even if I attach a scale to dim0, if I don't attach a scale to dim1 in the first dataset then I can attach a scale to dim1 of the copied dataset; the problem is specific to the axis with the attached scale.

```Python
import h5py
import tempfile
import numpy as np


data = np.log10(np.arange(1, 11).reshape(-1, 1))
channels = np.array([f'c{_}' for _ in range(10)], dtype=object)
attach_scales_ds1 = True

tf1 = tempfile.TemporaryFile()
f1 = h5py.File(tf1, mode='w')
g1 = f1.create_group('grp')
ds1 = g1.create_dataset('data', data=data)

ds1.dims[0].keys()  # []
#  ds1.dims[0][0]  # Unspecified error in H5DSiterate_scales

if attach_scales_ds1:
    scale0_ds = g1.create_dataset('channels', data=channels, dtype=h5py.string_dtype())
    scale0_ds.make_scale('d1 channels')
    ds1.dims[0].attach_scale(scale0_ds)

    ds1.dims[0].keys()  # ['d1 channels']
    ds1.dims[0][0][:]  # array(['c0', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9'], dtype=object)

tf2 = tempfile.TemporaryFile()
f2 = h5py.File(tf2, mode='w')
g2 = f2.create_group('grp')

g1.copy('data', g2)
f1.close()

# Data copied fine
np.array_equal(g2['data'][:], data)  # True

# The following does not work if attach_scales_ds1
g2['data'].dims[0].keys()  # Unspecified error in H5DSiterate_scales
g2['data'].dims[0][0]  # Unspecified error in H5DSiterate_scales
scale0_ds2 = g2.create_dataset('channels', data=channels, dtype=h5py.string_dtype())
scale0_ds2.make_scale('d1 channels')
g2['data'].dims[0].attach_scale(scale0_ds2)  # Unspecified error in H5DSattach_scale (return value <0)

# The following or not attach_scales_ds1
scale1_ds2 = g2.create_dataset('feature', data=np.array([0]))
scale1_ds2.make_scale('d1 channels')
g2['data'].dims[1].attach_scale(scale1_ds2)

```

Below error appears when trying to access `g2['data'].dims[0].keys()`:
```
Traceback (most recent call last):
  File "C:\Users\Chad\.conda\envs\indl\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-356f49345629>", line 1, in <module>
    g2['data'].dims[0][0]  # Unspecified error in H5DSiterate_scales
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\Chad\AppData\Roaming\Python\Python37\site-packages\h5py\_hl\dims.py", line 75, in __getitem__
    h5ds.iterate(self._id, self._dimension, scales.append, 0)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5ds.pyx", line 136, in h5py.h5ds.iterate
  File "h5py\defs.pyx", line 4179, in h5py.defs.H5DSiterate_scales
RuntimeError: Unspecified error in H5DSiterate_scales (return value <0)
```

**Comment by cboulay** [comment]
I've edited the code snippet in the previous post to demonstrate that this error occurs even when the dataset is copied using the system `h5copy` binary executable, so it isn't specific to h5py unless the error is in how h5py attaches scales to begin with.

I've also edited the snippet to show that the problem can be circumvented by unattaching the scales prior to copying then reattaching. I imagine this only helps in cases like mine where the scales are easily available to be manually copied after the data are copied. It would be nice if `shallow=True` flag did this, but it does not seem to.

I'm only interested in using group.copy if it offers significant savings over `dataset2[:] = dataset1[:]` when working with huge datasets that don't fit into memory. I can't figure out if it does or not. Does anyone know?

**Comment by takluyver** [comment]
'Attaching' a dimension scale is really just creating a reference to it in an attribute (you can see it in `ds.attrs`), so I'd guess that your copied dataset is referring to datasets in the same file, but the scale datasets themselves aren't being copied to the new file.

I see `group.copy()` has an `expand_refs` option. Have you tried setting that to `True`?

**Comment by takluyver** [comment]
`dataset2[:] = dataset1[:]` would definitely try to load the whole array into memory and then write it all to the new file. I don't know for sure, but I would guess that `.copy()` doesn't - it goes to a libhdf5 call with all the information it would need to copy the data piece by piece.

**Comment by takluyver** [comment]
@cboulay - did you try with `expand_refs=True`?

**Comment by cboulay** [comment]
Hi, yes, when I originally tested this I tried all combinations of the flags. But, I don't like to rely on my memory so I'd like to double-check... as soon as I finish this other thing that should only take a couple hours but so far has taken me 2 weeks. :/
