### ISSUE TITLE
OSError while saving a simulation

### ISSUE THREAD

**Issue by gfadini** [h5py/h5py#1592]
I got this error out of the blue and I'm not sure of what it means, maybe you can help with providing an interpretation on it.
I was running a long simulation, and I occurred after quite some hours from the start as a side detail, I was running multiple process in parallel, saving different files.

I attach my OS information and the traceback

```
 * Ubuntu 16.04.2 LTS
 * Python version 3.6
 * python3.6 from apt package
 * h5py version 2.7.1

- hdf5-helpers/bionic,now 1.10.0-patch1+docs-4 amd64 [installed,automatic]
- hdf5-tools/bionic,now 1.10.0-patch1+docs-4 amd64 [installed]
- libhdf5-100/bionic,now 1.10.0-patch1+docs-4 amd64 [installed,automatic]
- libhdf5-cpp-100/bionic,now 1.10.0-patch1+docs-4 amd64 [installed,automatic]
- libhdf5-dev/bionic,now 1.10.0-patch1+docs-4 amd64 [installed,automatic]
- libhdf5-mpi-dev/bionic,now 1.10.0-patch1+docs-4 amd64 [installed,automatic]
- libhdf5-openmpi-100/bionic,now 1.10.0-patch1+docs-4 amd64 [installed,automatic]
- libhdf5-openmpi-dev/bionic,now 1.10.0-patch1+docs-4 amd64 [installed,automatic]
```

```
Traceback (most recent call last):
  File "optimizer.py", line 36, in <module>
    population = algo.evolve(population)
  File "/home/gfadini/Desktop/pendulum_benchmark/genetic_algorithm.py", line 144, in fitness
    self.log_file['cost'][self.current_evaluation] = self.ddp.cost
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2847)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2805)
  File "/usr/lib/python3/dist-packages/h5py/_hl/dataset.py", line 632, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2847)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2805)
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write (/build/h5py-qzs83i/h5py-2.7.1/h5py/h5d.c:3715)
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw (/build/h5py-qzs83i/h5py-2.7.1/h5py/_proxy.c:2026)
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite (/build/h5py-qzs83i/h5py-2.7.1/h5py/_proxy.c:1736)
OSError: Can't prepare for writing data (file read failed: time = Fri Jul 24 17:25:48 2020
, filename = './results/results_3_link_20-07-22_18h06.hdf5', file descriptor = 3, errno = 5, error message = 'Input/output error', buf = 0x3fb4c58, total read size = 40944, bytes this sub-read = 40944, bytes actually read = 18446744073709551615, offset = 53152)
Killed
```

**Comment by tacaswell** [comment]
What kind of filesystem are you writing to?

This error is coming out of the underlying hdf5 library, there is not much we can do about it at the Python layer.

**Comment by gfadini** [comment]
@tacaswell thanks for the reply, that's what I was fearing too. I need to check that out. I think that it may not be ext4 as there are some snapshot features that I never actually used. I guess that if that is causing problems I need to ask a workaround to the sysadmin

**Comment by gfadini** [comment]
I think that the problem was related to a delay in the communication of the data to the server I was using. Storing the hdf5 file locally is not giving the same error anymore or so it seems. I think that I can close the issue for the moment and we can investigate more in depth if I'll stumble in the problem again also saving the file locally. Thanks for your help in any case
