### ISSUE TITLE
installing h5py against hdf5 1.12

### ISSUE THREAD

**Issue by AliAllaouiLAM** [h5py/h5py#1599]
Operating System Ubuntu 18.04.4 LTS
 * Python version 3.6
 * Where Python was acquired : virtualenv
 * h5py version : master
 * HDF5 version : 1.12 (compiled from sources)
 * The full traceback/stack trace shown :

```
Collecting h5py
  Using cached h5py-2.10.0.tar.gz (301 kB)
Requirement already satisfied: numpy>=1.7 in /home/ali/Dev/venv/lib/python3.6/site-packages (from h5py) (1.19.0)
Requirement already satisfied: six in /home/ali/.local/lib/python3.6/site-packages (from h5py) (1.15.0)
Skipping wheel build for h5py, due to binaries being disabled for it.
Installing collected packages: h5py
    Running setup.py install for h5py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ali/Dev/venv/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qt53daxr/h5py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qt53daxr/h5py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cvnmk07h/install-record.txt --single-version-externally-managed --compile --install-headers /home/ali/Dev/venv/include/site/python3.6/h5py
         cwd: /tmp/pip-install-qt53daxr/h5py/
    Complete output (514 lines):
    running install
(...)
Executing api_gen rebuild of defs
    Executing cythonize()
    [ 1/23] Cythonizing /tmp/pip-install-qt53daxr/h5py/h5py/_conv.pyx
    warning: h5py/api_types_hdf5.pxd:418:2: 'H5D_layout_t' redeclared
(...) numerous warnings
 Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # --- open, open_by_name, open_by_idx ---
    
    @with_phil
    def open(ObjectID loc not None, char* name=NULL, int index=-1, *,
                                   ^
    ------------------------------------------------------------
    
    h5py/h5a.pyx:54:32: Cannot convert 'void *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        H5Arename_by_name(loc.id, obj_name, name, new_name, pdefault(lapl))
    
    
    @with_phil
    def delete(ObjectID loc not None, char* name=NULL, int index=-1, *,
                                     ^
    ------------------------------------------------------------
    
    h5py/h5a.pyx:122:34: Cannot convert 'void *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        def _hash(self):
            return hash((self.corder_valid, self.corder, self.cset, self.data_size))
    
    
    @with_phil
    def get_info(ObjectID loc not None, char* name=NULL, int index=-1, *,
                                       ^
    ------------------------------------------------------------
    
    h5py/h5a.pyx:184:36: Cannot convert 'void *' to Python object
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qt53daxr/h5py/setup.py", line 159, in <module>
        cmdclass = CMDCLASS,
      File "/home/ali/Dev/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ali/Dev/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-qt53daxr/h5py/setup_build.py", line 209, in run
        language_level=2)
      File "/tmp/pip-install-qt53daxr/h5py/.eggs/Cython-3.0a5-py3.6.egg/Cython/Build/Dependencies.py", line 1105, in cythonize
        cythonize_one(*args)
      File "/tmp/pip-install-qt53daxr/h5py/.eggs/Cython-3.0a5-py3.6.egg/Cython/Build/Dependencies.py", line 1263, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: /tmp/pip-install-qt53daxr/h5py/h5py/h5a.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ali/Dev/venv/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qt53daxr/h5py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qt53daxr/h5py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cvnmk07h/install-record.txt --single-version-externally-managed --compile --install-headers /home/ali/Dev/venv/include/site/python3.6/h5py Check the logs for full command output.
```

**Comment by takluyver** [comment]
I think you may be installing a released version of h5py rather than the development version; I've just tried building the development version with 1.12, and I don't see this.

To install h5py master:

```
git clone https://github.com/h5py/h5py.git
cd h5py
pip install -v .
```

**Comment by takluyver** [comment]
h5py 3 works with HDF5 1.12.
