### ISSUE TITLE
BUG: issue with writing string datasets to a file buffer

### ISSUE THREAD

**Issue by danielballan** [h5py/h5py#1639]
Writing an `h5py.string_dtype()` to a `h5py.File` creating using a writable buffer (i.e. `h5py.File(open(..., "wb"), "w")`) raises an error. Writing to a file created internally by `h5py.File` (i.e. `h5py.File("...", "w")`) does not have this issue. Writing a numerical dataset to a writable buffer does not have this issue.

SSCCE:

```py
import h5py
import numpy

def test(file):
    group = file.create_group("group")
    data = numpy.array('6b035227-da6b-4d71-88fc-f3594748cee9', dtype=object)
    dataset = group.create_dataset("data", data=data, dtype=h5py.string_dtype())

file = h5py.File("/tmp/test1", "w")
test(file)  # works
file_like = open("/tmp/test2", "wb")
file = h5py.File(file_like, "w")
test(file)  # raises
```

Traceback is:

```
Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 158, in h5py.h5fd.H5FD_fileobj_read
io.UnsupportedOperation: read

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "help.py", line 14, in <module>
    test(file)  # raises
  File "help.py", line 7, in test
    dataset = group.create_dataset("data", data=data, dtype=h5py.string_dtype())
  File "/home/dallan/.conda/envs/py37/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/dallan/.conda/envs/py37/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 170, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 222, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 164, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
  File "h5py/defs.pyx", line 495, in h5py.defs.H5Dwrite
  File "h5py/h5fd.pyx", line 169, in h5py.h5fd.H5FD_fileobj_write
SystemError: <built-in method seekable of _io.FileIO object at 0x7f0a11eeffa0> returned a result with an error set
```

Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.4
Python  3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.0

Platform is specifically Ubuntu 18.04.

**Comment by dota17** [comment]
Maybe the duplicate issue, see this discussion: https://github.com/h5py/h5py/issues/1170#issuecomment-466029525

**Comment by takluyver** [comment]
There's definitely a bug that's messing up the error, but I think the error at the top is meaningful: `io.UnsupportedOperation: read`.

HDF5 has no write-only file mode - even when you're writing an HDF5 file, it expects to be able to read it as well. If you open the Python file object with mode `'w+b'`, this goes away.

I've got an idea about the error message getting mangled.

**Comment by takluyver** [comment]
#1642 fixes the errors. Unfortunately, it also revealed a much nastier bug which is making the tests segfault, so it needs a bit more work.

**Comment by danielballan** [comment]
Thanks you!
