### ISSUE TITLE
Error compiling Cython file

### ISSUE THREAD

**Issue by dota17** [h5py/h5py#1645]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
> Ubuntu 18.04
 * Python version (e.g. 2.7, 3.5)
> 3.6.8
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
>  Linux

```
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.4
Python  3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.18.0

```
 * The full traceback/stack trace shown (if it appears)

```c
[ 1/19] Cythonizing /data/h5py/h5py/h5.pyx

Error compiling Cython file:
------------------------------------------------------------
...

INDEX_NAME      = H5_INDEX_NAME       # Index on names
INDEX_CRT_ORDER = H5_INDEX_CRT_ORDER  # Index on creation order

HDF5_VERSION_COMPILED_AGAINST = HDF5_VERSION
NUMPY_VERSION_COMPILED_AGAINST = NUMPY_BUILD_VERSION
                                ^
------------------------------------------------------------

h5py/h5.pyx:24:33: undeclared name not builtin: NUMPY_BUILD_VERSION

Error compiling Cython file:
------------------------------------------------------------

INDEX_NAME      = H5_INDEX_NAME       # Index on names
INDEX_CRT_ORDER = H5_INDEX_CRT_ORDER  # Index on creation order

HDF5_VERSION_COMPILED_AGAINST = HDF5_VERSION
NUMPY_VERSION_COMPILED_AGAINST = NUMPY_BUILD_VERSION
CYTHON_VERSION_COMPILED_WITH = CYTHON_BUILD_VERSION
                              ^
------------------------------------------------------------

h5py/h5.pyx:25:31: undeclared name not builtin: CYTHON_BUILD_VERSION
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    cmdclass = CMDCLASS,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 75, in run
    buildobj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/data/h5py/setup_build.py", line 186, in run
    language_level=3)
  File "/usr/local/lib/python3.6/dist-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.6/dist-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /data/h5py/h5py/h5.pyx
```

I am using the master branch code to test this, it's caused by recently merged PR https://github.com/h5py/h5py/pull/1627 I think.
CC: @takluyver

**Comment by dota17** [comment]
Hi @aragilar 😃 It seems that you are online now, can you take a look at this?

**Comment by takluyver** [comment]
I just ran into this - you need to delete the generated file `h5py/config.pxi` . The next time you try to build it, it will regenerate the file with the new values. Or start from a clean checkout.

We could try to make it smarter about regenerating the file in cases like this. But we add values to it so rarely that I don't think it's worth adding extra complexity to the build process.

**Comment by dota17** [comment]
thanks, it works. 

> We could try to make it smarter about regenerating the file in cases like this. But we add values to it so rarely that I don't think it's worth adding extra complexity to the build process.

I agree.  We can keep this issue open for a while in case some other users run into this same situation, and they can quickly find the solution.

**Comment by takluyver** [comment]
OK, I think we can close this now.
