### ISSUE TITLE
OSError when creating a file with non-ASCII in path 

### ISSUE THREAD

**Issue by jnsebgosselin** [h5py/h5py#1650]
To assist reproducing bugs, please include the following:

 * Operating System: Windows 10
 * Python version: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:11:50) [MSC v.1916 64 bit (AMD64)]
 * Where Python was acquired: Anaconda on Windows
 * h5py version: 2.10.0
 * HDF5 version: 1.10.6
 * The full traceback/stack trace shown (if it appears)

Executing the following script in a clean conda environment with HDF5 version 1.10.6 results in a `OSError` . Downgrading HDF5  to version 1.10.5 solve the issue. Python and all packages were installed from the `conda-forge` channel. I cannot test the issue using the default Anaconda channel since HDF5 max version is 1.10.4 on this channel.

I cannot also reproduce the issue on a manual installation of Python 3.7.8 and a pip installed h5py 2.10.0. The version of HDF5 packaged with the h5py wheel is 1.10.5 thankfully.

```python
h5py    2.10.0
HDF5    1.10.6
Python  3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.19.1

Traceback (most recent call last):
  File "D:\test_h5py_unicode.py", line 17, in <module>
    h5py.File(os.path.join(dirname, 'test.h5'), mode='w')
  File "C:\Anaconda3\envs\test_h5py\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Anaconda3\envs\test_h5py\lib\site-packages\h5py\_hl\files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError
```

This is the results from `conda list`

```
# packages in environment at C:\Anaconda3\envs\test_h5py:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
h5py                      2.10.0          nompi_py37hde23a51_104    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
intel-openmp              2020.2                      254
libblas                   3.8.0                    16_mkl    conda-forge
libcblas                  3.8.0                    16_mkl    conda-forge
liblapack                 3.8.0                    16_mkl    conda-forge
mkl                       2020.1                      216
numpy                     1.19.1           py37h7cee19a_2    conda-forge
openssl                   1.1.1g               he774522_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
pyreadline                2.1                   py37_1001    conda-forge
python                    3.7.8           h60c2a47_1_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
setuptools                49.6.0           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               he774522_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
zlib                      1.2.11            h62dcd97_1007    conda-forge
``

**Comment by aragilar** [comment]
I think this is fixed by #1633, @jnsebgosselin are you able to test with latest master?
