### ISSUE TITLE
Unable to import h5py using Pypy 7.3.1 and Python 3.6.9

### ISSUE THREAD

**Issue by phanostech** [h5py/h5py#1651]
I installed h5py using the `pypy3 -m pip install h5py` without any errors. I also installed the HDF5 devel libraries for fedora using `dnf install hdf5-devel`. 

I get the error `Expected 72 from C header, got 24 from PyObject` but when I install h5py using anaconda on the same system, everything works.

 * Operating System Fedora 32
 * Python version: PYPY 7.3.1 with Python 3.6.9 
 * Where Python was acquired Pypy 7.3.1
 * h5py version 2.10.0
 * The full traceback/stack trace shown 
```
Python 3.6.9 (2ad108f17bdb, Apr 07 2020, 02:59:05)
[PyPy 7.3.1 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pypy/site-packages/h5py/__init__.py", line 55, in <module>
    from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z, h5pl
  File "h5py/h5d.pyx", line 1, in init h5py.h5d
ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject

```

**Comment by aragilar** [comment]
It's possible that anaconda has patches for h5py which add PyPy support?

**Comment by mattip** [comment]
I think this may be a duplicate of #1514

**Comment by yuy01** [comment]
i have also met the same proble, have you solved the problem?
