### ISSUE TITLE
Error getting virtual sources on empty virtual dataset

### ISSUE THREAD

**Issue by asmeurer** [h5py/h5py#1660]
If I create an empty virtual dataset and try to get the virtual sources, I get an error

```py
>>> with h5py.File('test.hdf5', 'w') as f:
...     data = np.empty((0,), dtype=np.float64)
...     f['raw_data'] = np.ones((1000,), dtype=np.float64)
...     layout = h5py.VirtualLayout(data.shape, dtype=data.dtype)
...     source = h5py.VirtualSource('.', name='raw_data', shape=(1000,), dtype=data.dtype)
...     layout[()] = source[0:0]
...     f.create_virtual_dataset('data', layout)
...     print(f['data'])
...     print(f['data'].virtual_sources())
<HDF5 dataset "data": shape (0,), type "<f8">
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/aaronmeurer/Documents/h5py/h5py/_hl/dataset.py", line 1067, in virtual_sources
    for j in range(dcpl.get_virtual_count())]
  File "/Users/aaronmeurer/Documents/h5py/h5py/_hl/dataset.py", line 1067, in <listcomp>
    for j in range(dcpl.get_virtual_count())]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5p.pyx", line 921, in h5py.h5p.PropDCID.get_virtual_srcspace
RuntimeError: Can't get selection bounds (can't get selection bounds)
```

This happens for any empty shape (shape with 0).

I think the problem is with the `dcpl.get_virtual_srcspace` function call.

```
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.5
Python  3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
[Clang 9.0.1 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.19.0
cython (built with) 0.29.21
numpy (built against) 1.14.3
HDF5 (built against) 1.10.5
```

This is the latest git version of h5py.

**Comment by dota17** [comment]
https://github.com/h5py/h5py/blob/036eb932b800bf5739eb035136bf02d10c1b2822/h5py/h5p.pyx#L915-L922

it seems that in `H5Pget_virtual_srcspace(self.id, index)`, index  can't be 0.

**Comment by takluyver** [comment]
I don't think `index=0` is a problem - that just refers to the first mapping for that virtual dataset. The docs for [H5Pget_virtual_srcspace](https://portal.hdfgroup.org/display/HDF5/H5P_GET_VIRTUAL_SRCSPACE) confirm that it's a 0 based index.

I suspect this is coming from HDF5 itself; perhaps it doesn't fully expect a mapping with 0 length in some dimension. Someone could check that hypothesis by trying to reproduce it with C code.

cc @epourmal

**Comment by dota17** [comment]
I think we mean the same thing. I read that document before, and tested that API with index = 0, the result is it can't work well, so I think that the index actually can't be 0. I mean the problem comes from HDF5 API too.

**Comment by asmeurer** [comment]
Somewhat related, if I modify my code to skip all the empty source indices and end up in a situation where no sources are set in the layout, `create_virtual_dataset` creates a dataset that isn't actually virtual. I don't know if this is intentional.

**Comment by takluyver** [comment]
That's a good point: we make a virtual dataset by calling [H5Pset_virtual](https://portal.hdfgroup.org/display/HDF5/H5P_SET_VIRTUAL) for each mapping. It looks like it's possible to use [H5Pset_layout](https://portal.hdfgroup.org/display/HDF5/H5P_SET_LAYOUT) to mark a dataset as virtual even if there are no mappings. I think that qualifies as a bug, and I think this one is in h5py rather than HDF5.

Do you want to do a PR? We may land it after 3.0 (which is almost there, we're just waiting for our CI to support Python 3.9).

**Comment by asmeurer** [comment]
I wasn't sure if it would be allowed. Would get_virtual_sources() just return an empty list in that case?

**Comment by takluyver** [comment]
I'd hope it would - that means that `H5Pget_virtual_count` would return 0. But I don't know if it will. :wink:

**Comment by asmeurer** [comment]
Sorry for not getting to this on time for the release. I think it wouldn't actually help me, in the sense that even if the dataset were virtual, I can't access the location of the raw dataset via dset_name if there are no datasets it points to, so I need to store that information somewhere else anyway.
