### ISSUE TITLE
OSError: Unable to open file (unable to lock file, errno = 5, error message = 'Input/output error')

### ISSUE THREAD

**Issue by yangadan** [h5py/h5py#1679]
To assist reproducing bugs, please include the following:
 * Operating System :Ubuntu 18.04.3
 * Python version: 3.7.4
 * Where Python was acquired: Anaconda on linux
  
 * h5py version: 2.10.0
 * HDF5 version: 1.10.4
 * The full traceback/stack trace shown (if it appears)

Traceback (most recent call last):
  File "hdf5.py", line 1055, in <module>
    inspect()
  File "hdf5.py", line 1023, in inspect
    f = h5py.File(filename, 'r')
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 5, error message = 'Input/output error')

**Comment by dota17** [comment]
Hi @yangadan The error message is `Input/output error`, but in order to find out the problem quickly, it's better to post your demo code in here.

**Comment by yangadan** [comment]
def inspect():
    filename="/share/lijiaming/ff/fps10_crop320.hdf5"
    f = h5py.File(filename, 'r')
    print(f['original_sequences/c40/114_face1'].attrs['len'])
The above function is the demo code, but i don't think it can help solve the problem. The problem is very strange. It work well until today and I can run the function on other machine. I have tried to restart my machine but the problem still exists. It's  worth noting that my code was reading the file  by many processes of two machines until it showed the error. I suspect it was caused by my storage. Could you provide me some suggestions about it ?

**Comment by songdongmei** [comment]
hi, dan,

Have you resolved the issue? I encounter similar issue. I guess it maybe related to storage, becuase the underlying filesystem changed, then it happened. And I set envirment variable to workaround. But I still dont know the root cause.
os.environ["HDF5_USE_FILE_LOCKING"]="FALSE"
