### ISSUE TITLE
Cannot resize virtual dataset

### ISSUE THREAD

**Issue by bomber8013** [h5py/h5py#1685]
It seems that virtual datasets cannot be resized, even though they should be able to as mentioned in the documentation. Virtual layouts can specify unlimited maximum dimensions but cannot be resized.

Version info:
```
Summary of the h5py configuration
---------------------------------

h5py    2.10.0
HDF5    1.10.5
Python  3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.19.2
```
Source code:
```
import h5py
import io
import numpy as np
import numpy.testing as test


def virtual_test():
    shape = (10, 2)
    with h5py.File("virtual.h5", "w") as hfile:
        source_dset: h5py.Dataset = hfile.create_dataset(
            "source",
            data=np.ones(shape, dtype="i8"),
            maxshape=(None, 2),
            chunks=True
        )

        layout0 = h5py.VirtualLayout((10, 1), dtype="i8", maxshape=(None, 1))
        layout0_source0 = h5py.VirtualSource(source_dset)
        layout0[:, 0] = layout0_source0[:, 0]

        virtual_dset0: h5py.Dataset = hfile.create_virtual_dataset("virtual_dset0", layout0)
        test.assert_array_equal(virtual_dset0, np.ones((10, 1), dtype="i8"))

        source_dset[:, 0] = range(10)
        test.assert_array_equal(virtual_dset0, np.arange(10).reshape(10, 1))

        # layout1 = h5py.VirtualLayout((10, 1), dtype="i8")
        # layout1_source0 = h5py.VirtualSource(source_dset)
        # layout1[:, 0] = layout1_source0[:, 1]

        # virtual_dset1 = hfile.create_virtual_dataset("virtual_dset1", layout1)
        # test.assert_array_equal(virtual_dset1, np.ones((10, 1), dtype="i8"))

        # source_dset[:, 1] = range(10, 20)
        # test.assert_array_equal(virtual_dset1, np.arange(10, 20).reshape(10, 1))
        
        source_dset.resize(20, axis=0)
        virtual_dset0.resize(20, axis=0)
        test.assert_array_equal(virtual_dset0[:, 0], source_dset[:, 0])


virtual_test()
```
Error:
```
Traceback (most recent call last):
  File "h5_virtual.py", line 42, in <module>
    virtual_test()
  File "h5_virtual.py", line 38, in virtual_test
    virtual_dset0.resize(20, axis=0)
  File ".\lib\site-packages\h5py\_hl\dataset.py", line 425, in resize
    raise TypeError("Only chunked datasets can be resized")
TypeError: Only chunked datasets can be resized
```

**Comment by bomber8013** [comment]
Looks like a simple fix in datasets.py causes the correct behavior. Line 424 of datasets.py
From:
```
if self.chunks is None:
```
To:
```
if self.chunks is None and not self.is_virtual:
```

**Comment by bomber8013** [comment]
Virtual datasets cannot be resized as referenced in #1167 and #1490 and after testing, applying H5Dset_extent to virtual datasets appears to be a no-op. Will work on fixing #1202 to obtain this functionality.
