### ISSUE TITLE
Can't work with h5py files from open file handles

### ISSUE THREAD

**Issue by Helveg** [h5py/h5py#1698]
To assist reproducing bugs, please include the following:
 * Operating System Windows 10
 * Python version 3.6
 * Pyenv build
 * h5py version (2.10 & 3.0.0rc1)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

```
Summary of the h5py configuration
---------------------------------

h5py    3.0.0rc1
HDF5    1.12.0
Python  3.6.10 (default, Mar 20 2020, 00:41:24) 
[GCC 7.5.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.17.4
cython (built with) 0.29.21
numpy (built against) 1.12.0
HDF5 (built against) 1.12.0
```

I thought you could create HDF5 files from file objects but I get "I/O operation on closed file" errors. What's going wrong here?

```
>>> with open("test.hdf5", "w") as f:
...  h = h5py.File(f, "w")
...  h.create_group("ehe")
... 
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
  File "h5py/h5fd.pyx", line 169, in h5py.h5fd.H5FD_fileobj_write
ValueError: I/O operation on closed file.
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
  File "h5py/h5fd.pyx", line 169, in h5py.h5fd.H5FD_fileobj_write
ValueError: I/O operation on closed file.
<HDF5 group "/ehe" (0 members)>
```

**Comment by jangarrevoet** [comment]
with h5py.File("test.hdf5", "w") as f:
    f.create_group("ehe")

**Comment by Helveg** [comment]
That's not possible in this situation, I need to write to an already existing file handle. I just reduced my example for the issue report here. It's also featured in the [docs](https://docs.h5py.org/en/stable/high/file.html#python-file-like-objects) that this should be possible starting from v2.9:

> The first argument to File may be a Python file-like object, such as an io.BytesIO or tempfile.TemporaryFile instance. This is a convenient way to create temporary HDF5 files, e.g. for testing or to send over the network.

**Comment by Helveg** [comment]
The error changes slightly with different file modes, for sure I should've opened it in binary mode:

```python
>>> with open("test.h5", "wb") as f:
...  f = h5py.File(f)
...  f.create_dataset("hello", shape=(100,))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
  File "h5py/h5fd.pyx", line 158, in h5py.h5fd.H5FD_fileobj_read
io.UnsupportedOperation: read
>>> with open("test.h5", "wb+") as f:
...  f = h5py.File(f)
...  f.create_dataset("hello", shape=(100,))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

**Comment by dota17** [comment]
Hi @Helveg 
The usage `open("test.h5", "wb")` is wrong. 
As I know, no `wb+` mode in h5py. 
If you want to write to an already existing file handle, first, open the file rightly with mode `r`, then write it with mode `r` or `a`.
You can read the documentation [here](https://docs.h5py.org/en/stable/high/file.html).

**Comment by Helveg** [comment]
The documentation link you've sent is the same as the one I sent?

`open("wb")` is Python's `open` method though, not `h5py` related. If I open the file handle with only `r` permissions I rightly get the error that the file does not exist, or if the file does exist I get the error that I don't have write :

```python
>>> with open('testt.h5', 'r') as f:
...  h = h5py.File(f)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'testt.h5'
```

If I pass a read only file handle into the h5py File constructor and then give the `a` mode things get even worse, it pretends like it created the group but there's still 0 bytes in the file:

```python
>>> with open('test.h5', 'r') as f:
...  with h5py.File(f, 'a') as f:
...    h.create_group("ello")
...    print(f.tell())
0
```

This also does not explain the fact that the documentation example doesn't work!

Does anyone know more?

**Comment by Helveg** [comment]
There are countless errors to be found when using file-like objects. A 

```python
>>> import h5py
>>> with open('tt.h5', 'w') as f:
...  with h5py.File(f, 'w') as h:
...   h.create_dataset("ello", shape=(100,))
...  f.seek(0,2)
...  print(f.tell())
... 
<HDF5 dataset "ello": shape (100,), type "<f4">
Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 171, in h5py.h5fd.H5FD_fileobj_write
TypeError: write() argument must be str, not h5py.h5fd._memoryviewslice

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 175, in h5py.h5fd.H5FD_fileobj_truncate
SystemError: <built-in method flush of _io.BufferedWriter object at 0x7faeb1ee47d8> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 169, in h5py.h5fd.H5FD_fileobj_write
SystemError: <built-in method flush of _io.BufferedWriter object at 0x7faeb1ee47d8> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 180, in h5py.h5fd.H5FD_fileobj_flush
SystemError: <built-in method flush of _io.BufferedWriter object at 0x7faeb1ee47d8> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 175, in h5py.h5fd.H5FD_fileobj_truncate
SystemError: <built-in method flush of _io.BufferedWriter object at 0x7faeb1ee47d8> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 475, in __exit__
    self.close()
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 457, in close
    h5i.dec_ref(id_)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5i.pyx", line 153, in h5py.h5i.dec_ref
  File "h5py/h5fd.pyx", line 169, in h5py.h5fd.H5FD_fileobj_write
SystemError: <built-in method flush of _io.BufferedWriter object at 0x7faeb1ee47d8> returned a result with an error set
```

```python
>>> import h5py
>>> with open('tt.h5', 'w+') as f:
...  with h5py.File(f, 'a') as h:
...   h.create_dataset("ello", shape=(100,))
<HDF5 dataset "ello": shape (100,), type "<f4">
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 475, in __exit__
    self.close()
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 457, in close
    h5i.dec_ref(id_)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5i.pyx", line 153, in h5py.h5i.dec_ref
  File "h5py/h5fd.pyx", line 169, in h5py.h5fd.H5FD_fileobj_write
  File "h5py/h5fd.pyx", line 175, in h5py.h5fd.H5FD_fileobj_truncate
  File "h5py/h5fd.pyx", line 180, in h5py.h5fd.H5FD_fileobj_flush
  File "h5py/h5fd.pyx", line 169, in h5py.h5fd.H5FD_fileobj_write
  File "h5py/h5fd.pyx", line 175, in h5py.h5fd.H5FD_fileobj_truncate
  File "h5py/h5fd.pyx", line 171, in h5py.h5fd.H5FD_fileobj_write
TypeError: write() argument must be str, not h5py.h5fd._memoryviewslice
>>> exit()
Segmentation fault (core dumped)
```

Clearly there must be either something wrong with my pip installed `h5py` or passing file-like objects into `h5py.File` does _not_ work. Could somebody try to reproduce my very simple examples?

**Comment by Helveg** [comment]
I've reproduced these errors on other machines, but they're all Linux. Booting into windows now

**Comment by takluyver** [comment]
> When closing the File object and the underlying handle is already closed, there's a segfault

I spent a while in #1642 trying to fix this. Unfortunately, HDF5 really doesn't like having a file object it can't close. I've told HDF group about it, but in h5py, we can either report errors accurately, which leaves the possibility of a segfault open until HDF5 is fixed, or tell HDF5 operations have succeeded even when they haven't, which leads to really confusing errors when things go wrong.

**Comment by takluyver** [comment]
My overall feeling on this is: avoid passing file like objects if you can. They're easier to make mistakes with, and the failure modes are more confusing if you do. h5py does try to support them, but it's really a special feature h5py is bolting on to HDF5, and it can probably never work as well as using HDF5 normally.

I've opened PR #1704 to point to alternatives for a couple of common use cases.

**Comment by rainwoodman** [comment]
Oh. We run into a similar issue a while ago.

The bug is more likely on the Cython side -- and likely only occurs with certain version of Cython (0.29.x, but not 3.x?). Cython calls into these callback functions during Exception handling (with PyErr_Occurred()), but at that point the object has already been closed.

If this only affects 0.29.x, then I thought we probably shouldn't do much about it (hence I didn't file a PR).

Anyhow, here is a patch what fixed the error. 

Now that I look at this again, a more proper fix (which looks sane even under Cython 3.0) than checking PyErr_Occurred is probably check and bail if fileobj has been closed; but the tricky part is not all file object support a 'closed' attribute.

```
Index: h5py/h5fd.pyx
===================================================================
--- h5py.orig/h5fd.pyx
+++ h5py/h5fd.pyx
@@ -13,6 +13,8 @@
 """
     File driver constants (H5FD*).
 """
+from cpython.exc cimport PyErr_Occurred
 
 # === Multi-file driver =======================================================
 
@@ -147,10 +149,16 @@ cdef herr_t H5FD_fileobj_set_eoa(H5FD_fi
     return 0
 
 cdef haddr_t H5FD_fileobj_get_eof(const H5FD_fileobj_t *f, H5FD_mem_t type) except -1:  # HADDR_UNDEF
+    if PyErr_Occurred():
+        return 1
     (<object>f.fileobj).seek(0, libc.stdio.SEEK_END)
     return (<object>f.fileobj).tell()
 
 cdef herr_t H5FD_fileobj_read(H5FD_fileobj_t *f, H5FD_mem_t type, hid_t dxpl, haddr_t addr, size_t size, void *buf) except 1:
+    if PyErr_Occurred():
+        return 1
     cdef unsigned char[:] mview
     (<object>f.fileobj).seek(addr)
     if hasattr(<object>f.fileobj, 'readinto'):
@@ -165,6 +173,9 @@ cdef herr_t H5FD_fileobj_read(H5FD_fileo
     return 0
 
 cdef herr_t H5FD_fileobj_write(H5FD_fileobj_t *f, H5FD_mem_t type, hid_t dxpl, haddr_t addr, size_t size, void *buf) except 1:
+    if PyErr_Occurred():
+        return 1
     cdef unsigned char[:] mview
     (<object>f.fileobj).seek(addr)
     mview = <unsigned char[:size]>buf
@@ -172,10 +183,16 @@ cdef herr_t H5FD_fileobj_write(H5FD_file
     return 0
 
 cdef herr_t H5FD_fileobj_truncate(H5FD_fileobj_t *f, hid_t dxpl, hbool_t closing) except 1:
+    if PyErr_Occurred():
+        return 1
     (<object>f.fileobj).truncate(f.eoa)
     return 0
 
 cdef herr_t H5FD_fileobj_flush(H5FD_fileobj_t *f, hid_t dxpl, hbool_t closing) except 1:
+    if PyErr_Occurred():
+        return 1
     # TODO: avoid unneeded fileobj.flush() when closing for e.g. TemporaryFile
     (<object>f.fileobj).flush()
     return 0
```

**Comment by takluyver** [comment]
Aha, that's interesting. I didn't check with Cython 3.0. If it can avoid the segfault, though, I'm inclined to say it's worth doing even if Cython 3.0 isn't affected - that's still only in alpha at the moment. Do you want to make a PR with that patch? There's a test I skipped - if it works, you should be able to re-enable it:

https://github.com/h5py/h5py/blob/c760dd6521ed53a7b44c54c2af1962c566b328a5/h5py/tests/test_file2.py#L228-L233

**Comment by DSLituiev** [comment]
Which version are `tempfile` and `io.BytesIO` examples are meant for? 
They all fail for the version `2.8.0` on the standard distribution with Python3.7. 
Trying to make it work on AWS lambda

**Comment by takluyver** [comment]
Using file-like objects with h5py was new in version 2.9. The docs do say that. :wink: 

https://docs.h5py.org/en/stable/high/file.html#python-file-like-objects
