### ISSUE TITLE
File-like object documentation example does not work in v3.0.0

### ISSUE THREAD

**Issue by Helveg** [h5py/h5py#1702]
On `h5py==3.0.0rc1` the example from the [docs](https://docs.h5py.org/en/stable/high/file.html#python-file-like-objects):

```
>>> tf = tempfile.TemporaryFile()
>>> f = h5py.File(tf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

It should be corrected to `h5py.File(tf, "w")`

**Comment by takluyver** [comment]
Thanks! Would you like to make a PR for the fix?

**Comment by Helveg** [comment]
Sure :+1:

**Comment by Helveg** [comment]
This was already corrected in the new documentation:

```
    >>> tf = tempfile.TemporaryFile()
    >>> f = h5py.File(tf, 'w')
```

**Comment by takluyver** [comment]
Aha, great. Well done @cydanil ;-)
