### ISSUE TITLE
`h5py.File("file")` should throw TypeError since they are now invalid args

### ISSUE THREAD

**Issue by Helveg** [h5py/h5py#1703]
Since in v3.0.0 it is invalid not to pass a mode argument an error is thrown when you use `h5py.File(f)` instead of `h5py.File(f, "w")`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/robin/.pyenv/versions/3.6.10/lib/python3.6/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

But the error is cryptic and can be caught way earlier by throwing the typical Python error

`"TypeError: File() is missing required positional argument: mode"` or similar

**Comment by takluyver** [comment]
The `mode` argument is not required, though - it just defaults to `'r'` for read-only now, like the regular Python `open()` function. We do have issues turning HDF5 errors into specific Python errors in general, and I'm pestering HDF group to give us better information (specifically, the POSIX errno) to let us improve that.

There are certainly some warts with passing file-like objects in, but let's discuss that on your specific issue.

**Comment by Helveg** [comment]
Ok, it seems that today my head is in overdrive and I'm jumping to conclusions everywhere, sorry for that :)
