### ISSUE TITLE
Bug in softlink to external link

### ISSUE THREAD

**Issue by woutdenolf** [h5py/h5py#1706]
h5py: 1.10.4
hdf5: 2.10.0

Script to produce the exception

```python
import h5py

with h5py.File("source.h5", mode="w") as f:
    f["/group/data"] = 10

with h5py.File("dest.h5", mode="w") as f:
    f["/link/external"] = h5py.ExternalLink("source.h5", "/group/data")
    f["/link/soft"] = h5py.SoftLink("external")

with h5py.File("dest.h5", mode="r") as f:
    f["/link/soft"].parent
```

The last line gives following exception:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    f["/link/soft"].parent
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/users/denolf/virtualenvs/silx/py38/lib/python3.8/site-packages/h5py/_hl/base.py", line 239, in parent
    return self.file[posixpath.dirname(self.name)]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/users/denolf/virtualenvs/silx/py38/lib/python3.8/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'link' doesn't exist)"
```

**Comment by woutdenolf** [comment]
I guess this is the issue:
```python
f["/link/soft"].file  == "source.h5" # the external file name
f["/link/soft"].name == "/link/soft" # the local name
```
