### ISSUE TITLE
Build error for parallel build

### ISSUE THREAD

**Issue by hoba87** [h5py/h5py#1717]
To assist reproducing bugs, please include the following:
 * CentOS 8
 * Python 3.7.9, compiled from source
 * h5py version 2.10.0
 * HDF5 version 1.12.0
 * OpenMPI 4.0.5
 * mpi4py 3.0.3

```
python3 setup.py configure --mpi
python3 setup.py configure --hdf5=/opt/hdf5/hdf5-1.12.0-mpi
python3 setup.py build
```
```
Traceback (most recent call last):
  File "setup.py", line 159, in <module>
    cmdclass = CMDCLASS,
  File "/opt/python/python-3.7.9/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/common/software/h5py-2.10.0/setup_build.py", line 183, in run
    v2 = StrictVersion(mpi4py.__version__) > StrictVersion("1.3.1")
AttributeError: module 'mpi4py' has no attribute '__version__'
```

when trying to workaround that by setting the \_\_version\_\_ manually I get:
```
Executing cythonize()
Traceback (most recent call last):
  File "setup.py", line 159, in <module>
    cmdclass = CMDCLASS,
  File "/opt/python/python-3.7.9/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/python/python-3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/common/software/h5py-2.10.0/setup_build.py", line 208, in run
    self.extensions = cythonize(self._make_extensions(config),
  File "/home/common/software/h5py-2.10.0/setup_build.py", line 116, in _make_extensions
    settings['include_dirs'] += [mpi4py.get_include()]
AttributeError: module 'mpi4py' has no attribute 'get_include'
```

**Comment by hoba87** [comment]
The issues are gone for mpi4py version 3.0.2, and for h5py version 2.10 hdf5 version 1.10.x is needed.

**Comment by takluyver** [comment]
It's not clear to me why those attributes would be missing in mpi4py 3.0.3. They appear to be there in the source code:

https://bitbucket.org/mpi4py/mpi4py/src/3.0.3/src/mpi4py/__init__.py

**Comment by hoba87** [comment]
... perhaps something goes wrong during the first installation of mpi4py 3.0.3, now it works.
