### ISSUE TITLE
Trouble running tests

### ISSUE THREAD

**Issue by ArchangeGabriel** [h5py/h5py#1728]
I’m packaging for:
 * Operating System: Arch Linux
 * Python version: 3.8 (system)
 * h5py: 3.0.0
 * HDF5: 1.12.0

Up to now, I used to run tests like this:
```
python setup.py test
```
This does still work, but `setuptools` is deprecating AFAIK. So I’ve tried to switch to this:
```
python -m pytest --pyargs h5py -rxXs
```
But I get this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1186, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "/usr/lib/python3.8/site-packages/_pytest/warnings.py", line 136, in pytest_load_initial_conftests
    with catch_warnings_for_item(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.8/site-packages/_pytest/warnings.py", line 52, in catch_warnings_for_item
    apply_warning_filters(config_filters, cmdline_filters)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1602, in apply_warning_filters
    warnings.filterwarnings(*parse_warning_filter(arg, escape=False))
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1576, in parse_warning_filter
    category = warnings._getcategory(
  File "/usr/lib/python3.8/warnings.py", line 262, in _getcategory
    raise _OptionError("invalid module name: %r" % (module,)) from None
warnings._OptionError: invalid module name: 'h5py.h5py_warnings'
```

Looking a bit arround, I’ve read that this could just be hiding the real issue, and tried a manual import with `python -c 'import h5py; from h5py.h5py_warnings import H5pyDeprecationWarning'`, and this is the result:
```
Traceback (most recent call last):
  File "/build/python-h5py/src/h5py-3.0.0/h5py/__init__.py", line 25, in <module>
    from . import _errors
ImportError: cannot import name '_errors' from partially initialized module 'h5py' (most likely due to a circular import) (/build/python-h5py/src/h5py-3.0.0/h5py/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/build/python-h5py/src/h5py-3.0.0/h5py/__init__.py", line 29, in <module>
    raise ImportError("You cannot import h5py from inside the install directory.\nChange to another directory first.")
ImportError: You cannot import h5py from inside the install directory.
Change to another directory first.
```
I’m not sure this is the actual issue it by the other command, nor whether to check that, but I figured out I should report this before `setup.py test` get removed later on.

**Comment by aragilar** [comment]
Are you running the tests in the checkout directory? Unless you do an in-place build (which I'm guessing isn't what you want to test), that breaks as python tries import h5py from the current directory instead of the installed one. You could change to a tempdir, and run the command from there.

**Comment by ArchangeGabriel** [comment]
Yes, I’m doing an in-place build and this is actually what I want to test. There is no “installed” h5py. After checking out in the source directory, I’m trying to run:
```
H5PY_SYSTEM_LZF=1 python setup.py build
PYTHONPATH="$PWD/build/lib.linux-x86_64-3.8" python -m pytest --pyargs h5py -rxXs
```
So indeed if I change to another directory and adjust `PYTHONPATH` accordingly it does indeed work, but this is kind of strange to me as this is the only python project I’ve seen so far where tests cannot be run from the source directory. Is that really expected?

**Comment by aragilar** [comment]
You could comment out https://github.com/h5py/h5py/blame/master/h5py/__init__.py#L28 and try to debug the error which is causing the module to fail to import in your particular case (as it should only be thrown if there's another issue), but the moving directory thing was implicitly (from a user's perspective - see https://github.com/h5py/h5py/blob/2.10.0/setup.py#L65) happening when you ran `python setup.py test`. tox is set up to do the same directory switch. The "cannot run tests from source directory" is something we explicitly force, as importing h5py while in the source directory without having things set up correctly throws up odd errors.

As a heads up, you probably also want to move to using a wrapper around pep517 to do the install/build, as I'm guessing you'd want to control the versions of numpy/cython used (rather than the one we use to build the wheels), as while I don't think setuptools is going to drop either the build or install commands any time soon, it wouldn't surprise me if you run into weird errors around them (there's some discussion around how Fedora handles that at https://discuss.python.org/t/pep-610-usage-guidelines-for-linux-distributions/4012).

**Comment by ArchangeGabriel** [comment]
Yeah I know about pep517, but this will be happening distro-wide (I’m packaging for Arch Linux), and we will have a migration to it when we’re ready (IIRC people don’t want to use pip, but I’m not in charge for this so I’ll just follow whatever new process they come with).

So if being in another directory is this much expected for h5py, it’s fine, I’ll just switch to this. Thanks for your input!
