### ISSUE TITLE
type error on assigning mixed type list containing str to .attrs

### ISSUE THREAD

**Issue by ivirshup** [h5py/h5py#1763]
This is a bit weird, but I'm trying to figure out some edge cases around the new string handling.

```python
import h5py

with h5py.File("test.h5", "w") as f:
    g = f.create_group("foo")
    g.attrs["list"] = ["abc", b"def"]
```

Traceback:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 103, in __setitem__
    self.create(name, data=value)
  File "/usr/local/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 180, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1629, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1653, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1719, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U3')
```

I would argue that `bytes` objects should not be considered text data, and there could be an error here about not being able to write mixed type attributes.

However, this would conflict with some other `attr` setting behaviour, which seems to go for very lenient conversion. For example `dset.attrs["key"] = [1, b"a"]` does not error, but is read back in as `array([b'1', b'a'], dtype='|S21')`.

AFAICT, this only seems to error if one of the elements is a `str`.
 

<details>
<summary> version info </summary>

```
Summary of the h5py configuration
---------------------------------

h5py    3.1.0
HDF5    1.12.0
Python  3.8.5 (default, Jul 23 2020, 15:50:11) 
[Clang 11.0.3 (clang-1103.0.32.62)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.19.4
cython (built with) 0.29.21
numpy (built against) 1.17.5
HDF5 (built against) 1.12.0
```

</details>

**Comment by ivirshup** [comment]
I've changed the name, to better reflect the strange behaviour. Basically that:

```python
>>> f.attrs["foo"] = [1, b"a"]
>>> f.attrs["foo"]
array([b'1', b'a'], dtype='|S21')  # Weird conversion
>>> f.attrs["bar"] = [b"a", "b"]
...
TypeError: No conversion path for dtype: dtype('<U21')   # Also weird conversion
>>> f.attrs["baz"] = [b"a", b"b"]
array(['a', 'b'], dtype=object)
# Why would this be str, if the example with an int became fixed length ascii?
```

**Comment by aragilar** [comment]
@ivirshup Did you see what happens when you convert those lists to a numpy array? If they behave the same then I think this behaviour is fine, if there's a difference, then that would be worth looking at.

**Comment by ivirshup** [comment]
Since these would all need to be `object` dtype, none of these work with numpy arrays. They all error like:

```pytb
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

<details>
<summary> Full traceback </summary>

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-c10f1a126e08> in <module>
----> 1 f.attrs["bar"] = np.array([1, 2, 3], dtype=object)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/usr/local/lib/python3.8/site-packages/h5py/_hl/attrs.py in __setitem__(self, name, value)
    101         use the methods create() and modify().
    102         """
--> 103         self.create(name, data=value)
    104 
    105     @with_phil

/usr/local/lib/python3.8/site-packages/h5py/_hl/attrs.py in create(self, name, data, shape, dtype)
    178             # Make HDF5 datatype and dataspace for the H5A calls
    179             if use_htype is None:
--> 180                 htype = h5t.py_create(original_dtype, logical=True)
    181                 htype2 = h5t.py_create(original_dtype)  # Must be bit-for-bit representation rather than logical
    182             else:

h5py/h5t.pyx in h5py.h5t.py_create()

h5py/h5t.pyx in h5py.h5t.py_create()

h5py/h5t.pyx in h5py.h5t.py_create()

TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

</details>

**Comment by takluyver** [comment]
What's happening here is that our special cases for vlen string data look for uniform lists/tuples/object arrays, where all of the elements are the same type (either str or bytes). If it doesn't match one of those rules, it lets numpy figure it out with `np.asarray(data)`. NumPy appears to be surprisingly gung-ho about converting numbers to strings and byte strings to unicode strings to make a homogeneous array.

In general, I'm inclined to leave it up to NumPy's rules. It's not what I'd pick, but it's nice to have a bigger project to point to. But as we special case lists of bytes and lists of str, maybe we should special case a list containing both to be treated like... one of them. Not sure which, at present.
