### ISSUE TITLE
"ValueError: Illegal slicing argument for scalar dataspace" from `AsStrWrapper`

### ISSUE THREAD

**Issue by nanthony21** [h5py/h5py#1779]
h5py    3.1.0
HDF5    1.10.6
Python  3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.19.2
cython (built with) 0.29.21
numpy (built against) 1.16.5
HDF5 (built against) 1.10.6

I have a `str` dataset that was saved like so: `h5pyFile.create_dataset(dataName, data=numpy.string_(strData))`

I can successfully read the dataset back as `str` using the following: `bytes(np.array(h5pyFile[dataName])).decode()`

I was hoping for something less difficult to read so I tried what is shown in the documentation: `h5pyFile[dataName].asstr()[:]`

However, this results in  the following error. Am I doing something wrong or is there an issue with the `AsStrWrapper`?

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\backman05\Anaconda3\envs\pwspyDev\lib\site-packages\h5py\_hl\dataset.py", line 203, in __getitem__
    bytes_arr = self.dset[args]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\backman05\Anaconda3\envs\pwspyDev\lib\site-packages\h5py\_hl\dataset.py", line 766, in __getitem__
    selection = sel2.select_read(fspace, args)
  File "C:\Users\backman05\Anaconda3\envs\pwspyDev\lib\site-packages\h5py\_hl\selections2.py", line 101, in select_read
    return ScalarReadSelection(fspace, args)
  File "C:\Users\backman05\Anaconda3\envs\pwspyDev\lib\site-packages\h5py\_hl\selections2.py", line 86, in __init__
    raise ValueError("Illegal slicing argument for scalar dataspace")
ValueError: Illegal slicing argument for scalar dataspace
```

**Comment by takluyver** [comment]
For scalar datasets you always need to read with `[()]` rather than `[:]` - `[:]` selects from the start to the end of the first dimension, but a scalar has no dimensions. This is the same whether or not you use `.asstr()`:

```python
f['a'][()].decode()
f['a'].asstr()[()]
```

**Comment by wkirgsn** [comment]
infuriating that this is not mentioned in the [quick start guide](https://docs.h5py.org/en/stable/quick.html)
