### ISSUE TITLE
Installing in GitHub Actions - ImportError: cannot import name h5l

### ISSUE THREAD

**Issue by dburkhardt** [h5py/h5py#1781]
Hi, our lab is transitioning from TravisCI to github actions and I'm getting a troublesome bug using h5py. You can see an example error in our most recent build attempt here: 
https://github.com/KrishnaswamyLab/scprep/runs/1559976140?check_suite_focus=true#step:8:426

The relevant trace:

```
======================================================================
ERROR: test_io.transplant_class.<locals>.C (test_10X_HDF5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/scprep/scprep/test/test_io.py", line 292, in test_10X_HDF5
    X_hdf5 = scprep.io.load_10X_HDF5(h5_file, backend="h5py")
  File "<decorator-gen-7>", line 2, in load_10X_HDF5
  File "/home/runner/work/scprep/scprep/scprep/io/hdf5.py", line 24, in with_HDF5
    return fun(*args, **kwargs)
  File "/home/runner/work/scprep/scprep/scprep/io/tenx.py", line 307, in load_10X_HDF5
    with hdf5.open_file(filename, "r", backend=backend) as f:
  File "<decorator-gen-3>", line 2, in open_file
  File "/home/runner/work/scprep/scprep/scprep/io/hdf5.py", line 24, in with_HDF5
    return fun(*args, **kwargs)
  File "/home/runner/work/scprep/scprep/scprep/io/hdf5.py", line 57, in open_file
    return h5py.File(filename, mode)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/h5py/_hl/files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
  File "h5py/h5g.pyx", line 267, in h5py.h5g.GroupID.__init__
  File "h5py/h5g.pyx", line 268, in h5py.h5g.GroupID.__init__
ImportError: cannot import name h5l
```

This is running on Ubuntu 18.04, Python 3.6-3.8, and it the libhdf5-dev verison is 1.10.0-patch1+docs-4 and h5py version 3.1.0.

The GitHub Actions YAML is here: https://github.com/KrishnaswamyLab/scprep/blob/dev/.github/workflows/run_tests.yml

Any idea what's going on?

**Comment by tacaswell** [comment]
The way that the paths jump around from `/opt/...` to just `h5py/...` makes me suspicious that you have a broken installation, but I can not see anything funny in the logs...

**Comment by cwiede** [comment]
I am having the same issue in a continuous integration test (it's using jenkins via docker in a virtual env). h5py Version 0.3.1. I have tried to open a h5 file in an interactive session using the same docker container, and this was working. These tests pass with version 0.2.10.

Traceback (most recent call last):
  File "/media/sf_C_DRIVE/Projects/iCV-Algo/nexxT/core/app-specific/python-nexxT/nexxT/filters/hdf5.py", line 427, in onSuggestDynamicPorts
    f = h5py.File(fn, "r")
  File "/home/jenkins/venvs/nexxT-42d9c9c238d56943a6e0cb84718ae0b9/lib/python3.7/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/home/jenkins/venvs/nexxT-42d9c9c238d56943a6e0cb84718ae0b9/lib/python3.7/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
  File "h5py/h5g.pyx", line 267, in h5py.h5g.GroupID.__init__
  File "h5py/h5g.pyx", line 268, in h5py.h5g.GroupID.__init__

**Comment by dburkhardt** [comment]
@tacaswell do you know of a minimum working example using h5py with GitHub Actions?

**Comment by vasole** [comment]
@dburkhardt 

Does this help?

https://github.com/silx-kit/hdf5plugin/blob/master/.github/workflows/ci.yml

**Comment by cwiede** [comment]
Just want to give a quick update on this, I think have found the issue causing this error for me. The application I'm using has a feature to automatically unload pure python modules on certain triggers. Once unloaded the error happens when trying to import the h5py package a second time. Avoiding this fixes the error for me. Admittedly, this might be declared as a misuse or at least a corner case.

A test case to reproduce is here (this fails with 3.2.1 and passes with 2.10.0):

```
import sys
from importlib.machinery import ExtensionFileLoader

modulesBefore = set(sys.modules.keys())
def importit():
    import h5py
    f = h5py.File("/tmp/tmpfile.h5", "w")
    f.close()

importit()
modulesAfter = set(sys.modules.keys())

for m in modulesAfter.difference(modulesBefore):
    mod = sys.modules[m]
    loader = getattr(mod, '__loader__', None)
    if not isinstance(loader, ExtensionFileLoader):
        print("unloading ", m)
        del sys.modules[m]

importit()

```

The traceback is given here:

```
Traceback (most recent call last):
  File "/tmp/h5py-issue-1781.py", line 20, in <module>
    importit()
  File "/tmp/h5py-issue-1781.py", line 7, in importit
    f = h5py.File("/tmp/tmpfile.h5", "w")
  File "/tmp/venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 445, in __init__
    swmr=swmr)
  File "/tmp/venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 201, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 116, in h5py.h5f.create
  File "h5py/h5g.pyx", line 267, in h5py.h5g.GroupID.__init__
  File "h5py/h5g.pyx", line 268, in h5py.h5g.GroupID.__init__
ImportError: cannot import name h5l
```
