### ISSUE TITLE
read_direct() throws TypeError when trying to slice into a multi-dimensional dataset

### ISSUE THREAD

**Issue by Spielix** [h5py/h5py#1783]
Config:
```
h5py    2.10.0
HDF5    1.10.6
Python  3.9.0 (default, Oct  6 2020, 00:00:00) 
[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.4
```
My linux distribution is Fedora 33 Workstation and the software comes from the Fedora packages.
Trace:
```
Traceback (most recent call last):
  File "/home/me/my_code.py", line 28, in <module>
    f[ks[timeIndex] + '/ComplexGrid/%i'%(index)].read_direct(field, source_sel=np.s_[0, :, :])
  File "/usr/lib64/python3.9/site-packages/h5py/_hl/dataset.py", line 732, in read_direct
    for mspace in dest_sel.broadcast(source_sel.mshape):
  File "/usr/lib64/python3.9/site-packages/h5py/_hl/selections.py", line 304, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (512, 512, 1024) -> (512, 1024)
```
As I specify in the source_sel to only take the 0th continuous 2D slice out of the 3D dataset, I would expect there to be no need to broadcast sth of shape (512, 512, 1024), but only of shape (1, 512, 1024) or (512, 1024). 
This might be connected to the problems in #1773 .

**Comment by Spielix** [comment]
The error was on my side. I didn't expect the shape to be (1,512,512,1024).
