### ISSUE TITLE
Issue when garbage collecting h5py objects during File.close

### ISSUE THREAD

**Issue by asmeurer** [h5py/h5py#1852]
There is an issue when the garbage collector is run during File.close. Here is a script that reproduce the issue

```py
import h5py

N = 100
with h5py.File('foo.h5', 'w') as f:
    for i in range(N):
        f[str(i)] = []

for i in range(100):
    print("i =",i)
    with h5py.File('foo.h5', 'r') as f:
        refs = []
        for i in range(N):
            refs.append(f[str(i)].id)
        refs.append(refs)
        del refs  # <-- important to make it likely that gc of id refs happens during h5py.File.close
```

The traceback is

```pytb
i = 0
i = 1
Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/versioned-hdf5/test3.py", line 15, in <module>
    del refs  # <-- important to make it likely that gc of id refs happens during h5py.File.close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/aaronmeurer/Documents/h5py/h5py/_hl/files.py", line 493, in __exit__
    self.close()
  File "/Users/aaronmeurer/Documents/h5py/h5py/_hl/files.py", line 463, in close
    id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 277, in h5py.h5f.get_obj_ids
RuntimeError: Can't increment id ref count (can't locate ID)
```

The loop is there to make sure that the issue consistently reproduces. Sometimes a small change can appear to "fix" the issue because it changes when the garbage collector is run, but it will still occur after enough iterations.

The issue exists in h5py 2.10, 3.1, and the git master. 

The problem is that `get_obj_ids` gets a list of valid object IDs from `H5Fget_obj_ids`, but one of the object IDs becomes invalid in the middle of the function call, so `H5Iinc_ref` fails. 

A viable workaround is to either call `gc.collect()` before the file is closed (at the end of the `with` block), or to disable garbage collection in `File.close`, like

```patch
diff --git a/h5py/_hl/files.py b/h5py/_hl/files.py
index 60a24c0c..a0f1766e 100644
--- a/h5py/_hl/files.py
+++ b/h5py/_hl/files.py
@@ -460,22 +460,27 @@ class File(Group):
 
                 # Close file-resident objects first, then the files.
                 # Otherwise we get errors in MPI mode.
-                id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
-                file_list = h5f.get_obj_ids(self.id, h5f.OBJ_FILE)
-
-                id_list = [x for x in id_list if h5i.get_file_id(x).id == self.id.id]
-                file_list = [x for x in file_list if h5i.get_file_id(x).id == self.id.id]
-
-                for id_ in id_list:
-                    while id_.valid:
-                        h5i.dec_ref(id_)
-
-                for id_ in file_list:
-                    while id_.valid:
-                        h5i.dec_ref(id_)
-
-                self.id.close()
-                _objects.nonlocal_close()
+                import gc
+                gc.disable()
+                try:
+                    id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
+                    file_list = h5f.get_obj_ids(self.id, h5f.OBJ_FILE)
+
+                    id_list = [x for x in id_list if h5i.get_file_id(x).id == self.id.id]
+                    file_list = [x for x in file_list if h5i.get_file_id(x).id == self.id.id]
+
+                    for id_ in id_list:
+                        while id_.valid:
+                            h5i.dec_ref(id_)
+
+                    for id_ in file_list:
+                        while id_.valid:
+                            h5i.dec_ref(id_)
+
+                    self.id.close()
+                    _objects.nonlocal_close()
+                finally:
+                    gc.enable()
 
     def flush(self):
         """ Tell the HDF5 library to flush its buffers.
```

Both of these appear to consistently make the issue go away. I don't know if that is a real "solution" or just a bandaid to the real underlying problem. I'm not familiar enough with the Python garbage collection, Cython, or HDF5 to know what a real fix should look like for this.

```
Summary of the h5py configuration
---------------------------------

h5py    3.2.1
HDF5    1.10.6
Python  3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:32:59)
[Clang 11.0.1 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.20.1
cython (built with) 0.29.21
numpy (built against) 1.19.3
HDF5 (built against) 1.10.6
```

**Comment by takluyver** [comment]
Opened #1854 to address this.
