### ISSUE TITLE
RuntimeError: Unable to create attribute (object header message is too large)

### ISSUE THREAD

**Issue by tdegeus** [h5py/h5py#1855]
With this:
```python
import numpy as np
import h5py

with h5py.File('test.h5', 'w') as data:

    data['mydataset'] = np.random.random(10000)
    data['mydataset'].attrs['myattr'] = np.random.random(10000)
```
I'm getting the error that 
```none
Traceback (most recent call last):
  File "/Users/tdegeus/Downloads/test.py", line 7, in <module>
    data['mydataset'].attrs['myattr'] = np.random.random(10000)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/tdegeus/opt/miniconda3/envs/stable/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 103, in __setitem__
    self.create(name, data=value)
  File "/Users/tdegeus/opt/miniconda3/envs/stable/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 197, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 50, in h5py.h5a.create
RuntimeError: Unable to create attribute (object header message is too large)
```
I didn't know that attributes couldn't be large as well?

---------

```
python -c 'import h5py; print(h5py.version.info)'
```

```
Summary of the h5py configuration
---------------------------------

h5py    3.1.0
HDF5    1.10.6
Python  3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38)
[Clang 11.0.1 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.20.1
cython (built with) 0.29.21
numpy (built against) 1.16.5
HDF5 (built against) 1.10.6
```

**Comment by takluyver** [comment]
It's kind of a limitation. Attributes are normally up to 64 KB. It is possible to store larger attributes, but you have to configure this when creating the object (e.g. the dataset) which will have the attributes ([HDF5 user guide](https://support.hdfgroup.org/HDF5/doc/UG/HDF5_Users_Guide-Responsive%20HTML5/index.html#t=HDF5_Users_Guide%2FAttributes%2FHDF5_Attributes.htm%23TOC_8_5_Special_Issuesbc-13&rhtocid=8.2_1)). The `set_attr_phase_change` method is exposed in h5py 3.x (PR #1638), but only in the [low-level API](https://api.h5py.org/), so you'd have to create the dataset with low-level functions to do that.

The error message comes from HDF5.
