### ISSUE TITLE
Trouble repeatadely copying a group and deleting its members

### ISSUE THREAD

**Issue by lwpiotr** [h5py/h5py#1886]
Hello,

I have an HDF5 file with "Run_0/Event_1" group that contains 176 "Traces_A..." groups. I multiply the events in the file, by copying Event_1 to Event_2, Event_3 and so on. In the process, I delete all the Traces copied from Event_1 and recreate a random number of them. If the recreated number is smaller than the original number, random crashes on copying the group happen. Meaning: the script usually crashes, but on copying random event. Sometimes finishes without crashing:

`EVENT! Event_2
EVENT! Event_3
EVENT! Event_4
Traceback (most recent call last):
  File "/data/GRAND/data_format/./hdf5toROOT_trackclass_varhdf5.py", line 500, in <module>
    a = main()
  File "/data/GRAND/data_format/./hdf5toROOT_trackclass_varhdf5.py", line 154, in main
    t = treelist2trees(trees, breed_events=96, hdf5_file=ft, hdf5_address=hdf5_address, hdf5_fieldname=hdf5_fieldname)
  File "/data/GRAND/data_format/./hdf5toROOT_trackclass_varhdf5.py", line 371, in treelist2trees
    hdf5_file.copy(hdf5_file["Run_0/Event_1"], hdf5_file["Run_0"], name="Event_%d"%(i+2))
  File "/usr/local/lib64/python3.9/site-packages/h5py/_hl/group.py", line 521, in copy
    h5o.copy(source.id, self._e(source_path), dest.id, self._e(dest_path),
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 217, in h5py.h5o.copy
RuntimeError: Unable to copy object (can't insert duplicate key)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't remove tag info from list)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 199, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (can't remove tag info from list)
Segmentation fault (core dumped)
`

If I stop recreating traces at all, just delete them, it seems to crash always, at copying to Event_4. This is the relevant part of the code:

`			for i in range(breed_events):
				vtraces.clear()
				print("EVENT!", "Event_%d"%(i+2))
				hdf5_file.copy(hdf5_file["Run_0/Event_1"], hdf5_file["Run_0"], name="Event_%d"%(i+2))
				# Deleting the original traces, so I can recreate variable number of them
				for trr in traces:
					del hdf5_file[f"/Run_0/Event_{i+2}/"+trr]
`

The fact that deleting without recreating the traces makes it crash always, and that copy complains about duplicate objects, makes me think that the deletion is somehow not complete. Of course, there could be some memory corruption in another part of the script, which is not that simple. Could you help me trace the issue?

Linux, Fedora 33, Python 3.9.4, h5py 3.2.1

**Comment by takluyver** [comment]
Can you make a minimal example that reproduces this from scratch (i.e. start by creating a new file)?

**Comment by lwpiotr** [comment]
Yes, please. I paste it below. If it helps: when I had 6 datasets instead of 1, it was crashing on Event_3. With 1 dataset, it is crashing on Event_4. I am sorry for the code formatting, but I am not sure why not all of my code is formatted...

`

#!/usr/bin/python

import h5py
import numpy as np
import random

def main():
	ft = h5py.File('test.hdf5','w')

	# Create the 1st event
	grp = ft.create_group("Event_1")
	# Some random, copied dataset
	grp.create_dataset("ds", data=np.random.rand(40).astype(dtype=np.float32))
	# Create traces in the first group
	trace_length = 1000
	for k in range(200):
		x1 = np.random.rand(trace_length).astype(dtype=np.float32)

		grp = ft.create_group(f"/Event_1/Traces_A{k}")
		grp.create_dataset("SimEfield_X", data=x1)

	# Create 100 more events, through copying, deleting, overwriting
	for ev in range(100):
		print(f"Event_{ev+2}", ev+2)
		# Copy the event
		ft.copy(ft["Event_1"], ft["/"], name="Event_%d"%(ev+2))
		
		print(ft["Event_1/Traces_A199"])
		
		# Delete the traces copied from Event_1
		for trr in range(200):
			print(f"/Event_{ev+2}/Traces_A{trr}")
			del ft[f"/Event_{ev+2}/Traces_A{trr}"]
			
	ft.close()
	
if __name__ == '__main__':
	a = main()
	
`

**Comment by takluyver** [comment]
Thanks! BTW, it's triple backticks to mark a block of code (I've just edited your post to fix the code block):

    ```python
    print('hello')
    ```

**Comment by takluyver** [comment]
I think this is coming from HDF5 itself - cc @epourmal . I turned on HDF5's error reporting (`h5py._errors.unsilence_errors()`), and this is what it shows:

```
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: H5Ocopy.c line 251 in H5Ocopy(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #001: H5VLcallback.c line 5530 in H5VL_object_copy(): object copy failed
    major: Virtual Object Layer
    minor: Unable to copy object
  #002: H5VLcallback.c line 5491 in H5VL__object_copy(): object copy failed
    major: Virtual Object Layer
    minor: Unable to copy object
  #003: H5VLnative_object.c line 126 in H5VL__native_object_copy(): unable to copy object
    major: Symbol table
    minor: Unable to copy object
  #004: H5Ocopy.c line 313 in H5O_copy(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #005: H5Ocopy.c line 1217 in H5O__copy_obj(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #006: H5Ocopy.c line 1161 in H5O__copy_header(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #007: H5Ocopy.c line 868 in H5O__copy_header_real(): unable to perform 'post copy' operation on message
    major: Object header
    minor: Unable to initialize object
  #008: H5Ostab.c line 403 in H5O__stab_post_copy_file(): iteration operator failed
    major: Symbol table
    minor: Unable to initialize object
  #009: H5B.c line 1212 in H5B_iterate(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #010: H5B.c line 1168 in H5B__iterate_helper(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #011: H5B.c line 1168 in H5B__iterate_helper(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #012: H5Gnode.c line 1300 in H5G__node_copy(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #013: H5Ocopy.c line 986 in H5O_copy_header_map(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #014: H5Ocopy.c line 868 in H5O__copy_header_real(): unable to perform 'post copy' operation on message
    major: Object header
    minor: Unable to initialize object
  #015: H5Ostab.c line 403 in H5O__stab_post_copy_file(): iteration operator failed
    major: Symbol table
    minor: Unable to initialize object
  #016: H5B.c line 1212 in H5B_iterate(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #017: H5B.c line 1168 in H5B__iterate_helper(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #018: H5Gnode.c line 1300 in H5G__node_copy(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #019: H5Ocopy.c line 986 in H5O_copy_header_map(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #020: H5Ocopy.c line 886 in H5O__copy_header_real(): unable to re-tag metadata entries
    major: Object cache
    minor: Unable to tag metadata in the cache
  #021: H5AC.c line 2223 in H5AC_retag_copied_metadata(): Can't retag metadata
    major: Object cache
    minor: Can't set value
  #022: H5Ctag.c line 804 in H5C_retag_entries(): can't insert tag info in skip list
    major: Object cache
    minor: Unable to insert object
  #023: H5SL.c line 1122 in H5SL_insert(): can't create new skip list node
    major: Skip Lists
    minor: Unable to insert object
  #024: H5SL.c line 783 in H5SL_insert_common(): can't insert duplicate key
    major: Skip Lists
    minor: Unable to insert object
```

(Followed by another error when it tries to close the objects)

**Comment by epourmal** [comment]
Yes, those errors are coming from HDF5. We will need to reproduce application/h5py behavior in C. Could you please submit C example to help@hdfroup.org? 

Have you tried the same script with h5py based on HDF5 1.10.* versions?

**Comment by takluyver** [comment]
I saw the same error with HDF5 1.10.5 - I'll put the traceback below.

As this isn't affecting me personally, I probably won't find time any time soon to work on reproducing this in C. For whoever does want to, `ft.copy(...)` is calling the C function `H5Ocopy`, and `del ft[...]` is calling `H5Gunlink`.


<details>
<summary>Traceback from 1.10.5</summary>

```
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 139794736166720:
  #000: H5Ocopy.c line 233 in H5Ocopy(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #001: H5Ocopy.c line 314 in H5O__copy(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #002: H5Ocopy.c line 1218 in H5O__copy_obj(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #003: H5Ocopy.c line 1162 in H5O__copy_header(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #004: H5Ocopy.c line 869 in H5O__copy_header_real(): unable to perform 'post copy' operation on message
    major: Object header
    minor: Unable to initialize object
  #005: H5Ostab.c line 403 in H5O__stab_post_copy_file(): iteration operator failed
    major: Symbol table
    minor: Unable to initialize object
  #006: H5B.c line 1211 in H5B_iterate(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #007: H5B.c line 1167 in H5B__iterate_helper(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #008: H5B.c line 1167 in H5B__iterate_helper(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #009: H5Gnode.c line 1302 in H5G__node_copy(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #010: H5Ocopy.c line 987 in H5O_copy_header_map(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #011: H5Ocopy.c line 869 in H5O__copy_header_real(): unable to perform 'post copy' operation on message
    major: Object header
    minor: Unable to initialize object
  #012: H5Ostab.c line 403 in H5O__stab_post_copy_file(): iteration operator failed
    major: Symbol table
    minor: Unable to initialize object
  #013: H5B.c line 1211 in H5B_iterate(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #014: H5B.c line 1167 in H5B__iterate_helper(): B-tree iteration failed
    major: B-Tree node
    minor: Iteration failed
  #015: H5Gnode.c line 1302 in H5G__node_copy(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #016: H5Ocopy.c line 987 in H5O_copy_header_map(): unable to copy object
    major: Object header
    minor: Unable to copy object
  #017: H5Ocopy.c line 887 in H5O__copy_header_real(): unable to re-tag metadata entries
    major: Object cache
    minor: Unable to tag metadata in the cache
  #018: H5AC.c line 2236 in H5AC_retag_copied_metadata(): Can't retag metadata
    major: Object cache
    minor: Can't set value
  #019: H5Ctag.c line 804 in H5C_retag_entries(): can't insert tag info in skip list
    major: Object cache
    minor: Unable to insert object
  #020: H5SL.c line 1122 in H5SL_insert(): can't create new skip list node
    major: Skip Lists
    minor: Unable to insert object
  #021: H5SL.c line 783 in H5SL_insert_common(): can't insert duplicate key
    major: Skip Lists
    minor: Unable to insert object
```
</details>
