### ISSUE TITLE
File "h5py\h5f.pyx", line 116, in h5py.h5f.create OSError: Unable to create file (unable to open file: name = 'models/bidirectional_LSTM_best_weights_01-0.8518.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)

### ISSUE THREAD

**Issue by NihaHoney** [h5py/h5py#1900]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
 * Python version (e.g. 2.7, 3.5)
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version (e.g. 2.6)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

**Comment by NihaHoney** [comment]
Operating System (Windows 10)
Python version (3.6.5)
Where Python was acquired (Without Anaconda on Windows)
h5py version (3.1.0)
HDF5 version (1.12.0)



`from kutilities.callbacks import MetricsCallback, PlottingCallback
from sklearn.metrics import f1_score, precision_score, recall_score
from keras.callbacks import ModelCheckpoint, TensorBoard

metrics = {
    "f1_e": (lambda y_test, y_pred:
             f1_score(y_test, y_pred, average='micro',
                      labels=[emotion2label['happy'],
                              emotion2label['sad'],
                              emotion2label['angry']
                              ])),
    "precision_e": (lambda y_test, y_pred:
                    precision_score(y_test, y_pred, average='micro',
                                    labels=[emotion2label['happy'],
                                            emotion2label['sad'],
                                            emotion2label['angry']
                                            ])),
    "recoll_e": (lambda y_test, y_pred:
                 recall_score(y_test, y_pred, average='micro',
                              labels=[emotion2label['happy'],
                                      emotion2label['sad'],
                                      emotion2label['angry']
                                      ]))
}

_datasets = {}
_datasets["dev"] = [[message_first_message_dev, message_second_message_dev, message_third_message_dev],
                    np.array(labels_categorical_dev)]
_datasets["val"] = [[message_first_message_val, message_second_message_val, message_third_message_val],
                    np.array(labels_categorical_val)]

metrics_callback = MetricsCallback(datasets=_datasets, metrics=metrics)

filepath = "models/bidirectional_LSTM_best_weights_{epoch:02d}-{val_acc:.4f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', save_best_only=True, save_weights_only=False,
                             mode='auto', period=1)
tensorboardCallback = TensorBoard(log_dir='./Graph', histogram_freq=0, write_graph=True, write_images=True)
history = model.fit([message_first_message_train, message_second_message_train, message_third_message_train],
                    np.array(labels_categorical_train),
                    callbacks=[metrics_callback, checkpoint, tensorboardCallback],
                    validation_data=(
                        [message_first_message_val, message_second_message_val, message_third_message_val],
                        np.array(labels_categorical_val)
                    ),
                    epochs=20,
                    batch_size=200)
model.load_weights("models/bidirectional_LSTM_best_weights_0010-0.9125.hdf5")
y_pred = model.predict([message_first_message_dev, message_second_message_dev, message_third_message_dev])`






This is the Code for Bidirectional LSTM 
Iam getting beow error...


Epoch 1/20
24128/24128 [==============================] - 142s 6ms/step - loss: 0.7730 - acc: 0.6909 - val_loss: 0.4105 - val_acc: 0.8518
         f1_e  precision_e  recoll_e
dev  0.596962     0.475783  0.800959
val  0.833550     0.827364  0.839830

Traceback (most recent call last):
  File "Jarvis.py", line 220, in <module>
    batch_size=200)
  File "C:\Users\Niharika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1037, in fit
    validation_steps=validation_steps)
  File "C:\Users\Niharika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_arrays.py", line 217, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\Niharika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\Niharika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\callbacks.py", line 444, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "C:\Users\Niharika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 1085, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Users\Niharika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 105, in save_model
    f = h5py.File(filepath, mode='w')
  File "C:\Users\Niharika\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 427, in __init__
    swmr=swmr)
  File "C:\Users\Niharika\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 196, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 116, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'models/bidirectional_LSTM_best_weights_01-0.8518.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)


Please help me in this.

@sismetanin
@Fahad113
@IvanEvan

**Comment by NihaHoney** [comment]
Solved by giving right directory path.
