### ISSUE TITLE
 object has no attribute 'get_nfilters

### ISSUE THREAD

**Issue by mba5811** [h5py/h5py#1906]
hello all,

I'm using h5py to save some calculated data but i get this error"

AttributeError: 'h5py.h5p.PropFCID' object has no attribute 'get_nfilters'

Actually, there is a similar problem, solved on github (you can find it here : https://github.com/h5py/h5py/issues/1437) but there, the error is about 'set_fapl_mpio' and not  'get_nfilters' as mine. Can anyone suggest something? Thanks in advance.

**Comment by takluyver** [comment]
What is your code doing? Can you show the traceback associated with the error?

**Comment by mba5811** [comment]
Here is my code: (of course, it has some preliminaries)

#########################################################################################
#Decay 
	rho_t = qutip.mesolve( H_0 + H_int , rho0, t_list, c_ops, [ ], options=OptList)

#########################################################################################

#########################################################################################
	save_path_data = 'rho_Ncells=%d_B0=%.1f_disor=%.1f_N_realizations=%.1f' %(Ncells,B0,hdisorder,N_realizations)
	if not os.path.exists(save_path_data): # checa se caminho acima existe. Caso não, cria. 
		os.makedirs(save_path_data)

	np.savetxt(os.path.join(save_path_data,'Bzlist_Nth=%d_Ncells=%d_B0=%.1f_disor=%.1f.dat') %(Nth_r,Ncells,B0,hdisorder) ,Bzlist)

#creating file name
	filename_out = 'rho_Nth=%d_Ncells=%d_B0=%.1f_disor=%.1f.h5' %(Nth_r,Ncells,B0,hdisorder) 

	f = h5py.File(os.path.join(save_path_data, filename_out), 'w')

	g1 = f.create_group('1')


	dset_rho = g1.create_dataset("rho", (len(t_list),2**Ncells,2**Ncells), dtype='complex64') 

	dset_time = g1.create_dataset("time", (len(t_list),), dtype='float64')

	dset_time[:]=np.array(t_list)[:]

	for t in range(0,len(t_list)):
		dset_rho[t,:,:] = rho_t.states[t].full()[:,:]

	del Bzlist, rho_t, H_0, dset_rho, dset_time, filename_out

totally in a loop.

**Comment by takluyver** [comment]
Thanks. And the traceback (which should show where the error comes from)

**Comment by mba5811** [comment]
Traceback (most recent call last):
  File "/storage/emulated/0/Download/Master_solve.py", line 134, in <module>
    dset_rho = g1.create_dataset("rho", (len(t_list),2*Ncells,2*Ncells), dtype='complex64') 
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/h5py/_hl/group.py", line 137, in create_dataset
    dset = dataset.Dataset(dsid)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/h5py/hl/dataset.py", line 405, in __init_
    self._filters = filters.get_filters(self._dcpl)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/h5py/_hl/filters.py", line 259, in get_filters
    nfilters = plist.get_nfilters()
AttributeError: 'h5py.h5p.PropFCID' object has no attribute 'get_nfilters'

**Comment by takluyver** [comment]
That's weird. I can't see anything wrong in your code or in h5py - it's getting a file creation property list when it should be getting a dataset creation one.

I see from the line numbers in your traceback that you're using an old version of h5py (2.10). Is it possible to upgrade to a newer version and see if that fixes the problem? And what version of HDF5 do you have?

**Comment by mba5811** [comment]
Thanks for your attention. In fact, i had some problem with installing h5py. I read on a website that I should install versioned-hdf5. I just did so. It's version is 1.3.1 . And it installs h5py, automatically, but as you said, the old one.

**Comment by takluyver** [comment]
What does `print(h5py.version.info)` give you? And how are you installing these (e.g. pip, conda...)

**Comment by mba5811** [comment]
It is as follows:

h5py   2.10.0
HDF5  1.10.4
Python  3.8.3 (default, May 27 2020, 02:08:17
[GCC 9.3.0]
sys.platform      linux
sys.maxsize     9223372036854775807
numpy  1.18.4

I use pip to install things.

**Comment by takluyver** [comment]
Can you try with a newer version (`pip install --upgrade h5py`)? It doesn't look like you're using versioned-hdf5 in the code that you showed.

**Comment by mba5811** [comment]
I'm using Android, actually. But I have exactly the same versions on another phone and it works properly.

**Comment by takluyver** [comment]
Hmm, that's weird. Maybe the installation has just got corrupted on one device? Try uninstalling & reinstalling h5py & HDF5, see if that makes any difference.
