### ISSUE TITLE
Memory leak in test_file2.py::TestFileObj.test_exception_writeonly

### ISSUE THREAD

**Issue by rainwoodman** [h5py/h5py#1907]
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7): Linux, generic
 * Python version (e.g. 2.7, 3.5): 3.6
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows): custom built.
 * h5py version (e.g. 2.6) 3.2.1
 * HDF5 version (e.g. 1.8.17) 1.12.1
 * The full traceback/stack trace shown (if it appears)

Leak occurs during tests of test_file2.py::TestFileObj.test_exception_writeonly.

```
Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x5629fb49a63d in malloc llvm/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x7f5eb63ed0ea in __pyx_f_4h5py_5utils_emalloc(unsigned long) h5py/utils.pyx_cython_generated.cc:1889:20
    #2 0x7f5eb7dc4e93 in __pyx_f_4h5py_5_conv_conv_str2vlen(void*, void*, void*, void*) h5py/_conv.pyx_cython_generated.cc:4836:15
    #3 0x7f5eb7db1383 in __pyx_f_4h5py_5_conv_generic_converter(long, long, H5T_cdata_t*, unsigned long, unsigned long, unsigned long, void*, void*, long, int (*)(void*, void*, void*, void*), int (*)(long, long, void**), H5T_bkg_t) h5py/_conv.pyx_cython_generated.cc:3555:23
    #4 0x7f5eb7db0f8c in __pyx_f_4h5py_5_conv_str2vlen(long, long, H5T_cdata_t*, unsigned long, unsigned long, unsigned long, void*, void*, long) h5py/_conv.pyx_cython_generated.cc:6233:15
    #5 0x5629fbb239dc in H5T_convert hdf5/src/H5T.c:5395:13
    #6 0x5629fbb234d3 in H5Tconvert hdf5/src/H5T.c:3021:9
    #7 0x7f5eb8822660 in __pyx_f_4h5py_4defs_H5Tconvert(long, long, unsigned long, void*, void*, long) h5py/defs.pyx_cython_generated.cc:44627:21
    #8 0x7f5eb516e5ff in __pyx_f_4h5py_6_proxy_dset_rw(long, long, long, long, long, void*, int) h5py/_proxy.pyx_cython_generated.cc:2925:21
    #9 0x7f5eb4cee567 in __pyx_pf_4h5py_3h5d_9DatasetID_2write h5py/h5d.pyx_cython_generated.cc:4728:15
    #10 0x7f5eb4cee567 in __pyx_pw_4h5py_3h5d_9DatasetID_3write(_object*, _object*, _object*) h5py/h5d.pyx_cython_generated.cc:4575:13
    #11 0x5629fda81b39 in _PyCFunction_FastCallDict python_runtime/v3_6/Objects/methodobject.c:231:22
    #12 0x5629fda197da in _PyObject_FastCallDict python_runtime/v3_6/Objects/abstract.c:2313:18
    #13 0x5629fda3d83c in methoddescr_call python_runtime/v3_6/Objects/descrobject.c:246:14
    #14 0x7f5eb828112c in __Pyx_PyObject_Call(_object*, _object*, _object*) h5py/_objects.pyx_cython_generated.cc:12946:14
    #15 0x7f5eb82a5edc in __pyx_pf_4h5py_8_objects_9with_phil_wrapper h5py/_objects.pyx_cython_generated.cc:4111:23
    #16 0x7f5eb82a5edc in __pyx_pw_4h5py_8_objects_9with_phil_1wrapper(_object*, _object*, _object*) h5py/_objects.pyx_cython_generated.cc:4032:13
    #17 0x7f5ebb6ec461 in __Pyx_CyFunction_CallMethod numpy/random/bit_generator.pyx_cython_generated.c:16647:16
    #18 0x7f5ebb6eb3ab in __Pyx_CyFunction_Call numpy/random/bit_generator.pyx_cython_generated.c:16692:12
    #19 0x7f5ebb6eb3ab in __Pyx_CyFunction_CallAsMethod numpy/random/bit_generator.pyx_cython_generated.c:16713:18
    #20 0x5629fda1973d in _PyObject_FastCallDict python_runtime/v3_6/Objects/abstract.c:2331:18
    #21 0x5629fdb3ea75 in call_function python_runtime/v3_6/Python/ceval.c:4875:17
    #22 0x5629fdb37892 in _PyEval_EvalFrameDefault python_runtime/v3_6/Python/ceval.c:3335:19
    #23 0x5629fdb3f613 in _PyEval_EvalCodeWithName python_runtime/v3_6/Python/ceval.c:4166:14
    #24 0x5629fdb2f3a3 in PyEval_EvalCodeEx python_runtime/v3_6/Python/ceval.c:4187:12
    #25 0x5629fda5e86d in function_call python_runtime/v3_6/Objects/funcobject.c:604:14
    #26 0x5629fda19364 in PyObject_Call python_runtime/v3_6/Objects/abstract.c:2261:14
    #27 0x5629fdb3754f in do_call_core python_runtime/v3_6/Python/ceval.c:5120:16
    #28 0x5629fdb3754f in _PyEval_EvalFrameDefault python_runtime/v3_6/Python/ceval.c:3404:22
    #29 0x5629fdb3f613 in _PyEval_EvalCodeWithName python_runtime/v3_6/Python/ceval.c:4166:14
    #30 0x5629fdb403d9 in fast_function python_runtime/v3_6/Python/ceval.c:4992:12
    #31 0x5629fdb3ea7c in call_function python_runtime/v3_6/Python/ceval.c:4872:17
    #32 0x5629fdb37b74 in _PyEval_EvalFrameDefault python_runtime/v3_6/Python/ceval.c:3351:19
    #33 0x5629fdb40930 in PyEval_EvalFrameEx python_runtime/v3_6/Python/ceval.c:754:12
    #34 0x5629fdb40930 in _PyFunction_FastCall python_runtime/v3_6/Python/ceval.c:4933:14
```

**Comment by schwehr** [comment]
Still seeing this issue at h5py version 3.11.0. Sorry I don't know about at newer versions yet.
