### ISSUE TITLE
new dataset can only set two attributes with swmr mode

### ISSUE THREAD

**Issue by ryan2x** [h5py/h5py#1910]
when using swmr mode, a newly created dataset can only set two attributes. However, when not using swmr mode, this problem does not exist.

`
h5_file = h5py.File("test1.hdf5", "w", libver='latest')
h5_file.swmr_mode = True
ds = h5_file.create_dataset(name="/good-stuff", data=np.random.uniform(size=(10,3)), maxshape=(None,4), chunks=(14,3))
for i in range(3):
    ds.attrs[f'key-{i+101}'] = np.random.uniform()
h5_file.close()
`

however, when not using swmr mode, it works
`
h5_file = h5py.File("test1.hdf5", "w", libver='latest')
ds = h5_file.create_dataset(name="/good-stuff", data=np.random.uniform(size=(10,3)), maxshape=(None,4), chunks=(14,3))
for i in range(3):
    ds.attrs[f'key-{i+101}'] = np.random.uniform()
h5_file.close()
`

**Comment by takluyver** [comment]
Thanks, I can reproduce this with h5py master & HDF5 1.12.0. I'll paste the traceback below.

cc @epourmal: I think the first 'Parent entry isn't pinned or protected' error is probably a bug in HDF5. The segfault may be a problem with how h5py handles that (though I can't see an obvious culprit at the moment).

```
Traceback (most recent call last):
  File "swmr-3-attrs.py", line 10, in <module>
    ds.attrs[f'key-{i+101}'] = np.random.uniform()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/takluyver/miniconda3/envs/h5py/lib/python3.7/site-packages/h5py/_hl/attrs.py", line 103, in __setitem__
    self.create(name, data=value)
  File "/home/takluyver/miniconda3/envs/h5py/lib/python3.7/site-packages/h5py/_hl/attrs.py", line 196, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 50, in h5py.h5a.create
RuntimeError: Unable to create attribute (Parent entry isn't pinned or protected)
Segmentation fault (core dumped)
```

**Comment by takluyver** [comment]
And here's the HDF5 traceback:

```
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 140159596828480:
  #000: H5A.c line 402 in H5Acreate_by_name(): unable to create attribute
    major: Attribute
    minor: Unable to initialize object
  #001: H5VLcallback.c line 1023 in H5VL_attr_create(): attribute create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 989 in H5VL__attr_create(): attribute create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_attr.c line 82 in H5VL__native_attr_create(): unable to create attribute
    major: Attribute
    minor: Unable to initialize object
  #004: H5Aint.c line 333 in H5A__create_by_name(): unable to create attribute
    major: Attribute
    minor: Unable to initialize object
  #005: H5Aint.c line 277 in H5A__create(): unable to create attribute in object header
    major: Attribute
    minor: Unable to insert object
  #006: H5Oattribute.c line 327 in H5O__attr_create(): unable to create new attribute in header
    major: Attribute
    minor: Unable to insert object
  #007: H5Omessage.c line 222 in H5O__msg_append_real(): unable to create new message
    major: Object header
    minor: No space available for allocation
  #008: H5Omessage.c line 1930 in H5O__msg_alloc(): unable to allocate space for message
    major: Object header
    minor: Unable to initialize object
  #009: H5Oalloc.c line 1343 in H5O__alloc(): unable to create a new object header data chunk
    major: Object header
    minor: No space available for allocation
  #010: H5Oalloc.c line 1195 in H5O__alloc_new_chunk(): can't allocate new object header chunk
    major: Object header
    minor: Can't allocate space
  #011: H5Oalloc.c line 1109 in H5O__alloc_chunk(): can't add new chunk to cache
    major: Object header
    minor: Unable to insert object
  #012: H5Ochunk.c line 129 in H5O__chunk_add(): unable to cache object header chunk
    major: Object header
    minor: Unable to insert object
  #013: H5AC.c line 811 in H5AC_insert_entry(): H5C_insert_entry() failed
    major: Object cache
    minor: Unable to insert metadata into cache
  #014: H5C.c line 1482 in H5C_insert_entry(): can't notify client about entry inserted into cache
    major: Object cache
    minor: Unable to notify object about action
  #015: H5Ocache.c line 969 in H5O__cache_chk_notify(): can't add object header chunk as parent of proxy
    major: Object header
    minor: Can't set value
  #016: H5ACproxy_entry.c line 182 in H5AC_proxy_entry_add_parent(): unable to set flush dependency on proxy entry
    major: Object cache
    minor: Unable to create a flush dependency
  #017: H5AC.c line 1237 in H5AC_create_flush_dependency(): H5C_create_flush_dependency() failed
    major: Object cache
    minor: Unable to create a flush dependency
  #018: H5C.c line 3581 in H5C_create_flush_dependency(): Parent entry isn't pinned or protected
    major: Object cache
    minor: Unable to create a flush dependency
```

**Comment by jangarrevoet** [comment]
It seems this has not been fixed yet. It would be nice to fix this since NeXus really relies on many attributes.
Used version to reproduce:
Summary of the h5py configuration
---------------------------------

h5py    3.13.0
HDF5    1.14.3
Python  3.11.11 | packaged by conda-forge | (main, Mar  3 2025, 20:43:55) [GCC 13.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.26.4
cython (built with) 3.0.12
numpy (built against) 2.0.2
HDF5 (built against) 1.14.3
