### ISSUE TITLE
h5py build from sources fails on python-3.9.5: ImportError: DLL load failed while importing

### ISSUE THREAD

**Issue by cheops** [h5py/h5py#1914]
environment:
* Windows 10
* Python 3.9.5 (from python.org)
* h5py source from github master (cc34c585ab29e859abda1d99830e7b9868197adb)
* hdf5 version 1.12.0
   downloaded hd5f libraries from https://www.hdfgroup.org/downloads/hdf5
   - hdf5-1.12.0-Std-win10_64-vs14-Intel.zip
   - hdf5plugin-1.12.0-win10_64-vs14-Intel.zip

installed packages in venv:
* Cython     0.29.23
* numpy      1.21.0
* pip        21.1.2
* setuptools 57.0.0
* six        1.16.0
* wheel      0.36.2

at some point I had replaced following line in `h5py/setup_configure.py` line 240 (removes special code from line 209 related to https://bugs.python.org/issue42114) otherwise I got an error that the hdf5.dll could not be found, but I cannot reproduce this   
```
-             lib = ctypes.CDLL(path, **load_kw)
+             lib = ctypes.CDLL(path)
```  
run this in a terminal

```
   set HDF5_DIR=C:\Program Files\HDF_Group\HDF5\1.12.0
   set H5PY_SETUP_REQUIRES=0
   python setup.py build
   python -m pip install . --no-build-isolation
```

resulting in this error:
```
python
...
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\...\venv\lib\site-packages\h5py\__init__.py", line 25, in <module>
    from . import _errors
ImportError: DLL load failed while importing _errors: The specified module could not be found.
```

Path=
* C:\dev\CSIMBA\TestDataGenerator_intelliJ\venv\Scripts
* C:\Program Files (x86)\Common Files\Oracle\Java\javapath
* C:\WINDOWS\system32
* C:\WINDOWS
* C:\WINDOWS\System32\Wbem
* C:\WINDOWS\System32\WindowsPowerShell\v1.0\
* C:\WINDOWS\System32\OpenSSH\
* C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\
* C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\
* C:\Program Files\TortoiseGit\bin
* C:\Program Files\Git\cmd
* C:\Program Files\HDF_Group\HDF5\1.12.0\bin\
* C:\Users\AGTENJ\AppData\Local\Microsoft\WindowsApps
* C:\Users\AGTENJ\AppData\Local\Programs\Microsoft VS Code\bin
* C:\Program Files\Python39\
* C:\Program Files\Python39\Scripts

**Comment by takluyver** [comment]
I'd guess you need to copy the HDF5 DLLs into the h5py package, like [this script](https://github.com/h5py/h5py/blob/cc34c585ab29e859abda1d99830e7b9868197adb/ci/fix_paths.py) does for Windows tests on our CI.

**Comment by cheops** [comment]
maybe the setup install step needs to be extended to do this copy of dll files?   

Because this works, copying all the dll files from C:\Program Files\HDF_Group\HDF5\1.12.0\bin to target folder ..\Lib\site-packages\h5py
 (not only hdf5.dll, hdf5_hl.dll and zlib.dll)

* cilkrts20.dll
* concrt140.dll
* hdf5.dll
* hdf5_hl_f90cstub.dll
* hdf5_hl.dll
* ifdlg100.dll
* hdf5_f90cstub.dll
* hdf5_fortran.dll
* hdf5_tools.dll
* hdf5_hl_cpp.dll
* hdf5_cpp.dll
* hdf5_hl_fortran.dll
* libchkp.dll
* libioffload_host.dll
* szip.dll
* libifcorert.dll
* libgfxoffload.dll
* libmpx.dll
* msvcp140.dll
* libirngmd.dll
* libifcoremd.dll
* libifcoremdd.dll
* libicaf.dll
* libmmdd.dll
* svml_dispmd.dll
* liboffload.dll
* libmmd.dll
* libifcorertd.dll
* libifportmd.dll
* vcruntime140.dll
* zlib.dll

**Comment by takluyver** [comment]
We do this when making Windows wheels (with [another script](https://github.com/h5py/h5py/blob/cc34c585ab29e859abda1d99830e7b9868197adb/ci/bundle_hdf5_whl.py)). I'm wary of trying to do it automatically on installation from source, because it probably isn't the right thing to do if HDF5 is installed with a package manager like conda. I also don't know how to determine which DLLs are actually needed in different situations - the wheels we publish seem to work with a much smaller list, and it doesn't seem like a good idea to copy everything across just in case.

**Comment by cheops** [comment]
Ok, I understand that it is not so straight forward as just copying all the dll files.
(the binary distribution I tried on Windows with `pip install h5py` is missing szip.dll f.ex.)

Would it be possible to mention it in the installation documentation?
https://docs.h5py.org/en/stable/build.html
On windows you need to copy the *necessary* dll files to the installation target directory
where *necessary* depends on the hdf5 file you try to open and read/write from/to
(ex: szip.dll is not needed if your hdf5file does not use SZIP compression)

**Comment by takluyver** [comment]
I'd guess it needs `szip.dll` if HDF5 is built with szip support, even if you're not trying to access szip compressed data.

Feel free to make a PR to add a note about this. There's already a 'Source installation on Windows' section where it could go. Though I might say 'you may need', because I guess you probably don't need to copy anything if you're e.g. in a conda environment with hdf5.

**Comment by yijinsee** [comment]
The copy method (copy ddl file) works for me.

**Comment by giminici** [comment]
I try to install lower version of h5py. that actually fix my problem . ps(i must delete h5py files to reinstal it  with pip install)

**Comment by SaaSGun** [comment]
@giminici - hey, I am also facing same issues with h5py installation on Windows 10 OS. Could you mention with version of h5py worked well in your case?
