### ISSUE TITLE
Trouble setting value for vlen type on compound data

### ISSUE THREAD

**Issue by FFY00** [h5py/h5py#1921]
* Operating System: Arch Linux
 * Where Python was acquired: Arch Linux

```
$ python -c 'import h5py; print(h5py.version.info)'
Summary of the h5py configuration
---------------------------------

h5py    3.2.1
HDF5    1.12.0
Python  3.9.5 (default, May 24 2021, 12:50:35)
[GCC 11.1.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.20.3
cython (built with) 0.29.22
numpy (built against) 1.20.1
HDF5 (built against) 1.12.0
```

# Reproducible

```
import h5py
import numpy as np


f = h5py.File('test.h5','w')

table = f.create_dataset(
    'packets',
    shape=(1,),
    chunks=True,
    maxshape=(None,),
    dtype=[
        ('timestamp', np.float64),
        ('data', h5py.vlen_dtype(np.uint8)),
    ],
)

table[0, 'timestamp'] = 1.5
table[0, 'data'] = np.frombuffer(b'test', dtype=np.uint8)

f.close()
```

```
$ python example.py
Traceback (most recent call last):
  File "/home/anubis/git/usbviewer/example.py", line 19, in <module>
    table[0, 'data'] = np.frombuffer(b'test', dtype=np.uint8)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 848, in __setitem__
    val = val.view(numpy.dtype([(names[0], dtype)]))
  File "/usr/lib/python3.9/site-packages/numpy/core/_internal.py", line 459, in _view_is_safe
    raise TypeError("Cannot change data-type for object array.")
TypeError: Cannot change data-type for object array.
```

I do not understand what I am doing wrong, the array is the correct type. An using the API incorrectly and not seting the value? Admittedly, I am a bit confused by this API and just trying to figure out how to actually write the data  :upside_down_face:. (also, is there any way to write the whole row as a tuple, eg. `table[0] = (1.5, array)`?)

**Comment by FFY00** [comment]
It seems that we have these the `data` I provided has a different type. It is `dtype('O')`, while it was expecting `dtype([('data', 'O')])`. Are there any significant differences there? AFAIK it's only the label, I would expect this to cast silently.

Anyway, adjusting the code to match the type.
```py
import h5py
import numpy as np


f = h5py.File('test.h5','w')

table = f.create_dataset(
    'packets',
    shape=(1,),
    chunks=True,
    maxshape=(None,),
    dtype=[
        ('timestamp', np.float64),
        ('data', h5py.vlen_dtype(np.uint8)),
    ],
)

table[0, 'timestamp'] = 1.5
table[0, 'data'] = np.frombuffer(b'test', dtype=[('data', np.uint8)])

f.close()
```

I am now getting.

```sh
$ python example.py
Traceback (most recent call last):
  File "/home/anubis/git/usbviewer/example.py", line 19, in <module>
    table[0, 'data'] = np.frombuffer(b'test', dtype=[('data', np.uint8)])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 946, in __setitem__
    mspace = h5s.create_simple(selection.expand_shape(mshape))
  File "/usr/lib/python3.9/site-packages/h5py/_hl/selections.py", line 269, in expand_shape
    raise TypeError("Can't broadcast %s -> %s" % (source_shape, self.array_shape))  # array shape
TypeError: Can't broadcast (4,) -> ()
```

**Comment by FFY00** [comment]
I tried patching `expand_shape` to return the source shape if `self.array_shape` is empty (which seems to be the case of vlen types), no exception is raise but the data isn't written. I am out of ideas now.

**Comment by takluyver** [comment]
What about if you put the array into an object array, something like this:

```python
a = np.array(None, dtype=object)
a[()] = np.frombuffer(b'test', dtype=np.uint8)
```

vlen data in h5py is somewhere between awkward and a kludge. Compound datatypes are somewhat better, but still not the main thing the API is designed around.  So it's not a great surprise that using a vlen inside a compound datatype causes problems. h5py, HDF5 and NumPy are all at their best with homogeneous arrays of numbers.

**Comment by FFY00** [comment]
That fails with

```
Traceback (most recent call last):
  File "/home/anubis/git/usbviewer/example.py", line 20, in <module>
    data[()] = np.frombuffer(b'test', dtype=np.uint8)
ValueError: setting an array element with a sequence.
```

I also tried doing `np.void(b'test')` and `np.object_(b'test')` instead of `np.frombuffer(b'test', dtype=np.uint8)`, but they both fail with

```
Traceback (most recent call last):
  File "/home/anubis/git/usbviewer/example.py", line 22, in <module>
    table[0, 'data'] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 948, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 784, in h5py._conv.ndarray2vlen
AttributeError: 'bytes' object has no attribute 'dtype'
```

> vlen data in h5py is somewhere between awkward and a kludge. Compound datatypes are somewhat better, but still not the main thing the API is designed around. So it's not a great surprise that using a vlen inside a compound datatype causes problems. h5py, HDF5 and NumPy are all at their best with homogeneous arrays of numbers.

I understand, this stack is mostly designed to hold datasets, not for variable data storage like what I am doing.

I think I am gonna go with

```python
import struct

import h5py
import numpy as np


f = h5py.File('test.h5','w')

table = f.create_dataset('packets',
    shape=(1,),
    chunks=True,
    maxshape=(None,),
    dtype=h5py.vlen_dtype(np.uint8)),
)

table[0] = struct.pack('f', 1.5) + b'test'
...
((timestamp,), data) = struct.unpack('f', raw_data[:4]), table[4:]
```

And if I ever need more complex data, `pickle.loads/dumps`.

It still would be very nice to see this issue fixed :confused:

**Comment by takluyver** [comment]
I'd be happy to see it get fixed - but I probably won't prioritise working on it myself. :wink:

**Comment by FFY00** [comment]
I would be happy to give it a try, but I would probably need some pointers. If/when you, or any of the other maintainers, have time, please let me know.

**Comment by takluyver** [comment]
Well, glancing at `Dataset.__setitem__`, I can see there are a few special cases around vlen data and accessing fields of compound types. I'm guessing they don't interact correctly:

https://github.com/h5py/h5py/blob/a6c659037aea2d2cadaca893116c8ef0c6449fe7/h5py/_hl/dataset.py#L783-L803

https://github.com/h5py/h5py/blob/a6c659037aea2d2cadaca893116c8ef0c6449fe7/h5py/_hl/dataset.py#L808-L813

https://github.com/h5py/h5py/blob/a6c659037aea2d2cadaca893116c8ef0c6449fe7/h5py/_hl/dataset.py#L851-L877

**Comment by urig** [comment]
I've bumped into a similar issue when trying to insert a compound object made up of vlen strings. I posted it on stackoverflow.com and received [an answer](https://stackoverflow.com/a/68430902/33404) that points in a different direction (which worked for me):

> You're setting the dtype as a tuple of variable length strings, so you'd set the tuple all at once. By only setting the label element, the other two tuple values aren't being set, so they are not string types.

In other words, perhaps try changing this: 
```
table[0, 'timestamp'] = 1.5
table[0, 'data'] = np.frombuffer(b'test', dtype=np.uint8)
```
into this:
```
table[0] = 1.5, np.frombuffer(b'test', dtype=np.uint8)
```
