### ISSUE TITLE
TypeError when reading region reference data from dataset with shared compound data type

### ISSUE THREAD

**Issue by ubrec** [h5py/h5py#1935]
When I try to read region reference data from a dataset that references a shared compound datatype, a TypeError is raised. This does not happen when reading other types of data in my experience. In my particular use case, I am trying to read data that I did not create and do not have access to modify. However, the below code produces example data that triggers this issue. This code produces an exception in h5py 3.3.0, but seems to work correctly in 2.10.0.

```python
import h5py
import numpy as np

with h5py.File("./example.hdf5", "w") as f:
    dataset = f.create_dataset("sample_data", data=[1])
    data_type_group = f.create_group("data_types")
    data_type = h5py.h5t.py_create(np.dtype([('reftype', h5py.regionref_dtype)]), logical=True)
    data_type.commit(data_type_group.id, b"ref_data_type")
    ref_data_type = f["/data_types/ref_data_type"]
    ref_data = f.create_dataset("refdata", (1,), dtype=ref_data_type)
    ref_data[...] = np.array([dataset.regionref[0:1]], dtype=ref_data_type)

    # raises TypeError: Unable to convert between src and dst data types (no appropriate function for conversion path)
    ref_data_read = f["/refdata"][...]
```

```
Traceback (most recent call last):
  File "D:/h5test.py", line 15, in <module>
    ref_data_read = f["/refdata"][...]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "D:\venv\lib\site-packages\h5py\_hl\dataset.py", line 762, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py\_proxy.pyx", line 141, in h5py._proxy.dset_rw
TypeError: Unable to convert between src and dst data types (no appropriate function for conversion path)
```

An h5 dump of the problematic dataset looks like this. I am only experiencing this issue with datasets that reference a datatype stored elsewhere in the hdf5 file like this, and only when those datasets include region references.
```
DATASET "/refdata" {
   DATATYPE  "/data_types/ref_data_type"
   DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
   DATA {
   }
}
```

Version Info
h5py    3.3.0
HDF5    1.12.0
Python  3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.21.1
cython (built with) 0.29.23
numpy (built against) 1.14.5
HDF5 (built against) 1.12.0

**Comment by ubrec** [comment]
Is anyone able to replicate this issue or recommend a workaround? Thanks!

**Comment by ubrec** [comment]
Came back to test this again, I can't reproduce the issue since h5py 3.4.0 so it's been fixed somewhere along the way.
