### ISSUE TITLE
Virtual datasets cannot be indexed with a boolean mask

### ISSUE THREAD

**Issue by asmeurer** [h5py/h5py#1936]
```py
>>> import h5py
>>> f = h5py.File('test.hdf5', 'w')
>>> f.create_dataset('data', data=[0, 1, 2])
<HDF5 dataset "data": shape (3,), type "<i8">
>>> layout = h5py.VirtualLayout(shape=(3,), dtype='int')
>>> source = h5py.VirtualSource(f['data'])
>>> layout[:3] = source
>>> f.create_virtual_dataset('virtual', layout)
<HDF5 dataset "virtual": shape (3,), type "<i8">
>>> f['virtual'][:]
array([0, 1, 2])
>>> import numpy as np
>>> f['virtual'][np.array([True, False, False])]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    with _phil:
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    return func(*args, **kwds)
  File "/Users/aaronmeurer/Documents/h5py/./h5py/_hl/dataset.py", line 762, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    with _phil:
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    return func(*args, **kwds)
  File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
    dset_rw(self_id, mtype_id, mspace_id, fspace_id, plist_id, data, 1)
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
    H5Dread(dset, mtype, mspace, fspace, dxpl, progbuf)
OSError: Can't read data (point selections not currently supported)
```

It's not clear to me, but the error seems to be coming from HDF5 itself. 

Indexing a normal dataset with a mask works.

```py
>>> f['data'][np.array([True, False, False])]
array([0])
```

As does indexing a virtual dataset with an equivalent integer array index.

```py
>>> f['virtual'][np.array([0])]
array([0])
```

I would suggest converting boolean masks to integer arrays for virtual datasets. 

I tested this on h5py master.

```
Summary of the h5py configuration
---------------------------------

h5py    3.3.0
HDF5    1.10.6
Python  3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35)
[Clang 11.1.0 ]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.20.1
cython (built with) 0.29.21
numpy (built against) 1.19.3
HDF5 (built against) 1.10.6
```

**Comment by takluyver** [comment]
I'm reluctant to do anything special for reading virtual datasets, because the idea is that they are transparent at the HDF5 API level.

Is it possible for you to try with a newer HDF5? I can see in the hdf5 code that a couple of instances of that error message have gone between 1.10.6 and 1.10.7.

**Comment by asmeurer** [comment]
This appears to be working correctly with h5py 3.6.0 and hdf5 1.12.1.

**Comment by takluyver** [comment]
Thanks @asmeurer !
