### ISSUE TITLE
trouble installing h5py from conda forge

### ISSUE THREAD

**Issue by bendichter** [h5py/h5py#1938]
To assist reproducing bugs, please include the following:
 * Operating System: MacOS 11.5.1
 * Python version: 3.9
 * Where Python was acquired: Anaconda
 * h5py version: 3.3.0
 * HDF5 version: 1.10.6, attempting to install with h5py using conda

```
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: dlopen(/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so, 2): Symbol not found: _H5Pget_fapl_ros3
  Referenced from: /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so
  Expected in: /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/libhdf5.103.dylib
 in /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so
```

I'm having trouble installing h5py from conda forge. Here are the steps I am using:
```bash
$ conda create -n test_h5py python=3.7 -y
$ conda activate test_h5py
$ conda install -c conda-forge h5py -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/bendichter/opt/miniconda3/envs/ajile

  added / updated specs:
    - h5py


The following NEW packages will be INSTALLED:

  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  h5py               conda-forge/osx-64::h5py-3.3.0-nompi_py39h1bb8402_100
  hdf5               conda-forge/osx-64::hdf5-1.10.6-nompi_h3e39495_100
  libblas            conda-forge/osx-64::libblas-3.9.0-8_openblas
  libcblas           conda-forge/osx-64::libcblas-3.9.0-8_openblas
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-7_5_0_h1a10cd1_23
  libgfortran4       conda-forge/osx-64::libgfortran4-7.5.0-h1a10cd1_23
  liblapack          conda-forge/osx-64::liblapack-3.9.0-8_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.12-openmp_h63d9170_1
  llvm-openmp        conda-forge/osx-64::llvm-openmp-12.0.1-hda6cdc1_1
  numpy              conda-forge/osx-64::numpy-1.21.1-py39h7eed0ac_0
  python_abi         conda-forge/osx-64::python_abi-3.9-2_cp39

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main::certifi-2021.5.30-py39hecd~ --> conda-forge::certifi-2021.5.30-py39h6e9494a_0
  openssl              pkgs/main::openssl-1.1.1k-h9ed2024_0 --> conda-forge::openssl-1.1.1k-h0d85af4_0

$ python
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: dlopen(/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so, 2): Symbol not found: _H5Pget_fapl_ros3
  Referenced from: /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so
  Expected in: /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/libhdf5.103.dylib
 in /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so
```

**Comment by bendichter** [comment]
thanks @tacaswell I will move this to h5py-feedstock

**Comment by tacaswell** [comment]
Thank you for being understanding.
