### ISSUE TITLE
h5py build fails with syntax error

### ISSUE THREAD

**Issue by AgilentGCMS** [h5py/h5py#1972]
I'm trying to install h5py 2.10.0 on a platform for python 2.7.18 from source. For various reasons I need to install from source and can't just use a wheel. The build process, `python setup.py build` fails with the error:
```
Traceback (most recent call last):
  File "setup.py", line 159, in <module>
    cmdclass = CMDCLASS,
  File "/nobackup/sbasu1/packages/python/2.7.18/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/nobackup/sbasu1/packages/python/2.7.18/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/nobackup/sbasu1/packages/python/2.7.18/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/nobackup/sbasu1/packages/python/2.7.18/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/nobackup/sbasu1/packages/python/2.7.18/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/nobackup/sbasu1/packages/python/2.7.18/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/nobackup/sbasu1/packages/python/2.7.18/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/nobackupp11/sbasu1/packages/sources/h5py-2.10.0/setup_build.py", line 166, in run
    config.run()
  File "/nobackupp11/sbasu1/packages/sources/h5py-2.10.0/setup_configure.py", line 160, in run
    self.hdf5_version = autodetect_version(self.hdf5)
  File "/nobackupp11/sbasu1/packages/sources/h5py-2.10.0/setup_configure.py", line 196, in autodetect_version
    import pkgconfig
  File "/nobackupp11/sbasu1/packages/sources/h5py-2.10.0/.eggs/pkgconfig-1.5.5-py2.7.egg/pkgconfig/__init__.py", line 1, in <module>
  File "/nobackupp11/sbasu1/packages/sources/h5py-2.10.0/.eggs/pkgconfig-1.5.5-py2.7.egg/pkgconfig/pkgconfig.py", line 281
    flags = _query(packages, *os_opts, *_build_options(option, static=static))
                                       ^
SyntaxError: invalid syntax
```

 * Operating System: Red Hat Linux
 * Python version: 2.7.18
 * Where Python was acquired: Compiled from source
 * h5py version: 2.10.0
 * HDF5 version: 1.8.22

**Comment by tacaswell** [comment]
I think you need to pre-install a version of pkgconfig that is old enough it still support python2.  

If I am reading the traceback correctly, I think that the offending line is https://github.com/matze/pkgconfig/blob/928418357bb5660919ac0e5979a8c32061bc0b7f/pkgconfig/pkgconfig.py#L281 which in from pkgconfig.  It looks like their meta-data is not quite correct and when pip tries to install h5py's build dependencies it pulls the lastest pkgconfig rather than the last version compatbile with py27 (it looks like you need 1.5.3 or less https://github.com/matze/pkgconfig#version-154 (I am not stoked they dropped Python 2 support in a bug release, but ok) ).

-----

I assume you are aware that Python2.7 is end-of-life and not supported by any of the core scientific Python libraries any more and are building old versions of everything for reasons?

**Comment by AgilentGCMS** [comment]
OK, I'll try that.

Yes, I'm aware of the EOL for python 2.7, but I'm faced with ~50,000 lines of python code that I need to port :-( It's all scientific/engineering code strewn with the division `/` operator, the **one** thing automated tools like 2to3 can't handle reliably. Add to that the lack of any performance benefit for scientific/engineering code in py3 over py2, and you have a group of users (including myself) who have to be dragged kicking and screaming over to py3 ;-)
