### ISSUE TITLE
AWS S3 h5py.File  error

### ISSUE THREAD

**Issue by FPRM** [h5py/h5py#2011]
Hin i have a issues with h5py file read.
My environment

 * Operating System Windows 10
 * Python version 3.7.11
 * Anaconda Virtual Env 
 * h5py version 3.6.0
 * HDF5 version 1.12.1

My h5py.version.info

'Summary of the h5py configuration\n---------------------------------\n\nh5py    3.6.0\nHDF5    1.12.1\nPython  3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]\nsys.platform    win32\nsys.maxsize     9223372036854775807\nnumpy   1.21.2\ncython (built with) 0.29.24\nnumpy (built against) 1.18.5\nHDF5 (built against) 1.12.1\n'
 
my code is the following

```
import boto3
from boto3 import Session
session = Session()
credentials = session.get_credentials()
SECRET_ID = bytes(credentials.access_key,'utf-8')
SECRET_KEY =  bytes(credentials.secret_key,'utf-8')
REGION = bytes(session.region_name,'utf-8')

# check if file exist in S3 Bucket
client = boto3.client('s3')
print(client.list_objects_v2(
    Bucket='sandbox-hdf5-repo'
))

## get file with h5py and ros3 driver
 h5py.File(
    's3://Bucket/subfolder/file.h5',
    driver='ros3',
    aws_region = REGION,
    secret_id = SECRET_ID,
    secret_key = SECRET_KEY
)
```

Traceback (most recent call last):

  File "C:\Users\XXXXX\AppData\Local\Temp/ipykernel_21036/177991195.py", line 6, in <module>
    secret_key = SECRET_KEY

  File "C:\Users\XXXXX\anaconda3\envs\dataS3\lib\site-packages\h5py\_hl\files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)

  File "C:\Users\XXXXX\anaconda3\envs\dataS3\lib\site-packages\h5py\_hl\files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5f.pyx", line 106, in h5py.h5f.open

OSError: Unable to open file (invalid SCHEME construction)

'Summary of the h5py configuration\n---------------------------------\n\nh5py    3.6.0\nHDF5    1.12.1\nPython  3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]\nsys.platform    win32\nsys.maxsize     9223372036854775807\nnumpy   1.21.2\ncython (built with) 0.29.24\nnumpy (built against) 1.18.5\nHDF5 (built against) 1.12.1\n'
```

**Comment by ajelenak** [comment]
You have to use the URL of your HDF5 file, not the S3 URI. Something like `https://s3.your-region.amazonaws.com/Bucket/subfolder/file.h5`.
