### ISSUE TITLE
Collective write only works when using a new variable

### ISSUE THREAD

**Issue by piyueh** [h5py/h5py#2017]
To assist reproducing bugs, please include the following:
 * Operating System: Arch Linux
 * Python version: `3.9.7` packaged by conda-forge
 * Where Python was acquired: Anaconda
 * h5py version (e.g. 2.6): `h5py=3.2.1=mpi_openmpi_py39h994c637_0` from Anaconda's `conda-forge` channel
 * HDF5 version (e.g. 1.8.17): `hdf5=1.10.6=mpi_openmpi_hd9270da_1014` from Anaconda's `conda-forge` channel

## Steps to reproduce
Consider the following two python scripts. The file `test_passed.py` works fine, and `test_failed.py` does not work.
* `test_passed.py`
   ```python
   import h5py
   from mpi4py import MPI
   
   with h5py.File("test.hdf5", "w", "mpio", comm=MPI.COMM_WORLD) as root:
       root.create_dataset("a", MPI.COMM_WORLD.size, "i8", compression="gzip")
       dset = root["a"]
       with dset.collective:
           dset[MPI.COMM_WORLD.rank] = MPI.COMM_WORLD.rank
   ```
* `test_failed.py`
   ```python
   import h5py
   from mpi4py import MPI
   
   with h5py.File("test.hdf5", "w", "mpio", comm=MPI.COMM_WORLD) as root:
       root.create_dataset("a", MPI.COMM_WORLD.size, "i8", compression="gzip")
       with root["a"].collective:
           root["a"][MPI.COMM_WORLD.rank] = MPI.COMM_WORLD.rank
   ```

Then run the two scripts with `mpiexec -n <any number of processes> python <script>`. The `test_passed.py` works fine, but `test_failed.py` script failed with this error message:
```
Traceback (most recent call last):
    File "/tmp/test/test_failed.py", line 11, in <module>
        root["a"][MPI.COMM_WORLD.rank*3:(MPI.COMM_WORLD.rank+1)*3] = data
    File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    File ".../lib/python3.9/site-packages/h5py/_hl/dataset.py", line 948, in __setitem__
        self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
    File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
    File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: Can't write data (Can't perform independent write with filters in pipeline.
    The following caused a break from collective I/O:
        Local causes: independent I/O was requested
        Global causes: independent I/O was requested)
```

The only difference between the two scripts is that whether they access the dataset directly through `root["a"]` or through `dset` while `dset = root["a"]`.

Is this an intentional design (i.e., requiring an extra variable to access a dataset)? If so, where can I find the documentation about this behavior? Thanks!

**Comment by aragilar** [comment]
I suspect (but haven't checked yet) that this is due to the failing case creating two different references to `/a`, with only the first being set to collective (whilst the passing case only has one reference).
