### ISSUE TITLE
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')

### ISSUE THREAD

**Issue by mechsihao** [h5py/h5py#2028]
## Background:
I want to train a two-dense-layer classification model, I use the k-fold strategy to train it and use tf.keras.callback.checkpoint utils to save the best model weights, it will occur this bug `randomly`:

`RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')`

I tried to change the version of h5py to fix this bug, but it did not work.(2.10.0 ~ 3.6.0) 
It seems like when training a k-fold model, the model will be saveing parallel, then this bug will be occurred.

when I track to source code of keras, the save_weights function is just like that:
```python
def save_weights(self, filepath, overwrite=True):
    ...
    with h5py.File(filepath, 'w') as f:
        saving.save_weights_to_hdf5_group(f, self.layers)
        f.flush()
```
`saving.save_weights_to_hdf5_group` means save weights into the HDF5 group

## this bug can be repeated by those codes:
```python
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import KFold
import numpy as np

input_dim = 256
input_x = Input(input_dim,)
x = Dense(128, activation='relu')(input_x)
p = Dense(2, activation='sigmoid')(x)
model = Model(inputs=input_x, outputs=p)

model.compile(loss='mse', optimizer=Adam(1e-5), metrics = ['acc'])

sample_num = 2000
train, label = np.random.random((sample_num, input_dim)), np.random.random((sample_num, 2))
kfold = KFold(n_splits=5)
for i, (train_ind, valid_ind) in enumerate(kfold.split(list(range(sample_num)))):
    model_path = f'model-{i}.h5'
    ckpt = ModelCheckpoint(model_path, monitor='val_loss')
    model.fit([train[train_ind], label[train_ind]], label[train_ind], validation_data=[train[valid_ind], label[valid_ind]], epochs=10, batch_size=64, callbacks=[ckpt])
```

## More detailed bug information is:
```python
Traceback (most recent call last):
  File "/home/notebook/code/personal/test_sihao/gitcode/oCTS_lsh/train_tf2.py", line 36, in <module>
    current_train_pickle_path, n_fold=5, monitor='val_categorical_crossentropy')
  File "/home/notebook/data/group/sihao_work/gitcode/oCTS_lsh/classifier/b4k_classifier_tf2.py", line 186, in model_train_kfold
    self.train(model, train_D, valid_D, tmp_model_save_path, monitor=monitor)
  File "/home/notebook/data/group/sihao_work/gitcode/oCTS_lsh/classifier/b4k_classifier_tf2.py", line 159, in train
    callbacks=[early_stopping, plateau, checkpoint])
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 331, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 311, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 969, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 998, in _save_model
    self.model.save_weights(filepath, overwrite=True)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1315, in save_weights
    self._ckpt_saved_epoch).encode('utf8')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 544, in __exit__
    self.close()
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 526, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 358, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
Segmentation fault
```

**Comment by mechsihao** [comment]
python version 3.7.2
h5py version 3.6.0
tensorflow version 2.3.2
keras version 2.4.3

**Comment by aragilar** [comment]
As a general rule, using multiprocessing with a single HDF5 is a bad idea (it's unclear whether you're referring to your own code or someone else's which is using multiprocessing). My suggestion would be to either use multiple files, and combine them in a final step (a.k.a the map-reduce philosophy), or drop the use of multiprocessing.

Given this is tensorflow/keras related, you might find more specific advice on their help forums.

**Comment by mechsihao** [comment]
Thanks for your answer, but please tell me how can I drop the use of multiprocessing, when I use k-fold training.
is there any args or trick?
the code when I track keras of saving model is:
```python
def save_weights(self, filepath, overwrite=True):
    ...
    with h5py.File(filepath, 'w') as f:
        saving.save_weights_to_hdf5_group(f, self.layers)
        f.flush()
```

**Comment by yilewang** [comment]
Hi! I have an exact error in my code when I tried to save my results as h5 file. The only difference is that I am running my code in HPC system using launcher(https://portal.tacc.utexas.edu/software/launcher) with SLURM system. 

```python
filename = '/scratch/'+netid+'/go/'+args.grp+'/'+args.caseid + '.h5'
with h5py.File(filename, 'w') as hdf:
    hdf.create_dataset('raw', data = raw_data[:,0,:,0])
```

the error message I have
```python
 File "/scratch/yxw190015/github/tvbdemos/tvb_slurm/sim2gc.py", line 58, in <module>
    hdf.create_dataset('raw', data = raw_data[:,0,:,0])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/yxw190015/.conda/envs/tvbenv/lib/python3.9/site-packages/h5py/_hl/files.py", line 544, in __exit__
    self.close()
  File "/home/yxw190015/.conda/envs/tvbenv/lib/python3.9/site-packages/h5py/_hl/files.py", line 526, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 358, in h5py.h5f.FileID._close_open_objects
**RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')**
/opt/ohpc/pub/unpackaged/apps/launcher/launcher-3.7/launcher: line 93: 1321042 Segmentation fault      (core dumped) python sim2gc.py --grp 'MCI' --caseid '2019A' --gc '0.018' --time '180000'
```
Any suggestion about this error? Thanks so much!!!
