### ISSUE TITLE
Segmentation fault when trying to access data on an unmounted network share

### ISSUE THREAD

**Issue by paulmueller** [h5py/h5py#2043]
* Operating System Ubuntu 20.04
 * Python version 3.8
 * Where Python was acquired: system
 * h5py version 3.6.0
 * HDF5 version 1.12.1

My users sometimes work with files on a network share. Sometimes this network share gets "unmounted" (due to connectivity issues) and then the network share becomes available again.

I was trying to write a wrapper that just closes the HDF5 file and tries to reopen it in case of exceptions, but then I got a segfault.

To reproduce:

1. Put a file on a network share (e.g. sshfs) and mount it (on Linux) with ``sshfs user@IP:/pathl/ /tmp/sshfs/``

2. Open the dataset on the share
    ```python

    import h5py
    ds = h5py.File("/tmp/sshfs/file.h5")
    ```

3. Now disconnect the network share forcefully (e.g. disconnect network cable, shutdown VM)

4. Try to access some data
    ```python

    ds["events"]
    RuntimeError: Unable to get group info (file read failed: time = Mon Jan 24 23:28:22 2022 , filename = '/tmp/sshfs/file.h5', file descriptor = 12, errno = 107, error message = 'Transport endpoint is not connected', buf = 0x2184110, total read size = 328, bytes this sub-read = 328, bytes actually read = 18446744073709551615, offset = 0)
    ```
    So far so good.

5. Now attempt to close the file and try to access data again.

    ```python

    ds.close()
    ds["events"]
   Segmentation fault (core dumped)
    ```

There is probably something not being cleaned up properly somewhere by h5py or HDF5.

This is what gdb gives me:

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    ds.close()
  File "/home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/_hl/files.py", line 526, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 358, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to close file, errno = 107, error message = 'Transport endpoint is not connected')
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff6d7e1f4 in H5F_get_nrefs () from /home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
```

and

```
(gdb) bt
#0  0x00007ffff6d7e1f4 in H5F_get_nrefs () from /home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#1  0x00007ffff6f7fe5a in H5VL__native_file_close () from /home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#2  0x00007ffff6f6c17f in H5VL_file_close () from /home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#3  0x00007ffff6d7490d in H5F__close_cb () from /home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#4  0x00007ffff6ded480 in H5I_dec_ref () from /home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#5  0x00007ffff6ded544 in H5I_dec_app_ref () from /home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#6  0x00007ffff6de9fd1 in H5Idec_ref () from /home/paul/repos/dclab/.env/lib/python3.8/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#7  0x00007ffff2d602af in __pyx_f_4h5py_4defs_H5Idec_ref () at /tmp/pip-req-build-kkolujxl/h5py/defs.c:17598
#8  0x00007ffff2b30b8b in __pyx_pf_4h5py_8_objects_8ObjectID_2__dealloc__ () at /tmp/pip-req-build-kkolujxl/h5py/_objects.c:5913
#9  __pyx_pw_4h5py_8_objects_8ObjectID_3__dealloc__ () at /tmp/pip-req-build-kkolujxl/h5py/_objects.c:5823
#10 __pyx_tp_dealloc_4h5py_8_objects_ObjectID () at /tmp/pip-req-build-kkolujxl/h5py/_objects.c:11085
#11 0x00000000005d1e98 in ?? ()
#12 0x00000000005a958d in ?? ()
#13 0x00000000005cedb3 in ?? ()
#14 0x00000000005d1cdc in ?? ()
#15 0x00000000006a715c in ?? ()
#16 0x00000000005d17d7 in ?? ()
#17 0x0000000000685293 in PyImport_Cleanup ()
#18 0x000000000068040f in Py_FinalizeEx ()
#19 0x00000000006b7a1d in Py_RunMain ()
#20 0x00000000006b7c8d in Py_BytesMain ()
#21 0x00007ffff7dadfd0 in __libc_start_call_main (main=main@entry=0x4eed30 <main>, argc=argc@entry=2, argv=argv@entry=0x7fffffffdcb8) at ../sysdeps/nptl/libc_start_call_main.h:58
#22 0x00007ffff7dae07d in __libc_start_main_impl (main=0x4eed30 <main>, argc=2, argv=0x7fffffffdcb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdca8)
    at ../csu/libc-start.c:409
#23 0x00000000005fb12e in _start ()
```
 
Please let me know if I should take this to the HDF5 people.

**Comment by tacaswell** [comment]
Is there a way to reproduce this short of ripping a network filesystem out from under a process?

**Comment by takluyver** [comment]
I've seen before that HDF5 really doesn't expect to encounter problems closing a file - see #1642. There's a test I had to skip because it caused segfaults if I didn't.

So my suspicion is that there's some sort of problem in HDF5 itself, and the obvious route forwards would be to try to reproduce it in C code using libhdf5. But it's possible that the extra complexity of Python interacting with HDF5 exposes something that you wouldn't hit with a simple C example.

**Comment by paulmueller** [comment]
HDFView at least behaves properly in such a case:
![image](https://user-images.githubusercontent.com/2853022/152341622-dc855c1c-6cea-445b-84a0-95e331746410.png)
