### ISSUE TITLE
KeyError: "Unable to open object (object 'dense' doesn't exist)" when trying to load saved pre-trained model to predict image classification

### ISSUE THREAD

**Issue by chikakorooney** [h5py/h5py#2089]
Hello, please see below for my system info:

 * Operating System : MacOS 12.3.1
 * Python version : 3.7.13
 * Where Python was acquired: Conda
 * h5py version: 2.9.0
 * HDF5 version 1.10.4
 * using conda tensorflow_env

========= entire error message=========
$ python predict.py ./test_images/wild_pansy.jpg my_model.h5
Traceback (most recent call last):
  File "predict.py", line 94, in <module>
    main()
  File "predict.py", line 76, in main
    model=tf.keras.models.load_model(my_model,custom_objects={'KerasLayer': hub.KerasLayer},compile = False)
  File "/Users/usr/opt/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/Users/usr/opt/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 171, in load_model_from_hdf5
    load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "/Users/usr/opt/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 668, in load_weights_from_hdf5_group
    g = f[name]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/usr/opt/anaconda3/envs/tensorflow_env/lib/python3.7/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'dense' doesn't exist)"

Could this be due to package mismatch between h5py and others? Please kindly advise... Thanks in advance.

**Comment by kif** [comment]
Looks strange, are you using the python from macos or the one from the conda environment ? if you are mixing them, not surprising that binary extensions don't work.

**Comment by chikakorooney** [comment]
Thanks for the comment @kif, I'm using the python from conda environment actually, sorry it was wrongly written in above description of my issue. I'm also running all these using conda environment (tensorflow_env) due to version mismatch on tensorflow and keras packages as described here [https://stackoverflow.com/questions/67549661/importerror-cannot-import-name-layernormalization-from-tensorflow-python-ker]. Since I'm only using this environment to run everything, I thought I can't mix them up (python on macos and that of conda), but can I ? Thanks in advance.

$ python --version
Python 3.7.13
$(tensorflow_env) user (master *) p2_image_classifier

**Comment by takluyver** [comment]
This looks like h5py & HDF5 are working correctly, but something you're trying to load is missing from the file. You either need to investigate where the file comes from - is it being saved correctly, and is it meant to be compatible with this - or take it up with tensorflow/keras as a possible bug in their file loading code.

**Comment by chikakorooney** [comment]
@takluyver thanks for your comment. When I tried running the same code with the same loaded .h5 file on hosted GPU environment provided by college, it works fine, so it might be related to the versions of tensorflow/keras on my local environment. I might ask tensorflow/keras - thank you!
