### ISSUE TITLE
Complex float16 problems

### ISSUE THREAD

**Issue by bhawkins** [h5py/h5py#2156]
I've got an HDF5 file that uses complex-valued data using the usual h5py {r, i} names for the members of a structured type (since HDF5 doesn't have a built in complex type). The problem is that the members are float16, and numpy doesn't have a corresponding type (see open issue [here](https://github.com/numpy/numpy/issues/14753)), which causes all kinds of grief. For example,
```Python
import h5py
import numpy as np
f = h5py.File("/tmp/foo.h5", "w")
c4 = np.dtype([('r', 'f2'), ('i', 'f2')])
ds = f.create_dataset("z", dtype=c4, shape=(10,))
print(ds.dtype)
```
Crashes with the error
```
Traceback (most recent call last):
  File "/private/tmp/test_c4.py", line 6, in <module>
    print(ds.dtype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/bhawkins/Library/Python/3.10/lib/python/site-packages/h5py-3.7.0-py3.10-macosx-12-x86_64.egg/h5py/_hl/dataset.py", line 518, in dtype
    return self.id.dtype
  File "h5py/h5d.pyx", line 131, in h5py.h5d.DatasetID.dtype.__get__
  File "h5py/h5d.pyx", line 134, in h5py.h5d.DatasetID.dtype.__get__
  File "h5py/h5t.pyx", line 434, in h5py.h5t.TypeID.dtype.__get__
  File "h5py/h5t.pyx", line 435, in h5py.h5t.TypeID.dtype.__get__
  File "h5py/h5t.pyx", line 1231, in h5py.h5t.TypeCompoundID.py_dtype
TypeError: data type '<c4' not understood
```

Lots of methods like slicing need access to the `dtype` attribute and fail with the same error.

Until numpy supports complex float16, I'd prefer if `h5py.Dataset.dtype` just returned the structured type. I could attempt this change if such a PR would be appreciated.

**Comment by bhawkins** [comment]
For completeness, here's my setup:
```
Summary of the h5py configuration
---------------------------------

h5py    3.7.0
HDF5    1.12.2
Python  3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.23.2
cython (built with) 0.29.32
numpy (built against) 1.23.2
HDF5 (built against) 1.12.2
```

**Comment by takluyver** [comment]
I think returning the compound type makes sense - although it will cause a bit of a headache if numpy does get round to adding a complex32 dtype, because then switching to that would be a breaking change. But we'll figure that out when we have to.

This is the piece of code you'll need to change (in the method that converts an HDF5 datatype to a numpy dtype):

https://github.com/h5py/h5py/blob/1487a54fb5149603dcc32604df4db418ea4f5236/h5py/h5t.pyx#L1222-L1231
