### ISSUE TITLE
Segmentation fault when writing sufficiently large HDF5 or NetCDF4 files with at least two variables to S3 via s3fs

### ISSUE THREAD

**Issue by d1mach** [h5py/h5py#2160]
Reporting here a bug first reported to xarray team [here](https://github.com/pydata/xarray/issues/7146). Probably a bug in libhdf5.

When creating an hdf5 file on S3 filesystem mounted via s3fs I am receiving a segfault

Code example (crafted by @keewis)
--------------------------------
```python
import h5py

N_TIMES = 48
with h5py.File("/my_s3_fs/test.nc", mode="w") as f:
    time = f.create_dataset("time", (N_TIMES,), dtype="d")
    time[:] = 0

    d1 = f.create_dataset("d1", (N_TIMES, 201, 201), dtype="d")
    d1[:] = 0
```

S3 compatible object storage is mounted on an Ubuntu 20.04 system with the following options:
```
s3fs on /mnt/fs type fuse.s3fs (rw,relatime,user_id=0,group_id=0,allow_other)
```
The filesystem is then mapped to a docker container with `-v /mnt/fs/data:/my_s3_fs`. Python is installed in the docker container via Anaconda.

Python stack trace
-------------------------------
```
Traceback (most recent call last):
  File "htest.py", line 9, in <module>
    d1[:] = 0
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/conda/lib/python3.8/site-packages/h5py/_hl/files.py", line 544, in __exit__
    self.close()
  File "/opt/conda/lib/python3.8/site-packages/h5py/_hl/files.py", line 526, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 358, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
Segmentation fault (core dumped)
```

Full segfault stack trace
--------------------------------
```
(gdb) bt
#0  0x00007fa9a25e9066 in H5F__close_cb () from /opt/conda/lib/python3.8/site-packages/h5py/../../../libhdf5.so.103
#1  0x00007fa9a265bc40 in H5I_dec_ref () from /opt/conda/lib/python3.8/site-packages/h5py/../../../libhdf5.so.103
#2  0x00007fa9a265bd06 in H5I_dec_app_ref () from /opt/conda/lib/python3.8/site-packages/h5py/../../../libhdf5.so.103
#3  0x00007fa9a265be27 in H5Idec_ref () from /opt/conda/lib/python3.8/site-packages/h5py/../../../libhdf5.so.103
#4  0x00007fa9936e05d1 in __pyx_f_4h5py_4defs_H5Idec_ref () from /opt/conda/lib/python3.8/site-packages/h5py/defs.cpython-38-x86_64-linux-gnu.so
#5  0x00007fa9a1466326 in __pyx_tp_dealloc_4h5py_8_objects_ObjectID () from /opt/conda/lib/python3.8/site-packages/h5py/_objects.cpython-38-x86_64-linux-gnu.so
#6  0x0000556529eeea0f in _Py_Dealloc (op=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/object.c:2215
#7  _Py_DECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:478
#8  _Py_XDECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:541
#9  dict_dealloc () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/dictobject.c:1990
#10 0x0000556529f90b07 in _Py_Dealloc (op=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/object.c:2215
#11 _Py_DECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:478
#12 subtype_dealloc () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/typeobject.c:1274
#13 0x0000556529eebf1c in _Py_Dealloc (op=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/object.c:2215
#14 _Py_DECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:478
#15 _Py_XDECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:541
#16 free_keys_object () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/dictobject.c:584
#17 0x0000556529eee8ec in dictkeys_decref () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/dictobject.c:324
#18 dict_dealloc () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/dictobject.c:1998
#19 0x0000556529f901ff in _Py_DECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:478
#20 _Py_XDECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:541
#21 module_dealloc (m=0x7fa9a395d810) at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/moduleobject.c:690
#22 0x0000556529f5bb67 in _Py_Dealloc (op=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/object.c:2215
#23 _Py_DECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:478
#24 _Py_XDECREF () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Include/object.h:541
#25 insertdict () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Objects/dictobject.c:1102
#26 0x0000556529fcbfa5 in PyImport_Cleanup () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Python/import.c:492
#27 0x000055652a02fffe in Py_FinalizeEx () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Python/pylifecycle.c:1240
#28 0x000055652a033350 in Py_RunMain () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Modules/main.c:652
#29 0x000055652a033739 in Py_BytesMain () at /home/conda/feedstock_root/build_artifacts/python_1591030388223/work/Modules/main.c:1082
#30 0x00007fa9a3233840 in __libc_start_main (main=0x556529ee7210 <main>, argc=2, argv=0x7ffc88c5b678, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffc88c5b668) at ../csu/libc-start.c:291
#31 0x0000556529fd7677 in _start () at ../sysdeps/x86_64/elf/start.S:103
```

Summary of the h5py configuration
---------------------------------

h5py    3.6.0
HDF5    1.10.6
Python  3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.19.1
cython (built with) 0.29.24
numpy (built against) 1.16.6
HDF5 (built against) 1.10.6

**Comment by takluyver** [comment]
I've come across something similar before - closing an HDF5 file object may try to write to the file, and if it fails, then we are left with a valid HDF5 object ID which can't be closed. I couldn't figure out a way to avoid this in h5py (though that doesn't mean it's not possible), so there's a skipped test for something similar:

https://github.com/h5py/h5py/blob/6ffb48b5ccb5f14f4fe1208b27e64aae9c85fd48/h5py/tests/test_file2.py#L230-L235

**Comment by ajelenak** [comment]
While HDF5 library could fail more graciously, the segfault points to some kind of problem between the library and the backend storage system. I am not familiar with the FUSE s3fs but what is gained using it here? There are no partial writes to an HDF5 file as a single S3 object so I bet there is a temporary HDF5 file somewhere in the local file system. Why not just create this HDF5 file in the traditional way and put it into S3 afterward?

**Comment by ajelenak** [comment]
Closing as there was no follow-up discussion.
