### ISSUE TITLE
After I built 400 groups in h5py, a ValueError occured and I cant create group

### ISSUE THREAD

**Issue by wangjiannb** [h5py/h5py#2212]
To assist reproducing bugs, please include the following:
 * Operating System (Ubuntu 18.04.1 LTS)
 * Python version (3.8.13)
 * Where Python was acquired (Anaconda on Linux)
 * h5py version (3.7.0)

 * The full traceback/stack trace shown (if it appears)
 * Traceback (most recent call last):                                                                                                                                              
  File "data_preprocess.py", line 60, in <module>
    save_h5py()
  File "data_preprocess.py", line 44, in save_h5py
    subgroup = f.create_group('epoch{}'.format(epoch))
  File "/home/chenshy2/anaconda3/envs/pytracking/lib/python3.8/site-packages/h5py/_hl/group.py", line 66, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 166, in h5py.h5g.create
ValueError: Unable to create group (bad object header version number)

**Comment by aragilar** [comment]
What happens if you run `h5ls` on the file?

**Comment by takluyver** [comment]
Is this reproducible - can you create a new file, run the same code, and see the error again - or is it a one off?

**Comment by takluyver** [comment]
Closing as there's not enough information to do anything here. It's possible that the file was corrupted somehow.
