### ISSUE TITLE
SystemError in h5fd with Python3.11 when exception is raised in `fileobj.seek`

### ISSUE THREAD

**Issue by janssenhenning** [h5py/h5py#2221]
Hello, I'm not completely sure, whether this is a h5py, Cython or Python issue, but the following code snippet stopped working with python3.11, no longer correctly raising the ValueError.

```
Traceback (most recent call last):
  File "/Users/janssen/Documents/cython-test/h5py_system_error.py", line 26, in <module>
    h5py.File(FileHandleNoBackwardsSeek(file), 'r')
  File "/opt/homebrew/lib/python3.11/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_get_eof
  File "/Users/janssen/Documents/cython-test/h5py_system_error.py", line 19, in seek
    raise ValueError('Error')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <class 'ValueError'> returned a result with an exception set
```

```python
import h5py

with h5py.File('test.h5', 'w') as f:
    f['dataset'] = range(10)

class Wrapper:

    def __init__(self, handle):
        self._handle = handle

    def seek(self, target, whence):
         raise ValueError('Error')

    def __getattr__(self, name):
        return getattr(self._handle, name)

with open('test.h5', 'rb') as file:
    h5py.File(Wrapper(file), 'r')
```

Versions:
```
h5py    3.8.0
HDF5    1.12.2
Python  3.11.0 (main, Oct 25 2022, 13:57:33) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.24.1
cython (built with) 0.29.33
numpy (built against) 1.23.2
HDF5 (built against) 1.12.2
```

**Comment by ajelenak** [comment]
I think h5py behaves here correctly. So this is likely on the Python side.

**Comment by tacaswell** [comment]
To be clear, the issue is that the type of the exception raised changed (not that it used to not raise)?

**Comment by janssenhenning** [comment]
> To be clear, the issue is that the type of the exception raised changed (not that it used to not raise)?

Yes, exactly. The usecase where this came up was a fileobject that does not support `whence=2` and previously raised a `NotImplementedError`

**Comment by takluyver** [comment]
I've got a guess what's going on:

I think it calls the `seek()` method the first time, and ValueError is raised. Internally, Python sets a flag saying 'exception propagating'. h5py returns to HDF5, indicating that an error occurred. While handling this, before returning to the 'outside' Python code, HDF5 calls seek() again, which goes back to executing the Python code 'inside' the driver. But the next time Python checks its internal exception flag, it sees that there's an exception being handled, even though it hasn't done anything that might raise an exception. So it raises SystemError as an 'I don't know what's going on'.

I notice that if you put `print()` on the line above the `raise`, you get ValueError again, but the traceback looks weird, which fits this theory:

```
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_get_eof
  File "/home/takluyver/Code/h5py/other/h5py_system_error.py", line 14, in seek
    print()
    ^^^^^^^
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_get_eof
  File "/home/takluyver/Code/h5py/other/h5py_system_error.py", line 14, in seek
    print()
    ^^^^^^^
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_get_eof
  File "/home/takluyver/Code/h5py/other/h5py_system_error.py", line 15, in seek
    raise ValueError('Error')
ValueError: Error
```

Unfortunately, if this is right, I don't have a great idea what to do about it. I think it's another example of where getting HDF5 to call back into a dynamic language is possible, but kind of fragile.
