### ISSUE TITLE
TypeError: bad operand type for unary ~: 'NoneType'

### ISSUE THREAD

**Issue by mobigroup** [h5py/h5py#2237]
All h5py versions everywhere generate the TypeError messages for every processing file:

```
Exception ignored in: <function CachingFileManager.__del__ at 0x106cbb2e0>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 248, in __del__
  File "/opt/homebrew/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 232, in close
  File "/opt/homebrew/lib/python3.10/site-packages/h5netcdf/core.py", line 1130, in close
  File "/opt/homebrew/lib/python3.10/site-packages/h5py/_hl/files.py", line 585, in close
TypeError: bad operand type for unary ~: 'NoneType'
Exception ignored in: <function File.close at 0x1086cf910>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/h5netcdf/core.py", line 1130, in close
  File "/opt/homebrew/lib/python3.10/site-packages/h5py/_hl/files.py", line 585, in close
TypeError: bad operand type for unary ~: 'NoneType'
```

The problem is in the code below where h5f.OBJ_FILE is None and so the operation "~h5f.OBJ_FILE" is not valid:

```
    def close(self):
        """ Close the file.  All open objects become invalid """
        with phil:
            # Check that the file is still open, otherwise skip
            if self.id.valid:
                # We have to explicitly murder all open objects related to the file

                # Close file-resident objects first, then the files.
                # Otherwise we get errors in MPI mode.
                self.id._close_open_objects(h5f.OBJ_LOCAL | ~h5f.OBJ_FILE)
                self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)

                self.id.close()
                _objects.nonlocal_close()
```

**Comment by ajelenak** [comment]
Can you provide a small example that produces this error?

**Comment by Kishore96in** [comment]
This appears to be due to some interaction between h5py and plotly. You can run the following script to reproduce the error.

```
import h5py

import plotly.io.orca #This needs to be present to reproduce the bug!

with h5py.File("test.h5", 'w') as f:
	f.create_dataset('kx', data=[1,2,3])

class h5w():
	def __init__(self, fname):
		self._cache = h5py.File(fname, 'r')

	def __del__(self):
		if hasattr(self, "_cache"):
			self._cache.close()

#Triggers the bug!
f = h5w("test.h5")
```

Saving this as `test_12.py` and running it, we get
```
$ python test_12.py                
Exception ignored in: <function h5w.__del__ at 0x7a92168d74c0>
Traceback (most recent call last):
  File "/home/kishore/Documents/h5py_bug_2237/test_12.py", line 14, in __del__
  File "/usr/lib/python3.12/site-packages/h5py/_hl/files.py", line 580, in close
TypeError: bad operand type for unary ~: 'NoneType'
```

I haven't checked what exactly plotly is doing to trigger this issue, but commenting out the `import plotly.io.orca` line in the script above removes the error.

OS: Arch Linux
h5py version: 3.11.0 (from Arch repos)
plotly version: 5.23.0+0.g83c7c850f.dirty (from Arch AUR)

**Comment by ajelenak** [comment]
I think the traceback error implies the constant `h5py.h5f.OBJ_FILE` is `None`. Have you reported in the plotly.io.orca repository as well since that package triggers this error?

**Comment by Kishore96in** [comment]
> Have you reported in the plotly.io.orca repository as well since that package triggers this error?

Not yet. Given that plotly does not even depend on h5py on my system, it is unclear how it is actually triggering this error.

It would be good if @AlexeyPechnikov could confirm if they were also using plotly while facing this issue (it is possible that that are other packages that trigger this issue as well).

**Comment by AlexeyPechnikov** [comment]
@Kishore96in 

I directly use the h5py library, and the issue arises within that context. I don’t use Plotly in my code.

**Comment by Kishore96in** [comment]
> I don’t use Plotly in my code.

@AlexeyPechnikov 

I also don't directly use plotly, but when I faced this error, it turned out to be because a package I was using had imported plotly (for functionality I was not even using).

In a context where you are able to trigger this error, can you see if 
```
import sys
print([m for m in sys.modules if "plotly" in m])
```
gives you a non-empty list?

**Comment by AlexeyPechnikov** [comment]
@Kishore96in Yes, it’s obviously unrelated to Plotly or the phase of the moon. It’s an internal h5py error, which the developers, for some reason, seem to deny acknowledging for years.

```
>>> import sys
>>> print([m for m in sys.modules if "plotly" in m])
[]
```

**Comment by neutrinoceros** [comment]
>  Yes, it’s obviously unrelated to Plotly or the phase of the moon. It’s an internal h5py error, which the developers, for some reason, seem to deny acknowledging for years.

This is condescending and uncalled for; you were asked for a reproducer *within hours* of your initial report and never replied until now. h5py is maintained by volunteers on their free time. You're not going to get help by disrespecting maintainers. Instead, try to be helpful yourself and provide a way to reproduce the error.

**Comment by AlexeyPechnikov** [comment]
@neutrinoceros

>  you were asked for a reproducer within hours of your initial report

Actually, I wasn’t asked how to reproduce it. The request was for “a small example”:

> Can you provide a small example that produces this error?

This is completely different because the issue occurs in a code that operates on lazy Dask xarray objects stored in NetCDF files. I believe it would be more straightforward to check the referenced h5py code lines. My script was far from being small, and I’m unsure how it’s possible to create a smaller test case that reproduces the issue: https://github.com/AlexeyPechnikov/pygmtsar/blob/pygmtsar/tests/S1A_Stack_CPGF_T173.py

> h5py is maintained by volunteers on their free time.

I also work on my open-source projects in my free time, and I make an effort to investigate bug reports. I’ve even provided you with the exact lines in h5py library code where the issue occurs. What more do you need?​

**Comment by Kishore96in** [comment]
> 
> This is completely different because the issue occurs in a code that operates on lazy Dask xarray objects stored in NetCDF files. I believe it would be more straightforward to check the referenced h5py code lines. My script was far from being small, and I’m unsure how it’s possible to create a smaller test case that reproduces the issue: https://github.com/AlexeyPechnikov/pygmtsar/blob/pygmtsar/tests/S1A_Stack_CPGF_T173.py
> 

FWIW, I also ran into this while using a wrapper class for hdf5 files (the class h5w in https://github.com/h5py/h5py/issues/2237#issuecomment-2301492813 is a highly simplified version).

**Comment by ajelenak** [comment]
@AlexeyPechnikov It is often not easy to troubleshoot issues related to specific computing environments. You are the best person to troubleshoot a problem like this because it is so rare. I quickly looked at your pygmtsar repo and notice that xarray is one of its dependencies. Do you know if it installs the netcdf4 package automatically or not? I saw you also specified h5netcdf and h5py. Depending how netcdf4 and h5py are installed they can sometimes bring their own libhdf5 binary into the python environment and cause problems.

**Comment by AlexeyPechnikov** [comment]
@ajelenak For some configurations, netcdf4 can be better than h5netcdf, especially when it was the only stable option for the Google Colab environment (before their last major upgrade). The issue seems hard to reproduce in a simple example, so I locally added a check for h5f.OBJ_FILE in the h5py code to clean up logs. I don't think it's a rare case because I’ve seen it also in other projects utilizing the dask distributed scheduler, but it does not crash programs and is only annoying when analyzing logs. Anyway, I think h5f.OBJ_FILE needs to be checked to exclude race conditions.

**Comment by tacaswell** [comment]
@AlexeyPechnikov You are being unprofessional and rude in your communication here.  Please do better.

-----

Given that this is a constant on a module it should never be `None` so putting in a check if it is `None` is not the correct fix.

One option is that some other package is reaching in and setting `h5f.OBJ_FILE = None`, which would clearly be an error on their part.  However, I am doubtful that is the root cause.

My theory is that this is happening during interpreter shutdown (note that one of the tracebacks starts in a `__del__` of dask presumably caused by the interpreter's shutdown tearing down that object) where the order of things being destroyed is not defined behavior.   I suspect the fix is to keep a hard reference to the `h5f` module on the `File` class so it won't be cleaned up until after all `File` objects are torn down.  This is also consistent with changing what is imported having an impact as that may change the order things are torn down and sometimes you "win" the ordering.  It looks like @Kishore96in has given us a pretty minimal example.

If this is the correct explanation, the unary error is just the first thing to go wrong.  I would expect `hf5.OBJ_LOCAL` to also be `None` and then `_close_open_objects` to protest to being passed `None` rather than a int farther down the stack.

**Comment by tacaswell** [comment]
```diff
diff --git a/h5py/_hl/files.py b/h5py/_hl/files.py
index bfcf3098..86a6052a 100644
--- a/h5py/_hl/files.py
+++ b/h5py/_hl/files.py
@@ -568,6 +568,9 @@ class File(Group):

         super().__init__(fid)

+    _NON_FILE_MASK = h5f.OBJ_LOCAL | ~h5f.OBJ_FILE
+    _FILE_MASK = h5f.OBJ_LOCAL | h5f.OBJ_FILE
+
     def close(self):
         """ Close the file.  All open objects become invalid """
         with phil:
@@ -577,8 +580,8 @@ class File(Group):

                 # Close file-resident objects first, then the files.
                 # Otherwise we get errors in MPI mode.
-                self.id._close_open_objects(h5f.OBJ_LOCAL | ~h5f.OBJ_FILE)
-                self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
+                self.id._close_open_objects(self._NON_FILE_MASK)
+                self.id._close_open_objects(self._FILE_MASK)

                 self.id.close()
                 _objects.nonlocal_close()
```

fixes this error, but exposes other issues with things not being available during teardown.

https://docs.python.org/3/library/sys.html#sys.is_finalizing will tell us if we are shutting down, but I'm not sure if we want to just skip closing stuff as we are being torn down or make sure that we hold onto enough things to ensure we can do a full teardown even during interpreter shutdown.   I think this will depend on of the c++ layer has enough of its own logic to make sure caches are flushed.


I don't have plotly installed, but just kept adding unused imports until @Kishore96in example started to fail for me

```
import sys
import h5py

# import plotly.io.orca #This needs to be present to reproduce the bug!
import matplotlib
import scipy
import requests
import IPython

with h5py.File("test.h5", 'w') as f:
	f.create_dataset('kx', data=[1,2,3])

class h5w():
	def __init__(self, fname):
		self._cache = h5py.File(fname, 'r')

	def __del__(self):
		if hasattr(self, "_cache"):
			self._cache.close()

#Triggers the bug!
f = h5w("test.h5")

print(len(sys.modules))

```

is what worked.  I'm surprised that it is not 50/50 on working for any given set of imports, but not going to speculate what CPython is doing internally 🤣 .

**Comment by tacaswell** [comment]
on a bit more thought (just after I hit post on the previous message), the best path may be a combination of the above patch and then conditionally calling `nonlocal_close` on not being in shutdown (as if we are shutting down then there _should_ be no further use of the child objects, but I guess there could still be further `__del__` that have references to them to try to do something with them).

**Comment by AlexeyPechnikov** [comment]
@tacaswell 

> You are being unprofessional and rude in your communication here. Please do better.

I believe it’s ‘unprofessional’ to leave a bug report unaddressed, especially when it targets the exact lines of code where the issue occurs. I would be happy to receive such detailed bug reports in my projects. The most common bug reports are vague, like ‘it does not work,’ yet you are rejecting the ones that provide exact details!

**Comment by rmrtcla** [comment]
I've come accross this bug as well. For me it happens in a custom loader/wrapper class that hold the handle to a single hdf5 file:

```
class Hdf5Loader:

    def __init__(self, filepath):
        self._file = h5py.File(name=filepath, mode='r')
        # <...>

    def __del__(self):
        self.close()

    def close(self) -> None:
        if self._file is not None:
            self._file.close()
            self._file = None

```

Multiple instances of `Hdf5Loader` are then filled using a `concurrent.futures.ProcessPoolExecutor`. I'm not quite sure yet where or why exactly the problem is then triggered...

**Comment by i44p** [comment]
I also run into this exception, similarly to rmrtcla, though I'm using `torch.utils.data.DataLoader`, not ProcessPoolExecutor

**Comment by tacaswell** [comment]
The problem is that on process exit Python start to teardown all of the objects that are alive (including modules and the things in the modules).  I can not quote you the exact algorithm, but the problems happen when the order is:

 1. h5py.h5f module is cleaned out (everything is replaced with None) so the mask is no longer defined as the type we need
 2. the object with a custom `__del__` is cleaned up
 3. the code in __del__ runs which calls close() with then gets None and we get the failure here.

But if your object is torn down first everything looks OK! The delicate nature of `__del__` is noted in the CPython docs: https://docs.python.org/3/reference/datamodel.html#object.__del__  The reason adding unused imports affected things as I discussed above is that they changed the order in which things were torn down which changes if you win or lose the race.

The fix on the library side is atleast the patch I proposed above, but I think on the user side if you do something like:

```python
class H5Loader:
    __keep_alive = h5py.h5f
    ...
```

you can probably prevent this issue but you may end up playing whack-a-mole with other problems!  You can also make sure that your objects are cleaned up before the interpeter starts to shutdown.

**Comment by jonaslb** [comment]
Running into this issue presently. In my case, I'm presenting some file objects for opening with xarray with `engine="h5netcdf"`, so I do control the underlying objects, but not the h5py objects directly. I think that using the `__keep_alive` trick above on my file wrapper did fix my problem though, but due to the flaky nature of this issue, I guess I can't say for certain.

Would it not be best here to accept that `close()` can get called during interpreter shutdown, and handle that somewhat properly? As for "whack-a-mole with other problems" - this practice doesn't have to extend to _every_ functionality, just for those situations that it really doesn't make sense to error out.

> I'm not sure if we want to just skip closing stuff as we are being torn down or make sure that we hold onto enough things to ensure we can do a full teardown even during interpreter shutdown

At least for my issue (read-only), closing during shutdown could just as well be a no-op. Maybe an error is still appropriate for write mode / if there is some non-written data or similar (I'm not familiar with whether h5 objects do something like that).

**Comment by AlexeyPechnikov** [comment]
@jonaslb Unfortunately, netCDF processing is completely broken for months, and it seems there is no way to use it on Google Colab at all. I.e. the library is dead, and we cannot wait for any fixes anymore.
