### ISSUE TITLE
DLL load failed for h5py package.

### ISSUE THREAD

**Issue by unikill066** [h5py/h5py#2245]
When I run *CellBender*, I get an error regarding *h5py* failing to load the DLLs:
--------------------------
I have followed the installation steps referring to the documentation [here](https://github.com/broadinstitute/CellBender):
Here are the dependencies: `CellBender <-- AnnData <-- h5py`
```
$ conda create -n cellbender python=3.7
$ source activate cellbender
(cellbender) $ conda install -c anaconda pytables
(cellbender) $ conda install pytorch torchvision -c pytorch
(cellbender) $ pip install -e CellBender
```

When I run cellbender, I see the following *Error*, please check and suggest what is the right fix here:
```
(CellBender) C:\Users\user12\Desktop\cellbender_test>cellbender remove-background --input C:\Users\user12\Desktop\feature_bc_matrix.h5 --output C:\Users\user12\Desktop\output.h5 --cuda --expected-cells 5000 --total-droplets-included 20000 --fpr 0.01 --epochs 150
Traceback (most recent call last):
  File "C:\Users\user12\AppData\Local\anaconda3\envs\CellBender\Scripts\cellbender-script.py", line 33, in <module>
    sys.exit(load_entry_point('cellbender', 'console_scripts', 'cellbender')())
  File "c:\users\user12\desktop\cellbender_test\cellbender\cellbender\base_cli.py", line 91, in main
    cli_dict = generate_cli_dictionary()
  File "c:\users\user12\desktop\cellbender_test\cellbender\cellbender\base_cli.py", line 52, in generate_cli_dictionary
    module_cli = importlib.import_module('.'.join(module_cli_str_list))
  File "C:\Users\user12\AppData\Local\anaconda3\envs\CellBender\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\user12\desktop\cellbender_test\cellbender\cellbender\remove_background\cli.py", line 4, in <module>
    from cellbender.remove_background.data.dataset import SingleCellRNACountsDataset
  File "c:\users\user12\desktop\cellbender_test\cellbender\cellbender\remove_background\data\dataset.py", line 10, in <module>
    import anndata
  File "C:\Users\user12\AppData\Local\anaconda3\envs\CellBender\lib\site-packages\anndata\__init__.py", line 7, in <module>
    from ._core.anndata import AnnData
  File "C:\Users\user12\AppData\Local\anaconda3\envs\CellBender\lib\site-packages\anndata\_core\anndata.py", line 17, in <module>
    import h5py
  File "C:\Users\user12\AppData\Local\anaconda3\envs\CellBender\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\user12\AppData\Local\anaconda3\envs\CellBender\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed: The specified procedure could not be found.
```
I tried installing h5py - 3.6.0 and 3.1.0 none of those versions worked in my case. Also, I debugged, printed out the import paths and copied the respective files from h5py, still no luck.

**Comment by takluyver** [comment]
I'm not familiar with Cellbender, but I see that you're installing pytables. Do you know if you're getting h5py from conda or from pip (PyPI)?

Both h5py and pytables wrap HDF5, so if you get pytables from conda and h5py from PyPI, this could be a conflict between them. In *theory*, if you're using conda, the best option is to make sure both pytables and h5py are installed from conda.

Unfortunately, in practice, that also doesn't work as well as one might hope, because there are some [longstanding](https://github.com/conda-forge/h5py-feedstock/issues/103) [issues](https://github.com/conda-forge/h5py-feedstock/issues/92) with h5py conda packages.

I don't really have a solution to that. Removing the h5py conda package and installing it with pip might work, even though this is worse in theory (be aware this is quite likely to get your conda env tangled so conda refuses to add/upgrade any packages afterwards). You could try with more recent versions of Python - I can see you've followed the cellbender instructions, but 3.7 is quite old now. Building h5py from source with the HDF5 in your conda environment would probably fix it, but building from source on Windows is a major hassle. :disappointed:
