### ISSUE TITLE
[SWMR] Error when closing writer if readers are present

### ISSUE THREAD

**Issue by voverius** [h5py/h5py#2259]
Hello,

I'am trying to:

- Process 1: Open file as a writer 
- Process 1: Set `swmr_mode=True`
- Process 2: Open file in SWMR as a reader
- Process 1: Close writer file object using `f.close()`

At this point python crashes and gives the following traceback:

```
Traceback (most recent call last):
  File "D:\Repositories\Commons\Testing\Commons\Data\test_DataHDF5.py", line 143, in DataHDF5WriterError
    dataManager._fileObject.close()
  File "D:\Repositories\Commons\.venv311\Lib\site-packages\h5py\_hl\files.py", line 586, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 360, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (file write failed: time = Sat May  6 13:30:37 2023
, filename = 'D:\Repositories\Commons\..structure\..i3uxwi3u\data\269.   ..Testing\030.   Temporary\..DataHDF5_Test.h5', file descriptor = 4, errno = 13, error message = 'Permission denied', buf = 000001DA8F2794C0, total write size = 48, bytes this sub-write = 48, bytes actually written = 18446744073709551615, offset = 0)
```

It seems that SWMR writer does not have permission to close the file object. This error does not occur if the reader closes the file object prior to the writer closing it...

Setup:
OS - Windows 11
Python - 3.11 / 3.10
h5py - 3.8.0
HDF5 - 1.12.2

**Comment by takluyver** [comment]
SWMR seems to be somewhat broken on Windows - see also #2022, #2238, #1470. As far as I know, there's nothing h5py can do about this - it's an issue with HDF5 itself.

Someone has recently asked about it on the HDF forum: https://forum.hdfgroup.org/t/swmr-fails-on-windows/11101

The only news I've heard is that HDF group are planning on removing the file locking altogether. If they do, that would probably fix this, but then there would be other problems to solve (the reasons they used locking in the first place), so I don't know what the plan is.

**Comment by takluyver** [comment]
I'd expect it to behave differently with one process versus two. When you open the same file twice in the same process, HDF5 internally reuses the same OS-level file descriptor, so in terms of file locking this is a very different thing to running two processes.

**Comment by takluyver** [comment]
On #2022, people seem to have found that setting the environment variable `HDF5_USE_FILE_LOCKING=FALSE` can avoid this problem. Disabling the locking may leave you open to weird problems if you're not careful with concurrent file access, but anecdotally it mostly seems to be OK. :shrug:
