### ISSUE TITLE
Cannot create 16bit float dataset with scaleoffset.

### ISSUE THREAD

**Issue by nup002** [h5py/h5py#2265]
On my system it is not possible to create a dataset that has `dtype=np.float16` and scaleoffset applied. Repro steps:

```
import h5py
with h5py.File('16bit_w_scaleoffset_test.hdf5', 'w') as fp:
    fp.create_dataset('no_scaleoffset', shape=(1,),  dtype=np.float16)  # Works fine
    fp.create_dataset('with_scaleoffset', shape=(1,),  dtype=np.float16, scaleoffset=1)  # Fails
```
 * Operating System: Windows 11
 * Python version: 3.10
 * Python installed through Anaconda
 * h5py version: 3.8.0
 * HDF5 version 1.14.0

```
Traceback (most recent call last):
  File "C:\Users\magla\miniconda3\envs\widcore_files\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\magla\miniconda3\envs\widcore_files\lib\site-packages\h5py\_hl\group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "C:\Users\magla\miniconda3\envs\widcore_files\lib\site-packages\h5py\_hl\dataset.py", line 165, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl, dapl=dapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 135, in h5py.h5d.create
ValueError: Unable to synchronously create dataset (cannot find matched memory dataype)
```

This error only occurs for `np.float16`. The 'normal' floats `np.float32` and `np.float64` works fine.

**Comment by takluyver** [comment]
I would guess this is to do with the fact that float32 and float64 are built-in HDF5 types, but float16 is defined as a custom float type. Possibly HDF5 only recognises certain data types for the scaleoffset filter.

https://github.com/h5py/h5py/blob/06d9d0d095c1e972f938d874a78598ae42b1df8e/h5py/h5t.pyx#L145-L149

https://github.com/h5py/h5py/blob/06d9d0d095c1e972f938d874a78598ae42b1df8e/h5py/h5t.pyx#L220-L229

I'm not sure where to go with that information, though.

**Comment by nup002** [comment]
I guess that means it's not a h5py problem, but a built-in limitation of HDF5, and we will just have to graciously wait for them to eventually support 16bit floats.

I wonder if a dataset stored as 16 bit float, 32 bit float, or 64 bit float will take up practically the same amount of storage with the same scale offset filter applied. If it does, then I can just store my data as 32 bit with my desired scale offset applied.

**Comment by takluyver** [comment]
Good idea. I would guess that the compressed data is similar size regardless of the datatype, so long as all the datatypes have enough precision to store the information you want. If you do try this, please post what you find (along with what sort of range your data covers, because the scale factor for floats is based on digits after the decimal point, not on significant figures).

**Comment by nup002** [comment]
It seems that my reasoning is correct. See the following result from writing datasets with the same 10 million random numbers in the range 1 to 10 (not inclusive):

```
SCALE OFFSET TEST  -  DIMENSIONS: (10000000,)  -  DATA RANGE: [1.0, 10.0)
Float16, no scale offset: 19.1 MiB  -  Write time: 33.7 ms  -  Read time: 3.9 ms
Float32, scale offset 1 : 8.4 MiB  -  Write time: 248.0 ms  -  Read time: 68.1 ms
Float64, scale offset 1 : 8.4 MiB  -  Write time: 246.3 ms  -  Read time: 70.2 ms
```

The same data stored as float32 or float64 takes up the same amount of space on the drive when they use the same scale offset, namely 8.4MiB.

We can also verify that this relationship holds for larger ranges of data, here from 0.001 to 1000:
```
SCALE OFFSET TEST  -  DIMENSIONS: (10000000,)  -  DATA RANGE: [0.001, 1000.0)
Float16, no scale offset: 19.1 MiB  -  Write time: 35.3 ms  -  Read time: 3.9 ms
Float32, scale offset 1 : 16.7 MiB  -  Write time: 234.4 ms  -  Read time: 86.3 ms
Float64, scale offset 1 : 16.7 MiB  -  Write time: 230.2 ms  -  Read time: 94.3 ms
```

We can therefore conclude that if you want to use scale offset to limit your dataset to a certain number of decimals, it does not matter which floating point type you are storing them as. Just keep in mind that the read and write performance degrades once scale offset is applied. In my particular example I want to store values in the range [-25, 25] with 1 digit of precision:
```
SCALE OFFSET TEST  -  DIMENSIONS: (10000000,)  -  DATA RANGE: [-25, 25)
Float16, no scale offset: 19.1 MiB  -  Write time: 33.8 ms  -  Read time: 3.9 ms
Float32, scale offset 1 : 10.8 MiB  -  Write time: 253.4 ms  -  Read time: 88.5 ms
Float64, scale offset 1 : 10.8 MiB  -  Write time: 232.9 ms  -  Read time: 84.3 ms
```
