### ISSUE TITLE
Installing for pypy on Windows

### ISSUE THREAD

**Issue by ptoews** [h5py/h5py#2278]
I'm trying to install h5py for pypy (7.3.11 with MSC v.1929 64 bit (AMD64), python 3.9) with conda on Windows.
Here are my commands:

```
conda create -c conda-forge -n converting_tools_pypy pypy
conda activate converting_tools_pypy
conda install h5py
```
This is the error I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\h5py\__init__.py", line 25, in <module>
    from . import _errors
ImportError: cannot import name '_errors' from partially initialized module 'h5py' (most likely due to a circular import) (...\lib\site-packages\h5py\__init__.py)
```

I found this similar issue (https://github.com/h5py/h5py/issues/753) so I also tried using pip.

```
> pip install h5py
Collecting h5py
  Using cached h5py-3.8.0.tar.gz (400 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.14.5 (1.25.0)
Building wheels for collected packages: h5py
  Building wheel for h5py (pyproject.toml) ...
...

      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DH5_USE_18_API -DNPY_NO_DEPRECATED_API=0 -D_HDF5USEDLL_ -DH5_BUILT_AS_DYNAMIC_LIB -I.\h5py -IC:\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-oekv5bf0\h5py_65c30bcd9f5a4b6c93d602669679d8cc\lzf -IC:\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-oekv5bf0\h5py_65c30bcd9f5a4b6c93d602669679d8cc\lzf\lzf -IC:\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-oekv5bf0\h5py_65c30bcd9f5a4b6c93d602669679d8cc\windows -IC:\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-build-env-ll4neotu\overlay\Lib\site-packages\numpy\core\include -IC:\Users\Philipp.Toews\AppData\Local\miniconda3\envs\converting_tools_pypy11\include -IC:\Users\Philipp.Toews\AppData\Local\miniconda3\envs\converting_tools_pypy11\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\cppwinrt" /TcC:\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-oekv5bf0\h5py_65c30bcd9f5a4b6c93d602669679d8cc\h5py\defs.c /Fobuild\temp.win-amd64-pypy39\Release\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-oekv5bf0\h5py_65c30bcd9f5a4b6c93d602669679d8cc\h5py\defs.obj
      defs.c
      C:\Users\Philipp.Toews\AppData\Local\Temp\pip-install-oekv5bf0\h5py_65c30bcd9f5a4b6c93d602669679d8cc\h5py\api_compat.h(27): fatal error C1083: Datei (Include) kann nicht ge\x94ffnet werden: "hdf5.h": No such file or directory
      C:\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-build-env-ll4neotu\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
```

Note that it's not finding the hdf5.h. As per [this issue](https://github.com/hhoeflin/hdf5r/issues/112) I tried `conda install -c anaconda hdf5` but this results in the same error. I checked whether hdf5.h is in the `include` directory of my env, and it's not there. Is it supposed to be there and if yes, how do I get it there?

Thanks for any help in advance.

**Comment by ajelenak** [comment]
Why you didn't try `conda install -c conda-forge hdf5`? I also recommend deleting the conda environment and starting clean.

**Comment by ptoews** [comment]
@ajelenak Tried that as well (with a clean env), but that doesn't install the h5py package. Trying pip install after this resulted in the same error as above. Same for setting condas channel_priority to flexible and then trying `conda install -c conda-forge h5py`

**Comment by ajelenak** [comment]
Perhaps h5py's source installation [docs](https://docs.h5py.org/en/stable/build.html#source-installation-on-windows) can help?

**Comment by ptoews** [comment]
Not sure how, had a look at appveyor and get_hdf5_win.py, did it manually to build hdf5. Copied the hdf5.h to my include directory. Now the error when running the pip command is:

```
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Philipp.Toews\AppData\Local\hdf5\1.12.2\14\lib /LIBPATH:C:\Users\Philipp.Toews\AppData\Local\hdf5\1.12.2\14\bin /LIBPATH:C:\Users\Philipp.Toews\AppData\Local\miniconda3\envs\converting_tools_pypy13\libs /LIBPATH:C:\Users\Philipp.Toews\AppData\Local\miniconda3\envs\converting_tools_pypy13 /LIBPATH:C:\Users\Philipp.Toews\AppData\Local\miniconda3\envs\converting_tools_pypy13\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\um\x64" hdf5.lib hdf5_hl.lib /EXPORT:PyInit_defs build\temp.win-amd64-pypy39\Release\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-3tpz4mqj\h5py_5470c8f488f44fa592dc842cfd41302e\h5py\defs.obj /OUT:build\lib.win-amd64-pypy39\h5py\defs.pypy39-pp73-win_amd64.pyd /IMPLIB:build\temp.win-amd64-pypy39\Release\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-3tpz4mqj\h5py_5470c8f488f44fa592dc842cfd41302e\h5py\defs.pypy39-pp73-win_amd64.lib
      LINK : fatal error LNK1104: Datei "build\temp.win-amd64-pypy39\Release\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-3tpz4mqj\h5py_5470c8f488f44fa592dc842cfd41302e\h5py\defs.pypy39-pp73-win_amd64.exp" kann nicht ge\x94ffnet werden.
      C:\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-build-env-usxx899h\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1104
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
```
It's partially German but it cannot open the file build\...\...exp
Not sure if that's an improvement

**Comment by ajelenak** [comment]
Not a Windows user but having to copy `hdf5.h` is not a good sign. I always use `HDF5_DIR` env. variable to set the install folder of the HDF5 library. That's the folder with a `include` and `lib` folders in it. Example command: `HDF5_DIR=/path/to/hdf5 pip install --no-binary=h5py h5py`.

**Comment by ptoews** [comment]
Tried that with a new env, same error (cannot open file). The path of that file is weird, it seems to be relative starting with `build\`?

**Comment by ajelenak** [comment]
My final suggestion is to install/upgrade the latest setuptools and pip in the conda environment.

**Comment by ptoews** [comment]
Sadly no success either. I gave up and tried the same on a Linux machine, worked on the first try.
How can I find out where that build directory is created? I suspect that Windows' filepath length limit of 260 characters might be an issue if this is the full path:
`C:\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-3tv9zj60\h5py_5d5a77417cd64d58aa909e078278bd92\build\temp.win-amd64-pypy39\Release\Users\PHILIP~1.TOE\AppData\Local\Temp\pip-install-3tv9zj60\h5py_5d5a77417cd64d58aa909e078278bd92\h5py\defs.pypy39-pp73-win_amd64.exp` (269 characters)

**Comment by ajelenak** [comment]
Yes, that could be the cause. I found mention of this problem in the pip repo and several StackOverflow questions.

My final-final suggestion is to try and install h5py in the developer mode. That may reduce the folder names involved. You would need h5py source and then in its top folder do something like: `HDF5_DIR=... pip install -e .`.

**Comment by tacaswell** [comment]
The `--no-build-isolation` flag to pip may also help.  Because `setuptools` will by default try to create a virtual environment to build the wheel (which it will then install into your actual environment) in, very funny things can happen with compilers / native libraries.

**Comment by ptoews** [comment]
> --no-build-isolation

Tried this in a new env but got the same ImportError as above.

**Comment by tacaswell** [comment]
see: https://github.com/h5py/h5py/issues/2240#issuecomment-1584336273  This may be a pip / setuptools bug as well.
