### ISSUE TITLE
External links not being passed mpio driver or comm world

### ISSUE THREAD

**Issue by leonfoks** [h5py/h5py#2287]
To assist reproducing bugs, please include the following:
 * Operating System MacOS 12.6.7
 * Python version 3.10.8
 * Where Python was acquired. Anaconda
 * h5py version 3.7.0
 * HDF5 version 1.12.2
 * The full traceback/stack trace shown (if it appears)

I've been testing ExternalLinks inside a "head" file that simply manages other files by creating external links.

In serial this all works fine, but when running in parallel using MPI, I cannot reopen just the head file with mpio drivers.

Here is a minimal example script that produces correct results in serial, and barfs in parallel.  I have two environments when I run this, one is serial enabled, the other has mpi4py and h5py intstalled with MPI.

For testing this script simply do 

```
conda activate serial
python script.py
conda deactivate

conda activate parallel
mpirun -n 2 python script.py --mpi
conda deactivate
```

Expected Outcome
-------------------

The following should be repeated 4 times if running on 4 cores.
```
['101001', '101002', '101003']
<HDF5 group "/" (1 members)>
```

Actual Outcome
----------------
Running with mpirun -n 2

```
['101001', '101002', '101003']
['101001', '101002', '101003']
<HDF5 group "/" (1 members)>
Traceback (most recent call last):
  File "/Users/nfoks/test/mpio_external_link.py", line 39, in <module>
    test_driver(driver='mpio', comm=comm)
  File "/Users/nfoks/test/mpio_external_link.py", line 23, in test_driver
    print(f['101001'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/nfoks/miniconda3/envs/pGeobipy/lib/python3.10/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to synchronously open object (unable to open external file, external link file name = './101001.h5')"
```
Notice that "<HDF5 group "/" (1 members)>" is written only once.  The head file has been successfully opened on both cores, but the ExternalLink has not.

```python
import numpy as np
import h5py

def test_driver(**kwargs):

    # Three external files, one per line number
    lines = [101001, 101002, 101003]

    # Create each h5 file per line
    for line in lines:
        with h5py.File('{}.h5'.format(line), 'w', **kwargs) as f:
            f.create_dataset('data', data=np.arange(10))

    # Create the handler
    with h5py.File('head.h5', 'w', **kwargs) as f:
        for line in lines:
            f['{}'.format(line)] = h5py.ExternalLink("./{}.h5".format(line), '/')

    # Files are closed at this point. Reopen using only the head
    with h5py.File('head.h5', 'r+', **kwargs) as f:

        print(list(f.keys()))
        print(f['101001'])


if __name__ == "__main__":

    import argparse

    Parser = argparse.ArgumentParser(description="test", formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    Parser.add_argument('--mpi', dest='mpi', action='store_true', help='Run with MPI libraries.')

    args = Parser.parse_args()

    if args.mpi:
        from mpi4py import MPI
        comm = MPI.COMM_WORLD

        test_driver(driver='mpio', comm=comm)
    else:
        test_driver()

```

**Comment by ajelenak** [comment]
The challenge for issues like this is to determine whether the error comes h5py/Python or libhdf5. Can you create a C example that would only test the libhdf5?

**Comment by leonfoks** [comment]
Let me see what I can do.  I'm not very good in C, more of a Fortran background. Ill see what I can put together with examples online.
