### ISSUE TITLE
h5py 3.1.0 on ppc64le: h5py/_conv.pyx:21:0: 'h5py/h5t/H5PY_OBJ.pxd' not found; undeclared name not builtin: H5PY_PYTHON_OPAQUE_TAG

### ISSUE THREAD

**Issue by eugeneswalker** [h5py/h5py#2300]
Trying to install `h5py-3.1.0.tgz` via pip on:
* Ubuntu 20.04
* PPC64LE
* Python 3.8.10
* pip 23.2.1
* HDF5 1.10.4 (installed via `apt install libhdf5-dev`)

Edit: It looks like others are having this issue too
* https://forums.developer.nvidia.com/t/jetson-nano-4-6-1-h5py-build-error/263455
* I am able to get around the issue below if I follow the suggestion of manually checking out h5py 3.1.0 source code and cherry-picking 3bf862daa4ebeb2eeaf3a0491e05f5415c1818e4, then doing the build that way

**pip list**
```
$> pip list
Package             Version
------------------- ---------
boto3               1.20.35
botocore            1.23.42
certifi             2023.7.22
cffi                1.15.1
charset-normalizer  3.2.0
clingo              5.6.2
Cython              3.0.0
gnureadline         8.1.2
idna                3.4
jmespath            0.10.0
Keras-Preprocessing 1.1.2
minio               7.1.15
numpy               1.19.5
opt-einsum          3.3.0
packaging           23.1
pip                 23.2.1
pycparser           2.21
python-dateutil     2.8.2
pytz                2023.3
PyYAML              6.0.1
requests            2.31.0
s3transfer          0.5.2
setuptools          68.0.0
six                 1.16.0
urllib3             1.26.16
wheel               0.41.2
```

Full log: [output.log](https://github.com/h5py/h5py/files/12447851/output.log) (excerpted below)

```
$> pip install --no-cache-dir ./tensorflow-2.6.5-cp38-cp38-linux_ppc64le.whl 2>&1 | tee output.log
...
Collecting h5py~=3.1.0 (from tensorflow==2.6.5)
  Downloading h5py-3.1.0.tar.gz (371 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 371.4/371.4 kB 80.4 MB/s eta 0:00:00
...
  Building wheel for h5py (pyproject.toml): started
  Building wheel for h5py (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for h5py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [485 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-ppc64le-cpython-38
      creating build/lib.linux-ppc64le-cpython-38/h5py
      copying h5py/ipy_completer.py -> build/lib.linux-ppc64le-cpython-38/h5py
      copying h5py/h5py_warnings.py -> build/lib.linux-ppc64le-cpython-38/h5py
      copying h5py/__init__.py -> build/lib.linux-ppc64le-cpython-38/h5py
      copying h5py/version.py -> build/lib.linux-ppc64le-cpython-38/h5py
      creating build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.linux-ppc64le-cpython-38/h5py/_hl
      creating build/lib.linux-ppc64le-cpython-38/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.linux-ppc64le-cpython-38/h5py
...
      running build_ext
      warning: h5py/config.pxi:3:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: h5py/config.pxi:4:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: h5py/config.pxi:5:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: h5py/config.pxi:6:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: h5py/config.pxi:7:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
...
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # License:  Standard 3-clause BSD; see "license.txt" for full license terms
      #           and contributor agreement.

      from .defs cimport *

      from ._objects cimport class ObjectID
                             ^
      ------------------------------------------------------------

      h5py/h5t.pxd:13:23: Expected an identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      from logging import getLogger

      from .h5 import get_config
      from .h5r cimport Reference, RegionReference, hobj_ref_t, hdset_reg_ref_t
      from .h5t cimport H5PY_OBJ, typewrap, py_create, TypeID, H5PY_PYTHON_OPAQUE_TAG
      ^
      ------------------------------------------------------------

      h5py/_conv.pyx:21:0: 'h5py/h5t/H5PY_OBJ.pxd' not found
      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      from logging import getLogger

      from .h5 import get_config
      from .h5r cimport Reference, RegionReference, hobj_ref_t, hdset_reg_ref_t
      from .h5t cimport H5PY_OBJ, typewrap, py_create, TypeID, H5PY_PYTHON_OPAQUE_TAG
      ^
      ------------------------------------------------------------

      h5py/_conv.pyx:21:0: 'h5py/h5t/typewrap.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      from logging import getLogger

      from .h5 import get_config
      from .h5r cimport Reference, RegionReference, hobj_ref_t, hdset_reg_ref_t
      from .h5t cimport H5PY_OBJ, typewrap, py_create, TypeID, H5PY_PYTHON_OPAQUE_TAG
      ^
      ------------------------------------------------------------

      h5py/_conv.pyx:21:0: 'h5py/h5t/py_create.pxd' not found
...
      h5py/_conv.pyx:741:8: 'TypeID' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                               hid_t dxpl) except -1 with gil:
          cdef:
              int command = cdata[0].command
              size_t src_size, dst_size
              TypeID supertype
              TypeID outtype
              ^
      ------------------------------------------------------------

      h5py/_conv.pyx:742:8: 'TypeID' is not a type identifier
...
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef char* ctag = NULL
          try:
              if H5Tget_class(obj) == H5T_OPAQUE:
                  ctag = H5Tget_tag(obj)
                  if ctag != NULL:
                      if strcmp(ctag, H5PY_PYTHON_OPAQUE_TAG) == 0:
                                      ^
      ------------------------------------------------------------

      h5py/_conv.pyx:156:32: undeclared name not builtin: H5PY_PYTHON_OPAQUE_TAG

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          elif command == H5T_CONV_FREE:
              pass

          elif command == H5T_CONV_CONV:
              # need to pass element dtype to converter
              supertype = typewrap(H5Tget_super(src_id))
                          ^
      ------------------------------------------------------------

      h5py/_conv.pyx:644:20: undeclared name not builtin: typewrap
...
      Loading library to get version: /usr/lib/powerpc64le-linux-gnu/hdf5/serial/libhdf5.so
      ********************************************************************************
                             Summary of the h5py configuration

      HDF5 include dirs: [
        '/usr/include/hdf5/serial'
      ]
      HDF5 library dirs: [
        '/usr/lib/powerpc64le-linux-gnu/hdf5/serial'
      ]
           HDF5 Version: (1, 10, 4)
            MPI Enabled: False
       Rebuild Required: True

      ********************************************************************************
      Executing api_gen rebuild of defs
      Executing cythonize()
      [ 1/24] Cythonizing /tmp/pip-install-xh3vrfkl/h5py_d3bdabe2a91f4ca2bdb002d8b9f96625/h5py/_conv.pyx
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 158, in <module>
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-oe2w7x2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-xh3vrfkl/h5py_d3bdabe2a91f4ca2bdb002d8b9f96625/setup_build.py", line 169, in run
          self.extensions = cythonize(self._make_extensions(config),
        File "/tmp/pip-build-env-oe2w7x2z/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-oe2w7x2z/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: /tmp/pip-install-xh3vrfkl/h5py_d3bdabe2a91f4ca2bdb002d8b9f96625/h5py/_conv.pyx
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
...
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
```

I was able to install this same TensorFlow wheel about ~3 months ago, also on Ubuntu 20.04 for PPC64LE, also with Python 3.8.10. Not sure what could have changed since then.

**Comment by ajelenak** [comment]
I noticed Cython 3.0.0 in your installed packages list. It is known that any Cython 3.x is producing errors with the current h5py code so I suggest installing h5py binary packages if possible.

**Comment by eugeneswalker** [comment]
> I noticed Cython 3.0.0 in your installed packages list. It is known that any Cython 3.x is producing errors with the current h5py code so I suggest installing h5py binary packages if possible.

Are there h5py binary packages available for `ppc64le` ?

**Comment by ajelenak** [comment]
Not sure if there are binary packages for your computer architecture. What might work is to install h5py from source prior to installing your main package. The command is:

    $ pip install --no-binary=h5py h5py

Source installation is described at https://docs.h5py.org/en/stable/build.html#source-installation.

The _pip_ command should pull the correct Cython version and avoid the errors you are seeing. This may be true only for the latest h5py. At some point, don't remember exactly when, the Cython version upper limit was put to avoid 3.x.

**Comment by vasole** [comment]
> Not sure if there are binary packages for your computer architecture. 

We maintain a repository with ppc64le wheels.

http://www.silx.org/pub/wheelhouse/

If you want to install h5py 3.1.0, the command below or something similar should work

'pip install h5py==3.1.0 --pre --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse/`

**Comment by takluyver** [comment]
I think @vasole and @ajelenak have this covered between their answers - you either need a precompiled package, or if you want to compile from source, you'll need to figure out how to do so with an older version of Cython.

The package metadata *now* specifies that it needs Cython 0.x so pip can find that automatically, but back when h5py 3.1 was released, it didn't say that, so pip will try to build it with the newest Cython by default.

**Comment by eugeneswalker** [comment]
Thank you!
