### ISSUE TITLE
OSError: [Errno 116] Unable to synchronously create file (unable to fstat file, errno = 116, error message = 'Stale file handle')

### ISSUE THREAD

**Issue by FSet89** [h5py/h5py#2346]
### Info
Ubuntu 20.04.2 
h5py    3.10.0
HDF5    1.14.2
Python  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.26.2
cython (built with) 0.29.36
numpy (built against) 1.21.6
HDF5 (built against) 1.14.2

### Problem
I am training a TF+Keras model and the checkpoints are saved on a mounted NAS in h5 format. When `model.save()` is called, I get the attached error. Some times the first call to `save()` succeeds but the second one throws the error.

### Traceback
**Traceback (most recent call last):
  File "/mnt/NAS/mypath/train.py", line 395, in <module>
    model.save(save_path, 
  File "/home/myuser/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/myuser/.local/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/myuser/.local/lib/python3.10/site-packages/h5py/_hl/files.py", line 241, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 122, in h5py.h5f.create
OSError: [Errno 116] Unable to synchronously create file (unable to fstat file, errno = 116, error message = 'Stale file handle')**

**Comment by ajelenak** [comment]
The error (stale file handle) comes from the operating system and means there was some kind of change in the NFS file handle that represented your file on the NAS device. There can be several reasons  why that NFS file handle became stale and it could be related to how your training application writes data to an HDF5 file. Bottom line, this is not an h5py issue.
