### ISSUE TITLE
Initializing dataset with vlen data

### ISSUE THREAD

**Issue by jreadey** [h5py/h5py#2429]
I ran into a strange bug when trying to initialize a dataset based on vlen data.
Things work if the number of vlen elements works, but not if each array element has the same number. an AttributeError is raised.

Example:
"""
import h5py
import numpy as np

print("h5py version:", h5py.version.api_version)
print("hdf5 version:", h5py.version.hdf5_version)

dtvlen = h5py.special_dtype(vlen=np.float64)
f = h5py.File("vlen_test.h5", "w")
e2a = np.array([1.9, 2.8], dtype=np.float64) 
e2b = np.array([2.9, 3.8], dtype=np.float64)
e3 = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr1 = np.array([e2a, e3], dtype=dtvlen)  # this works
dset1 = f.create_dataset("dset1", data=arr1)
print(f"dset1: { dset1}")
arr2 = np.array([e2a, e2b], dtype=dtvlen)
dset2 = f.create_dataset("dset2", data=arr2)  # this doesn't
print(f"dset2: { dset2}")
"""

Output:
"""
$ python vlen_test.py 
h5py version: 1.8
hdf5 version: 1.14.3
dset1: <HDF5 dataset "dset1": shape (2,), type "|O">
Traceback (most recent call last):
  File "/home/john/gists/vlen_test.py", line 16, in <module>
    dset2 = f.create_dataset("dset2", data=arr2)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/anaconda3/envs/hstest/lib/python3.11/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/anaconda3/envs/hstest/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 166, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 282, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 147, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 808, in h5py._conv.ndarray2vlen
AttributeError: 'float' object has no attribute 'dtype'
"""
I could get around this by creating an empty dataset and assigning elements individually, but that seems unnecessarily slow.
Any thoughts on this?

**Comment by takluyver** [comment]
The problem is setting in before h5py gets involved: numpy doesn't like to create an array-of-arrays if it can make sense of your data as an n+1 dimensional array instead. So `arr2` is a 2D array of numbers:

```
In [2]: arr1
Out[2]: array([array([1.9, 2.8]), array([1.1, 2.2, 3.3])], dtype=object)

In [3]: arr2
Out[3]: 
array([[1.9, 2.8],
       [2.9, 3.8]], dtype=object)
```

Working around it doesn't require assigning elements individually:

```
In [7]: dset3 = f.create_dataset('dset3', shape=2, dtype=dtvlen)

In [8]: dset3[:] = arr2

In [9]: dset3[:]
Out[9]: array([array([1.9, 2.8]), array([2.9, 3.8])], dtype=object)
```

Or you can do an ugly trick to get an array of arrays up front:

```
In [11]: arr2a = np.array([e2a, e2b, np.array([])], dtype=dtvlen)

In [12]: arr2a[:-1]
Out[12]: array([array([1.9, 2.8]), array([2.9, 3.8])], dtype=object)

In [13]: dset4 = f.create_dataset('dset4', data=arr2a[:-1])
```
