### ISSUE TITLE
Problems with h5py wheel and usage of HDF5 dimension scales

### ISSUE THREAD

**Issue by rmvanhees** [h5py/h5py#2453]
To assist reproducing bugs, please include the following:
 * Operating System Debian Bookworm, Ubuntu 22.04
 * Python version 3.12
 * h5py version (e.g. 3.11.0)
 * HDF5 version (e.g. 1.14.2 / 1.14.4)
 * The full traceback/stack trace shown (if it appears)

This week I discovered that my code where I create of modify HDF5 dimension scales did not work anymore, generating Runtime exceptions with H5DSset_scale (return value <0). First, I thought that it was due to the upgrade to numpy 2.0.0, but downgrading to 1.26.4 did not solve the problem. I checked my code against the h5py documentation (no obvious mistakes), then I decided to install h5py using the latest source tree from gitHub. And everything worked again as expected. But still I am a bit puzzled: is it the HDF5 library (1.14.2 -> 1.14.4)? Or is something changed in the source tree of h5py (v3.11.0 -> current master)? Any ideas?

Greetings, Richard

This is output of 'h5py.version.info' of the h5py installation on my system using 'pip install h5py', just after the release of v3.11.0:

    >>> import h5py
    >>> print(h5py.version.info)
    Summary of the h5py configuration
    ---------------------------------

    h5py    3.11.0
    HDF5    1.14.2
    Python  3.12.3 (main, Apr 26 2024, 15:28:32) [GCC 12.2.0]
    sys.platform    linux
    sys.maxsize     9223372036854775807
    numpy   2.0.0
    cython (built with) 3.0.10
    numpy (built against) 2.0.0rc1
    HDF5 (built against) 1.14.2

This is output of 'h5py.version.info' of the h5py installation from 'pip install -v .' in the source tree cloned from gitHub last Wednesday (July 3, 2024):

    >>> import h5py
    >>> print(h5py.version.info)
    Summary of the h5py configuration
    ---------------------------------

    h5py    3.11.0
    HDF5    1.14.4
    Python  3.12.3 (main, Apr 26 2024, 15:28:32) [GCC 12.2.0]
    sys.platform    linux
    sys.maxsize     9223372036854775807
    numpy   2.0.0
    cython (built with) 3.0.10
    numpy (built against) 2.0.0
    HDF5 (built against) 1.14.4

**Comment by neutrinoceros** [comment]
Can you provide a minimal reproducer as well as the complete exception traceback ?

**Comment by ZedThree** [comment]
Could this be related to https://github.com/Unidata/netcdf4-python/issues/1343 ?

We're seeing issues when using `h5py>=3.10.0` and `netCDF4>=1.7.1` together. Here's an MVCE:

```python
import netCDF4 as nc
import h5netcdf.legacyapi as h5

import h5py
print(f"h5py hdf5 version: {h5py.h5.get_libversion()}")
print(f"netcdf4 hdf5 version: {nc.__hdf5libversion__}")
print()

with h5.Dataset('mydata.nc', 'w') as ds:
    ds.createDimension('x', 5)
```

gives:

```
h5py version: 3.11.0 using hdf5 version: (1, 14, 2)
netcdf4 version: 1.7.1.post1 using hdf5 version: 1.14.2

Traceback (most recent call last):
  File "mvce.py", line 9, in <module>
    ds.createDimension('x', 5)
  File ".venv/lib64/python3.11/site-packages/h5netcdf/legacyapi.py", line 141, in createDimension
    self._dimensions[name] = size
    ~~~~~~~~~~~~~~~~^^^^^^
  File ".venv/lib64/python3.11/site-packages/h5netcdf/dimensions.py", line 28, in __setitem__
    self._objects[name] = Dimension(self._group, name, size, create_h5ds=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib64/python3.11/site-packages/h5netcdf/dimensions.py", line 89, in __init__
    self._create_scale()
  File ".venv/lib64/python3.11/site-packages/h5netcdf/dimensions.py", line 209, in _create_scale
    if not self._root._h5py.h5ds.is_scale(self._h5ds.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5ds.pyx", line 35, in h5py.h5ds.is_scale
  File "h5py/defs.pyx", line 4505, in h5py.defs.H5DSis_scale
RuntimeError: Unspecified error in H5DSis_scale (return value <0)
```

Switching the order of the imports and using `nc.Dataset` gives a similar, but less specific HDF5-based error.

Also downgrading `h5py` to 3.9.0 and/or `netCDF4` to 1.6.5 works:

```
h5py version: 3.9.0 using hdf5 version: (1, 12, 2)
netcdf4 version: 1.6.5 using hdf5 version: 1.12.2
```

**Comment by ajelenak** [comment]
@ZedThree Is it possible not to use both netCDF4 and h5netcdf packages together? Shouldn't they provide the same functionality?

**Comment by ajelenak** [comment]
For more information about libhdf5 errors, put `h5py._errors.unsilence_errors()` somewhere early in the [example](https://github.com/h5py/h5py/issues/2453#issuecomment-2223351184) and post the output.

**Comment by ZedThree** [comment]
@ajelenak The use of h5netcdf there was just for simplicity for the MVCE, but it's entirely reasonable to end up using both h5py and netcdf4 in the same application, or using one indirectly via a dependency. In the latter case, the user might not even realise both packages are being used.

Here's perhaps a better example that just uses h5py and netcdf4 and includes `unsilence_errors`:

```python
import netCDF4
import h5py

h5py._errors.unsilence_errors()
print(f"h5py version: {h5py.__version__} using hdf5 version: {h5py.h5.get_libversion()}")
print(f"netcdf4 version: {netCDF4.__version__} using hdf5 version: {netCDF4.__hdf5libversion__}")

with h5py.File("test.h5", "w") as f:
    dset = f.create_dataset("x", (5,), dtype='i')
    f["x"].make_scale()

# with netCDF4.Dataset('test.nc', 'w') as ds:
#     ds.createDimension('x', 5)
```

with output:

```
h5py version: 3.11.0 using hdf5 version: (1, 14, 2)
netcdf4 version: 1.7.1.post1 using hdf5 version: 1.14.2
Traceback (most recent call last):
  File "mvce.py", line 10, in <module>
    f["x"].make_scale()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File ".venv/lib64/python3.11/site-packages/h5py/_hl/dataset.py", line 1133, in make_scale
    h5ds.set_scale(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5ds.pyx", line 27, in h5py.h5ds.set_scale
  File "h5py/defs.pyx", line 4450, in h5py.defs.H5DSset_scale
RuntimeError: Unspecified error in H5DSset_scale (return value <0)
```

Again, reordering the imports or downgrading the packages fixes the issue.

**Comment by rmvanhees** [comment]
@ZedThree I can reproduce your result when I use the same h5py and netCDF4. However, when I install h5py from source the problem is gone. The output of your code is:

> h5py version: 3.11.0 using hdf5 version: (1, 14, 4)
> netcdf4 version: 1.7.1.post1 using hdf5 version: 1.14.2

Maybe because h5py and netcdf4 are using different instances/versions of the hdf5 library?

**Comment by ZedThree** [comment]
@rmvanhees I think it must have something to do with some conflict with the libhdf5.so somehow, but I don't understand what's causing it. 

The built .so's are practically identical except for build-time info in the pypi versions. `auditwheel` (I think) gives the bundled .so's different names and different SONAMES:

```
$ diff <(readelf -d .venv/lib/python3.11/site-packages/netCDF4.libs/libhdf5-*) <(readelf -d .venv/lib/python3.11/site-packages/h5py.libs/libhdf5-*)
9c9
<  0x000000000000000e (SONAME)             Library soname: [libhdf5-7b49ac63.so.310.2.0]
---
>  0x000000000000000e (SONAME)             Library soname: [libhdf5-7f639dcd.so.310.2.0]
```

If you use h5py==3.9.0 and netcdf4==1.6.5, they both use hdf5==1.12.2, and that seems to work fine.

In that case, there are also more differences (e.g. for netcdf4 1.6.5, hdf5 is also linked against pthread), but I would've thought that would cause more of a problem!

Are you able to also build netcdf4 from source with hdf5 1.14.4 and see if there's still an issue there? It's not clear if it's an issue with the built wheels on pypi, or just something to do with hdf5 1.14.2 (somehow?!)

**Comment by rmvanhees** [comment]
@ZedThree When I install netcdf4-python from source with hdf5 1.14.4, then your code runs fine.

> h5py version: 3.11.0 using hdf5 version: (1, 14, 4)
> netcdf4 version: 1.7.1.post1 using hdf5 version: 1.14.4

However, your script also runs fine with the  h5py wheels from pypi and  netcdf4-python from source.

> h5py version: 3.11.0 using hdf5 version: (1, 14, 2)
> netcdf4 version: 1.7.1.post1 using hdf5 version: 1.14.4

Thus the issue only occurs when both modules (netcdf4-python and h5py) are build against hdf5 v1.14.2

**Comment by ZedThree** [comment]
@rmvanhees Thanks! Ok, I think that actually leaves two possibilities:

1. it's something specific to hdf5 v1.14.2
2. it's something to do with `cibuildwheels` and/or the wheels of both projects as built on CI

Any chance you could build them both locally, but using hdf5 1.14.2? Because if that fails, then all we need to do is bump hdf5 to 1.14.4 on one/both projects and make a new release.

On the other hand, if still that works, then I think that means it must be something to do with the build process on github actions?
