### ISSUE TITLE
Unlock an HDF5 file that wasn't properly closed?

### ISSUE THREAD

**Issue by doronbehar** [h5py/h5py#2539]
* Operating System: NixOS
 * Python version: 3.12
 * Where Python was acquired: NixOS distribution
 * h5py version: 3.12.1
 * HDF5 version: 1.14.5

In my project, I create `.h5` files in 1 script and read them in another. Sometimes, there's a bug in the script that reads them and it crashes and the open `.h5` files are not properly closed afterwards. My script that reads the files is closing them properly if it doesn't crash, but if it does crash, I guess it doesn't close them properly?

Anyway, now I want to perform a very small edit to some of these files, with `h5py.File(..., mode="r+")`, and I get this error:

```
Traceback (most recent call last):
  File "<path>", line 34, in <module>
    with h5py.File(args.h5file[0], mode="r+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/13nc6hmlrj6zf6dpy49crpkwlvcjlg39-python3-3.12.7-env/lib/python3.12/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/13nc6hmlrj6zf6dpy49crpkwlvcjlg39-python3-3.12.7-env/lib/python3.12/site-packages/h5py/_hl/files.py", line 237, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file is already open for read-only)
```

I checked with `lsof` and it is not opened according to the OS. Is there any way to unlock these files? Or do I have no choice but to copy each group in there to a different file, close the new file properly, and then run my small modification script on the new files?

**Comment by doronbehar** [comment]
Oh found the mistake! It was due to an `xarray.open_dataset()` call that retained references to the read only open file... Sorry for the noise.
