### ISSUE TITLE
Improve error message when using unsupported slicing objects

### ISSUE THREAD

**Issue by evertrol** [h5py/h5py#431]
I've come across seemingly inconsistent behaviour when slicing a one dimensional dataset, with a list or a numpy array (note: not a boolean array). The following piece of code shows:

``` python
import h5py
import numpy as np

data = np.arange(50)
with h5py.File('test.h5', 'w') as h5file:
    dataset = h5file.create_dataset('data', data=data)

    subsection = h5file['data'][[1,2,3]]
    np.testing.assert_array_equal(subsection, [1,2,3])

    subsection = h5file['data'][np.array([1,2,3]).tolist()]
    np.testing.assert_array_equal(subsection, [1,2,3])

    subsection = h5file['data'][np.array([1,2,3]),...]
    np.testing.assert_array_equal(subsection, [1,2,3])

    subsection = h5file['data'][np.array([1,2,3])]
```

The first three slices all work fine (though I'm a bit surprised by the third one, which appears to use a two-dimensional slice on a one dimensional dataset); the last one, however, raises a TypeError:

```
Traceback (most recent call last):
  File "h5pydatasetslice.py", line 13, in <module>
    subsection = h5file['data'][np.array([1,2,3])]
  File "/sw/lib/python3.3/site-packages/h5py-2.4.0a0-py3.3-linux-x86_64.egg/h5py/_hl/dataset.py", line 425, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/sw/lib/python3.3/site-packages/h5py-2.4.0a0-py3.3-linux-x86_64.egg/h5py/_hl/selections.py", line 71, in select
    sel[arg]
  File "/sw/lib/python3.3/site-packages/h5py-2.4.0a0-py3.3-linux-x86_64.egg/h5py/_hl/selections.py", line 209, in __getitem__
    raise TypeError("PointSelection __getitem__ only works with bool arrays")
TypeError: PointSelection __getitem__ only works with bool arrays
```

I'm not sure if this is intended. A quick look in `selection.py` does show a check that will raise this exception if the slice is not a boolean numpy array. But then I don't understand why a list can be used, or a two-dimensional slice. 
Even if it's intended, it does feel inconsistent (and as the second and third slicing example show, there are work-arounds).

**Comment by johncsnyder** [comment]
how about this simple change to handle the last case above:

at line 70 in `h5py/_hl/selections.py`, the following block:
```
elif isinstance(arg, np.ndarray):
    sel = FancySelection(shape)
    sel[arg]
    return see
```
becomes
```
elif isinstance(arg, np.ndarray) and arg.dtype.kind == 'b':
    sel = PointSelection(shape)
    sel[arg]
    return sel

elif isinstance(arg, np.ndarray):
    sel = FancySelection(shape)
    sel[arg]
    return see
```

I'm not sure if this would have unintended consequences elsewhere...

A separate issue: the indices still have to be sorted (e.g. does not allow [1,3,2]). What's the reason for this?

**Comment by jakirkham** [comment]
So I'm confused why a NumPy array would not work here. Especially given a list does. Is there a particular reason for barring it?

**Comment by jakirkham** [comment]
Interestingly, one can get around this error message in some cases and run into other issues. In particular, one can get issue ( https://github.com/h5py/h5py/issues/584 ). Please see the code below for an example.

```python
In [1]: import numpy

In [2]: import h5py

In [3]: with h5py.File("file.h5", "w") as f:
   ...:     f["data"] = numpy.arange(12.0).reshape(3,4)
   ...:     

In [4]: with h5py.File("file.h5") as f:
   ...:     print(f["data"][[1, 2]])
   ...:     
[[  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]

In [5]: with h5py.File("file.h5") as f:
   ...:     print(f["data"][numpy.array([1, 2])])
   ...:     
   ...:     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-5acd1b14e2d4> in <module>()
      1 with h5py.File("file.h5") as f:
----> 2     print(f["data"][numpy.array([1, 2])])
      3 
      4 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/work/h5py-2.6.0/h5py/_objects.c:2696)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/work/h5py-2.6.0/h5py/_objects.c:2654)()

/zopt/conda2/envs/nanshenv/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in __getitem__(self, args)
    460 
    461         # Perform the dataspace selection.
--> 462         selection = sel.select(self.shape, args, dsid=self.id)
    463 
    464         if selection.nselect == 0:

/zopt/conda2/envs/nanshenv/lib/python2.7/site-packages/h5py/_hl/selections.pyc in select(shape, args, dsid)
     70         elif isinstance(arg, np.ndarray):
     71             sel = PointSelection(shape)
---> 72             sel[arg]
     73             return sel
     74 

/zopt/conda2/envs/nanshenv/lib/python2.7/site-packages/h5py/_hl/selections.pyc in __getitem__(self, arg)
    208         """ Perform point-wise selection from a NumPy boolean array """
    209         if not (isinstance(arg, np.ndarray) and arg.dtype.kind == 'b'):
--> 210             raise TypeError("PointSelection __getitem__ only works with bool arrays")
    211         if not arg.shape == self.shape:
    212             raise TypeError("Boolean indexing array has incompatible shape")

TypeError: PointSelection __getitem__ only works with bool arrays

In [6]: with h5py.File("file.h5") as f:
   ...:     print(f["data"][([1, 2], slice(None))])
   ...:     
[[  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]

In [7]: with h5py.File("file.h5") as f:
   ...:     print(f["data"][([1, 2], slice(None))])
   ...:     
[[  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
```

**Comment by takluyver** [comment]
This limitation has been lifted in PR #963.
