### ISSUE TITLE
Possible vlen issue with float32/float64

### ISSUE THREAD

**Issue by andrewcollette** [h5py/h5py#433]
From the list (original thread: https://groups.google.com/forum/#!topic/h5py/dllnsNWRA-I):

```
import h5py
import numpy as np

f = h5py.File('test.h5', 'w')
dt = h5py.special_dtype(vlen=np.
dtype('float64'))
dset = f.create_dataset('vlen_float', (100,), dtype=dt)
dset[0] = [1.0,2.1,3.5]
dset[1] = [1,2,3,4, 5.0, 4.0]
f.close()
--8<---->8--

produces:

Traceback (most recent call last):
File "testvlenfloat.py", line 7, in <module>
dset[0] = [1.0,2.1,3.5]
File "/usr/local/lib/python2.7/dist-packages/h5py/hl/dataset.py", line 578, in __setitem_
self.id.write(mspace, fspace, val, mtype)
File "h5d.pyx", line 219, in h5py.h5d.DatasetID.write (h5py/h5d.c:2936)
File "_proxy.pyx", line 163, in h5py._proxy.dset_rw (h5py/_proxy.c:1834)
File "defs.pyx", line 2622, in h5py.defs.H5Tconvert (h5py/defs.c:56587)
File "defs.pyx", line 2623, in h5py.defs.H5Tconvert (h5py/defs.c:56484)
File "_conv.pyx", line 708, in h5py._conv.ndarray2vlen (h5py/_conv.c:5451)
AttributeError: 'float' object has no attribute 'dtype'
```

@tecki, any thoughts on what might be causing this?

**Comment by parkin** [comment]
After some digging, I found the problem in this [line](https://github.com/h5py/h5py/blob/62e0311e688a12f76668febf4fbb2f6c7d4ed606/h5py/_hl/dataset.py#L482) in `dataset.py`.

```python
if vlen not in (bytes, six.text_type, None):
  # If we have vlen array, convert val to numpy array
  ...
```

However, for some reason (which I haven't looked into yet) the following is true

```python
import numpy
numpy.dtype('float32') == None # False
numpy.dtype('float64') == None # True

numpy.dtype('float32') is None # False
numpy.dtype('float64') is None # False
```

So this means that for `vlen = numpy.dtype('float64')` the process of converting `val` to a numpy array is skipped.

I'll send in a pull request with some tests shortly.

**Comment by parkin** [comment]
Here's the [numpy issue](https://github.com/numpy/numpy/issues/2190).
