### ISSUE TITLE
pip install fails on Cython dependency

### ISSUE THREAD

**Issue by martijnvermaat** [h5py/h5py#535]
This is on Debian wheezy.

For some reason, the Cython dependency doesn't work as it should. I see that there has been quite some refactoring in `setup.py` and Cython is listed in both `requires` and `install_requires`, so I really don't know why that doesn't work.

As you can see, pip correctly fetches h5py, numpy and Cython and then proceeds to install them in that order.

```
martijn@hue:~$ virtualenv /tmp/h5py
New python executable in /tmp/h5py/bin/python
Installing setuptools, pip...done.
martijn@hue:~$ /tmp/h5py/bin/pip install h5py
Downloading/unpacking h5py
  Downloading h5py-2.4.0.tar.gz (172kB): 172kB downloaded
  Running setup.py (path:/tmp/h5py/build/h5py/setup.py) egg_info for package h5py
    
    warning: no previously-included files found matching 'h5py/defs.pyx'
    warning: no previously-included files found matching 'h5py/defs.pxd'
    warning: no previously-included files found matching 'h5py/config.pxi'
Downloading/unpacking numpy>=1.6.1 (from h5py)
  Downloading numpy-1.9.1.tar.gz (4.0MB): 4.0MB downloaded
  Running setup.py (path:/tmp/h5py/build/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking Cython>=0.17 (from h5py)
  Downloading Cython-0.21.2.tar.gz (1.5MB): 1.5MB downloaded
  Running setup.py (path:/tmp/h5py/build/Cython/setup.py) egg_info for package Cython
    Compiling module Cython.Plex.Scanners ...
    Compiling module Cython.Plex.Actions ...
    Compiling module Cython.Compiler.Lexicon ...
    Compiling module Cython.Compiler.Scanning ...
    Compiling module Cython.Compiler.Parsing ...
    Compiling module Cython.Compiler.Visitor ...
    Compiling module Cython.Compiler.FlowControl ...
    Compiling module Cython.Compiler.Code ...
    Compiling module Cython.Runtime.refnanny ...
    Compiling module Cython.Tempita._tempita ...
    
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
Installing collected packages: h5py, numpy, Cython
  Running setup.py install for h5py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/h5py/build/h5py/setup.py", line 147, in <module>
        cmdclass = CMDCLASS,
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 61, in run
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setup_build.py", line 99, in run
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
    Complete output from command /tmp/h5py/bin/python -c "import setuptools, tokenize;__file__='/tmp/h5py/build/h5py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nyKOEl-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/h5py/include/site/python2.7:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/h5py

copying h5py/version.py -> build/lib.linux-x86_64-2.7/h5py

copying h5py/__init__.py -> build/lib.linux-x86_64-2.7/h5py

copying h5py/highlevel.py -> build/lib.linux-x86_64-2.7/h5py

copying h5py/ipy_completer.py -> build/lib.linux-x86_64-2.7/h5py

creating build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/base.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/dims.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/group.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/files.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/selections.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-2.7/h5py/_hl

copying h5py/_hl/filters.py -> build/lib.linux-x86_64-2.7/h5py/_hl

creating build/lib.linux-x86_64-2.7/h5py/tests

copying h5py/tests/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests

copying h5py/tests/common.py -> build/lib.linux-x86_64-2.7/h5py/tests

creating build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_dataset.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_h5.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_slicing.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_dimension_scales.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_selections.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_attrs.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_h5p.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_h5t.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_group.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_file.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_h5f.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/common.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_objects.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_datatype.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_base.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

copying h5py/tests/old/test_attrs_data.py -> build/lib.linux-x86_64-2.7/h5py/tests/old

creating build/lib.linux-x86_64-2.7/h5py/tests/hl

copying h5py/tests/hl/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl

copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl

copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl

copying h5py/tests/hl/test_file.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl

running build_ext

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/h5py/build/h5py/setup.py", line 147, in <module>

    cmdclass = CMDCLASS,

  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 61, in run

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "setup_build.py", line 99, in run

    from Cython.Build import cythonize

ImportError: No module named Cython.Build

----------------------------------------
Cleaning up...
Command /tmp/h5py/bin/python -c "import setuptools, tokenize;__file__='/tmp/h5py/build/h5py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nyKOEl-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/h5py/include/site/python2.7 failed with error code 1 in /tmp/h5py/build/h5py
Storing debug log for failure in /home/martijn/.pip/pip.log
martijn@hue:~$
```

**Comment by taion** [comment]
:+1:

Looks like pip is being a bit stupid here. If you try to install both `Cython` and `h5py` simultaneously from e.g. a `requirements.txt` file, `Cython` will not be available for building `h5py`, and `h5py` will fail to install.

**Comment by taion** [comment]
This is some ridiculous pip bug. In a clean virtualenv, if I do:

`pip install --no-use-wheel --no-cache-dir h5py`

pip does the right thing and installs Cython first. However, if I do:

`pip install --no-use-wheel --no-cache-dir Cython h5py`

then pip does the wrong thing and tries to build h5py before installing Cython.

**Comment by taion** [comment]
I filed an issue on the pip repo regarding subrequirement ordering: https://github.com/pypa/pip/issues/2478

**Comment by jluttine** [comment]
Is there any workaround for this? I have a package which requires, for instance, h5py and numpy. But "pip install mypackage" fails on h5py installation because "no module named numpy". I don't understand why numpy isn't installed before h5py. Any ideas what I can do to setup.py of my package to get this working?

**Comment by taion** [comment]
Can you manually install h5py first?

**Comment by jluttine** [comment]
That should work but I don't find that satisfactory. It's complicated for the users if they have to install manually some dependencies. So I really want "pip install mypackage" to work directly.. I thought that's the purpose of pip anyway. Hmm.. Any ideas?
On Mar 13, 2015 5:49 PM, Jimmy Jia <notifications@github.com> wrote:Can you manually install h5py first?

**Comment by taion** [comment]
Well, the change to pip I am proposing would resolve this issue. I have not yet gotten around to writing that code, though. Maybe early next week.

In some sense the "correct" thing to do would be to add `Cython` and `numpy` to `setup_requires` for h5py, but for various reasons that's a very unpleasant fix in practice.

**Comment by andrewcollette** [comment]
I am going to close this, since it seems to be a pip issue and there's no immediate way to fix it from h5py.  Please feel free to speak up if anyone has more info.

**Comment by taion** [comment]
I'm sort of okay with this. I haven't written the pip patch yet because I'm lazy. What h5py is doing is not strictly correct, though. Cython and numpy _should_ be under `setup_requires`, but in practical terms everyone is going to have a better experience if pip installs things in an order that will work better most of the time.

**Comment by skorokithakis** [comment]
I worked around this by:

```
pip install Cython
pip install h5py
```

**Comment by taion** [comment]
This actually just works with newer versions of pip.

**Comment by dalexander** [comment]
what version of pip is needed?

**Comment by taion** [comment]
6.1.0 or higher.

**Comment by pandeytushar** [comment]
Can't Install Cython and scipy
In both of the installation process, the terminal hangs after message: Running setup.py bdist_wheel for Cython... /
and similar for scipy.
Tried everything in the comment section here and from stackoverflow as well. Still the problem persists!!
Need instant help.

**Comment by tacaswell** [comment]
try `pip install Cython -vv`

**Comment by pandeytushar** [comment]
@tacaswell that worked thanks. 
But a similar code for scipy is not working.  Please help.

**Comment by msiraj83** [comment]
@skorokithakis ....thanks ... it work for me...

**Comment by parulm** [comment]
If someone is having this issue even after trying all above suggestions, it may be because of difference in pip and python versions. 
If you are running python2, try:
pip2 install Cython
pip2 install h5py
For python3, use pip3.

**Comment by ido-ran** [comment]
Thank you @parulm, using `pip3` to install solved my problem because I'm running `python3`.

**Comment by shizukanaskytree** [comment]
```
sudo apt-get install libhdf5-dev
```

from: https://stackoverflow.com/questions/24744969/installing-h5py-on-an-ubuntu-server

**Comment by afsane-reyhani** [comment]
Hello i want install cython on sage. but error 
Requirement already satisfied: cython in /opt/sagemath-8.9/local/lib/python2.7ite-packages (0.29.12)
please  help me .

**Comment by kif** [comment]
h5py no more supports Python2. 
It is specified at the setup.py "Python >=3.6"

**Comment by afsane-reyhani** [comment]
> h5py no more supports Python2.
> It is specified at the setup.py "Python >=3.6"

The problem was solved by putting %%cython in each cell in Python 2.7 of the Sage version 8.9, but the new problem is that in one cell it used both def and cdef. Can you help me solve it please.

**Comment by afsane-reyhani** [comment]
> h5py no more supports Python2.
> It is specified at the setup.py "Python >=3.6"

The problem was solved by putting %%cython in each cell in Python 2.7 of the Sage version 8.9, but the new problem is that in one cell it used both def and cdef. Can you help me solve it please.

**Comment by tacaswell** [comment]
@afsane-reyhani That is a question that should go to the sage mailing list / issue tracker.  Good luck!

**Comment by afsane-reyhani** [comment]
> @afsane-reyhani That is a question that should go to the sage mailing list / issue tracker. Good luck!

ok. thank you
