### ISSUE TITLE
File handles remain open after File object is collected

### ISSUE THREAD

**Issue by campagnola** [h5py/h5py#549]
I am using h5py 2.2.1 on ubuntu 14.04. It appears that file handles remain open even after the File object has been deleted:

    >>> import h5py
    >>> f = h5py.File('envelope.ma', 'r')
    >>> del f
    >>> f = h5py.File('envelope.ma', 'r+')
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 207, in __init__
        fid = make_fid(name, mode, userblock_size, fapl)
    File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 81, in make_fid
        fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
    File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:1806)
    IOError: unable to open file (File accessibilty: Unable to open file)

..and I can verify at this point that the handle is still open using `lsof`.

**Comment by andrewcollette** [comment]
This should be fixed under h5py 2.4.  Let us know if you continue to have problems!

**Comment by campagnola** [comment]
Thanks! I did a quick search for this bug; apologies if I missed an existing issue.
