### ISSUE TITLE
ValueError when saving empty list  as attribute

### ISSUE THREAD

**Issue by paugier** [h5py/h5py#559]
```python
import h5py

with h5py.File('test.h5', 'w') as f:
    f.attrs.create('empty_list', [])
```

works fine under Debian wheezy for which
```
In [2]: print(h5py.version.info)
Summary of the h5py configuration
---------------------------------

h5py    2.4.0
HDF5    1.8.8
Python  2.7.8 (default, Feb 27 2015, 13:51:39) 
[GCC 4.7.2]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.9.1
```

but raises the error:
```
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)
```

under Debian squeeze for which
```
In [2]: print(h5py.version.info)
Summary of the h5py configuration
---------------------------------

h5py    2.4.0
HDF5    1.8.4
Python  2.7.8 (default, Jan 18 2015, 09:41:02) 
[GCC 4.4.5]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.9.1
```

**Full traceback:**

```
Traceback (most recent call last):
  File "test_h5py.py", line 5, in <module>
    f.attrs.create('empty_list', [])
  File "/opt/python/2.7.8/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 120, in create
    space = h5s.create_simple(shape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-qVsNLc/h5py/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-qVsNLc/h5py/h5py/_objects.c:2362)
  File "h5py/h5s.pyx", line 99, in h5py.h5s.create_simple (/tmp/pip-build-qVsNLc/h5py/h5py/h5s.c:1353)
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)
```

**Comment by andrewcollette** [comment]
Yes, versions of HDF5 earlier than 1.8.7 have trouble with zero-sized datasets and attributes.  As a workaround I would suggest upgrading to a newer version of HDF5.
