### ISSUE TITLE
h5py runs out of ids

### ISSUE THREAD

**Issue by gpwright** [h5py/h5py#598]
My issue is illustrated by the test below.  The test fails by throwing an exception within 5 minutes after 16776885 iterations.  My configuration is Ubuntu 14.04 running h5py version 2.5 built against hdf5-1.9.178-swmr_chksum5.

```python
import h5py

i = 0
try:
    with h5py.File("test.h5", "w") as f:
        sid = h5py.h5s.create(h5py.h5s.SCALAR)
        dsid = h5py.h5d.create(f.id, b"test", h5py.h5t.IEEE_F32LE, sid)
        while True:
            dsid.get_type()
            i += 1
finally:
    print(i)
```

**Comment by andrewcollette** [comment]
What's the exception message?  Btw, I would encourage you to also raise this issue on the HDF-Forum list, since identifier exhaustion is supposed to be a fixed problem in 1.9/1.10:

https://lists.hdfgroup.org/mailman/listinfo/hdf-forum_lists.hdfgroup.org

**Comment by gpwright** [comment]
Hi Andrew,

The exception is as follows:

```python
afferalab@AFRA-LAB2:~$ python test.py
16776885
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    dsid.get_type()
  File "_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/afferalab/Sources/h5py/h5py/_objects.c:2508)
  File "_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/afferalab/Sources/h5py/h5py/_objects.c:2461)
  File "h5d.pyx", line 309, in h5py.h5d.DatasetID.get_type (/home/afferalab/Sources/h5py/h5py/h5d.c:4152)
RuntimeError: Unable to register datatype (Can't insert duplicate key)
```

I have been having an email discussion with the hdf5 help desk.  They think that the version 1.9.178 was based on a version that was earlier than when the identifier exhaustion fixes were made.  So they just published a rebased version for me to test, it's available here:

ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/SWMR/src/hdf5-1.9.222-swmr0.tar.gz

However, it seems that whatever changes were made are incompatible with h5py version 2.5.  I rebuilt h5py against the new libs.  The build is successful, but after importing into a python console I get the following errors.  I'm not sure whether this is an hdf5 problem or an h5py problem.  Any thoughts?

```python
In [1]: import h5py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-e81388eeaef8> in <module>()
----> 1 import h5py

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/__init__.py in <module>()
     29 h5z._register_lzf()
     30
---> 31 from .highlevel import *
     32
     33 from .h5 import get_config

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/highlevel.py in <module>()
     11
     12 from ._hl import filters
---> 13 from ._hl.base import is_hdf5, HLObject
     14 from ._hl.files import File
     15 from ._hl.group import Group, SoftLink, ExternalLink, HardLink

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/base.py in <module>()
     76     return lcpl
     77
---> 78 dlapl = default_lapl()
     79 dlcpl = default_lcpl()
     80

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/base.py in default_lapl()
     63 def default_lapl():
     64     """ Default link access property list """
---> 65     lapl = h5p.create(h5p.LINK_ACCESS)
     66     fapl = h5p.create(h5p.FILE_ACCESS)
     67     fapl.set_fclose_degree(h5f.CLOSE_STRONG)

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_objects.so in h5py._objects.with_phil.wrapper (/home/afferalab/Sources/h5py/h5py/_objects.c:2508)()

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_objects.so in h5py._objects.with_phil.wrapper (/home/afferalab/Sources/h5py/h5py/_objects.c:2461)()

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/h5p.so in h5py.h5p.create (/home/afferalab/Sources/h5py/h5py/h5p.c:2548)()

/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/h5p.so in h5py.h5p.propwrap (/home/afferalab/Sources/h5py/h5py/h5p.c:2348)()

ValueError: Not a property list class (Not a property list class)
```

**Comment by gpwright** [comment]
Update: it seems that the second issue was resolved in a changeset yesterday in the latest version of h5py.

https://github.com/h5py/h5py/pull/597

So the original issue about identifiers is specific to version 1.9.178 of hdf5.  Updating to version 1.9.222 resolved that.  Closing the issue.
