### ISSUE TITLE
Support for blosc family of compressors

### ISSUE THREAD

**Issue by aldanor** [h5py/h5py#611]
Blosc is one of the fastest (de)compressors out there and supports SIMD shuffling, wonder if the licensing would permit to bring the support for it into h5py? (I believe it's BSD)

It's fairly simple, in fact -- I have a prototype that works and I could probably make a PR if we decide to go ahead.

As an added benefit, h5py (and tools based on it) would be able to read all files saved with pytables which is a big win on its own.

@andrewcollette Thoughts?

**Comment by aldanor** [comment]
Edit: using blosc is already possible because it's just another HDF5 filter but require quite a bit of manual work, building and linking everything properly, and `compression` / `compression_opts` look a bit ugly: e.g., it would be nicer to be able to write

```python
create_dataset(compression='blosc:lz4', complevel=1, shuffle=True)
```

than

```python
register_blosc()
create_dataset(compression=32001, compression_opts=(0, 0, 0, 0, 9, 1, 1), shuffle=False)

**Comment by andrewcollette** [comment]
@aldanor, the main challenge with integrating new compressors is the work required on the Cython/C side, including maintenance and deployment issues with new dependencies.

I think a permanent solution here might be to leverage the new HDF5 loadable-filter approach.  That way the Blosc people could provide a stand-alone filter module that would work with any installation of HDF5, not just in Python.  Changes on the h5py side would then be limited to a small amount of Python code to make it more convenient to use well-known filters; for example, h5py would know that "blosc" meant "filter code 32001", and could perform some basic validation of the options.

**Comment by aldanor** [comment]
@andrewcollette I've no idea how much it would be to maintain for Windows, but I have redistributable conda recipes and a little Cython package that makes h5py be aware of all things blosc, works fine on Linux and OSX. Same as you have the source code for lzf and compile it on the go, you need to compile blosc_filter which needs to compile blosc which needs to compile lz4/snappy/zlib; all the sources are provided internally by blosc.

The loadable-filter approach from HDF5: not always feasible and not as good as it seems. It always looks for the plugins in `/usr/local/hdf5` which is not an option in any shared server or corporate environment, or it pulls it from an environment variable -- which, again, is ugly because it doesn't play well with virtual environments or conda environments. There is no way of tying a plugin to a Python environment.

Aside from h5py knowing about code 32001, there's other things like being aware that blosc implements its own SIMD shuffle so the defalt HDF5 shuffle filter has to be switched off, and a few other things..

**Comment by andrewcollette** [comment]
@aldanor, I'm wary of bundling another filter with h5py, LZF-style.  Downstream Linux distributors already patch h5py to use the system LZF, and it's likely that trying a similar approach with Blosc will cause more headaches there.  And the Blosc developers are in a better position to maintain/improve their code if they're not anchored to dependent projects.

FWIW, the HDF5 loadable-filter system was designed specifically to handle this kind of situation.  Interested parties could distribute Blosc (or other filters) along with HDF5, rather than along with h5py or Pytables or other middleware.  IOW, such filters are not supposed to be tied to a particular Python environment, but deployed along with HDF5.  The great thing is that they would be usable by any client of the HDF5 library, including things like HDFView or other environments like R.

There is evidently already such a loadable filter in the Blosc source repository, although it's not clear to me right now if anyone from the Blosc project has undertaken to distribute binaries to end users (which to be fair is challenging).  @FrancescAlted might know.  It's linked from this discussion:

https://github.com/timholy/HDF5.jl/issues/254

**Comment by aldanor** [comment]
@andrewcollette Thanks for detailed response, yes, I totally see your point. 

I'd just like to outline a few other ones:
- there's only two major players HDF5-wise in Python: h5py and pytables
- there's not much else compressor-wise aside from what h5py + pytables offers
- blosc compressors *are* the fastest ones out there at this point; there is no better publicly available option that I'm aware of
- often times, people only use pytables and tolerate it's api solely because of compression options
- tools/guis based on h5py don't understand files compressed by pytables as if it's two completely different formats
- I would go as far as assume that most h5py users would just install it and use whatever's there (be it a conda install or a manual build), noone would really bother trying to compile pieces of blosc and scavange through both h5py/blosc source code to find out how to piece things together (which is what you *have* to do atm) to make it work
- the HDF5 loadable plugin system works well for deploying applications; especially system-wide. This doesn't hold true re: development, especially if you work with multiple hdf5 versions and maintain virtual environments -- e.g., because the plugin location is predefined globally or by a global environment variable

Back to the point though, even if we assume h5py would never ship with blosc filters pre-built, can we at least make it understand the config for them? (that would only concern `_hl.filters` and `compression` property of datasets; a fairly trivial change all in all)

**Comment by FrancescAlted** [comment]
Yes, as Blosc was originally meant for PyTables, and in order to bootstrap the process, what we traditionally did is to put the Blosc sources in the PyTables sources (via git subtree I think) so as to avoid having C-Blosc libraries installed in the system (although detection of the library is supported too).

And no, we are not distributing a binary version of Blosc (we let that to package managers which probably do a much better work than us).

**Comment by andrewcollette** [comment]
@aldanor, I think everyone's on the same page that Blosc would be valuable to use from h5py.  In fact, with the upcoming h5py/PyTables merger I think this is the right time to start talking about how to handle it.  The only question is whether there is a realistic alternative to distributing the Blosc filter as part of h5py, for example as a separate Python project or as a generic HDF5 plugin.

@FrancescAlted, any thoughts for the combined project?  Also pinging @avalentino and @scopatz.

**Comment by aldanor** [comment]
@andrewcollette There's now a separate repo: https://github.com/Blosc/hdf5 -- but I doubt the average user would go into trouble of writing C/Cython bindings to glue things together; there would have to be a Python project on PyPI / in conda that's easy to install and just makes things work.

**Comment by FrancescAlted** [comment]
Exactly, I think Blosc/hdf5 is the right place to develop a generic filter to HDF5 (in fact, this was my intent).  If you need to tailor something, PR there are welcome.  Also, tell me if you want to become developers of the repo and I will give you the proper rights.

**Comment by aldanor** [comment]
@FrancescAlted I'd be interested -- could try to port the Cython part of my h5py/blosc bridge back to Blosc/hdf5. Assuming it provides an HDF5 filter that can be registered from within Python (register_blosc), and some generic parameter conversion methods, PyTables could then also use that as a dependency?

@andrewcollette As for h5py, it could try importing this package and if it succeeds it would register blosc filter and know how to convert parameters and all. Something like that?

**Comment by aldanor** [comment]
Also pinging @asmeurer to see if he has any inputs distribution-wise

**Comment by FrancescAlted** [comment]
@aldanor Yes, I think that would a good first step.  You can check that you are not breaking things for PyTables by just dropping the new version of the driver in https://github.com/PyTables/PyTables/tree/develop/c-blosc/hdf5 directory and recompiling.  Could you please send a PR on this? Also, I suppose it is clear, but as this is meant to work as generic HDF5 filter, Cython should be out of the game.

Thanks!

**Comment by asmeurer** [comment]
Sorry, any specific questions? 

Regarding looking in /usr/local/hdf5, it would be better to look in $PREFIX/hdf5, where $PREFIX is the prefix where it is installed.

**Comment by aldanor** [comment]
Yea, but /usr/local/hdf5 is hardcoded in HDF5, so unless you set a certain environment variable it's not going to work. That's why I was trying to say initially the whole HDF5 plugin idea doesn't play well with Python virtual environments / conda environments.

**Comment by asmeurer** [comment]
So upstream hdf5 needs to be fixed.

**Comment by FrancescAlted** [comment]
+1 hardcoded paths are something that is difficult to workaround.  Meanwhile, as c-blosc is getting through Linux distributions, one can setup some kind of library discovery in h5py.  Main problem is Windows platforms, but the conda team might want to cover this too by providing a c-blosc library package.  Not perfect, but could be an interim solution until HDF5 folks make the pluggable filters approach better.

**Comment by jreadey** [comment]
@aldanor - I'm not sure I follow your comment.  If you create an environment variable in a shell it will be local to that shell context, so you'd be ok for development work.  For virtual environments, isn't there a way to specify environment variables for a particular env?  E.g. Conda updates my path when I do a 'source activate'.

**Comment by aldanor** [comment]
@jreadey no, there's no way to specify environment variables for virtualenvs / conda envs, that's the whole point; which implies HDF5 won't be able to pick up an env-local version of the plugin.

**Comment by tacaswell** [comment]
@aldanor You can force conda to set envs (actually run any script you want) on activating an environment, but Ilan and @asmeurer  are both not fans of it.  The issue is that there are use-cases where you may not want to / can not actually activate the environment (and practically, the testing during a conda build).

The most reliable way I have found to deal with this sort of thing is to make full use of conda's on-installation hard-coded-path re-writing.

**Comment by andreabedini** [comment]
> So upstream hdf5 needs to be fixed.

:+1: \<rant\> I don't understand this thing we that we need to fix everything at python level \</rant\>

**Comment by epourmal** [comment]
Hi Francesc, Andrew, and All,

This is a very good discussion. The HDF Group's participation in it is long overdue :-)

The dynamically loaded filters were created to give HDF5 applications greater flexibility in using custom filters. The feature was designed to allow software like MATLAB (does it already with the 2015a version), h5py, PyTable, IDL, etc. to use custom filters transparently on read and use existing filters mechanism to compress data on write. Of course, this works only if the HDF5 library can find "so" or "DLL" file with the HDF5 filter needed and the corresponding compression library .

As I understand from this discussion, the environment variable and default hard-coded path are not the ideal  solutions for the Python applications. The HDF5 developers will be more than happy to work with you to improve Python users experience with HDF5. 

We have several features in HDF5 (external storage, external links, and dynamically loaded filters ) that would benefit if an application could set a search path. We are already moving in this direction with the external files and would like to extend it to other features. Do you think this will help?

Other observation from the 10K meters view: If h5py and PyTables implement dynamically loaded mechanism, they would rely only on the HDF5 library to do all heavy lifting. H5py and PyTables would only need to provide access to the HDF5 property to set a search path  or to rely on the HDF5 defaults, but there shouldn't be need to built-in the filters as it is done now.

Currently we use the repository https://svn.hdfgroup.uiuc.edu/hdf5_plugins/ for internal testing of the feature. Filters can be built on both Windows (CMake) and UNIX (CMake, autotools). The code still needs some clean-up, but is usable as it is if you would like to try the filters and see how they work (or don't work) with h5py and PyTables. 

The HDF Group developers and the sponsors of the feature entertained an idea of moving HDF5 plugins repository to Git; getting h5py and PyTables developers involved in maintaining the repository and setting guidance for adding, maintaining, and releasing new HDF5 filters that would be registered with The HDF Group ( see https://www.hdfgroup.org/services/contributions.html#filters); providing pre-built filters binaries that HDF5 and HDF5-based software could use. 

Please let me know if you are interested in 
1) an idea of providing a central, maintained repository of the HDF5 filters that would be used by HDF5,  h5py and PyTables, (others TBD , e.g., Pandas)
2) any improvements to the HDF5 library that would provide more flexible access to the HDF5 dynamically loaded filters including the one described above.

Thank you!
Elena

P.S. May be a telecon will be a better way to discuss the topic.

**Comment by untom** [comment]
Hi!
It looks like this issue has gone tale. For me personally BLOSC support is the one big feature missing in h5py. Yes, I am aware that there are some hacks (outlined in this very thread) to make it work, but those are a complete no-go for end-users. Thus I just wanted to ask if any progress has been made on this issue? If not, consider this one end-user's wish to look into it once more. :)

**Comment by estan** [comment]
@aldanor I'm interested in using Blosc from h5py right now, despite it being a bit awkward. I have to ask, when you said it's possible with:

```python
register_blosc()
create_dataset(compression=32001, compression_opts=(0, 0, 0, 0, 9, 1, 1), shuffle=False)
```

Is this with https://github.com/Blosc/hdf5-blosc installed such that HDF5 can find it, and the `register_blosc` is actually a call to the C function? E.g. I have to wrap it for Python first?

**Comment by aldanor** [comment]
@estan I had to write Cython extension that wraps `hdf5-blosc` and exposes registering function and does argument convertion. I believe many are using h5py and blosc in this weird way :) Too sad it won't be properly supported "out of the box" anytime soon, given that blosc compressors are far superior to everything else out there.

**Comment by estan** [comment]
Alright, that makes sense. I'll give it ago first using the "hackish" way of "import tables; import h5py", then I'll see about writing a Cython extension as well if it gives very good result with my data (tomography volumes). Thanks.

**Comment by untom** [comment]
@aldanor would you be willing to make your Cython extension public? I'm sure it would help out a lot of people (like me). Maybe it would even be possible to pack this up for PyPI something :)

**Comment by aldanor** [comment]
@untom I guess I could, if it would be useful to anyone.

(although I'm still of opinion that's something h5py should support natively...)

**Comment by untom** [comment]
I agree completely that that's a much more desirable solution, but it doesn't look like it'll get done any time soon.

**Comment by ViaFerrata** [comment]
For me it's also not working anymore (though it seems to be a different problem?). With Python 2.7.13, latest pytables and h5py:
```
>>> import tables
>>> import h5py
>>> import numpy as np
>>> a = np.zeros(10)
>>> h5f = h5py.File('test.h5', 'w')
>>> dset_hists = h5f.create_dataset('x', data=a, dtype='uint8', compression=32001, shuffle=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hpc/capn/mppi033h/.local/lib/python2.7/site-packages/h5py/_hl/group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/hpc/capn/mppi033h/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 120, in make_new_dset
    shuffle, fletcher32, maxshape, scaleoffset)
  File "/home/hpc/capn/mppi033h/.local/lib/python2.7/site-packages/h5py/_hl/filters.py", line 201, in generate_dcpl
    raise ValueError("Unknown compression filter number: %s" % compression)
ValueError: Unknown compression filter number: 32001
```

**Comment by micfan** [comment]
"but it also comes with support for import/export facilities to/from HDF5/PyTables tables and pandas dataframes."

https://bcolz.readthedocs.io/en/latest/reference.html#bcolz.ctable.ctable.tohdf5, then we don't need add a HDF5 filter. 

However, c-blosc2 is under developing, and it got Google's bonus...

**Comment by aldanor** [comment]
Fast forward year and a half from original discussion...

It's sad there's not much incentive to try and make h5py support blosc natively (which is completely trivial implementation-wise; the main questions really would be re: packaging and licensing). Is there any strong opposition to this? If not, would any help be required? I believe many would gladly volunteer if need be.

For myself, many of my colleagues and a lot of other programmers I know one of the main selling points of modern HDF5 is actually its neat support for blosc (zstd in particular, as of late). On the other hand, h5py is, subjectively, better than pytables at being an HDF5 adapter that supports almost all of the core functionality *as is*. But, you can't have both, unless you build and maintain the filter/plugin/adapter and figure out a way for it to be registered (or, if it's a shared environment where you can't install things globally, you have to register it manually in your code every time; HDF5 plugin discovery mechanism is good in theory but not so good in practice, particularly when HDF5 is most always sandboxed into a virtualenv and it's a shared computing environment).

Building and distributing a separate "h5py-blosc" adapter as a Python package would be a bit of pain, since you would have to link the filter it to a specific version of HDF5 at build time (when building blosc-hdf5), which is outside of distutils scope. It could potentially be done as a conda package, but the cleanest way (and the easiest for downstream users) would probably be just including it into h5py itself, along with compressors, just like pytables does it.

**Comment by aldanor** [comment]
... in the meanwhile, a hint for other poor souls in this thread:

```python
import tables  # <------------
import h5py

# now h5py "supports" blosc for reading

def blosc_opts(complevel=9, complib='blosc:lz4', shuffle=True):
    shuffle = 2 if shuffle == 'bit' else 1 if shuffle else 0
    compressors = ['blosclz', 'lz4', 'lz4hc', 'snappy', 'zlib', 'zstd']
    complib = ['blosc:' + c for c in compressors].index(complib)
    args = {
        'compression': 32001,
        'compression_opts': (0, 0, 0, 0, complevel, shuffle, complib)
    }
    if shuffle:
        args['shuffle'] = False
    return args

# for writing, do something like this
with h5py.File('foo.h5', 'w') as f:
    f.create_dataset('x', data=x, **blosc_opts(9, 'blosc:zstd', True)
```

That's kind of what I've being doing, except for having hdf5-blosc filter wrapped in Cython instead of importing PyTables, and then registering it manually each time.

**Comment by aragilar** [comment]
@aldanor There exists https://github.com/silx-kit/hdf5plugin which is adding other filters. There was also some work to make it easier to register plugins.

**Comment by aldanor** [comment]
> @aldanor There exists https://github.com/silx-kit/hdf5plugin which is adding other filters. There was also some work to make it easier to register plugins.

Thanks, @aragilar, looks like that's +1 workaround to all the existing ones. 

// Functionally though, if all you need is blosc support in h5py, looks like that's no different than just importing pytables before h5py, as in the example above...

**Comment by aldanor** [comment]
There's also a separate question of h5py converting blosc compression parameters automatically, sort of like like `blosc_opts()` above, but natively in `create_dataset()`, so you don't have to write (32001, (0, 0, 0, 0, 9, 2, 5)) etc.

**Comment by ViaFerrata** [comment]
Is there any way to make this workaround work with virtualenvs, like a conda env? I guess it's due to the hardcoded ```/usr/local/hdf5``` path.

**Comment by aldanor** [comment]
@ViaFerrata Yea, HDF5 built-in plug-in discovery mechanism is quite useless. So for now (and quite possibly for ever) you'll have to use one of the hacks described above in this thread.

**Comment by ViaFerrata** [comment]
So the workaround with pytables is supposed to work for virtual environments? 

With a Python 2.7.13 conda env, newest h5py & tables I still get ```ValueError: Unknown compression filter number: 32001``` if I use your workaround (thank you by the way for making it available!).
Like in my previous post here from last year, that's why I was asking.

**Comment by analog-cbarber** [comment]
FWIW, the pytables workaround works for me using a Python 3.6 conda environment and the latest versions of pytables (3.4.3) and h5py (2.8.0). Not sure whether using 2.7 is your problem, but it is time that everyone start to make an effort to move to 3.*. Many projects are already deprecating 2.7.

I agree that anyone interested in compression is highly likely to want the blosc compressors, so any effort to provide relatively painless configuration would be highly valuable. Yes, there is a workaround, but it wastes hours of user time every time someone encounters this issue to discover and implement it.

**Comment by prativadas** [comment]
when i run  
" f = h5py.File(os.path.join(data_path, 'train_16.h5'), 'w', compression='blosc:lz4', compression_opts=9)" 
i got error 
TypeError: 'compression' is an invalid keyword argument for this function
what is the solution

**Comment by prativadas** [comment]
> Just confirming my [previous point](https://github.com/h5py/h5py/issues/611#issuecomment-353715114)... people are confused.
> 
> @prativadas You need to do `compression=32001, compression_opts=(0, 0, 0, 0, 9, 1, 5)`.

still, it doesn't work for me.

**Comment by tacaswell** [comment]
@prativadas Compression is a per-dataset not per-file concept.    You will need to pass those options when you create the dataset instead.

**Comment by prativadas** [comment]
if i remove the compressssion part 

f = h5py.File(os.path.join(data_path, 'train_16.h5'), 'w'), then following error comes

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.create()

IOError: Unable to create file (unable to truncate a file which is already open)

**Comment by vasole** [comment]
I'm working on adding the blosc family to hdf5plugin. Can anybody point me to a file using that compression? I have tested it using the example code (example.c) supplied with the plugin sources, but since it is tested and generated on the same machine I'm not 100% confident about getting it right.

**Comment by tacaswell** [comment]
@vasole Can you be a bit more specific about what you are doing?

**Comment by vasole** [comment]
Nothing interfering with h5py. As you can read above in this thread, I prepared long ago a module (hdf5plugin) allowing a user desiring to use HDF5 plugins to have access to them just by importing that module prior to import h5py. I just needed it for myself, put I preferred to give people the opportunity to profit from it.

It has turned out to be helpful to quite a bit of people.

What I am doing now is to try to add the blosc plugin to the list.

**Comment by chanshing** [comment]
> ... in the meanwhile, a hint for other poor souls in this thread (or rather a dirty hack, but the simplest to get it working really without building anything yourself). I've already mentioned it above, but here's a full example:
> 
> ```python
> # conda install h5py pytables
> 
> __import__('tables')  # <-- import PyTables; __import__ so that linters don't complain
> import h5py
> 
> # now h5py "supports" blosc
> 
> def blosc_opts(complevel=9, complib='blosc:lz4', shuffle=True):
>     shuffle = 2 if shuffle == 'bit' else 1 if shuffle else 0
>     compressors = ['blosclz', 'lz4', 'lz4hc', 'snappy', 'zlib', 'zstd']
>     complib = ['blosc:' + c for c in compressors].index(complib)
>     args = {
>         'compression': 32001,
>         'compression_opts': (0, 0, 0, 0, complevel, shuffle, complib)
>     }
>     if shuffle:
>         args['shuffle'] = False
>     return args
> 
> # for writing, do something like this
> 
> with h5py.File('foo.h5', 'w') as f:
>     f.create_dataset('x', data=x, **blosc_opts(9, 'blosc:zstd', True)
> ```
> 
> That's kind of what I've being doing, except for having hdf5-blosc filter wrapped in Cython instead of importing PyTables, and then registering it manually each time; but the idea is the same.

Thanks for the code. Would you mind explaining what are the options `(0,0,0,0,9,1,5)` etc.? Seems it is not documented anywhere. Thanks to your code I now understand the last three. Also, what are the default values in `h5py` for blosc (32001)?

**Comment by aldanor** [comment]
@chanshing The other values are unused, iirc. There are no default values as h5py is unaware of blosc.

Which reminds me of - do h5py maintainers still think blosc is not worth integrating? Would anyone in their sane mind use anything except blosc zstd/lz4 for hdf5 compression these days, especially when it comes to large amounts of network-stored data? All other compression options are so hilariously inferior it continues to baffle me why don’t we join efforts and make it available for everyone (we have been using h5py for the last 3-4 years, converted and used dozens of terabytes of data without a single problem - it’s just the inconvenience of not having it built-in, illustrated by comments in this thread and external links to it).

**Comment by chanshing** [comment]
@aldanor Thank you. I have tried blosc in h5py and it still worked without passing `compression_opts`, i.e. `f.create_dataset('x', data=x, compression=32001)`. It compressed my data by about a half. Now I am trying to recreate the result by explicitly passing `compression_opts`, but still haven't found the magical combination that yields the "default".

**Comment by aldanor** [comment]
@chanshing I think it’s something like blosclz with complevel 5 and shuffle on, but I may be wrong.

**Comment by chanshing** [comment]
> @chanshing I think it’s something like blosclz with complevel 5 and shuffle on, but I may be wrong.

I can now confirm that the "default" is `blosclz` level 9 with shuffle, `(0,0,0,0,9,1,0)`. It is the same default as http://python-blosc.blosc.org/reference.html#blosc.compress_ptr

**Comment by chanshing** [comment]
> @chanshing I think it’s something like blosclz with complevel 5 and shuffle on, but I may be wrong.

Yes, I can confirm that this seems to be the "default" option, i.e. `(0,0,0,0,5,1,0)`.

**Comment by CaptainDuke** [comment]
> For me it's also not working anymore (though it seems to be a different problem?). With Python 2.7.13, latest pytables and h5py:
> 
> ```
> >>> import tables
> >>> import h5py
> >>> import numpy as np
> >>> a = np.zeros(10)
> >>> h5f = h5py.File('test.h5', 'w')
> >>> dset_hists = h5f.create_dataset('x', data=a, dtype='uint8', compression=32001, shuffle=False)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/hpc/capn/mppi033h/.local/lib/python2.7/site-packages/h5py/_hl/group.py", line 106, in create_dataset
>     dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
>   File "/home/hpc/capn/mppi033h/.local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 120, in make_new_dset
>     shuffle, fletcher32, maxshape, scaleoffset)
>   File "/home/hpc/capn/mppi033h/.local/lib/python2.7/site-packages/h5py/_hl/filters.py", line 201, in generate_dcpl
>     raise ValueError("Unknown compression filter number: %s" % compression)
> ValueError: Unknown compression filter number: 32001
> ```
> 
> I'm using a conda virtualenv though, so regarding the comments above, this may be the issue.

Hi , I met same problem, 32001 not found. Have you fixed it?

**Comment by ViaFerrata** [comment]
> 
> Hi , I met same problem, 32001 not found. Have you fixed it?

Unfortunately not, I'm stil using gzip instead. I think the fix just does not work with a conda env.

**Comment by aldanor** [comment]
@CaptainDuke @ViaFerrata

`conda install pytables`

`__import__('tables')`

**Comment by ViaFerrata** [comment]
@aldanor 
Thank you! I'll try it out when I find some time.

**Comment by aiguofer** [comment]
I'm trying the above mentioned hack on a regular virtualenv and it doesn't seem to be working for reading files. Here's the error I'm getting:

```
import tables
import h5py

with h5py.File('myfile.h5') as f:
    for row in f["p0"]["table"]:
        print(row)
```

This gives me an error about `/usr/local/hdf5/lib/plugin` not existing, and when I create that dir I get:

````
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-bf1592f10eb3> in <module>
----> 1 t()

~/work/hdf5venv/hdf2csv.py in t()
     26 
     27     with h5py.File(get_fname("d403", "pgns")) as f:
---> 28         for row in f["p0"]["table"]:
     29             print(row)
     30 

~/.pyenv/versions/hdf5venv/lib/python3.7/site-packages/h5py/_hl/dataset.py in __iter__(self)
    472             raise TypeError("Can't iterate over a scalar dataset")
    473         for i in xrange(shape[0]):
--> 474             yield self[i]
    475 
    476     @with_phil

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/.pyenv/versions/hdf5venv/lib/python3.7/site-packages/h5py/_hl/dataset.py in __getitem__(self, args)
    571         mspace = h5s.create_simple(mshape)
    572         fspace = selection.id
--> 573         self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
    574 
    575         # Patch up the output for NumPy

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.DatasetID.read()

h5py/_proxy.pyx in h5py._proxy.dset_rw()

h5py/_proxy.pyx in h5py._proxy.H5PY_H5Dread()

OSError: Can't read data (required filter 'blosc' is not registered)
```

I get the same error when using https://github.com/silx-kit/hdf5plugin

Any thoughts?

**Comment by aldanor** [comment]
@aiguofer Can you read it with pytables? Maybe your pytables is missing the blosc filters for whatever reason.

**Comment by aiguofer** [comment]
@aldanor yeah, it works fine in tables... I can easily read it into Pandas using `read_hdf`. The issue is I have large files and would like to convert them to CSVs by iterating over rows because loading it all into mem crashes most machines. It seems that's a lot easier with `h5py` than with `tables`.

**Comment by ViaFerrata** [comment]
@aldanor @aiguofer 
So I also tried it again with 
```
conda install pytables
__import__('tables')
```
, but unfortunately with a venv in Conda it just doesn't recognize the filter number.

**Comment by MaxNoe** [comment]
@aldanor 

The list of compressors you hardcoded there is actually `tables.filters.blosc_copressor_list()`, right?
So just use this and then the import is also not unused.

**Comment by salotz** [comment]
It didn't work for me when I had h5py installed with pip, but it works if you install with conda.

**Comment by t20100** [comment]
We've been refactoring the `hdf5plugin` project (https://github.com/silx-kit/hdf5plugin/) in order to provide blosc, bitshuffle and lz4 HDF5 filters for compression and decompression on Windows, Linux and macOS (all in 64bits).

We are preparing a pre-release, but you are invited to give a try to wheels built from the master available here: https://silx.gitlab-pages.esrf.fr/bob/hdf5plugin/ and provide feedback on the project page: https://github.com/silx-kit/hdf5plugin/.

While it is best to install the filters system-wide whenever possible, this gives a solution that is meant to work in any case.
The plugins are using dynamic loading of the HDF5 library so they are not bound to a single version of the HDF5 library.

**Comment by thomasaarholt** [comment]
We've been (naively) using the trick of `import pytables` in order to have blosc support in h5py. With h5py 3.0, this no longer works with the following error. Has anyone fixed this in their package? I'd appreciate any advice.

```python
    def fill_dcpl(plist, shape, dtype, chunks, compression, compression_opts,
                  shuffle, fletcher32, maxshape, scaleoffset, external,
                  allow_unknown_filter=False):
        """ Generate a dataset creation property list.

        Undocumented and subject to change without warning.
        """

        if shape is None or shape == ():
            shapetype = 'Empty' if shape is None else 'Scalar'
            if any((chunks, compression, compression_opts, shuffle, fletcher32,
                    scaleoffset is not None)):
                raise TypeError(
                    f"{shapetype} datasets don't support chunk/filter options"
                )
            if maxshape and maxshape != ():
                raise TypeError(f"{shapetype} datasets cannot be extended")
            return h5p.create(h5p.DATASET_CREATE)

        def rq_tuple(tpl, name):
            """ Check if chunks/maxshape match dataset rank """
            if tpl in (None, True):
                return
            try:
                tpl = tuple(tpl)
            except TypeError:
                raise TypeError('"%s" argument must be None or a sequence object' % name)
            if len(tpl) != len(shape):
                raise ValueError('"%s" must have same rank as dataset shape' % name)

        rq_tuple(chunks, 'chunks')
        rq_tuple(maxshape, 'maxshape')

        if compression is not None:
            if isinstance(compression, FilterRefBase):
                compression_opts = compression.filter_options
                compression = compression.filter_id

            if compression not in encode and not isinstance(compression, int):
>               raise ValueError('Compression filter "%s" is unavailable' % compression)
E               ValueError: Compression filter "blosc" is unavailable
```

**Comment by t20100** [comment]
You can give a try to `hdf5plugin` (https://github.com/silx-kit/hdf5plugin/) which provides blosc and a few other compression plugins for `h5py`.

**Comment by magehrig** [comment]
I am currently using the [blosc-hdf5-plugin](https://github.com/conda-forge/blosc-hdf5-plugin-feedstock) on conda with which I can avoid the `import tables` workaround. I.e. `import h5py` is sufficient together with the filter id and compression options.

Not enough of an HDF5/h5py expert to judge, but currently the best solution for me.
