### ISSUE TITLE
Requirement.parse('numpy>=1.6.1') fails when using numpy 1.10.0.dev0-b3476a7

### ISSUE THREAD

**Issue by nilswagner** [h5py/h5py#633]
nils@linux-5jkt:~/git/h5py> python setup.py install --prefix=$HOME/local
Traceback (most recent call last):
  File "setup.py", line 140, in <module>
    cmdclass = CMDCLASS,
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 268, in __init__
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 836, in resolve
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1074, in best_match
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 711, in find
    
pkg_resources.VersionConflict: (numpy 1.10.0.dev0-b3476a7 (/home/nils/local/lib64/python2.7/site-packages), Requirement.parse('numpy>=1.6.1'))

**Comment by aragilar** [comment]
This isn't an h5py bug, it's a numpy bug (I presume b3476a7 is the git hash?), you probably want a version which includes https://github.com/numpy/numpy/pull/6347.
