### ISSUE TITLE
BUG: ipy_completer with iPython 4

### ISSUE THREAD

**Issue by jakirkham** [h5py/h5py#637]
When starting iPython from the command line (I automatically load `h5py` autocompletion), I get the following traceback:

    Traceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/IPython/core/shellapp.py", line 267, in init_extensions
        self.shell.extension_manager.load_extension(ext)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/IPython/core/extensions.py", line 89, in load_extension
        __import__(module_str)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/h5py/ipy_completer.py", line 59, in <module>
        from IPython import generics
    ImportError: cannot import name generics

Stack includes:

* Python 2.7
* h5py 2.5.0
* iPython 4.0.0

**Comment by jakirkham** [comment]
I haven't looked at the code so don't know what is being used from generics, but it appears this module was moved so doing `from IPython.utils import generics` might work.

**Comment by jakirkham** [comment]
Looking closer, it appears that is already done. Instead it looks like this is the problem `from IPython import TryNext`. It now should be imported like this `from IPython.core.error import TryNext`. As both of these are in the same `try`/`except` block and the `generics` import occurs first, we don't see this issue.

**Comment by jakirkham** [comment]
Nevermind, this appears to be fixed in master.
