### ISSUE TITLE
H5py writing to compound types with subarrays

### ISSUE THREAD

**Issue by glenflet** [h5py/h5py#645]
consider the following data set, witch is valid for hdf5,
````{.py}
test = create_dataset('test', (6,) dtype=[('a','f',(5,6)),....])
````

can be accessed by

````{.py}
test[i, 'a']
````

however the following fails

````{.py}
test[1, 'a'] = np.ones((5,6),dtype='f')
````
giving:
````
Traceback (most recent call last):

  File "<ipython-input-10-343fe44da5d7>", line 1, in <module>
    test[1,'a'] = np.ones((5,6),dtype='f')

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2475)

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2432)

  File "E:\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\h5py\_hl\dataset.py", line 586, in __setitem__
    self.id.write(mspace, fspace, val, mtype)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2475)

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2432)

  File "h5py\h5d.pyx", line 217, in h5py.h5d.DatasetID.write (D:\Build\h5py\h5py-2.5.x\h5py\h5d.c:3362)

  File "h5py\_proxy.pyx", line 132, in h5py._proxy.dset_rw (D:\Build\h5py\h5py-2.5.x\h5py\_proxy.c:1699)

  File "h5py\_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite (D:\Build\h5py\h5py-2.5.x\h5py\_proxy.c:1430)

IOError: Can't prepare for writing data (Src and dest data spaces have different sizes)
````
````{.py}
test[1, 'a'][...] = np.ones((5,6),dtype='f')
````
works however it doesn't store the data as ```test[1, 'a'][...]``` provides a numpy copy of the data which is overwritten
````{.py}
test[1,'a'][...] = np.ones((5,6),dtype='f')

test[1,'a']
array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)
````

**Comment by kiyo-masui** [comment]
Have you found a workaround for this? This is really hanging me up at the moment.

**Comment by glenflet** [comment]
No, I end up saving my data, in NumPy (NPY) formatted files https://docs.scipy.org/doc/numpy/neps/npy-format.html, rather than hdf5, however I was just looking to dump results for later processing, this may not work depending on your needs. As for with h5py, I believe its possible using the low level interface however from what I can see it is complicated and I haven't had time to work out the details of do this.

You may want to look at the code for h5py dataset objects
```
File "E:\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\h5py\_hl\dataset.py", line 586, in __setitem__
    self.id.write(mspace, fspace, val, mtype)
```
This is the function where the problem is, basically it needs to be rewritten to loop through the data and write the individual elements using the low level hdf5 functions, when passed a compound datatype, rather than trying to write the compound datatype.

**Comment by eudoxos** [comment]
This bug is still present, see e.g. [h5py: assigning or broadcasting to 2×2 column in a structured array](https://stackoverflow.com/questions/67451714/h5py-assigning-or-broadcasting-to-2%c3%972-column-in-a-structured-array/67454495). It only affects arrays with `dtype.ndim>1`.

**Comment by eudoxos** [comment]
The workaround is to read the entire row, modify the field using index access and write the row back, as in (`test` is a `h5py.Dataset`):
```python
rowdata=test[0]
row[test.dtype.names.index('a')]=np.ones((5,6))
test[0]=rowdata
```
The same technique can be used to work around #581 (writing vlen fields in compound; see also [Writing variable-length sequence to a compound array](https://stackoverflow.com/questions/67192725/writing-variable-length-sequence-to-a-compound-array)).

H5py should at least raise an explanatory exception (a fix would be even better, of course).
