### ISSUE TITLE
numpy error:ValueError: numpy.dtype has the wrong size, try recompiling

### ISSUE THREAD

**Issue by DanlanChen** [h5py/h5py#684]
import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/h5py/__init__.py", line 23, in <module>
    from . import _conv
  File "h5py/h5t.pxd", line 14, in init h5py._conv (/home/ilan/minonda/conda-bld/work/h5py/_conv.c:7364)
  File "h5py/numpy.pxd", line 66, in init h5py.h5t (/home/ilan/minonda/conda-bld/work/h5py/h5t.c:20460)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by DanlanChen** [comment]
hello, I have no issue after upgrading my numpy.

**Comment by aragilar** [comment]
What version of numpy did you have?
