### ISSUE TITLE
Parallel write fails with 

### ISSUE THREAD

**Issue by iyer-arvind** [h5py/h5py#709]
Writing H5py under certain conditions fails with the following trace back(relative path truncated):

 Traceback (most recent call last):
  File "h5py/_objects.pyx", line 54, in h5p
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/lustre/atlas2/ard116/proj-shared/Downloads/titan/h5py-2.5.0/h5py/_objects.c:2716)
  File ".../h5py-2.5.0-py3.4-linux-x86_64.egg/h5py/_hl/files.py", line 306, in __exit__
    self.close()
  File ".../h5py-2.5.0-py3.4-linux-x86_64.egg/h5py/_hl/files.py", line 288, in close
    h5i.dec_ref(id_)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/lustre/atlas2/ard116/proj-shared/Downloads/titan/h5py-2.5.0/h5py/_objects.c:2759)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/lustre/atlas2/ard116/proj-shared/Downloads/titan/h5py-2.5.0/h5py/_objects.c:2716)
  File "h5py/h5i.pyx", line 150, in h5py.h5i.dec_ref (/lustre/atlas2/ard116/proj-shared/Downloads/titan/h5py-2.5.0/h5py/h5i.c:2339)
RuntimeError: **Can't decrement id ref count** (Other i/o error , error stack:
adioi_gen_close(120): other i/o error input/output error)
Rank 72 [Thu Mar 31 13:06:17 2016] [c17-6c0s3n0] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 72
.../pytools-2016.1-py3.4.egg/pytools/prefork.py:74: UserWarning: Prefork server exiting upon
  warn("%s exiting upon apparent death of %s" % (who, partner))
_pmiu_daemon(SIGCHLD): [NID 12614] [c17-6c0s3n0] [Thu Mar 31 13:06:18 2016] PE RANK 72 exit signal Aborted
[NID 12614] 2016-03-31 13:06:18 Apid 10570897: initiated application termination

 
The conditions when this was found to happen are listed below
 

1. H5Py Parallel write with MPIO
2. MPI rank is about 5000
3. Huge file writes each file is roughly 1.5TB in size, 5000 separate data sets
4. Not always, we have observed about 1 failure in two/three writes
5. File is unlocked and can be opened but has some junk data/zero
6. Not reproducible in smaller files/fewer rank

It seems to be some race condition in decrementing the reference count . This bug 
may be related to the 

https://github.com/h5py/h5py/issues/495 which gave a similar error but that bug 
was fixed later.

**Comment by aragilar** [comment]
@iyer-arvind Do you still see this with 2.7.1? Also, how did you install h5py (the egg part of the file path concerns me slightly)?

**Comment by danzafar** [comment]
I am seeing this issue using a multi-node cluster on Azure pushing to a mount. The code pushes this error many times:

```
File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (file write failed: time = Fri Dec 20 14:10:16 2019
, filename = '/dbfs/mnt/datalake_read_write/.../keras_model_v1.h5', file descriptor = 13, errno = 95, error message = 'Operation not supported', buf = 0x55c025877580, total write size = 4, bytes this sub-write = 4, bytes actually written = 18446744073709551615, offset = 103696)
```
before failing with:
```
RuntimeError: Unable to flush file's cached information
```
Any thoughts @aragilar?

**Comment by nareshr8** [comment]
I am also facing this issue in Azure Databricks version 6.2. I tried various versions of h5py from 2.10.0 to 2.7.0 and even changing numpy versions. Still no use. I can save the file with similar versions on my local system without any issue. Any help is appreciated.

**Comment by danzafar** [comment]
@nareshr8 , when working with Databricks the FUSE mount that underlies how DBFS has some major issues with the Keras save() function. If you want to use regular keras the workflow needed to save to dbfs is to first save to a local file, like /tmp/your_model.h5, and then move that over to dbfs using %fs magic command.

The other option is to simply use tf.keras instead of keras or MLflow. Both of these are supposed to play nicer with the FUSE mount to dbfs.

**Comment by nareshr8** [comment]
@danzafar Thanks for the response. I am able to save the model to temp folder. Thank you. 

However, I used tf.keras.Sequential to create the model, still it wasnt saving in the DBFS location. Having the workaround to work is great. However, the I am curious why the direct save to DBFS isnt working for me.

**Comment by danzafar** [comment]
Feel free to create a support ticket on Databricks and mention me, I'd be curious about this.

**Comment by nareshr8** [comment]
Reported the same to Databricks [here](https://github.com/databricks/spark-deep-learning/issues/220)

**Comment by hthouse** [comment]
any updates on this issue ? I have similar issue training custom model on databricks.... Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (file write failed: time = Wed Jan 29 17:40:30 2020
, filename = '/dbfs/FileStore/tables/FileStore/models/detection_model-ex-001--loss-0013.289.h5', file descriptor = 47, errno = 95, error message = 'Operation not supported', buf = 0x55ba4e17cb10, total write size = 3456, bytes this sub-write = 3456, bytes actually written = 18446744073709551615, offset = 129272)

**Comment by nareshr8** [comment]
Seems there are 2 work arounds as @danzafar suggests:

- Use MLFlow

- Create the model in tmp folder and move to databricks dbfs folder later.

**Comment by hthouse** [comment]
Thank y'all, using the server local tmp (file:/tmp/) and moving it to the cluster file system dbfs:/ works well !

**Comment by danzafar** [comment]
I think we can probably close this issue :)

**Comment by HelloFloor** [comment]
> @nareshr8 , when working with Databricks the FUSE mount that underlies how DBFS has some major issues with the Keras save() function. If you want to use regular keras the workflow needed to save to dbfs is to first save to a local file, like /tmp/your_model.h5, and then move that over to dbfs using %fs magic command.
> 
> The other option is to simply use tf.keras instead of keras or MLflow and don't use h5py. That will play nicer with the FUSE mount to dbfs.

Can I ask you how you move the model from temporary to DFBS? When I try: 

model.save("/tmp/best_model.h5")
dbutils.fs.mv("/tmp/best_model.h5","/dbfs/FileStore/tables/small_gamestates/best_model.h5")

I get the error: 
java.io.FileNotFoundException: /tmp/best_model.h5
Even though I can load it with  tf.keras.models.load_model("/tmp/best_model.h5").
Thank you!

**Comment by nareshr8** [comment]
Can u try using the generic python or shell script to move, like mv command. It might work..

**Comment by HelloFloor** [comment]
If I try this: 
%fs mv /tmp/best_model.h5  /dbfs/FileStore/tables/small_gamestates/best_model
 I get the same error...

**Comment by nareshr8** [comment]
Did you try actual shell code like:
```
%sh
mv <src> <dest>

```
The `%fs` and the dbfs commands are equivalent and they usually query the databricks file system. I guess, Since tmp is not in DBFS it might have the issue.

**Comment by HelloFloor** [comment]
Thanks! It can find the file now.
Only problem is the next error: 
mv: preserving permissions for ‘/dbfs/FileStore/tables/small_gamestates/best_model.h5’: Operation not permitted 

I am not sure how to fix this, but I think it is a different problem..

**Comment by Ophelia20444** [comment]
> any updates on this issue ? I have similar issue training custom model on databricks.... Exception ignored in: 'h5py._objects.ObjectID.**dealloc**' Traceback (most recent call last): File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.**dealloc** RuntimeError: Can't decrement id ref count (file write failed: time = Wed Jan 29 17:40:30 2020 , filename = '/dbfs/FileStore/tables/FileStore/models/detection_model-ex-001--loss-0013.289.h5', file descriptor = 47, errno = 95, error message = 'Operation not supported', buf = 0x55ba4e17cb10, total write size = 3456, bytes this sub-write = 3456, bytes actually written = 18446744073709551615, offset = 129272)

I also encountered the same error, have you solved this error?

**Comment by PabloAMC** [comment]
I am finding a similar error, by using h5py with jax (with a certain level of jit compilation), during execution in google colab (though not on my laptop).
```
RuntimeError                              Traceback (most recent call last)
/content/gdrive/MyDrive/folder/file.py in function(fpath, key, randomize, training)

8 frames
h5py/h5g.pyx in h5py.h5g.GroupID.__iter__()

h5py/h5g.pyx in h5py.h5g.GroupID.__iter__()

h5py/h5g.pyx in h5py.h5g.GroupIter.__init__()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5g.pyx in h5py.h5g.GroupID.get_num_objs()

RuntimeError: Unable to get group info (file read failed: time = Thu Jan 12 14:49:00 2023
, filename = '/content/gdrive/MyDrive/q-data-dft/data/training/W4-17/ch3_9.hdf5', file descriptor = 67, errno = 103, error message = 'Software caused connection abort', buf = 0x4e14f4a0, total read size = 328, bytes this sub-read = 328, bytes actually read = 18446744073709551615, offset = 0)

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

[/usr/local/lib/python3.8/dist-packages/h5py/_hl/files.py](https://localhost:8080/#) in close(self)
    456                     while id_.valid:
--> 457                         h5i.dec_ref(id_)
    458 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5i.pyx in h5py.h5i.dec_ref()

RuntimeError: Can't decrement id ref count (unable to close file, errno = 107, error message = 'Transport endpoint is not connected')

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by ajelenak** [comment]
@PabloAMC There are two important error messages in your traceback &mdash; `'Software caused connection abort'`, `'Transport endpoint is not connected'` &mdash; that indicate the problem is likely with the backend storage system and not h5py or libhdf5.

**Comment by PabloAMC** [comment]
I see, thanks. In the end I seemingly have solved the issue by slightly modifying the datafiles to not read a new hdf5 for every (quite large) object. Though I am not sure why this seems to work.

**Comment by pniedziela** [comment]
@PabloAMC could you elaborate more about that? I'm facing exactly the same problem now.

**Comment by PabloAMC** [comment]
Honestly, I am not sure: I think this happened when I iterated over hdf5 files during a training epoch, something like opening a closing lots of hdf5 files. Since I was having such error, I switched to having the same info in a single hdf5 file (or at least not that many hdf5 files), which seemed to avoid the problem.
