### ISSUE TITLE
ValueError: Unable to insert member (Member overlaps with another member) on win32

### ISSUE THREAD

**Issue by cgohlke** [h5py/h5py#711]
Probably related to #701.

I get one test error with git-master on 32-bit Python 2.7, 3.4, and 3.5 for Windows (64-bit passes all tests):

```
.....................................................x.................................................................x....................................s........ss.ss............................................................................................ssssss..............................E................................x....x..x..................x.....x......................................ssssssssss..............
======================================================================
ERROR: test_ref (h5py.tests.old.test_h5t.TestCompound)
Reference types are correctly stored in compound types (issue 144)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35-x32\lib\site-packages\h5py\tests\old\test_h5t.py", line 32, in test_ref
    tid = h5t.py_create(dt,logical=True)
  File "h5py\h5t.pyx", line 1449, in h5py.h5t.py_create (D:\Build\h5py\h5py-git\h5py\h5t.c:16180)
  File "h5py\h5t.pyx", line 1469, in h5py.h5t.py_create (D:\Build\h5py\h5py-git\h5py\h5t.c:16011)
  File "h5py\h5t.pyx", line 1491, in h5py.h5t.py_create (D:\Build\h5py\h5py-git\h5py\h5t.c:15510)
  File "h5py\h5t.pyx", line 1423, in h5py.h5t._c_compound (D:\Build\h5py\h5py-git\h5py\h5t.c:14831)
ValueError: Unable to insert member (Member overlaps with another member)

----------------------------------------------------------------------
Ran 427 tests in 0.884s

FAILED (errors=1, skipped=21, expected failures=7)
```

```
Summary of the h5py configuration
---------------------------------

h5py    2.6.0
HDF5    1.8.17
Python  3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
sys.platform    win32
sys.maxsize     2147483647
numpy   1.10.4
```

**Comment by andrewcollette** [comment]
Thanks @cgohlke.  Looks like the #701 patch didn't handle the "logical" flag code branch, which I didn't notice...
