### ISSUE TITLE
H5py errors out after reading a file a random number of times

### ISSUE THREAD

**Issue by jasonmar53** [h5py/h5py#736]
Hi this is my error

Traceback (most recent call last):
  File "plot_6_baselines_ver2_h5.py", line 431, in update
    nlFlag = track(lowerSideband[i], upperSideband[i], i)
  File "plot_6_baselines_ver2_h5.py", line 313, in track
    thislisti = np.array(imagVal)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "/home/corr/anaconda3/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 646, in __array__
    self.read_direct(arr)
  File "/home/corr/anaconda3/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 609, in read_direct
    self.id.read(mspace, fspace, dest)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "h5py/h5d.pyx", line 177, in h5py.h5d.DatasetID.read (/home/ilan/minonda/conda-bld/work/h5py/h5d.c:3128)
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw (/home/ilan/minonda/conda-bld/work/h5py/_proxy.c:1774)
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread (/home/ilan/minonda/conda-bld/work/h5py/_proxy.c:1416)
OSError: Can't read data (Addr overflow, addr = 6573584, size=8192, eoa=6573584)

This is my code 
    low = h5py.File(lfile, 'r')
    upp = h5py.File(ufile, 'r')

```
realVal = low.get('/fullData/real')
imagVal = low.get('/fullData/imag')

realVal2 = upp.get('/fullData/real')
imagVal2 = upp.get('/fullData/imag')

thislistr = np.array(realVal)
thislisti = np.array(imagVal)
thislistr2 = np.array(realVal2)
thislisti2 = np.array(imagVal2)

thislistr = np.transpose(thislistr)
thislisti = np.transpose(thislisti)
thislistr2 = np.transpose(thislistr2)
thislisti2 = np.transpose(thislisti2)
```

I have 12 files that I'm reading every 1 - 4 seconds (time doesn't matter, it eventually errors out), I successfully read until I hit the error then some files are read successfully while others are not for the rest of the program runtime.

Any tips would be great!

**Comment by jasonmar53** [comment]
I should mention that the data files are being updated real time roughly every 4 seconds so that's why I have to constantly be reading the files to use its data

**Comment by jasonmar53** [comment]
Summary of the h5py configuration
---------------------------------

h5py    2.5.0
HDF5    1.8.15
Python  3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.10.4

**Comment by lucasb-eyer** [comment]
I just had this too, with a file where one process is slowly filling up an array row by row, and another one is reading it from time to time. I noticed this only happens when the reader tries to access the last row, which is not "complete" yet. Not sure if/how this makes sense yet, but reading `f['arr'][:-1]` works, while reading `f['arr'][-1]` gives this error.

Note that the writer and reader don't access the same file, but the reader accesses a copy of the writer's file that's copied by rsync. That might be part of the reason. The reader calls `flush` regularly.

**Comment by tacaswell** [comment]
This is generically not safe at the hdf5 level and in why SWMR was added in hdf5 1.10 (see https://support.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesSwmrDocs.html ).

In both cases eventually the file is in an internally inconsistent state.  Either use SWMR or implement some locking between the writer process closing the file and the reader either re-opening or triggering the rsync.

Closing as there is nothing that can be done about this at the h5py level.
