### ISSUE TITLE
DimensionManager .items() and .values() methods broken

### ISSUE THREAD

**Issue by jjhelmus** [h5py/h5py#744]
The `items` and `values` methods of the DimensionManager class seem to be broken as can be seen in this snippet:

``` Python
import h5py

f = h5py.File('foo.h5', 'w')
f['x1'] = [1, 2]
f['data'] = [1, 2]
f['data'].dims.create_scale(f['x1'])
f['data'].dims[0].attach_scale(f['x1'])

for i in f['data'].dims.items():
    pass

for i in f['data'].dims.values():
    pass
```

```
$ python bug.py
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    for i in f['data'].dims.items():
  File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/h5py/_hl/base.py", line 338, in __iter__
    yield (key, self._mapping.get(key))
  File "/Users/jhelmus/anaconda/lib/python3.5/_collections_abc.py", line 595, in get
    return self[key]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2541)
  File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/h5py/_hl/dims.py", line 157, in __getitem__
    if index > len(self) - 1:
TypeError: unorderable types: DimensionProxy() > int()
```

The `__getitem__` method of the class seems to be expecting an integer but is being passed a DimensionProxy instance.

**Comment by jjhelmus** [comment]
Changing the __iter__ method of the DimensionsManager class to `yield i` rather than `yield self[i]`would solve this issue.  Would be happy to put together a PR if desired.

**Comment by kmuehlbauer** [comment]
This is still an issue with h5py `2.10.0`, although the ErrorMessage changed slightly:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-2fe68ce88f85> in <module>
      7 f['data'].dims[0].attach_scale(f['x1'])
      8 
----> 9 for i in f['data'].dims.items():
     10     pass
     11 

/home/kai/miniconda/envs/wradlib_38/lib/python3.8/site-packages/h5py/_hl/base.py in __iter__(self)
    366         with phil:
    367             for key in self._mapping:
--> 368                 yield (key, self._mapping.get(key))
    369 
    370 

/home/kai/miniconda/envs/wradlib_38/lib/python3.8/_collections_abc.py in get(self, key, default)
    658         'D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.'
    659         try:
--> 660             return self[key]
    661         except KeyError:
    662             return default

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/home/kai/miniconda/envs/wradlib_38/lib/python3.8/site-packages/h5py/_hl/dims.py in __getitem__(self, index)
    157         """ Return a Dimension object
    158         """
--> 159         if index > len(self) - 1:
    160             raise IndexError('Index out of range')
    161         return DimensionProxy(self._id, index)

TypeError: '>' not supported between instances of 'DimensionProxy' and 'int'
```

The proposed solution doesn't help since this breaks downstream code. Is there any workaround or the like?

**Comment by takluyver** [comment]
It looks like the solution might be to ditch the mapping interface entirely, and treat `ds.dims` like a sequence instead.
