### ISSUE TITLE
ValueError when trying to use custom filter

### ISSUE THREAD

**Issue by estan** [h5py/h5py#750]
Hi,

I have a strange issue on Arch Linux when trying to use a custom HDF5 filter plugin for Blosc compression. It works fine on Ubuntu 16.04 (Python 3.5.1, HDF5 library 1.8.16, h5py 2.6.0), but on Arch Linux (Python 3.5.2, HDF5 library 1.8.17, h5py 2.6.0) I get

```
Traceback (most recent call last):
  File "h5py-example.py", line 34, in <module>
    datatype_size=4
  File "/usr/lib/python3.5/site-packages/h5py/_hl/group.py", line 105, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 129, in make_new_dset
    dset_id = h5d.create(parent.id, None, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/python-h5py/src/h5py-2.6.0/h5py/_objects.c:2678)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/python-h5py/src/h5py-2.6.0/h5py/_objects.c:2636)
  File "h5py/h5d.pyx", line 79, in h5py.h5d.create (/build/python-h5py/src/h5py-2.6.0/h5py/h5d.c:1968)
ValueError: Unable to create dataset (Not a property list)
```

when trying to create a dataset.

My test code is

```python
import h5py

# Blosc filter number
BLOSC_FILTER = 32001

# Codes for Blosc shuffling
BLOSC_NOSHUFFLE = 0  # No shuffle
BLOSC_SHUFFLE = 1    # Byte-wise shuffle
BLOSC_BITSHUFFLE = 2 # Bit-wise shuffle

# Codes for compressors shipped with Blosc
BLOSC_BLOSCLZ = 0
BLOSC_LZ4 = 1
BLOSC_LZ4HC = 2
BLOSC_SNAPPY = 3
BLOSC_ZLIB = 4
BLOSC_ZSTD = 5

def blosc_opts(compressor=BLOSC_BLOSCLZ, level=9, shuffle=BLOSC_SHUFFLE, datatype_size=0):
    """Create a compression_opts tuple for Blosc compression"""
    return (0, 0, datatype_size, 0, level, shuffle, compressor) # Element 0, 1, 3 unused

with h5py.File('h5py-example.hdf5', 'w') as outfile:
    outfile.create_dataset(
        'example',
        shape=(3, 3),
        dtype='float32',
        data=[0, 1, 2, 3, 4, 5, 6, 7, 8],
        shuffle=False,
        compression=BLOSC_FILTER,
        compression_opts=blosc_opts(
            compressor=BLOSC_LZ4,
            level=9,
            datatype_size=4
        ),
    )
```

I'm attaching the custom HDF5 filter plugin I'm using, but I'm not sure it's related to the problem. You can build it with

    make

on Ubuntu and

    PKG_CONFIG_PATH=arch make

on Arch Linux, and install it to `/usr/local/hdf5/lib/plugin/lib` (where HDF5 will find it) with `make install`. Or skip installing and set `HDF5_PLUGIN_PATH` to the `hdf5-blosc-filter` directory.

Do you have any idea why I could be getting this error on Arch Linux but not on Ubuntu? I tried to trace the involved code, but couldn't really find what goes wrong :(

[hdf5-blosc-plugin.tar.gz](https://github.com/h5py/h5py/files/422298/hdf5-blosc-plugin.tar.gz)

**Comment by estan** [comment]
I forgot to say, the same code works fine also on Arch Linux if I remove the compression related parameters (i.e. not using my filter), and also if I use e.g. just `compression="gzip"` to use the built-in GZIP support.

So my problem must have something to do with my custom filter or how I'm using it, but I don't think it's related to the actual filter code, since that was taken verbatim from the pytables project (and because it works fine on Ubuntu).

**Comment by estan** [comment]
I found the issue, it was a simple PEBKAC, a library version mismatch: h5py was using one version of the HDF5 library, while I was linking my custom filter against another.

Sorry for the noise.
