### ISSUE TITLE
Region references do not work when stored in datasets

### ISSUE THREAD

**Issue by jjhelmus** [h5py/h5py#756]
Region references do not appear to work when they are stored as a dataset element but work fine when they are stored as attributes.  Not sure if this is an issue with h5py or HDF5 itself.

Minimal example:

``` Python
import h5py

f = h5py.File('test.h5', 'w')
dset1 = f.create_dataset('dset1', data=range(10))
region_ref = dset1.regionref[::2]

f.attrs['region_reference_attr'] = region_ref

ref_dtype = h5py.special_dtype(ref=h5py.Reference)
ref_dataset = f.create_dataset("ref_dataset", (1, ), dtype=ref_dtype)
ref_dataset[0] = region_ref
f.close()

f = h5py.File('test.h5', 'r')

region_ref_from_attr = f.attrs['region_reference_attr']
region_ref_from_dataset = f['ref_dataset'][0]

dset1 = f['dset1']
print(dset1[region_ref_from_attr])         # works print [0 2 4 6 8]
print(dset1[region_ref_from_dataset])  # fails 

f.close()
```

This raises a TypeError

```
[0 2 4 6 8]
Traceback (most recent call last):
  File "/home/jhelmus/anaconda/lib/python3.5/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'h5py.h5r.Reference'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 23, in <module>
    print(dset1[region_ref_from_dataset])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "/home/jhelmus/anaconda/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/jhelmus/anaconda/lib/python3.5/site-packages/h5py/_hl/selections.py", line 88, in select
    sel[args]
  File "/home/jhelmus/anaconda/lib/python3.5/site-packages/h5py/_hl/selections.py", line 362, in __getitem__
    raise TypeError("Advanced selection inappropriate")
TypeError: Advanced selection inappropriate
```

**Comment by jjhelmus** [comment]
If you change the dtype of the reference dataset to be `RegionReference` then region references can be stored in a dataset:

``` Python
ref_dtype = h5py.special_dtype(ref=h5py.RegionReference)
```

`RegionReference` and `Reference` objects are not equivalent, for instance they have different `typesize` (12 vs 8).  Trying to set a HDF5 dataset of type `Reference` with an `RegionReference` should probably raise a TypeError.

**Comment by jjhelmus** [comment]
I believe that the [`conv_pyref2objref`](https://github.com/h5py/h5py/blob/master/h5py/_conv.pyx#L361-L362) function should check that the typecode of the Reference object is ** H5R_OBJECT** and raise a TypeError if the check fails.  Does this seem reasonable?  I can submit a PR implementing this is desired.

**Comment by leezu** [comment]
I have the same issue.

This is quite surprising to me given that the manual even contains a section explaining how to store `Reference` in datasets.

**Comment by aragilar** [comment]
This seems reasonable, if you can create a PR, that'd be great.

**Comment by mitar** [comment]
I also got the same confusing error when I made a mistake of using reference dtype instead of region reference dtype. I think there should be some error if you try to store region reference inside the reference dtype. Currently it works, but when you try to use it to dereference, you get the strange `Advanced selection inappropriate` error.
