### ISSUE TITLE
TypeError when creating hard link with python3

### ISSUE THREAD

**Issue by prjemian** [h5py/h5py#769]
ref: https://groups.google.com/a/continuum.io/forum/#!mydiscussions/anaconda/IK2TDOovnu4

Getting a **TypeError** when trying to create a hard link (tested against v2.5.0 & 2.6.0) in Python 3.5.2 (works in Python 2.7.12):

    Traceback (most recent call last):
      File "demo.py", line 8, in <module>
        h5_file_object._id.link(ds.name, "the_link", h5py.h5g.LINK_HARD)

      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
      File "h5py/h5g.pyx", line 262, in h5py.h5g.GroupID.link (/home/ilan/minonda/conda-bld/work/h5py/h5g.c:3807)
    TypeError: expected bytes, str found

Here is the code to demonstrate the problem:

    import h5py
    import h5py.h5g

    print("h5py.__version__ = " + h5py.__version__)
    h5_file_object = h5py.File("demo.h5", "w")
    ds = h5_file_object.create_dataset("data", [1.0, 2.0, 3.0])
    h5_file_object._id.link(ds.name, "the_link", h5py.h5g.LINK_HARD)
    h5_file_object.close()

**Comment by prjemian** [comment]
It's a python3 thing.  In the link(I) call, need to wrap strings with ``str.encode(str(string_text))`` to be compatible with both Python2 and Python3, such as

    h5_file_object._id.link(str.encode(str(ds.name)), str.encode(str("the_link")), h5py.h5g.LINK_HARD)
