### ISSUE TITLE
Advanced indexing

### ISSUE THREAD

**Issue by andrewcollette** [h5py/h5py#8]
_Original author: bioinformed@gmail.com (November 19, 2008 16:34:35)_

Is it possible to enable advanced indexing to extract an array of row 
indexes or a boolean array?  There seems to be support for extracting 
slices and coordinates, but not arbitrary indexes.

_Original issue: http://code.google.com/p/h5py/issues/detail?id=8_

**Comment by johntyree** [comment]
What do you mean by duplicate coordinates here?

The docs describe it as ["duplicate selections"](http://docs.h5py.org/en/latest/high/dataset.html#fancy-indexing), but either way I'm not sure what it's referring to. Not repeated indices in a fancy indexing selection, it seems.

```python
>>> f['test'] = np.arange(5)
>>> f['test'][[0,0]]        
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/vagrant/pisi/tmp/h5py-2.5.0-3/work/h5py-2.5.0/h5py/_objects.c:2458)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/vagrant/pisi/tmp/h5py-2.5.0-3/work/h5py-2.5.0/h5py/_objects.c:2415)
  File "/home/john/projects/genia/genia-dev/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 451, in __getitem__
    self.id.read(mspace, fspace, arr, mtype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/vagrant/pisi/tmp/h5py-2.5.0-3/work/h5py-2.5.0/h5py/_objects.c:2458)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/vagrant/pisi/tmp/h5py-2.5.0-3/work/h5py-2.5.0/h5py/_objects.c:2415)
  File "h5py/h5d.pyx", line 177, in h5py.h5d.DatasetID.read (/home/vagrant/pisi/tmp/h5py-2.5.0-3/work/h5py-2.5.0/h5py/h5d.c:3058)
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw (/home/vagrant/pisi/tmp/h5py-2.5.0-3/work/h5py-2.5.0/h5py/_proxy.c:1670)
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread (/home/vagrant/pisi/tmp/h5py-2.5.0-3/work/h5py-2.5.0/h5py/_proxy.c:1336)
IOError: Can't read data (Src and dest data spaces have different sizes)
>>> 
```

**Comment by andrewcollette** [comment]
@johntyree, looks like the validation code didn't catch this particular slice ``dset[[0,0]]``.  When using a coordinate list to index a dataset, repeated/duplicate coordinates aren't allowed.

**Comment by johntyree** [comment]
Right. I'm wondering if we need to update the docs to clarify what that section I linked to means.

Can you give an example of what a "duplicate selection" is? I thought it would be the example I gave.

**Comment by andrewcollette** [comment]
Sorry I wasn't clear... the code you provided is indeed an example of a duplicate selection.  This means a list of coordinates for any axis which contains duplicate elements.  In NumPy this is allowed, but HDF5 requires a 1:1 mapping between source and destination elements.

The docs suggest such coordinates are simply ignored... I think a better approach would be to raise an exception since people might otherwise expect the NumPy behavior.  In any case the IOError from your example is simply a bug; it should either ignore the second "0" or raise an exception complaining about duplicates.

**Comment by johntyree** [comment]
I see. Personally, I strongly advocate the latter rather than have H5Py silently behave differently than numpy. It's common to pass around dataset objects as if they were already in-memory arrays and using duplicate selections to expand an array is quite common.

I'll add this to my list of things to look at in detail someday :)
