### ISSUE TITLE
Setting fillvalue to NaN raises ValueError

### ISSUE THREAD

**Issue by laliberte** [h5py/h5py#805]
The following legitimate-looking code raises a ValueError on python 3.5:
```
import h5py
import numpy as np
f = h5py.File("mytestfile.hdf5", "w")
dset = f.create_dataset("mydataset", (100,), dtype='c', fillvalue=np.nan)
```

**Comment by shoyer** [comment]
Does setting `fillvalue=(np.nan + 1j * np.nan)` work?

**Comment by laliberte** [comment]
No it doesn't:
```
import h5py
import numpy as np
f = h5py.File("mytestfile.hdf5", "w")
dset = f.create_dataset("mydataset", (100,), dtype='c', fillvalue=(np.nan + 1j * np.nan))
```
has the same behaviour.

**Comment by andreabedini** [comment]
I can reproduce. See the traceback below. Latest versions of everything (numpy 1.11.2, h5py 2.6.0). Same backtrace with Python 2.

```
In [1]: import h5py
   ...: import numpy as np
   ...: f = h5py.File("mytestfile.hdf5", "w")
   ...: dset = f.create_dataset("mydataset", (100,), dtype='c', fillvalue=np.nan
   ...: )
   ...: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-9b0509531ce3> in <module>()
      2 import numpy as np
      3 f = h5py.File("mytestfile.hdf5", "w")
----> 4 dset = f.create_dataset("mydataset", (100,), dtype='c', fillvalue=np.nan)

/usr/local/lib/python3.5/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    103         """
    104         with phil:
--> 105             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    106             dset = dataset.Dataset(dsid)
    107             if name is not None:

/usr/local/lib/python3.5/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
    127 
    128 
--> 129     dset_id = h5d.create(parent.id, None, tid, sid, dcpl=dcpl)
    130 
    131     if data is not None:

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-zn72z7s3-build/h5py/_objects.c:2853)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-zn72z7s3-build/h5py/_objects.c:2811)()

h5py/h5d.pyx in h5py.h5d.create (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-zn72z7s3-build/h5py/h5d.c:2126)()

ValueError: Unable to create dataset (No appropriate function for conversion path)
```

**Comment by root-11** [comment]
Help! This bug blocks my usage of HDF5 too.

With 
```
import numpy as np

values = np.array([np.nan, np.nan, -340282366920938463463374607431768211456, np.nan, np.nan,
       340282366920938463463374607431768211456], dtype=object)
```

I get Error:
```
Traceback (most recent call last):
  File "...\...\...\hdf5\writer.py", line 147, in __init__
    self.array = self.h5group.require_dataset('data', shape=shape, dtype=dtype.numpy.newbyteorder(byteorder))
  File "...\...\...\h5py\_hl\group.py", line 229, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "...\...\...\h5py\_hl\group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "...\...\...\h5py\_hl\dataset.py", line 89, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1663, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1687, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1747, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

Suggestion:
Add 1 byte for special values, so that IEEE-754 is complied to with:

|value | IEEE754 |
|:---|:---|
|0|np.NZERO|
|1|np.euler_gamma|
|2|np.e|
|3|np.pi|
|4|np.NAN = np.NaN = np.nan|
|5|np.inf = np.Infinity = np.PINF = np.infty|
|6|np.NINF|
