### ISSUE TITLE
H5py 2.7.0 failures on windows

### ISSUE THREAD

**Issue by cournape** [h5py/h5py#855]
I see the following failures:

``` python
======================================================================
ERROR: test_load_from_image (tests.old.test_file_image.TestFileImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vagrant\.edm-build\envs\build-env\lib\site-packages\h5py\tests\old\test_file_image.py", line 20, in test_load_from_image
    fapl.set_file_image(image)
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_file_image'

======================================================================
ERROR: test_write_direct_chunk (tests.old.test_h5d_direct_chunk_write.TestWriteDirectChunk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vagrant\.edm-build\envs\build-env\lib\site-packages\h5py\tests\old\test_h5d_direct_chunk_write.py", line 25, in test_write_direct_chunk
    dataset.id.write_direct_chunk((index, 0, 0), a.tostring(), filter_mask=1)
AttributeError: 'h5py.h5d.DatasetID' object has no attribute 'write_direct_chunk'
```

System details:

* python 2.7.6
* windows 7 64 bits
* built against hdf5 1.8.16

**Comment by aragilar** [comment]
This sounds like there's a difference between what version of HDF5 h5py was complied and run against, and the version that h5py thinks it was built against. Is --hdf5-version=1.8.16 passed to the setup.py, or HDF5_VERSION=1.8.16 set?

**Comment by cournape** [comment]
That's indeed the issue: on windows, the hdf5 version is not automatically detected, and falls back to `1.8.4`.

**Comment by cournape** [comment]
Warning would be nice, as I am not the only who got caught up in this (the h5py package from conda has the exact same issue on winows).
