### ISSUE TITLE
dataset.read_direct fails with ZeroDivisionError when '0 in shape'

### ISSUE THREAD

**Issue by achilleas-k** [h5py/h5py#870]
Potential regression of #281, or simply related. H5py allows storing of empty arrays where any one of the dimensions can be 0 (e.g., `(0,)`, `(1, 0)`, `(1, 0, 3)`). If this dataset is read using `read_direct`, a `ZeroDivisionError` is thrown.

<details>
    <summary>System version details (click to expand)</summary>
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
Arch Linux

 * Python version (e.g. 2.7, 3.5)
3.6.0

 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
System repositories

 * h5py version (e.g. 2.6)
2.7.0

 * HDF5 version (e.g. 1.8.17)
1.10
</details>

Minimal script:
```python
import h5py
import numpy as np


print(h5py.version.info)

shape = (0,)  # also try (1, 0, 2) or anything with 0 in it
hfile = h5py.File("/tmp/zerodata.h5", "w")
ds = hfile.create_dataset("ds", data=np.zeros(shape))

print("---------------------------------")
print(ds)
print(hfile["ds"])
print(hfile["ds"][:])

dsread = np.zeros(shape)
hfile["ds"].read_direct(dsread)  # division by zero
hfile.close()
```

Output
```
Summary of the h5py configuration
---------------------------------

h5py    2.7.0
HDF5    1.10.0
Python  3.6.0 (default, Jan 16 2017, 12:12:55)
[GCC 6.3.1 20170109]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.12.1

---------------------------------
<HDF5 dataset "ds": shape (0,), type "<f8">
<HDF5 dataset "ds": shape (0,), type "<f8">
[]
Traceback (most recent call last):
  File "zero.py", line 17, in <module>
    hfile["ds"].read_direct(dsread)  # division by zero
  File "/usr/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 654, in read_direct
    for mspace in dest_sel.broadcast(source_sel.mshape):
  File "/usr/lib/python3.6/site-packages/h5py/_hl/selections.py", line 303, in broadcast
    chunks = tuple(x//y for x, y in zip(count, tshape))
  File "/usr/lib/python3.6/site-packages/h5py/_hl/selections.py", line 303, in <genexpr>
    chunks = tuple(x//y for x, y in zip(count, tshape))
ZeroDivisionError: integer division or modulo by zero
```

**Comment by rmvanhees** [comment]
Dear Acchilleas,

You are trying to write an empty array because the size of an array is
always zero if any of the dimensions are zero (see the numpy documentation).

If your goal is to write an empty dataset then please follow the
instructions you can find on this page (
http://docs.h5py.org/en/latest/high/dataset.html).

I think that h5py can handle this more gracefully by checking is the
dataset is empty (ds.size == 0).

Greetings, Richard

**Comment by achilleas-k** [comment]
Yes, the array is empty. My goal isn't to write an empty dataset, it's to discover whether the behaviour I'm getting is the intended.

I'm curious whether it would be better for the write to fail (when a dimension is 0), or the read to fail more gracefully, or at least have an error that points towards the underlying problem (instead of ZeroDivisionError).

**Comment by aragilar** [comment]
We should at least have a better error message.
