### ISSUE TITLE
Error when writing vlen with arrays of same lengths

### ISSUE THREAD

**Issue by constantinpape** [h5py/h5py#875]
Hi,
I have run into an error when writing an numpy array of arrays with the same lengths via vlen.
Here is a minimal example (either of the options for x produces the same error).

```
import h5py
import numpy as np

def write_vlen(x, ff, key):
    dt = h5py.special_dtype(vlen=np.float64)
    #dtype = np.dtype([('c1', dt)])
    with h5py.File(ff) as f:
        f.create_dataset(key, data = x, dtype = dt) 

x = np.array([np.array([1.,2.,3.]),np.array([2.,3.,4])])    
#x = np.array([],dtype='float64')
#x = np.array([1,2,3])
write_vlen(x, 'tmp.h5', 'data')
``` 

I get the following stack trace:

```
Traceback (most recent call last):
  File "test_vlen.py", line 14, in <module>
    write_vlen(x, 'tmp.h5', 'data')
  File "test_vlen.py", line 9, in write_vlen
    f.create_dataset(key, data = x, dtype = dt)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 108, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 140, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write (/tmp/pip-nCYoKW-build/h5py/h5d.c:3694)
  File "h5py/_proxy.pyx", line 152, in h5py._proxy.dset_rw (/tmp/pip-nCYoKW-build/h5py/_proxy.c:2221)
  File "h5py/_proxy.pyx", line 318, in h5py._proxy.needs_bkg_buffer (/tmp/pip-nCYoKW-build/h5py/_proxy.c:3813)
TypeError: Operation not defined for data type class (Operation not defined for data type class)
```

Note that this may be the same error that was already reported in #755. 

System Details:
 * Ubuntu 14.04
 * Python 2.7
 * I reproduced this error with h5py 2.6 and 2.7 (versions from pip and conda)
 * HDF5 version (e.g. 1.8.11)

**Comment by reuben** [comment]
I'm running into the same problem. @constantinpape did you find a workaround?

**Comment by constantinpape** [comment]
My workaround for this was checking if this case arises and then saving the data 
as normal 2d array. Though it would be great if this was fixed, s.t. vlen works in general.

**Comment by reuben** [comment]
Thanks! I ended up using PyTables which doesn't choke on the same input.

**Comment by gamazeps** [comment]
I am also having an issue when storing a list of strings (json metadata big enough not to fit in attributes) which all have the same size.

No minimal repro for now, I should write one soon.

**Comment by meereeum** [comment]
yup, vlen saving seems to fall down for any asymmetric input, including all singleton lists (e.g. `x=np.array([np.array([1.,2.,3.])])`)

this is a terribly hacky work-around, but until someone can put the work in for a more permanent fix:
```
import h5py
import numpy as np

FF = 'tmp.h5'
KEY = 'data'

def write_vlen(x, ff, key):
    dt = h5py.special_dtype(vlen=np.float64)

    x_most, x_rest = (
        (x[:-1], x[-1]) if len(x) > 1 else
        (x[:], np.array([])) # deal w/ singleton arrays
    ) 
    x_most = list(x_most) + [np.array([])] # dummypad

    with h5py.File(ff) as f:
        f.create_dataset(key, data=x_most, dtype=dt)
        f[key][-1:] = x_rest               # dummyclobber

x = np.array([np.array([1.,2.,3.]),np.array([2.,3.,4])])
write_vlen(x, FF, KEY)
```

aand voila:

```
with h5py.File(FF) as f:
    print(f[KEY][...])

>> [array([1., 2., 3.]) array([2., 3., 4.])]
```

this can surely be rewritten more elegantly, but the idea is to replace one entry of the original outer array with a dummy empty array (thus ensuring asymmetry), and then overwrite the empty array with the leftover real array. (unfortunately, singletons will be left with a dummy array that has to be overwritten during the next pass, if the array is extended)

this way, you can save nested arrays of dynamic/unbounded width & height when used in conjunction with `maxshape=(None,)`.

sharing only because i haven't seen any other solution that works for this (probably frequent) problem...
