### ISSUE TITLE
IOError: Unable to open file (Truncated file: eof = ...

### ISSUE THREAD

**Issue by mbhall88** [h5py/h5py#879]
To assist reproducing bugs, please include the following:
 * Operating System: Ubuntu 16.04.2 LTS

```

h5py    2.7.0
HDF5    1.8.18
Python  2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.12.1

```

The full traceback/stack trace shown (if it appears):

```

Traceback (most recent call last):
  File "rtSimReadDeposit.py", line 135, in <module>
    if __name__ == "__main__": main()
  File "rtSimReadDeposit.py", line 126, in main
    staging_list.append(associate_time(entry.path))
  File "rtSimReadDeposit.py", line 99, in associate_time
    t = calculate_timestamp(extract_time_fields(file_))
  File "rtSimReadDeposit.py", line 47, in extract_time_fields
    with h5.File(file_, 'r') as f:
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/tmp/pip-nCYoKW-build/h5py/h5f.c:2117)
IOError: Unable to open file (Truncated file: eof = 646174, sblock->base_addr = 0, stored_eoa = 658132)

```

Get this error for the odd file when trying to open the file. The filetypes are `.fast5` and when trying to open approx. 70,000 files I get this with about 10 of them. 

I searched around for anyone else reporting and couldn't seem to find anything. Is this something simple I'm missing?

**Comment by aragilar** [comment]
That sounds to me like the file is corrupt in some way, can you try running h5dump (or any of the other hdf5-provided tools)? If they can't read it (which would suggest corruption), then there's not much you can do as far as I know, apart from recreate the files.

**Comment by mbhall88** [comment]
Apologies, it is an issue with the file I am trying to open. Thanks for the suggestion.
