### ISSUE TITLE
Using h5py in spyder gives some weird behaviour

### ISSUE THREAD

**Issue by wiedemannc** [h5py/h5py#881]
**Environment**: 
  h5py    2.7.0
  HDF5    1.8.18
  Python  3.5.3 (default, Jan 19 2017, 14:11:04) **system python running on virtualenv, packages installed with pip**
  [GCC 6.3.0 20170118]
  sys.platform    linux **(debian stretch)**
  sys.maxsize     9223372036854775807
  numpy   1.12.1

**Error Description**
if I (re-)run the attached simple script (h5py_bugreport.py) multiple times from within spyder/IPython without restarting the interpreter, it does run fine a few times but after a random amount of runs (e.g. 4) I get the attached traceback (ipython.html). I can't reproduce it with a simple script, but with a more complex script I occasionally also get this error:

SystemError:../Objects/moduleobject.c:449: bad argument to internal function (when calling h5py.File to open a hdf5 file in "r" mode). Stacktrace is also attached as ipython2.txt

**Comment by wiedemannc** [comment]
added attachment: file:///tmp/h5pybugreport.ZIP

**Comment by tacaswell** [comment]
@wiedemannc Can you past the traceback directly into the issue?

**Comment by wiedemannc** [comment]
Sorry @tacaswell github didn't accept my .zip files for whatever reason. I've updated the original post with corrected files.

**Comment by tacaswell** [comment]
Please paste the content directly into the issue (you can mark things as 'code' via triple backticks ( ` ) ).  It is much easier to work with than having to download a file.

**Comment by tacaswell** [comment]
```python
import h5py
import numpy

f = h5py.File("SimpleBlenderScene.h5", "r")
a = numpy.zeros(f["original/Z"].shape)
Z = f["original/Z"].read_direct(a)
f.close()
del f


```

```pytb
In [5]: runfile('/home/me/temp/h5py_bugreport/h5py_bugreport.py', wdir='/home/me/temp/h5py_bugreport')
Reloaded modules: h5py._hl.selections, h5py.version, h5py._conv, h5py._hl.group, h5py.h5z, h5py._hl.base, h5py._hl.dataset, h5py.tests.hl.test_dims_dimensionproxy, h5py.h5g, h5py._hl.attrs, h5py._hl.datatype, h5py.tests.hl.test_dataset_getitem, h5py.h5d, h5py.h5o, h5py.h5a, h5py.tests.old.test_dataset, h5py.tests.hl.test_threads, h5py.tests.old.test_objects, h5py.h5p, h5py.tests.old, h5py._hl.filters, h5py.tests.hl.test_dataset_swmr, h5py.tests.old.test_datatype, h5py.tests.old.test_group, h5py._hl.files, h5py.h5t, h5py.tests.old.test_dimension_scales, h5py._hl.selections2, h5py.tests.old.test_attrs_data, h5py.tests.old.test_file_image, h5py.tests.old.common, h5py.tests.hl, h5py, h5py.highlevel, h5py.tests.old.test_h5p, h5py.tests.old.test_selections, h5py._hl, h5py.tests.old.test_slicing, h5py.h5ds, h5py.h5s, h5py.tests.hl.test_attribute_create, h5py.h5l, h5py.h5, h5py._hl.compat, h5py.tests.common, h5py.tests.old.test_base, h5py._errors, h5py.tests.old.test_h5f, h5py.h5f, h5py.h5r, h5py.tests.old.test_h5, h5py.tests.old.test_h5t, h5py.tests, h5py.tests.hl.test_datatype, h5py.h5i, h5py.tests.old.test_file, h5py.tests.hl.test_file, h5py.h5fd, h5py._objects, h5py.tests.old.test_attrs
Traceback (most recent call last):

  File "<ipython-input-5-4153703766ca>", line 1, in <module>
    runfile('/home/me/temp/h5py_bugreport/h5py_bugreport.py', wdir='/home/me/temp/h5py_bugreport')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/me/temp/h5py_bugreport/h5py_bugreport.py", line 4, in <module>
    f = h5py.File("SimpleBlenderScene.h5", "r")

  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)

  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2842)

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2800)

  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/build/h5py-b1xqNM/h5py-2.7.0/h5py/h5f.c:2135)

  File "h5py/h5g.pyx", line 256, in h5py.h5g.GroupID.__init__ (/build/h5py-b1xqNM/h5py-2.7.0/h5py/h5g.c:3860)

  File "h5py/h5g.pyx", line 257, in h5py.h5g.GroupID.__init__ (/build/h5py-b1xqNM/h5py-2.7.0/h5py/h5g.c:3750)

KeyError: "'__name__' not in globals"

```

**Comment by tacaswell** [comment]
My guess is that something is going funny with re-loading the c-extension.
