### ISSUE TITLE
KeyError exception in IPython autocompleter 

### ISSUE THREAD

**Issue by jakirkham** [h5py/h5py#885]
It seems that in some cases h5py tries to autocomplete an expression that it can't. Have noticed this primarily in `list`s. However instead of simply doing nothing, it raises an exception inside the autocompleter. This ends up leaving the input line in a nebulous state. Also it ends up breaking IPython's autocompleter for the remainder of the session. This behavior can be reproduced by typing `[a[<TAB>` on the input line where `<TAB>` is the tab key. The issue occurs on both Python 2 and 3, but this example is done with Python 3.

Traceback:

<details>

```python
$ ipython
Python 3.6.1 | packaged by conda-forge | (default, May 11 2017, 18:00:28) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: [a[Exception in thread Thread-40:
Traceback (most recent call last):                                                                          
  File "/zopt/conda2/envs/test/lib/python3.6/threading.py", line 916, in _bootstrap_inner                   
    self.run()                                                                                              
  File "/zopt/conda2/envs/test/lib/python3.6/threading.py", line 864, in run                                
    self._target(*self._args, **self._kwargs)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 860, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 75, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/IPython/terminal/ptutils.py", line 85, in _get_completions
    for c in completions:
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/IPython/core/completer.py", line 429, in _deduplicate_completions
    completions = list(completions)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/IPython/core/completer.py", line 1647, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/IPython/core/completer.py", line 1687, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/IPython/core/completer.py", line 1829, in _complete
    custom_res = self.dispatch_custom_completer(text)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/IPython/core/completer.py", line 1582, in dispatch_custom_completer
    res = c(event)
  File "/zopt/conda2/envs/test/lib/python3.6/site-packages/h5py/ipy_completer.py", line 175, in h5py_completer
    if not isinstance(self._ofind(base)['obj'], (AttributeManager, HLObject)):
KeyError: 'obj'
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: test
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::appnope=0.1.0=py36_0
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.4.17=0
- conda-forge::certifi=2017.4.17=py36_0
- conda-forge::decorator=4.0.11=py36_0
- conda-forge::h5py=2.7.0=np112py36_0
- conda-forge::hdf5=1.8.17=9
- conda-forge::ipython=6.0.0=py36_0
- conda-forge::ipython_genutils=0.2.0=py36_0
- conda-forge::jedi=0.10.0=py36_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py36_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pexpect=4.2.1=py36_0
- conda-forge::pickleshare=0.7.3=py36_0
- conda-forge::pip=9.0.1=py36_0
- conda-forge::prompt_toolkit=1.0.14=py36_0
- conda-forge::ptyprocess=0.5.1=py36_0
- conda-forge::pygments=2.2.0=py36_0
- conda-forge::python=3.6.1=2
- conda-forge::readline=6.2=0
- conda-forge::setuptools=33.1.1=py36_0
- conda-forge::simplegeneric=0.8.1=py36_0
- conda-forge::six=1.10.0=py36_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::traitlets=4.3.2=py36_0
- conda-forge::wcwidth=0.1.7=py36_0
- conda-forge::wheel=0.29.0=py36_0
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.11=0
- pip:
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
```

</details>

<br>
Edit: Dropped unneeded channels from the environment file.

**Comment by tacaswell** [comment]
I can not reproduce this.

How is the completer getting enabled?

**Comment by jakirkham** [comment]
I have the following lines in `~/.ipython/profile_default/ipython_config.py`.

```python
c = get_config()

try:
    import h5py
    c.InteractiveShellApp.extensions = ['h5py.ipy_completer']
except ImportError:
    pass
```

The `try...except` exists as not every development environment I use has `h5py`, but they all use the same IPython configuration files.

**Comment by jakirkham** [comment]
Have you had any luck trying this with that config addition @tacaswell?

**Comment by tacaswell** [comment]
How can I tell from inside IPYthon if it is turned on?  I still can not reproduce this.

**Comment by jakirkham** [comment]
Maybe try running `get_ipython().config` inside of an IPython console. This is what it shows me.

```python
In [1]: get_ipython().config
Out[1]: {'InteractiveShellApp': {'extensions': ['h5py.ipy_completer']}}
```

**Comment by jakirkham** [comment]
Could also try this in an active IPython session. It won't show up in `get_ipython().config`, but it will work. Just now tested this with 2.7.1.

```python
In [1]: import h5py

In [2]: h5py.enable_ipython_completer()
```

**Comment by aragilar** [comment]
I've managed to reproduce this on 2.7.1 and master, with the latest ipython, by doing:

```python
In [1]: import h5py
In [2]: h5py.enable_ipython_completer()
In [3]: a = [<TAB here>
```
