### ISSUE TITLE
Tests failing with `ImportError: libhdf5.so.100: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by ArchangeGabriel** [h5py/h5py#889]
Environment:
 * ArchLinux
 * Python 2.7+3.6 (system)
 * h5py version (e.g. 2.7)
 * HDF5 version (e.g. 1.10.1) (with Fortran, MPI, CPP, Parallel)

After running `python setup.py configure --mpi` and `python setup.py build`, I’ve got failure with `python setup.py test`:
```
running test
running build_py
running build_ext
Autodetected HDF5 1.10.1
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.10.1'
     MPI Enabled: True
Rebuild Required: False

********************************************************************************
Executing cythonize()
/<pathto>/python-h5py-openmpi/src/h5py-2.7.0/h5py/h5p.pyx: cannot find cimported module 'mpi4py.mpi_c'
Traceback (most recent call last):
  File "setup.py", line 165, in <module>
    cmdclass = CMDCLASS,
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 85, in run
    import h5py
  File "/<pathto>/python-h5py-openmpi/src/h5py-2.7.0/build/lib.linux-x86_64-3.6/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: libhdf5.so.100: cannot open shared object file: No such file or directory
```

Is that expected?

**Comment by ArchangeGabriel** [comment]
Retried in a clean environment and it worked, not sure about the diff but I consider this solved. Sorry for the noise.
