### ISSUE TITLE
Multiprocess read from h5py File with vlen data

### ISSUE THREAD

**Issue by davidye** [h5py/h5py#934]
To assist reproducing bugs, please include the following:
 * MacOS 10.11
 * Python 3.4
 * Conda
 * h5py 2.7.1
 * HDF5 1.8.18

Stack trace:
```
Traceback (most recent call last):
  File "test/test.py", line 9, in test
    print(i, f['test'][0])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/davidye/miniconda2/envs/brine3/lib/python3.4/site-packages/h5py/_hl/dataset.py", line 496, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 158, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (addr overflow, addr = 17592186044417, size=4096, eoa=6256)
```

Test script:
```
from multiprocessing import Process
import time
import h5py


def test(i, f):

    while True:
        print(i, f['test'][0])
        time.sleep(0.01)


if __name__ == '__main__':
    out = h5py.File('test.h5', 'w')
    out.create_dataset('test', (1, 1), dtype=h5py.special_dtype(vlen=str))
    out['test'][0] = "hello world"
    out.close()

    f = h5py.File('test.h5', 'r')

    for i in range(2):
        p = Process(target=test, args=(i, f))
        p.start()
```

This test crashes if f is created outside of the process and passed in. But if I move f = h5py.File('test.h5', 'r') to within the test() function, this works. It also appears to be an issue specifically with variable length data.

**Comment by tacaswell** [comment]
I suspect that this is a limitation of the underlying hdf5 library.  Can you pass hdf5 file handles across forks in c?

**Comment by jakirkham** [comment]
I don't think so. Others have worked around this constraint by reopening the file in another process using the filename and other relevant info. For more complex use cases, caching of file handles within processes is necessary.

ref: https://github.com/Exteris/h5pickle (decent write-up in README about related issues).

**Comment by jakirkham** [comment]
Have you tried `h5pickle`?

**Comment by helderc** [comment]
@jakirkham actually I did. In my processing I have to open two files, one of each class, when I try to get a dataset from the second file, it rises the error:

```
runfile('/media/lavi/HD/MATLAB/2018, Autoencoder/train_autoencoder.py', wdir='/media/lavi/HD/MATLAB/2018, Autoencoder')
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-1-cc52f1bccd5f>", line 1, in <module>
    runfile('/media/lavi/HD/MATLAB/2018, Autoencoder/train_autoencoder.py', wdir='/media/lavi/HD/MATLAB/2018, Autoencoder')

  File "/home/lavi/miniconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/home/lavi/miniconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/lavi/HD/MATLAB/2018, Autoencoder/train_autoencoder.py", line 45, in <module>
    verbose=False)

  File "/media/lavi/HD/MATLAB/2018, Autoencoder/utils.py", line 248, in __init__
    self.lst_imgs_noAD = list(self.hf_noAD.get('/NonAD'))

TypeError: 'NoneType' object is not iterable
```
This happend in both windows and Linux. I have no idea how to solve it of even where to start to understand this behavior. All of this to *try* to solve the problem that I reported here [1], that I **suppose** to be related to the one reported on this very thread...

Please, any help would be welcome!

[1] https://stackoverflow.com/questions/51958246/hdf5-inflate-error-on-windows

**Comment by aparamon** [comment]
On my Windows host, I now (h5py 2.9) get:
````pytb
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
KeyError: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
Traceback (most recent call last):
  File "stringsource", line 7, in h5py.h5f.__pyx_unpickle_FileID
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
  File "h5py\_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__
KeyError: 0
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 200, in h5py._objects.ObjectID.__dealloc__
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
KeyError: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "stringsource", line 7, in h5py.h5f.__pyx_unpickle_FileID
  File "h5py\_objects.pyx", line 178, in h5py._objects.ObjectID.__cinit__
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
````
My knowledge of HDF5 library strongly suggests that file and other HDF5 object IDs are private to the creating process, and the issue is not specific to vlen types. I neither think that the limitation is HDF5 **bug**: just a lack of feature.

I'll check with multiprocessing *fork* driver once I get to my Linux machine though, to see if something weird specifically with vlen takes place there.

**Comment by aparamon** [comment]
For what it's worth, on h5py 2.9 and Debian GNU/Linux I do get the stack trace
````pytb
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 9, in test
    print(i, f['test'][0])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 158, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (address of object past end of allocation)
````
very quickly... but not when I change
````py
    f = h5py.File('test.h5', 'r')
````
to
````py
    f = h5py.File(open('test.h5', 'rb'), 'r')
````
What happens when two processes do share a file handle? How e.g. `seek()` works in this case (is there a single, shared file position, or each process possesses it's own file position)?
Is it likely that the small file size and Python-level buffering together help to avoid failure in the former variant basically by chance, and the inherent problem is still there?

**Comment by aparamon** [comment]
Finally, I got to my Linux box, and here are the experimental results!

Unlike
````py
f = h5py.File(open('test.h5', 'rb'), 'r')
````
the following fails :
````py
f = h5py.File(open('test.h5', 'rb', buffering=0), 'r')
````
So, the former worked just by coincidence (buffering).

After `fork`, [two processes do share the file offset](https://stackoverflow.com/a/11734354), and `lseek` + `read` is not atomic.

But using atomic [pread](http://man7.org/linux/man-pages/man2/pread.2.html) provides the reliable work-around!
A minimal example:
````py
import os

class MyFile:
    def __init__(self, path):
        self.fd = os.open(path, os.O_RDONLY)
        self.pos = 0

    def seek(self, pos, whence=0):
        if whence == 0:
            self.pos = pos
        elif whence == 1:
            self.pos += pos
        else:
            self.pos = os.lseek(self.fd, pos, whence)
        return self.pos

    def tell(self):
        return self.pos

    def read(self, size):
        b = os.pread(self.fd, size, self.pos)
        self.pos += len(b)
        return b

f = h5py.File(MyFile('test.h5'), 'r')
````

Whether `pread`/`pwrite` should be used in stock HDF5 file driver is a matter of discussion on HDF5 forum:
https://forum.hdfgroup.org/t/hdf5-and-parallelism-with-fork-2

@davidye Please let me know if workaround provided is good enough so the issue can be now closed.

**Comment by askerlee** [comment]
I never encountered such an error until yesterday. In the past the data in my h5 were not compressed, and probably that's the reason that the error didn't occur to me when reading it with multiple processes. However my colleague sent me a file with a compression filter two days ago, and then I was haunted by this error.

After some online search, I asked him to regenerate the h5 with SWMR. but the error was still there. I couldn't even check the file with h5ls. Found out that hdf5lib on my Linux (Ubuntu 16.04) was v5.8.xx. And seems for Ubuntu 16.04 there's no apt source that provides the precompiled hdf5lib v5.10.5. So I compiled hdf5lib v5.10.5 and h5py from source. Now the error is gone. 😃

**Comment by takluyver** [comment]
Just to add to this, it appears that HDF5 (or h5py?) can cache open file handles. So if you have the file open in the parent process before forking and open it again in the children, they may reuse the cached file handle, sharing it across processes even if it looks like you're opening it in each process.

As a workaround for this, close any HDF5 files you want to use before forking the child processes. Another workaround may be to select one of the other multiprocessing [start methods](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) (i.e. spawn or forkserver), but I haven't tried this.

I haven't looked to see if there's any way to force HDF5/h5py to open a new handle for a file rather than reusing an existing one.

**Comment by epourmal** [comment]
I entered https://jira.hdfgroup.org/browse/HDFFV-10908 to check if the issue is related to the shared file pointer issue we are working on now.

**Comment by sakshamg94** [comment]
> 
> 
> Finally, I got to my Linux box, and here are the experimental results!
> 
> Unlike
> 
> ```python
> f = h5py.File(open('test.h5', 'rb'), 'r')
> ```
> 
> the following fails :
> 
> ```python
> f = h5py.File(open('test.h5', 'rb', buffering=0), 'r')
> ```
> 
> So, the former worked just by coincidence (buffering).
> 
> After `fork`, [two processes do share the file offset](https://stackoverflow.com/a/11734354), and `lseek` + `read` is not atomic.
> 
> But using atomic [pread](http://man7.org/linux/man-pages/man2/pread.2.html) provides the reliable work-around!
> A minimal example:
> 
> ```python
> import os
> 
> class MyFile:
>     def __init__(self, path):
>         self.fd = os.open(path, os.O_RDONLY)
>         self.pos = 0
> 
>     def seek(self, pos, whence=0):
>         if whence == 0:
>             self.pos = pos
>         elif whence == 1:
>             self.pos += pos
>         else:
>             self.pos = os.lseek(self.fd, pos, whence)
>         return self.pos
> 
>     def tell(self):
>         return self.pos
> 
>     def read(self, size):
>         b = os.pread(self.fd, size, self.pos)
>         self.pos += len(b)
>         return b
> 
> f = h5py.File(MyFile('test.h5'), 'r')
> ```
> 
> Whether `pread`/`pwrite` should be used in stock HDF5 file driver is a matter of discussion on HDF5 forum:
> https://forum.hdfgroup.org/t/hdf5-and-parallelism-with-fork-2
> 
> @davidye @helderc @jakirkham Please let me know if work-around provided is good enough so the issue can be now closed.

That workaround did not work for me :(
