### ISSUE TITLE
Incorrect error message when opening corrupt file

### ISSUE THREAD

**Issue by pletnes** [h5py/h5py#940]
Minimal working example:
```python
import h5py
h5py.File('./corrupt-file.hdf', 'a')
```

Corrupt file example can be downloaded here, if necessary.
https://www.dropbox.com/s/7gttf9h8s0mbxkw/corrupt-file.hdf?dl=0

Version info:
```ipython
In [7]: print(h5py.version.info)
Summary of the h5py configuration
---------------------------------
h5py    2.7.0
HDF5    1.8.17
Python  3.5.4 |Anaconda, Inc.| (default, Oct 13 2017, 11:22:58) 
[GCC 7.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.12.1
```

Tried to open a file in 'a' mode. After the fact, I have found that the file is corrupt. The error message is incorrect, and I get a 'core dumped', which should not happen (python should exit normally). Seems like some edge case to do with interpreting error codes when opening files. The error message is 'file exists', but this should be okay when opening with `h5py.File(mode='a')`.
```
Traceback (most recent call last):
  File "/home/paul/anaconda3/envs/ecopy/lib/python3.5/site-packages/h5py/_hl/files.py", line 113, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/h5f.c:2123)
OSError: Unable to open file (File signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paul/PycharmProjects/ecopy/ecopy/apps/uhivis/UHIvis.py", line 164, in select_file
    self.loadData(os.path.join(self.head, file))
  File "/home/paul/PycharmProjects/ecopy/ecopy/apps/uhivis/UHIvis.py", line 182, in loadData
    dfBands = self.specImg.default_bands
  File "/home/paul/PycharmProjects/ecopy/ecopy/hypimg/hypimg_hdf5.py", line 287, in default_bands
    self._default_bands = self.img_raw_rgb.attrs['bands']
  File "/home/paul/PycharmProjects/ecopy/ecopy/hypimg/hypimg_hdf5.py", line 238, in img_raw_rgb
    self.f_processed.require_group(self.h5path)
  File "/home/paul/PycharmProjects/ecopy/ecopy/hypimg/hypimg_hdf5.py", line 265, in f_processed
    self.__f_processed = h5py.File(self.filename_processed, 'a')
  File "/home/paul/anaconda3/envs/ecopy/lib/python3.5/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/paul/anaconda3/envs/ecopy/lib/python3.5/site-packages/h5py/_hl/files.py", line 115, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/home/ilan/minonda/conda-bld/h5py_1490028461908/work/h5py/h5f.c:2290)
OSError: Unable to create file (Unable to open file: name = 'lusa2_20161121_013005_processed.hdf', errno = 17, error message = 'file exists', flags = 15, o_flags = c2)
[1]    3239 abort (core dumped)  uhivis LUSA2_20161121_013005.hdf
```

**Comment by pletnes** [comment]
Corrupt file example can be downloaded here, if necessary.
https://www.dropbox.com/s/7gttf9h8s0mbxkw/corrupt-file.hdf?dl=0

If this bug is of interest, I could try creating a minimal working example?

**Comment by aragilar** [comment]
The exception information comes from HDF5, so it's likely that the internal nature of how the file is corrupted will determine what error message is shown. I'm not too worried about that.

I am concerned about the abort/core dump. Have you enabled [faulthander](https://docs.python.org/3/library/faulthandler.html) (e.g. is PYTHONFAULTHANDLER set?), or have some other similar error handling module set up? Also, would you be able to provide a backtrace using the core file (see https://stackoverflow.com/questions/8305866/how-to-analyze-a-programs-core-dump-file-with-gdb), so we can determine what is causing the abort.

**Comment by pletnes** [comment]
@aragilar apologies. That was an artifact of me running the code in a PyQt application I believe. Qt seems prone to coredump/segfault type situations. I guess we should focus on the error message being confusing and the exception-in-except-clause situation. The minimal example does not segfault nor coredump.

I've never heard of PYTHONFAULTHANDLER so I guess not.

I think it's worth an attempt to get an appropriate error message. Also it's not a good situation with exceptions occurring inside exception-handling code.

**Comment by aragilar** [comment]
Ok, we won't worry about the abort then.

The relevant lines are https://github.com/h5py/h5py/blob/master/h5py/_hl/files.py#L106-L113, in which we first try to open the file with read-write (which fails, in this case due to corruption), then we try creating the file if it doesn't exist (which in this case it does). We could hint in the second exception that a likely cause would be corruption, but all the error information we have comes from the HDF5 library, so h5py is fairly limited in what new information it can provide. The double exception is actually a useful feature, as it's providing information about why the open and the create failed, and if they happen to fail for different reasons that provides more information to the user (The "File signature not found" says that the file cannot be opened for some reason, which implies corruption, and the exclusive open proves that the file exists and can be found by HDF5).

**Comment by pletnes** [comment]
Those are very good points. I didn't think of the exception-in-exception as a feature, but I see your point now.

Since the first error message actually is correct, would it make sense to just `raise` and skip the "nested try" in the case that "File signature is not found"? You're bound to get "file exists" at that point - I think?

**Comment by tacaswell** [comment]
> Qt seems prone to coredump/segfault type situations.

This is a feature of newer versions PyQt, if a callback raises an exception on the event loop there is no way for the developer to _do_ anything about it.  In previous versions it would just print the traceback and move on, now it fails hard.  It is not a _wrong_ approach, but can be a bit annoying.

**Comment by aparamon** [comment]
@pletnes Could you please update the example file link -- it is no more accessible :-(

**Comment by pletnes** [comment]
Apologies, I've left that job and that dropbox. I don't have the file anymore. I took it the issue was closed though.
