### ISSUE TITLE
Setting fillvalue for datasets with variable length string dtype

### ISSUE THREAD

**Issue by shoyer** [h5py/h5py#941]
This does not appear to work:
```
In [34]: f = h5py.File('varlenstr.h5')

In [35]: vlen_str = h5py.special_dtype(vlen=str)

In [36]: f.create_dataset('foo', (2,), dtype=vlen_str, fillvalue='bar')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-ace807cb8186> in <module>()
----> 1 f.create_dataset('foo', (2,), dtype=vlen_str, fillvalue='bar')

~/conda/envs/xarray-netcdf4-py36/lib/python3.6/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    106         """
    107         with phil:
--> 108             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    109             dset = dataset.Dataset(dsid)
    110             if name is not None:

~/conda/envs/xarray-netcdf4-py36/lib/python3.6/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
    119     if fillvalue is not None:
    120         fillvalue = numpy.array(fillvalue)
--> 121         dcpl.set_fill_value(fillvalue)
    122
    123     if track_times in (True, False):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/_objects.c:2846)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/_objects.c:2804)()

h5py/h5p.pyx in h5py.h5p.PropDCID.set_fill_value (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/h5p.c:5073)()

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/h5t.c:17938)()

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/h5t.c:17897)()

TypeError: No conversion path for dtype: dtype('<U3')
```

Summary of the h5py configuration:
<details>
h5py    2.7.0,
HDF5    1.8.17,
Python  3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59),
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)],
sys.platform    darwin,
sys.maxsize     9223372036854775807,
numpy   1.13.1
</details>

**Comment by aragilar** [comment]
bytes appear not to work either.

**Comment by wrobell** [comment]
Please consider also the following issues.

Let's create variable length `uint8` type
```
dt = h5py.special_dtype(vlen=np.dtype('uint8'))
```

##### Issue 1:
```
ds = f.create_dataset('t1', dtype=dt, shape=(10,))
print(ds[0], ds.fillvalue)
```
The `ds[0]` is `[]`, but fill value is `None`.

##### Issue 2
Exception is thrown
```
ds = f.create_dataset('t1', dtype=dt, shape=(10,), fillvalue=np.array([], dtype='uint8'))
... or ...
ds = f.create_dataset('t1', dtype=dt, shape=(10,), fillvalue=[])
```

##### Issue 3
The below results in segfault. I would expect an exception
```
ds = f.create_dataset('t1', dtype=dt, shape=(10,), fillvalue=np.array([], dtype=dt))
```

**Comment by jreadey** [comment]
Also, I'm getting a segfault when I open a file as read-only and try to do: dset.fillvalue where the dtype is variable length strings and the fillvalue is set.

**Comment by asmeurer** [comment]
Not sure if this is covered by what's already been said here. If you try to set a fillvalue of `b''` or a variable length ascii dataset, you get an error. But it seems to create the dataset anyway but in a corrupted way. 

```py
>>> dt = h5py.string_dtype(encoding='ascii')
>>> f.create_dataset('test', dtype=dt, data=np.full(10, 'hello world', dtype='O'), chunks=(10,), maxshape=(None,), fillvalue=b'')
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/aaronmeurer/Documents/h5py/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/Users/aaronmeurer/Documents/h5py/h5py/_hl/dataset.py", line 136, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 232, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 146, in h5py._proxy.dset_rw
OSError: Can't write data (address of object past end of allocation)
>>> f['test']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/aaronmeurer/Documents/h5py/h5py/_hl/group.py", line 295, in __getitem__
    return dataset.Dataset(oid, readonly=(self.file.mode == 'r'))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/aaronmeurer/Documents/h5py/h5py/_hl/dataset.py", line 587, in __init__
    self._dcpl = self.id.get_create_plist()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 334, in h5py.h5d.DatasetID.get_create_plist
RuntimeError: Can't get creation plist (address of object past end of allocation)
```

This is with h5py master.

**Comment by kmuehlbauer** [comment]
I've managed to hack something together using low level api:

The following has to be added into h5p.pyx since I've not managed to unpack the string from numpy into the wanted c void pointer and to create the needed typeid. If someone is able to show me the details it should be possible to fit this into the normal `set_fill_value` method.

```python
@with_phil
def set_string_fill_value(self, char *name, TypeID tid):
    H5Pset_fill_value(self.id, tid.id, &name)
```

Low level code to create file/group with empty vlen string dataset with applied fillvalue.

```python
filename = b"test.h5"
fid = h5f.create(tmp_local_netcdf, h5f.ACC_TRUNC, h5p.DEFAULT, h5p.DEFAULT)
grpid = h5g.create(fid, b"grp0", h5p.DEFAULT, h5p.DEFAULT)
tid = h5t.C_S1.copy()
tid.set_size(h5t.VARIABLE)
sid = h5s.create_simple((5,), (5,))
dcpl = h5p.create(h5p.DATASET_CREATE)
dt = h5py.string_dtype("utf-8")
fill = np.array("fill", dtype=dt)
dcpl.set_string_fill_value(b"fill", tid)
dsetid = h5d.create(grpid, b"var0", tid, sid, dcpl, h5p.DEFAULT)
dsetid.close()
dcpl.close()
tid.close()
sid.close()
grpid.close()
fid.close()
```

Output of `h5dump -Bpi test.h5`:
```
HDF5 "test.h5" {
SUPER_BLOCK {
   SUPERBLOCK_VERSION 0
   FREELIST_VERSION 0
   SYMBOLTABLE_VERSION 0
   OBJECTHEADER_VERSION 0
   OFFSET_SIZE 8
   LENGTH_SIZE 8
   BTREE_RANK 16
   BTREE_LEAF 4
   ISTORE_K 32
   FILE_SPACE_STRATEGY H5F_FSPACE_STRATEGY_FSM_AGGR
   FREE_SPACE_PERSIST FALSE
   FREE_SPACE_SECTION_THRESHOLD 1
   FILE_SPACE_PAGE_SIZE 4096
   USER_BLOCK {
      USERBLOCK_SIZE 0
   }
}
GROUP "/" {
   OBJECTID { 1 }
   GROUP "grp0" {
      OBJECTID { 4 }
      DATASET "var0" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 5 ) / ( 5 ) }
         OBJECTID { 1 }
         STORAGE_LAYOUT {
            CONTIGUOUS
            SIZE 0
            OFFSET HADDR_UNDEF
         }
         FILTERS {
            NONE
         }
         FILLVALUE {
            FILL_TIME H5D_FILL_TIME_IFSET
            VALUE  "fill"
         }
         ALLOCATION_TIME {
            H5D_ALLOC_TIME_LATE
         }
         DATA {
         (0): "fill", "fill", "fill", "fill", "fill"
         }
      }
   }
}
}
```

The problem is obviously that the original `set_fill_value` function is not able to correctly deduce the needed typeID and void pointer for the call to `H5Pset_fill_value`. If we just feed in the assumed correct values everything works as expected.

**Comment by kmuehlbauer** [comment]
If at first you don't succeed... I've finally managed to correctly feed the vlen fill_values to `H5Pset_fill_value`, see #2044.
