### ISSUE TITLE
"Zero-sized dimension specified" Error with structured array with 0 length field

### ISSUE THREAD

**Issue by tyrion** [h5py/h5py#944]
I think it would be nice to be able to store any kind of numpy arrays using h5py, including ones with 0-length fields.
```
tyrion ~$ mkvirtualenv -p $(which python3) h5py-test
(h5py-test) tyrion ~$ pip install h5py
(h5py-test) tyrion ~$ python
Python 3.5.2 (default, Sep 14 2017, 22:51:06)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import h5py
>>> print(h5py.version.info)
Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.8.18
Python  3.5.2 (default, Sep 14 2017, 22:51:06)
[GCC 5.4.0 20160609]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.13.3

>>> file = h5py.File("test.h5")
>>> x = np.zeros((2,), [('a', '<f4'), ('b', '<f4', 0)])
>>> file.create_dataset("foo", data=x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyrion/.local/lib/virtualenvwrapper/h5py-test/lib/python3.5/site-packages/h5py/_hl/group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/tyrion/.local/lib/virtualenvwrapper/h5py-test/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1530, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1552, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1574, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1488, in h5py.h5t._c_compound
  File "h5py/h5t.pyx", line 1552, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1579, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1390, in h5py.h5t._c_array
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5t.pyx", line 273, in h5py.h5t.array_create
ValueError: Zero-sized dimension specified (zero-sized dimension specified)
>>>
```

**Comment by aragilar** [comment]
I'm not sure having a zero-sized element make sense, or how HDF5 is supposed to store this.
