### ISSUE TITLE
ValueError: Invalid File Name - when trying model.load_weights

### ISSUE THREAD

**Issue by hobbycodernovice** [h5py/h5py#948]
>  * Operating System - Windows 10
>  * Python version - 3.6.3
>  * h5py version - 2.7.1
>  * HDF5 version 1.10.1

I'm a hobby coder, playing around with a neural network for the first time, using source code listed here -->https://github.com/ChunML/text-generator

The network trains and stores training data as a hdf5 file, but defaults to epoch = 0 when run. When forced to load weights, I get the following error.

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\models.py", line 721, in load_weights
    f = h5py.File(filepath, mode='r')
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
ValueError: Invalid file name (invalid file name)
```

Not quite sure what's gone wrong, can anybody help?

**Comment by aragilar** [comment]
It looks like you're trying to open a file with the name '', which is not a valid file name. I'd suggest asking the developer of that code where the data is supposed to be stored, and modify the code as needed.
