### ISSUE TITLE
"Unknown compression filter number: 32017" with SZ lossy compressor

### ISSUE THREAD

**Issue by dingwentao** [h5py/h5py#951]
To assist reproducing bugs, please include the following:
 * Operating System: CentOS7
 * Python version: 3.6.2
 * Where Python was acquired: Anaconda3
 * h5py version: 2.7.0
 * HDF5 version: 1.10.1

I would like to use h5py to write an hdf5 data file with our customized filter "SZ lossy compressor" (UD=32017) as follows.

img = np.zeros((100,100),dtype=np.float32)
f = h5py.File("test.h5","w")
grp = f.create_group("bar")
dset = grp.create_dataset("/data",img.shape,dtype=img.dtype, compression=32017)
dset[...]=img

However, I got the following error messages:

Traceback (most recent call last):
  File "test.py", line 31, in <module>
    dset = grp.create_dataset("/data",img.shape,dtype=img.dtype, compression=32017)
  File "/home/software/anaconda3/5.0.0/lib/python3.6/site-packages/h5py/_hl/group.py", line 108, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/software/anaconda3/5.0.0/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 117, in make_new_dset
    shuffle, fletcher32, maxshape, scaleoffset)
  File "/home/software/anaconda3/5.0.0/lib/python3.6/site-packages/h5py/_hl/filters.py", line 201, in generate_dcpl
    raise ValueError("Unknown compression filter number: %s" % compression)
ValueError: Unknown compression filter number: 32017

I believe I set the correct HDF5_PLUGIN_PATH, since I can use "h5repack -f UD=32017,0" to write correctly with our developed filter. There is a more specific description of our lossy compression flster shown online: https://support.hdfgroup.org/services/filters.html. 

Anyone could help?

**Comment by aragilar** [comment]
How was HDF5 and h5py installed? It may be that you have two different HDF5 installations.

**Comment by dingwentao** [comment]
After loading anaconda3, hdf5 and h5py are automatically loaded. I use conda list hdf5 and conda list h5py to check the installation of them. Here it is:
$ conda list hdf5
# packages in environment at /soft/anaconda3/5.0.0:
#
hdf5                      1.10.1               hb0523eb_0

$ conda list h5py
# packages in environment at /soft/anaconda3/5.0.0:
#
h5py                      2.7.0            py36he81ebca_1

I also confirmed that "h5repack" I used to test our filter is the same installation that h5py uses.
$ which h5repack
/home/software/anaconda3/5.0.0/bin/h5repack

The experience of using other customized filters (such as zfp) with h5py could be also helpful!
Thanks!

**Comment by aragilar** [comment]
Can you try using https://github.com/silx-kit/hdf5plugin, and see if you can access the plugins that it contains? h5py should support using custom compressors, so I'm wondering if there's some problem with conda or your system which is messing with the paths...

**Comment by fengwei0907** [comment]
Hello, have you resolved this issue? Thank you for your answer.

**Comment by vasole** [comment]
You can give a try at https://github.com/silx-kit/hdf5plugin

SZ should be supported.
