### ISSUE TITLE
OSError: Unable to create file (unable to open file: name = 'models/gru_1_0.028946343809366226.hdf5'

### ISSUE THREAD

**Issue by JangHoPeter** [h5py/h5py#976]
**## How to solve it? I thought it was about import problem. But 'import h5py' code couldn't help me.**
  

To assist reproducing bugs, please include the following:
 * Operating System Ubuntu 16.04.5
* Python version  3.4
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version 2.7.1
 * HDF5 version 1.8.11
 * The full traceback/stack trace shown (if it appears)

```
Traceback (most recent call last):
  File "LB77-KerasGRU-with-filterbanks-Silva-v1.py", line 151, in <module>
    model.save('models/gru_{}_{}.hdf5'.format(bag+1,best_loss))
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 103, in save_model
    with h5py.File(filepath, mode='w') as f:
  File "/usr/local/lib/python3.4/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.4/dist-packages/h5py/_hl/files.py", line 105, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'models/gru_1_0.028946343809366226.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
```

**Comment by aragilar** [comment]
Does the `models` directory exist? Or is it read only? Something is preventing h5py from creating the file.

**Comment by JangHoPeter** [comment]
Thanks.. I thought wrong. solved!

**Comment by tiansongwang** [comment]
Hello, I'd like to know how do you solve this problem? Thank you. I had this problem, too.

**Comment by tacaswell** [comment]
@tiansongwang make sure the full directory path exists and is writable.
