### ISSUE TITLE
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

### ISSUE THREAD

**Issue by bighorn-sheep** [h5py/h5py#982]
are there someone can solve this ,thank you !!
 codes:

import pandas as pd

left = pd.DataFrame({'key':['K0','K1','K2','K3'],
                     'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3']})

print(left)

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

* Operating System : Ubuntu 14.04 LTS,
 * Python version :  2.7
 * Where Python was acquired : Linux
 * h5py version (e.g. 2.6)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/yt/Documents/Jacky‘s programming/pandas by Movan/合并merge.py", line 45, in <module>
    print(left)
  File "/usr/lib/python2.7/dist-packages/pandas/core/base.py", line 35, in __str__
    return self.__bytes__()
  File "/usr/lib/python2.7/dist-packages/pandas/core/base.py", line 47, in __bytes__
    return self.__unicode__().encode(encoding, 'replace')
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 460, in __unicode__
    line_width=width, show_dimensions=show_dimensions)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 1299, in to_string
    formatter.to_string()
  File "/usr/lib/python2.7/dist-packages/pandas/core/format.py", line 380, in to_string
    strcols = self._to_str_columns()
  File "/usr/lib/python2.7/dist-packages/pandas/core/format.py", line 329, in _to_str_columns
    fmt_values = self._format_col(i)
  File "/usr/lib/python2.7/dist-packages/pandas/core/format.py", line 501, in _format_col
    space=self.col_space
  File "/usr/lib/python2.7/dist-packages/pandas/core/format.py", line 1626, in format_array
    return fmt_obj.get_result()
  File "/usr/lib/python2.7/dist-packages/pandas/core/format.py", line 1642, in get_result
    fmt_values = self._format_strings()
  File "/usr/lib/python2.7/dist-packages/pandas/core/format.py", line 1670, in _format_strings
    is_float = lib.map_infer(vals, com.is_float) & notnull(vals)
  File "/usr/lib/python2.7/dist-packages/pandas/core/common.py", line 276, in notnull
    return -res
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

**Comment by bighorn-sheep** [comment]
the first time i ask a Q in github, wish i can get the solution..

**Comment by aragilar** [comment]
@bighorn-sheep This looks like a problem in pandas, not h5py. You want to create the issue at https://github.com/pandas-dev/pandas/issues/new.

**Comment by bhartiya007** [comment]
I am getting the same error in GDB. I have raised the question there. Awaiting response.
