### ISSUE TITLE
Test failures (numpy 1.14?)

### ISSUE THREAD

**Issue by ArchangeGabriel** [h5py/h5py#987]
* ArchLinux
 * Python 3.6 (system)
 * h5py 2.7.1
 * HDF5 1.10.1

(At least) two tests are failing, I highly suspect those to be related to numpy 1.14 and types changes.
```
======================================================================
FAIL: test_out_of_order_offsets (h5py.tests.old.test_h5t.TestCompound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-h5py/src/h5py-2.7.1/build/lib.linux-x86_64-3.6/h5py/tests/old/test_h5t.py", line 61, in test_out_of_order_offsets
    self.assertEqual(tid.dtype, expected_dtype)
AssertionError: dtype[13 chars]1','f3','f2'], 'formats':['<f4','<f8','<i4'], [30 chars]:20}) != dtype[13 chars]1','f2','f3'], 'formats':['<f4','<i4','<f8'], [30 chars]:20})

======================================================================
FAIL: test_out_of_order_offsets (h5py.tests.hl.test_datatype.TestOffsets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-h5py/src/h5py-2.7.1/build/lib.linux-x86_64-3.6/h5py/tests/hl/test_datatype.py", line 198, in test_out_of_order_offsets
    self.assertArrayEqual(fd['data'], data)
  File "/build/python-h5py/src/h5py-2.7.1/build/lib.linux-x86_64-3.6/h5py/tests/common.py", line 124, in assertArrayEqual
    "Dtype mismatch (%s vs %s)%s" % (dset.dtype, arr.dtype, message)
AssertionError: False is not true : Dtype mismatch ({'names':['f1','f3','f2'], 'formats':['<f4','<f8','<i4'], 'offsets':[0,8,16], 'itemsize':20} vs {'names':['f1','f2','f3'], 'formats':['<f4','<i4','<f8'], 'offsets':[0,16,8], 'itemsize':20})

----------------------------------------------------------------------
```

**Comment by aragilar** [comment]
@ArchangeGabriel There's a tracking bug (#969) for the numpy 1.14 changes, so I'm going to close this as duplicate.
