### ISSUE TITLE
KeyError: Unable to open object (object overruns end of direct block)

### ISSUE THREAD

**Issue by williamdjones** [h5py/h5py#991]
## KeyError: Unable to open object (object overruns end of direct block)

I am attempting to use multiple processes, implemented via pytorch multiprocessing module (which itself wraps the native multiprocessing), to read from an h5 file (I created using external links to a number of subsets of my full data) in parallel so I can train a machine learning method more quickly. I am at times able to do this with no issue and life is great. Other times I get this cryptic traceback to an error that I can't myself address. I have searched for similar issues and have not been successful (hopefully I'm wrong and this has been handled before).  

 ---
* Operating System: Ubuntu 16.04.3 LTS
 * Python version: 3.6.4
 * Where Python was acquired: Anaconda 3, version 4.3.30
 * h5py version: 2.7.1
 * HDF5 version: 1.8.16
 * The full traceback/stack trace shown (if it appears)
>  Traceback (most recent call last):
  File "MoleculeDataset.py", line 117, in <module>
    for idx, batch in tqdm(enumerate(mydata), total=num_iters):
  File "/u/spa-d2/grad/derek/anaconda3/envs/deep_protein_binding/lib/python3.6/site-packages/tqdm/_tqdm.py", line 953, in __iter__
    for obj in iterable:
  File "/u/spa-d2/grad/derek/anaconda3/envs/deep_protein_binding/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/u/spa-d2/grad/derek/anaconda3/envs/deep_protein_binding/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/u/spa-d2/grad/derek/anaconda3/envs/deep_protein_binding/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/u/spa-d2/grad/derek/anaconda3/envs/deep_protein_binding/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "MoleculeDataset.py", line 83, in __getitem__\n    target_list.append(self.fo[receptor][drugID][target][0])\n  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n  File "/u/spa-d2/grad/derek/anaconda3/envs/deep_protein_binding/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__\n    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n  File "h5py/h5o.pyx", line 190, in h5py.h5o.open\nKeyError: \'Unable to open object (object overruns end of direct block)\'\n'

**Comment by aragilar** [comment]
@williamdjones Have you tried running this in a single process (i.e. disabling multiprocessing)? I suspect using multiprocessing will cause things to break in strange ways, I'd recommend using MPI, as HDF5 has support for it (note you'll need to build h5py from source).

**Comment by williamdjones** [comment]
yes, I have run several tests on the machine I am training with. I can get by with a single process, however this severely limits the usefulness of this library and I may as well use a csv version of the dataset on a machine with more memory. However, I am interested in writing code that scales up and down. 

More specifically, there appears to be a relationship between the number of available "cores" on the particular machine and the ability for the multiprocessing to work. On this machine I have 8 cores (product: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz) and as I increase the number of workers, i.e. subprocesses, I increase the probability of my workers failing to successfully read from the file. I am using libver="latest" and I have also tried libver="earliest". I have tried setting swmr=True and swmr=False. These solutions appear to have limited to no effect. As I understand, if I open my file in read mode, then this format should not have a problem supporting simultaneous reads as the file is not able to be changed during these accesses. It seems as if I have more processes try to perform read operations, there is some sort of "crowding out" effect. This does not make sense to me as the memory where the data resides does not change as a consequence of the external linking that I use to create the aggregated file. So somehow, the processes think that they must start reading from different offsets in memory in order to access the file information. I don't know why this makes sense and I don't know if this is the intent of the swmr functionality or if this may be a bug. I can try to run my script multiple times and eventually it works, but this seems to underline my point that this may be a bug either in the h5py implementation or in the underlying c implementation.

**Comment by williamdjones** [comment]
I'm also only working on a single node, I've only thought of MPI as being useful for multiple node implementations, but I may be wrong about that and am willing to try it out.

**Comment by aragilar** [comment]
My suggestion for using the single process is to flag whether it's a multiprocessing issue or not (and based the increasing failures, I suspect it is a multiprocessing issue), not that you should only have a single process/thread. MPI definitely seems like something worth looking into, and it works on a single node or multiple nodes, and HDF5 supports it natively (both for reading and writing), which is going to be the major issue with other possible frameworks (HDF5 does a bunch of locking, and a fair proportion of h5py is connecting Python's GC to HDF5's).

I'm not sure whether SWMR should be working in your case or if there is actually a bug in HDF5 (I suspect it's the locking problem again), but given SWMR is handled internally by HDF5 (so all h5py can do is activate/deactivate it), you'd probably need to spend some time with C testing under what conditions there is a problem in HDF5.

If you really want/need to use multiprocessing, you could dig into the underlying multiprocessing primitives, and connect them to the HDF5 primitives (as has been done for the HDF5 and Python GCs), but I suspect that's going to be more effort than it's worth.

**Comment by williamdjones** [comment]
Thank you, I'll look into using MPI instead and see if that suits my needs. I'm fairly confident that this is indeed a multiprocessing issue as I seem to have no problem running things with a single process, however that results in iterating over my data on the order of hours as opposed to minutes if I could instead effectively leverage the threading capabilities of my processor. This is just something I thought needed to be pointed out in the event another person runs into the problem. If I find some spare time I'll continue digging into the python and or c implementations.

**Comment by tacaswell** [comment]
Are you both reading an writing to the hdf5 files from all of the processes?
