### ISSUE TITLE
Python/hdf5 files freezing when trying to fill datasets with data [BUG]

### ISSUE THREAD

**Issue by Moondra** [h5py/h5py#998]
To assist reproducing bugs, please include the following:
 * Operating System : Windows 7
 * Python version : 3.6
 * Where Python was acquired : Python.org
 * h5py version : '2.7.0'
 * HDF5 version : 1.8.18

`Summary of the h5py configuration`
h5py    2.7.0
HDF5    1.8.18
Python  3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.13.3`

This is my code

 

       with h5py.File(hdf5_path, mode='w') as hdf5:
                hdf5.create_dataset("train_bottle", train_shape, np.float32)
                hdf5.create_dataset("train_labels", (len(train.filenames), params['bottle_labels']),np.uint8)
                hdf5.create_dataset("validation_bottle", validation_shape, np.float32)
                hdf5.create_dataset("validation_labels",
                                              (len(valid.filenames),params['bottle_labels']),np.uint8)

                current_iteration = 0
                print('created_datasets')
                for x, y in train:

                    number_of_examples = len(train.filenames) # number of images
                    prediction = model.predict(x)
                    labels = y
                    print(prediction.shape) # (120,10,10,2048)
                    print(y.shape) # (120, 12)
                    print('start',current_iteration*params['batch_size']) # 0
                    print('end',(current_iteration+1) * params['batch_size']) # 120

                    hdf5["train_bottle"][current_iteration*params['batch_size']: (current_iteration+1) * params['batch_size'],...] = prediction
                    hdf5["train_labels"][current_iteration*params['batch_size']: (current_iteration+1) * params['batch_size'],...] = labels
                    current_iteration += 1
                    print(current_iteration)
                    if current_iteration == 3:
                       break`

Basically when I run this code above, which consists of a few  iterations, the script gets stuck in the first iteration and can't get to the next iteration. I've waited a half-hour and the first iteration is still going.
If I try to access the file to see size,  Windows Explorer slows down to a snail and It's hard to see the file size. If I try to close Python shell, it just freezes. `

 ##Now The relevant part is here

        hdf5["train_bottle"][current_iteration*params['batch_size']: (current_iteration+1) * params['batch_size'],...] = prediction
   
    hdf5["train_labels"][current_iteration*params['batch_size']: (current_iteration+1) * params['batch_size'],...] = labels
`

After playing around with my code for a bit, there seems to be a strange bug/behavior.
If I run either of these above lines,(comment out any of those lines) my script will go through the iterations, and automatically break as expected. So there is NO freeze if I run either-or. It happens fairly quickly as well -- less than one min.

If I run the first line ('train_bottle'), my memory is taking up about 69-72 gigs, even if it's only a couple of batches. If I try more batches, the memory is the same. So I'm assuming the train_bottle decided storage based on the size parameters I'm assigning the dataset, and not actually when it gets filled. So despite taking up the 72 gigs, it's running fairly quickly (one min).

If I run the second line, train_labels , my memory takes up a few megabytes. There is no problem with the iterations, and break statement is executed.

So running either of these lines in my script produces no problem. The problem is only if I try to run
both lines within my script.

If I try to run both lines as in my original script (which in my case is necessary as I need to save both 'train_bottle' and 'train_labels'), I'm experiencing a freeze on the first iteration. Python will not advance to the second iteration even after 30 mins. The Hdf5 file is slowly growing, but if I try to access it, Windows Explorer slows down to a snail and I can't close Python -- I have to restart the OS.

So I'm not sure what the problem is when trying to running both lines. 
Even running the 'train_bottle' line which requires a lot of hardrive memory ALONE, takes up less than a min, so I don't understand why running the 'train_label' line in addition would crash my system.

I'm assuming there is something wrong with my code, but no one on Stackoverflow has been able to find anything wrong with my code thus far.

**Comment by tacaswell** [comment]
Can you simplify the example a bit to a copy-paste-runable example?  For example, replace all of the `params[]` (which is good practice for production code!) with hard-coded numbers and remove all of the ML training code.

Can you try changing the sizes the data sets to see how that affects things?

You probably want to be using dataset chunking at this size of data.

Not being able quit python makes me think that the code is hung down in c (the hdf5 library) or in a systemcall (from OS).

**Comment by Moondra** [comment]
Sure. I will work on it now.

**Comment by Moondra** [comment]
@tacaswell Okay will do. The only thing I'm confused about is best way to reproduce the generator object. I"m using Keras's built-in ImageDataGenerator, which requires us to point to the image folders we want to use as our input data, and it automatically creates the generator for us. I wonder if a regular generator would be an okay replacement.

**Comment by Moondra** [comment]
@tacaswell Ah sorry, I had screwed up the formatting in the post. I fixed it now. It should be copy + paste ready.  Basically there are only two functions:  create_generators_numpy () create_hdf5_test(hdf5_path).  Despite using dummy data, I'm still getting the freeze at the first iteration.

**Comment by aragilar** [comment]
@Moondra Do you still have the freeze when you remove the `keras` imports?

**Comment by Moondra** [comment]
@aragilar Yes.  I just tested it with these imports and I'm still getting the freeze.
`import numpy as np`
`import os`
`import math`
`import datetime`
`from random import shuffle`
`import h5py`

**Comment by aragilar** [comment]
Odd, I can't reproduce this (this is on linux though, could be a windows-only problem).
@Moondra How did you install h5py, and could you try h5py 2.7.1 to see if the bug fixes included fixes the freezing?

**Comment by Moondra** [comment]
@aragilar I've updated to 2.7.1. I haven't ran my numpy script yet but I did run  `h5py.run_tests()` and got two errors, which I've included in the OP. Going to try running the numpy script and report back. Thank you.

**Comment by Moondra** [comment]
@aragilar 

Someone on stackoverflow recommened using`import h5py_cache as h5c`,
`import tables` and specifying chunk_size, and that seems to have fixed the problem. See update (bottom) in OP please.

**Comment by aragilar** [comment]
@Moondra That seems interesting, there must something going on with either chunking or compression which avoids the problem, you could try not preforming the compression, to see if it's the chunking that is fixing your problem, or if it's the compression.

**Comment by vasole** [comment]
That is indeed puzzling and I am also interested in the answer.

The original code did not include any compression so it seems using chunking helps HDF5 (or h5py) to figure out how to handle the data.

**Comment by Moondra** [comment]
@aragilar  Sorry for the late reply. I will get to it this weekend. I just have to backup all my scripts and open tabs as turning off one of the two options (chunking or compression) will freeze my computer (forcing a restart). I've just been postponing the tidying up .

**Comment by loheden** [comment]
Will there be a new release available for anaconda?

Seemingly I cannot install a version later than 2.7.1.

And when I install it and test it as instructed, I get the following error below. It does not tell me anything, I have no clue how to fix it.And I also wonder if it is OK to discard this error or do I need to fix it before continuing? A bit frustrating that such a problem lingers around for a long long time.... :)

import h5py
h5py.run_tests()

.....................................................x.........................s.........................................x....................................s...s......ss....................................................................................................ssssss..............................F..................................x....x........................x.....x.................................................ssss.........F....
======================================================================
FAIL: test_out_of_order_offsets (h5py.tests.old.test_h5t.TestCompound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cesncn/anaconda3/envs/tensorflow/lib/python3.5/site-packages/h5py/tests/old/test_h5t.py", line 61, in test_out_of_order_offsets
    self.assertEqual(tid.dtype, expected_dtype)
AssertionError: dtype[13 chars]1','f3','f2'], 'formats':['<f4','<f8','<i4'], [30 chars]:20}) != dtype[13 chars]1','f2','f3'], 'formats':['<f4','<i4','<f8'], [30 chars]:20})

======================================================================
FAIL: test_out_of_order_offsets (h5py.tests.hl.test_datatype.TestOffsets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cesncn/anaconda3/envs/tensorflow/lib/python3.5/site-packages/h5py/tests/hl/test_datatype.py", line 198, in test_out_of_order_offsets
  File "/home/cesncn/anaconda3/envs/tensorflow/lib/python3.5/site-packages/h5py/tests/common.py", line 124, in assertArrayEqual
    dset.shape == arr.shape,
AssertionError: False is not true : Dtype mismatch ({'names':['f1','f3','f2'], 'formats':['<f4','<f8','<i4'], 'offsets':[0,8,16], 'itemsize':20} vs {'names':['f1','f2','f3'], 'formats':['<f4','<i4','<f8'], 'offsets':[0,16,8], 'itemsize':20})

----------------------------------------------------------------------
Ran 446 tests in 2.265s

FAILED (failures=2, skipped=15, expected failures=6)
